#!/usr/bin/env python3
"""Append remaining ortaokul questions to reach 500"""
import os

questions = [
# Coğrafya +20
'{k:"Coğrafya",s:"Meridyen nedir?",o:["Yatay çizgi","Boyunca çizilen dikey çizgi","Ekvator çizgisi","Kutup noktası"],d:1,a:"Meridyenler kutupları birleştiren dikey hayali çizgilerdir."}',
'{k:"Coğrafya",s:"Paralel nedir?",o:["Dikey çizgi","Ekvator paraleli yatay çizgi","Meridyen çizgisi","Boylam çizgisi"],d:1,a:"Paraleller ekvatore paralel çizilen yatay hayali çizgilerdir."}',
'{k:"Coğrafya",s:"Hangi rüzgar Türkiye ye yağış getirir?",o:["Poyraz","Lodos","Yıldız","Keşişleme"],d:1,a:"Lodos güneyden esen sıcak ve nemli rüzgardır yağış getirir."}',
'{k:"Coğrafya",s:"Muson iklimi nerelerde görülür?",o:["Kutuplarda","Güney ve Güneydoğu Asya","Avrupa","Kuzey Amerika"],d:1,a:"Muson iklimi özellikle Güney ve Güneydoğu Asya da görülür."}',
'{k:"Coğrafya",s:"Dünya üzerinde kaç zaman dilimi vardır?",o:["12","18","24","36"],d:2,a:"Dünya 24 zaman dilimine bölünmüştür."}',
'{k:"Coğrafya",s:"Yer kabuğunu oluşturan büyük parçalara ne denir?",o:["Magma","Levha (plaka)","Manto","Çekirdek"],d:1,a:"Yer kabuğu tektonik levhalardan (plakalardan) oluşur."}',
'{k:"Coğrafya",s:"Tropikal iklim hangi bölgelerde görülür?",o:["Kutuplarda","Ekvator çevresinde","Ilıman kuşakta","Çöllerde"],d:1,a:"Tropikal iklim ekvator çevresindeki sıcak ve nemli bölgelerde görülür."}',
'{k:"Coğrafya",s:"Fırtına hangi olaydan kaynaklanır?",o:["Deprem","Basınç farkı ve rüzgar","Volkan","Tsunami"],d:1,a:"Fırtınalar atmosferik basınç farklarından kaynaklanan güçlü rüzgarlardır."}',
'{k:"Coğrafya",s:"Göl ile deniz arasındaki fark nedir?",o:["Boyut","Göller karayla çevrili denizler değil","Renk","Derinlik"],d:1,a:"Göller her tarafı karayla çevrili su kütleleridir denizler okyanuslarla bağlantılıdır."}',
'{k:"Coğrafya",s:"Delta nasıl oluşur?",o:["Depremle","Nehirlerin denize döküldüğü yerde alüvyon birikmesiyle","Volkanla","Rüzgarla"],d:1,a:"Delta nehirlerin taşıdığı alüvyonları denize döküldüğü yerde biriktirmesiyle oluşur."}',
'{k:"Coğrafya",s:"Yer altı suyu nasıl oluşur?",o:["Volkanla","Yağışların toprağa sızmasıyla","Depremle","Rüzgarla"],d:1,a:"Yağış suları toprağa sızarak yer altında birikerek yer altı suyunu oluşturur."}',
'{k:"Coğrafya",s:"Barometle ne ölçülür?",o:["Sıcaklık","Hava basıncı","Nem","Rüzgar hızı"],d:1,a:"Barometre hava basıncını ölçen alettir."}',
'{k:"Coğrafya",s:"Troposfer nedir?",o:["Uzay","Atmosferin en alt katmanı","Ozon tabakası","Yer kabuğu"],d:1,a:"Troposfer atmosferin en alt katmanıdır hava olayları burada gerçekleşir."}',
'{k:"Coğrafya",s:"Okyanus akıntıları ne etkiler?",o:["Depremleri","İklimi ve deniz canlılarını","Volkanları","Dağ oluşumunu"],d:1,a:"Okyanus akıntıları iklimi ve deniz ekosistemlerini etkiler."}',
'{k:"Coğrafya",s:"Tundra iklimi nerelerde görülür?",o:["Ekvator","Kutup bölgeleri","Tropikal","Akdeniz"],d:1,a:"Tundra iklimi kutuplara yakın soğuk bölgelerde görülür."}',
'{k:"Coğrafya",s:"Step iklimi nedir?",o:["Çok yağışlı","Yarı kurak bozkır iklimi","Tropikal","Kutupsal"],d:1,a:"Step iklimi az yağışlı yarı kurak bozkır alanlarında görülür."}',
'{k:"Coğrafya",s:"Tsunami nasıl oluşur?",o:["Rüzgarla","Deniz altı deprem veya volkanla","Yağmurla","Gel gitlerle"],d:1,a:"Tsunami deniz altındaki deprem veya volkanik aktivitelerle oluşan dev dalgalardır."}',
'{k:"Coğrafya",s:"Gece gündüz eşitliği ne zaman olur?",o:["21 Haziran","21 Aralık","21 Mart ve 23 Eylül","1 Ocak"],d:2,a:"21 Mart ve 23 Eylül tarihlerinde gece gündüz eşitliği yaşanır."}',
'{k:"Coğrafya",s:"Karstik oluşum hangisidir?",o:["Volkan","Mağara","Delta","Vadi"],d:1,a:"Kireçtaşının erimesiyle oluşan mağaralar karstik oluşumlardır."}',
'{k:"Coğrafya",s:"Akdeniz ikliminin özelliği nedir?",o:["Yazlar yağışlı","Yazlar sıcak kuru kışlar ılık yağışlı","Her mevsim soğuk","Her mevsim yağışlı"],d:1,a:"Akdeniz ikliminde yazlar sıcak ve kurak kışlar ılık ve yağışlıdır."}',
# Bilim +20
'{k:"Bilim",s:"Protonun yükü nedir?",o:["Negatif","Nötr","Pozitif","Değişken"],d:2,a:"Protonun yükü pozitiftir."}',
'{k:"Bilim",s:"Elektronun yükü nedir?",o:["Pozitif","Nötr","Negatif","Değişken"],d:2,a:"Elektronun yükü negatiftir."}',
'{k:"Bilim",s:"Hangi gezegen güneş sisteminin en sıcak gezegenidir?",o:["Merkür","Venüs","Mars","Jüpiter"],d:1,a:"Venüs yoğun atmosferi nedeniyle sera etkisiyle en sıcak gezegendir."}',
'{k:"Bilim",s:"Karbon elementinin sembolü nedir?",o:["Ca","Co","C","Cr"],d:2,a:"Karbon elementinin sembolü C dir."}',
'{k:"Bilim",s:"Hangi cihaz hava basıncını ölçer?",o:["Termometre","Barometre","Voltmetre","Ampermetre"],d:1,a:"Barometre hava basıncını ölçen cihazdır."}',
'{k:"Bilim",s:"Foton nedir?",o:["Atom parçacığı","Işık parçacığı","Ses dalgası","Elektrik birimi"],d:1,a:"Foton ışığın en küçük enerji paketidir."}',
'{k:"Bilim",s:"Hangi gaz yanmayı destekler?",o:["Azot","Karbondioksit","Oksijen","Helyum"],d:2,a:"Oksijen yanmayı destekleyen gazdır."}',
'{k:"Bilim",s:"İnsan vücudunda en sert doku hangisidir?",o:["Kemik","Kıkırdak","Diş minesi","Tırnak"],d:2,a:"Diş minesi insan vücudundaki en sert dokudur."}',
'{k:"Bilim",s:"Hangi bilim dalı yıldızları inceler?",o:["Jeoloji","Biyoloji","Astronomi","Meteoroloji"],d:2,a:"Astronomi gök cisimlerini ve yıldızları inceleyen bilim dalıdır."}',
'{k:"Bilim",s:"Sindirim sisteminin ilk organı hangisidir?",o:["Mide","Ağız","Yemek borusu","İnce bağırsak"],d:1,a:"Sindirim ağızda başlar çiğneme ve tükürük ile mekanik ve kimyasal sindirim yapılır."}',
'{k:"Bilim",s:"Kan grupları kaç tanedir?",o:["2","3","4","6"],d:2,a:"4 ana kan grubu vardır A B AB ve 0."}',
'{k:"Bilim",s:"Newton un üçüncü yasası nedir?",o:["Kuvvet","Her etkiye eşit ve zıt tepki","İvme","Enerji korunumu"],d:1,a:"Her etkiye eşit büyüklükte ve zıt yönde bir tepki kuvveti vardır."}',
'{k:"Bilim",s:"Hangi madde sıvı metal olarak bilinir?",o:["Altın","Gümüş","Civa","Bakır"],d:2,a:"Civa oda sıcaklığında sıvı halde bulunan tek metaldir."}',
'{k:"Bilim",s:"Klorofil hangi renk ışığı emer?",o:["Yeşil","Kırmızı ve mavi","Sarı","Beyaz"],d:1,a:"Klorofil kırmızı ve mavi ışığı emer yeşili yansıtır."}',
'{k:"Bilim",s:"Deprem dalgalarını ölçen cihaz nedir?",o:["Barometre","Sismograf","Termometre","Voltmetre"],d:1,a:"Sismograf deprem dalgalarını ölçen ve kaydeden cihazdır."}',
'{k:"Bilim",s:"Suyun kimyasal formülü nedir?",o:["H2O","CO2","NaCl","O2"],d:0,a:"Suyun kimyasal formülü H2O dur."}',
'{k:"Bilim",s:"Genetik biliminin babası kimdir?",o:["Darwin","Mendel","Pasteur","Watson"],d:1,a:"Gregor Mendel genetik biliminin babası olarak kabul edilir."}',
'{k:"Bilim",s:"Hücrenin enerji santrali hangisidir?",o:["Çekirdek","Ribozom","Mitokondri","Lizozom"],d:2,a:"Mitokondri hücrenin enerji santralıdır."}',
'{k:"Bilim",s:"Hangisi bir bileşiktir?",o:["Oksijen","Demir","Su","Altın"],d:2,a:"Su iki farklı elementten oluşan bir bileşiktir."}',
'{k:"Bilim",s:"Evrenin yaşı yaklaşık kaç milyar yıldır?",o:["4.5","9","13.8","20"],d:2,a:"Evrenin yaşı yaklaşık 13.8 milyar yıl olarak hesaplanmıştır."}',
# Doğa +20
'{k:"Doğa",s:"Mantar hangi canlı grubuna aittir?",o:["Bitki","Hayvan","Mantarlar alemi","Bakteri"],d:2,a:"Mantarlar ne bitki ne hayvan olan ayrı bir canlı alemine aittir."}',
'{k:"Doğa",s:"Simbiyoz ilişki nedir?",o:["Düşmanlık","İki canlının birlikte yaşayıp karşılıklı fayda sağlaması","Avlanma","Rekabet"],d:1,a:"Simbiyoz iki canlının birlikte yaşayarak karşılıklı fayda sağladığı ilişkidir."}',
'{k:"Doğa",s:"Predatör ne demektir?",o:["Bitki","Avcı hayvan","Otçul","Çürükçül"],d:1,a:"Predatör başka hayvanları avlayarak beslenen avcı hayvandır."}',
'{k:"Doğa",s:"Omurgasız hayvan hangisidir?",o:["Kedi","Balık","Ahtapot","Kuş"],d:2,a:"Ahtapot omurgası olmayan yumuşakça sınıfından bir hayvandır."}',
'{k:"Doğa",s:"Erozyon nedir?",o:["Bitki büyümesi","Toprağın su ve rüzgarla aşınması","Volkanik patlama","Deprem"],d:1,a:"Erozyon toprağın su rüzgar gibi etkenlerle aşınıp taşınmasıdır."}',
'{k:"Doğa",s:"Hangi hayvan sonar kullanır?",o:["Kartal","Yunus","Aslan","Tavşan"],d:1,a:"Yunuslar ekolokasyon ile sonar kullanarak yön bulur ve avlanır."}',
'{k:"Doğa",s:"Toprak katmanlarına ne denir?",o:["Magma","Toprak horizonları","Lav","Plaka"],d:1,a:"Toprağın farklı katmanlarına toprak horizonları denir."}',
'{k:"Doğa",s:"Fotosentezde üretilen gaz hangisidir?",o:["Karbondioksit","Azot","Oksijen","Metan"],d:2,a:"Fotosentez sonucunda oksijen gazı üretilir."}',
'{k:"Doğa",s:"Doğal seleksiyon teorisini kim öne sürdü?",o:["Mendel","Einstein","Darwin","Newton"],d:2,a:"Charles Darwin doğal seleksiyon teorisini ortaya koymuştur."}',
'{k:"Doğa",s:"Orman yangınlarının en büyük nedeni nedir?",o:["Volkan","İnsan kaynaklı nedenler","Deprem","Sel"],d:1,a:"Orman yangınlarının büyük çoğunluğu insan kaynaklı nedenlerle çıkar."}',
'{k:"Doğa",s:"Parazit canlı nedir?",o:["Serbest yaşayan","Başka canlının üzerinde yaşayıp zarar veren","Üretici","Tüketici"],d:1,a:"Parazit başka bir canlının üzerinde yaşayıp ondan beslenip zarar veren canlıdır."}',
'{k:"Doğa",s:"Hangi hayvan en zeki kabul edilir?",o:["Köpek","Yunus","Kedi","Papağan"],d:1,a:"Yunuslar en zeki hayvanlardan biri olarak kabul edilir."}',
'{k:"Doğa",s:"Çölde yaşayan bitkiler suyu nasıl depolar?",o:["Yapraklarda","Gövde ve köklerinde","Çiçeklerinde","Tohumlarında"],d:1,a:"Çöl bitkileri suyu kalın gövdelerinde ve derin köklerinde depolar."}',
'{k:"Doğa",s:"Hangi kuş en büyük yumurtayı bırakır?",o:["Kartal","Deve kuşu","Penguen","Flamingo"],d:1,a:"Deve kuşu dünyanın en büyük yumurtasını bırakan kuştur."}',
'{k:"Doğa",s:"Asit yağmuru nedir?",o:["Normal yağmur","Hava kirliliğinin neden olduğu asitli yağış","Tuzlu yağmur","Sıcak yağmur"],d:1,a:"Asit yağmuru hava kirliliğindeki gazların yağmur suyuyla birleşmesiyle oluşur."}',
'{k:"Doğa",s:"Hangi böcek en çok türe sahiptir?",o:["Karınca","Kelebek","Kın kanatlılar (böcek)","Arı"],d:2,a:"Kın kanatlılar (Coleoptera) en fazla türe sahip böcek takımıdır."}',
'{k:"Doğa",s:"Tozlaşma nedir?",o:["Toz temizleme","Polenin çiçeğe taşınması","Toprağın aşınması","Rüzgar oluşumu"],d:1,a:"Tozlaşma polenin rüzgar veya böceklerle çiçeğin dişi organına taşınmasıdır."}',
'{k:"Doğa",s:"Hangi hayvan dünyada en çok popülasyona sahiptir?",o:["İnsan","Tavuk","Karınca","Balık"],d:2,a:"Karıncalar dünyada en yüksek popülasyona sahip canlılardan biridir."}',
'{k:"Doğa",s:"Habitat ne demektir?",o:["Hayvan türü","Canlının doğal yaşam alanı","Bitki türü","Hava durumu"],d:1,a:"Habitat bir canlının doğal olarak yaşadığı çevre ve alandır."}',
'{k:"Doğa",s:"Birincil tüketici ne demektir?",o:["Bitki","Bitkilerle beslenen otçul hayvan","Etçil hayvan","Ayrıştırıcı"],d:1,a:"Birincil tüketiciler bitkilerle beslenen otçul hayvanlardır."}',
# Başkentler +20
'{k:"Başkentler",s:"Belçika nın başkenti neresidir?",o:["Amsterdam","Brüksel","Lüksemburg","Paris"],d:1,a:"Brüksel Belçika nın başkentidir."}',
'{k:"Başkentler",s:"Hollanda nın başkenti neresidir?",o:["Rotterdam","Amsterdam","Lahey","Utrecht"],d:1,a:"Amsterdam Hollanda nın resmi başkentidir."}',
'{k:"Başkentler",s:"Şili nin başkenti neresidir?",o:["Buenos Aires","Santiago","Lima","Bogota"],d:1,a:"Santiago Şili nin başkentidir."}',
'{k:"Başkentler",s:"Slovenya nın başkenti neresidir?",o:["Zagreb","Belgrad","Ljubljana","Sarajevo"],d:2,a:"Ljubljana Slovenya nın başkentidir."}',
'{k:"Başkentler",s:"Hırvatistan ın başkenti neresidir?",o:["Ljubljana","Zagreb","Belgrad","Sarajevo"],d:1,a:"Zagreb Hırvatistan ın başkentidir."}',
'{k:"Başkentler",s:"Sırbistan ın başkenti neresidir?",o:["Zagreb","Ljubljana","Belgrad","Tiran"],d:2,a:"Belgrad Sırbistan ın başkentidir."}',
'{k:"Başkentler",s:"Bosna Hersek in başkenti neresidir?",o:["Zagreb","Belgrad","Sarajevo","Tiran"],d:2,a:"Sarajevo Bosna Hersek in başkentidir."}',
'{k:"Başkentler",s:"Arnavutluk un başkenti neresidir?",o:["Belgrad","Tiran","Podgorica","Üsküp"],d:1,a:"Tiran Arnavutluk un başkentidir."}',
'{k:"Başkentler",s:"Kuzey Makedonya nın başkenti neresidir?",o:["Tiran","Belgrad","Üsküp","Priştine"],d:2,a:"Üsküp Kuzey Makedonya nın başkentidir."}',
'{k:"Başkentler",s:"Bulgaristan ın başkenti neresidir?",o:["Bükreş","Sofya","Belgrad","Tiran"],d:1,a:"Sofya Bulgaristan ın başkentidir."}',
'{k:"Başkentler",s:"Suudi Arabistan ın başkenti neresidir?",o:["Dubai","Riyad","Mekke","Cidde"],d:1,a:"Riyad Suudi Arabistan ın başkentidir."}',
'{k:"Başkentler",s:"Birleşik Arap Emirlikleri nin başkenti neresidir?",o:["Dubai","Abu Dabi","Doha","Riyad"],d:1,a:"Abu Dabi BAE nin başkentidir."}',
'{k:"Başkentler",s:"Katar ın başkenti neresidir?",o:["Dubai","Riyad","Doha","Muskat"],d:2,a:"Doha Katar ın başkentidir."}',
'{k:"Başkentler",s:"İsrail in başkenti neresidir?",o:["Tel Aviv","Kudüs","Hayfa","Eilat"],d:1,a:"İsrail Kudüs ü başkent olarak kabul eder."}',
'{k:"Başkentler",s:"Lübnan ın başkenti neresidir?",o:["Bağdat","Şam","Beyrut","Amman"],d:2,a:"Beyrut Lübnan ın başkentidir."}',
'{k:"Başkentler",s:"Suriye nin başkenti neresidir?",o:["Beyrut","Şam","Bağdat","Amman"],d:1,a:"Şam Suriye nin başkentidir."}',
'{k:"Başkentler",s:"Ürdün ün başkenti neresidir?",o:["Beyrut","Şam","Bağdat","Amman"],d:3,a:"Amman Ürdün ün başkentidir."}',
'{k:"Başkentler",s:"Malezya nın başkenti neresidir?",o:["Singapur","Kuala Lumpur","Jakarta","Manila"],d:1,a:"Kuala Lumpur Malezya nın başkentidir."}',
'{k:"Başkentler",s:"Myanmar ın başkenti neresidir?",o:["Yangon","Naypyidaw","Bangkok","Hanoi"],d:1,a:"Naypyidaw Myanmar ın başkentidir."}',
'{k:"Başkentler",s:"Moğolistan ın başkenti neresidir?",o:["Pekin","Astana","Ulan Batur","Bişkek"],d:2,a:"Ulan Batur Moğolistan ın başkentidir."}',
# Türkiye +25
'{k:"Türkiye",s:"Sumela Manastırı hangi vadide yer alır?",o:["Fırtına Vadisi","Altındere Vadisi","Ihlara Vadisi","Köprülü Kanyon"],d:1,a:"Sumela Manastırı Trabzon Altındere Vadisinde yer alır."}',
'{k:"Türkiye",s:"Ihlara Vadisi hangi ildedir?",o:["Nevşehir","Aksaray","Kayseri","Niğde"],d:1,a:"Ihlara Vadisi Aksaray ilinde bulunan 14 km uzunluğunda bir kanyondur."}',
'{k:"Türkiye",s:"Türkiye de en çok zeytin hangi bölgede üretilir?",o:["Karadeniz","Ege","İç Anadolu","Doğu Anadolu"],d:1,a:"Zeytin üretimi en çok Ege Bölgesinde yapılmaktadır."}',
'{k:"Türkiye",s:"Boğaziçi Köprüsü kaç yılında açıldı?",o:["1970","1973","1980","1985"],d:1,a:"Boğaziçi Köprüsü 1973 yılında hizmete açılmıştır."}',
'{k:"Türkiye",s:"Türkiye nin en eski şehirlerinden biri olan Mardin hangi bölgededir?",o:["Akdeniz","İç Anadolu","Güneydoğu Anadolu","Doğu Anadolu"],d:2,a:"Mardin Güneydoğu Anadolu Bölgesinde yer alır."}',
'{k:"Türkiye",s:"Harran Ovası hangi ildedir?",o:["Mardin","Şanlıurfa","Diyarbakır","Gaziantep"],d:1,a:"Harran Ovası Şanlıurfa ilinde yer alır."}',
'{k:"Türkiye",s:"Antalya Müzesi hangi döneme ait eserleriyle ünlüdür?",o:["Osmanlı","Roma ve antik dönem","Cumhuriyet","Selçuklu"],d:1,a:"Antalya Müzesi Roma ve antik dönem eserleriyle ünlü bir müzedir."}',
'{k:"Türkiye",s:"Hierapolis Antik Kenti hangi ilde yer alır?",o:["Muğla","Denizli","Aydın","İzmir"],d:1,a:"Hierapolis Antik Kenti Denizli Pamukkale de yer alır."}',
'{k:"Türkiye",s:"Olympos Antik Kenti hangi ildedir?",o:["Muğla","İzmir","Antalya","Mersin"],d:2,a:"Olympos Antik Kenti Antalya nın Kumluca ilçesindedir."}',
'{k:"Türkiye",s:"Türkiye de hangi il en çok fındık üretir?",o:["Trabzon","Ordu","Giresun","Rize"],d:1,a:"Ordu ili Türkiye nin en fazla fındık üreten ilidir."}',
'{k:"Türkiye",s:"Selimiye Camii hangi ildedir?",o:["İstanbul","Konya","Bursa","Edirne"],d:3,a:"Mimar Sinan ın ustalık eseri Selimiye Camii Edirne dedir."}',
'{k:"Türkiye",s:"Topkapı Sarayı hangi şehirdedir?",o:["Ankara","Edirne","Bursa","İstanbul"],d:3,a:"Topkapı Sarayı İstanbul da yer alan Osmanlı sarayıdır."}',
'{k:"Türkiye",s:"Dolmabahçe Sarayı hangi boğazda yer alır?",o:["Çanakkale","İstanbul Boğazı","Kerç","Süveyş"],d:1,a:"Dolmabahçe Sarayı İstanbul Boğazı kıyısında yer alır."}',
'{k:"Türkiye",s:"Yedigöller Milli Parkı hangi ildedir?",o:["Kastamonu","Bartın","Bolu","Düzce"],d:2,a:"Yedigöller Milli Parkı Bolu ilinde yer alır."}',
'{k:"Türkiye",s:"Aizanoi Antik Kenti hangi ildedir?",o:["Kütahya","Afyon","Eskişehir","Uşak"],d:0,a:"Aizanoi Antik Kenti Kütahya nın Çavdarhisar ilçesindedir."}',
'{k:"Türkiye",s:"Türkiye nin en geniş ovası hangisidir?",o:["Çukurova","Konya Ovası","Bafra Ovası","Muş Ovası"],d:1,a:"Konya Ovası Türkiye nin en geniş ovasıdır."}',
'{k:"Türkiye",s:"Likya Yolu hangi bölgededir?",o:["Karadeniz","Ege","Akdeniz","Marmara"],d:2,a:"Likya Yolu Akdeniz Bölgesinde Antalya ve Muğla arasında uzanır."}',
'{k:"Türkiye",s:"Uludağ hangi ildedir?",o:["İstanbul","Bursa","Eskişehir","Bilecik"],d:1,a:"Uludağ Bursa ilinde yer alan kış turizmi merkezidir."}',
'{k:"Türkiye",s:"Abant Gölü hangi ildedir?",o:["Düzce","Sakarya","Bolu","Kastamonu"],d:2,a:"Abant Gölü Bolu ilinde yer alan doğal güzelliklerden biridir."}',
'{k:"Türkiye",s:"Xanthos Antik Kenti hangi ildedir?",o:["Antalya","Muğla","Aydın","Denizli"],d:0,a:"Xanthos Likya medeniyetinin başkenti olarak Antalya dadır."}',
'{k:"Türkiye",s:"Türkiye de kaç UNESCO Dünya Mirası alanı vardır?",o:["10-12","15-17","19-21","25-27"],d:2,a:"Türkiye 2024 itibarıyla 21 UNESCO Dünya Mirası alanına sahiptir."}',
'{k:"Türkiye",s:"Karain Mağarası hangi ildedir?",o:["Mersin","Antalya","Muğla","Burdur"],d:1,a:"Karain Mağarası Antalya da bulunan Anadolunun en eski yerleşim yerlerinden biridir."}',
'{k:"Türkiye",s:"Safranbolu evleri hangi mimari tarzda yapılmıştır?",o:["Modern","Osmanlı sivil mimarisi","Gotik","Barok"],d:1,a:"Safranbolu evleri Osmanlı sivil mimarisi örneğidir."}',
'{k:"Türkiye",s:"Hasankeyf hangi ildedir?",o:["Mardin","Şırnak","Batman","Siirt"],d:2,a:"Hasankeyf antik kenti Batman ilinde yer almaktadır."}',
'{k:"Türkiye",s:"Türkiye nin en yağışlı ili hangisidir?",o:["Trabzon","Rize","Artvin","Giresun"],d:1,a:"Rize Türkiye nin en çok yağış alan ilidir."}',
# Spor +25
'{k:"Spor",s:"Tour de France hangi spor dalının yarışıdır?",o:["Koşu","Bisiklet","Yüzme","Kayak"],d:1,a:"Tour de France dünyanın en ünlü bisiklet yarışıdır."}',
'{k:"Spor",s:"Bir rugby maçında kaç oyuncu sahadadır?",o:["11","13","15","18"],d:2,a:"Rugby Union da her takımdan 15 oyuncu sahada bulunur."}',
'{k:"Spor",s:"Badminton da kullanılan topa ne denir?",o:["Top","Birdie","Koza","Tüylü top"],d:3,a:"Badminton da kullanılan tüylü topa shuttlecock veya tüylü top denir."}',
'{k:"Spor",s:"Super Bowl hangi sporun finalidir?",o:["Basketbol","Beyzbol","Amerikan futbolu","Hokey"],d:2,a:"Super Bowl Amerikan futbolunun (NFL) final maçıdır."}',
'{k:"Spor",s:"Pele hangi ülkenin futbolcusudur?",o:["Arjantin","Brezilya","Portekiz","İspanya"],d:1,a:"Pele Brezilyalı efsanevi futbolcudur."}',
'{k:"Spor",s:"Hangi spor dalında paralel bar kullanılır?",o:["Atletizm","Jimnastik","Yüzme","Boks"],d:1,a:"Jimnastikte paralel bar kullanılan aletlerden biridir."}',
'{k:"Spor",s:"Olimpiyatlarda kış sporları hangileridir?",o:["Yüzme futbol","Kayak buz pateni biatlon","Tenis golf","Atletizm güreş"],d:1,a:"Kış Olimpiyatlarında kayak buz pateni biatlon gibi sporlar yapılır."}',
'{k:"Spor",s:"Usain Bolt hangi yarış mesafesinin rekorunu kırdı?",o:["400 metre","200 metre","100 metre","800 metre"],d:2,a:"Usain Bolt 100 metre de 9.58 saniye ile dünya rekorunu kırmıştır."}',
'{k:"Spor",s:"Boks ringinin şekli nasıldır?",o:["Daire","Kare","Dikdörtgen","Altıgen"],d:1,a:"Boks ringi kare şeklindedir."}',
'{k:"Spor",s:"Halter sporunda kaç hareket yapılır?",o:["1","2","3","4"],d:1,a:"Halterde koparma ve silkme olmak üzere 2 hareket yapılır."}',
'{k:"Spor",s:"Polo sporunda hangi hayvan kullanılır?",o:["Deve","At","Fil","Eşek"],d:1,a:"Polo at üzerinde oynanan bir spordur."}',
'{k:"Spor",s:"Bowling da kaç pini devirmek gerekir?",o:["8","9","10","12"],d:2,a:"Bowling da 10 pini devirmek amaçlanır."}',
'{k:"Spor",s:"Dart tahtasında en yüksek tek alan puanı kaçtır?",o:["20","25","50","60"],d:3,a:"Üçlü 20 alanı 60 puanla en yüksek tek alan puanını verir."}',
'{k:"Spor",s:"Bir golf sahasında kaç delik vardır?",o:["9","12","15","18"],d:3,a:"Standart bir golf sahasında 18 delik bulunur."}',
'{k:"Spor",s:"Kano ve kayak farkı nedir?",o:["Aynı spor","Kanoda tek kürek kayakta çift kürek","Biri denizde biri nehirde","Fark yok"],d:1,a:"Kanoda tek taraflı kürek kayakta çift taraflı kürek kullanılır."}',
'{k:"Spor",s:"Sörf hangi doğal güçle yapılır?",o:["Rüzgar","Dalga","Akıntı","Gel git"],d:1,a:"Sörf okyanus dalgaları üzerinde tahta ile yapılan bir spordur."}',
'{k:"Spor",s:"Paralimpik oyunlar kimler için düzenlenir?",o:["Yaşlılar","Engelli sporcular","Çocuklar","Amatörler"],d:1,a:"Paralimpik oyunlar engelli sporcular için düzenlenen uluslararası spor etkinliğidir."}',
'{k:"Spor",s:"Bir maratonu tamamlama süresi dünya rekoru yaklaşık kaç dakikadır?",o:["90","100","120","150"],d:2,a:"Maraton dünya rekoru yaklaşık 2 saat yani 120 dakika civarındadır."}',
'{k:"Spor",s:"Wushu hangi ülkenin geleneksel spor dalıdır?",o:["Japonya","Kore","Çin","Tayland"],d:2,a:"Wushu Çin in geleneksel dövüş sanatı ve sporudur."}',
'{k:"Spor",s:"Taekwondo hangi ülkenin dövüş sanatıdır?",o:["Japonya","Çin","Kore","Tayland"],d:2,a:"Taekwondo Güney Kore kökenli bir dövüş sanatıdır."}',
'{k:"Spor",s:"Karate hangi ülkede ortaya çıkmıştır?",o:["Çin","Kore","Japonya","Vietnam"],d:2,a:"Karate Japonya da özellikle Okinawa adasında ortaya çıkmıştır."}',
'{k:"Spor",s:"Muay Thai hangi ülkenin dövüş sanatıdır?",o:["Japonya","Çin","Vietnam","Tayland"],d:3,a:"Muay Thai Tayland ın geleneksel dövüş sanatıdır."}',
'{k:"Spor",s:"Hentbol maçı kaç dakikadır?",o:["40","50","60","70"],d:2,a:"Hentbol maçı 2x30 toplam 60 dakikadır."}',
'{k:"Spor",s:"Masa tenisi maçında bir seti kazanmak için kaç sayıya ulaşılmalıdır?",o:["9","11","15","21"],d:1,a:"Masa tenisinde seti kazanmak için 11 sayıya ulaşmak gerekir."}',
'{k:"Spor",s:"Sutopu maçı kaç periyottan oluşur?",o:["2","3","4","5"],d:2,a:"Sutopu maçı 4 periyottan oluşur."}',
# Matematik +25
'{k:"Matematik",s:"Bir prizmada kaç adet taban yüzeyi vardır?",o:["1","2","3","4"],d:1,a:"Prizmada 2 taban yüzeyi bulunur."}',
'{k:"Matematik",s:"Kesir türünde payda sıfır olabilir mi?",o:["Evet","Hayır","Bazen","Pozitifse evet"],d:1,a:"Payda hiçbir zaman sıfır olamaz tanımsız olur."}',
'{k:"Matematik",s:"1000 in yüzde 15 i kaçtır?",o:["100","150","200","250"],d:1,a:"1000 x 0.15 = 150 dir."}',
'{k:"Matematik",s:"Paralel kenarın alanı nasıl hesaplanır?",o:["a x b","taban x yükseklik","2(a+b)","pi r kare"],d:1,a:"Paralelkenarın alanı taban x yükseklik formülüyle hesaplanır."}',
'{k:"Matematik",s:"Yamuk nedir?",o:["4 kenarı eşit","Sadece bir çift kenarı paralel dörtgen","Tüm kenarları paralel","Üçgen"],d:1,a:"Yamuk sadece bir çift kenarı paralel olan dörtgendir."}',
'{k:"Matematik",s:"Ondalık sayı 0.75 kesir olarak nasıl yazılır?",o:["1/2","3/4","2/3","4/5"],d:1,a:"0.75 kesir olarak 3/4 tür."}',
'{k:"Matematik",s:"Bir çemberin yarıçapı 5 ise çevresi yaklaşık kaçtır?",o:["25","31.4","50","15.7"],d:1,a:"Çevre = 2 x pi x r = 2 x 3.14 x 5 = 31.4 tür."}',
'{k:"Matematik",s:"Kareköklerin hangi özelliği vardır?",o:["Negatif olamaz","Her zaman tam sayı","Sıfırdan küçük","Paydası sıfır"],d:0,a:"Reel sayılarda karekök negatif olamaz sonuç sıfır veya pozitiftir."}',
'{k:"Matematik",s:"Romen rakamıyla L kaçtır?",o:["10","50","100","500"],d:1,a:"Romen rakamıyla L 50 demektir."}',
'{k:"Matematik",s:"Romen rakamıyla C kaçtır?",o:["10","50","100","500"],d:2,a:"Romen rakamıyla C 100 demektir."}',
'{k:"Matematik",s:"Bir doğru parçasının kaç uç noktası vardır?",o:["0","1","2","Sonsuz"],d:2,a:"Doğru parçasının 2 uç noktası vardır."}',
'{k:"Matematik",s:"İki doğru birbirine dik ise aralarındaki açı kaç derecedir?",o:["45","60","90","180"],d:2,a:"Birbirine dik iki doğru arasında 90 derecelik açı vardır."}',
'{k:"Matematik",s:"Eşkenar üçgenin açıları kaçar derecedir?",o:["45","60","90","120"],d:1,a:"Eşkenar üçgenin her açısı 60 derecedir."}',
'{k:"Matematik",s:"Karenin köşegen sayısı kaçtır?",o:["1","2","4","6"],d:1,a:"Karenin 2 köşegeni vardır."}',
'{k:"Matematik",s:"Altıgenin kaç köşegeni vardır?",o:["6","9","12","15"],d:1,a:"Düzgün altıgenin 9 köşegeni vardır."}',
'{k:"Matematik",s:"Bir sayının negatif kuvveti ne anlama gelir?",o:["Sıfır olur","O sayının tersinin pozitif kuvveti","Tanımsız","Negatif sayı"],d:1,a:"Negatif kuvvet sayının tersinin pozitif kuvveti anlamına gelir."}',
'{k:"Matematik",s:"Ortalama nasıl hesaplanır?",o:["Toplam x sayı","Toplam / sayı adet","En büyük - en küçük","Ortanca değer"],d:1,a:"Ortalama tüm değerlerin toplamının değer sayısına bölünmesiyle bulunur."}',
'{k:"Matematik",s:"2 üzeri 10 kaç eder?",o:["512","1000","1024","2048"],d:2,a:"2 üzeri 10 = 1024 tür."}',
'{k:"Matematik",s:"Faktöriyel işareti nedir?",o:["#","!","@","&"],d:1,a:"Faktöriyel ünlem işareti ! ile gösterilir."}',
'{k:"Matematik",s:"5 faktöriyel kaçtır?",o:["60","100","120","150"],d:2,a:"5! = 5x4x3x2x1 = 120 dir."}',
'{k:"Matematik",s:"Koordinat düzleminde orijin noktası neresidir?",o:["(1,1)","(0,0)","(1,0)","(0,1)"],d:1,a:"Orijin noktası koordinat düzleminin merkezi olan (0,0) noktasıdır."}',
'{k:"Matematik",s:"Bir dik üçgende en uzun kenara ne denir?",o:["Kenar","Taban","Hipotenüs","Yükseklik"],d:2,a:"Dik üçgenin en uzun kenarına hipotenüs denir."}',
'{k:"Matematik",s:"Pisagor teoremi nedir?",o:["a+b=c","a kare + b kare = c kare","a x b = c","2a + 2b = c"],d:1,a:"Pisagor teoremine göre dik üçgende a kare + b kare = hipotenüs kare dir."}',
'{k:"Matematik",s:"Doğal sayılar sıfırdan başlar mı?",o:["Evet","Hayır","Bazen","Sadece pozitifler"],d:0,a:"Doğal sayılar 0 dan başlar: 0 1 2 3 4..."}',
'{k:"Matematik",s:"Rasyonel sayı nedir?",o:["Pi sayısı","Kesir olarak yazılabilen sayı","Kök 2","Sonsuz"],d:1,a:"Rasyonel sayılar a/b şeklinde yazılabilen sayılardır (b sıfırdan farklı)."}',
]

filepath = os.path.join("c:", os.sep, "Users", "safir", "OneDrive", "Masaüstü", "SmartCampusAI", "views", "_by_ortaokul.txt")

with open(filepath, "a", encoding="utf-8") as f:
    for q in questions:
        f.write(q + "\n")

with open(filepath, "r", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip().startswith("{k:")]
    print(f"Total: {len(lines)}")
    cats = {}
    for l in lines:
        cat = l.split('"')[1]
        cats[cat] = cats.get(cat, 0) + 1
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")
