#!/usr/bin/env python3
"""Append remaining ilkokul questions to _by_ilkokul.txt"""

questions = [
'{k:"Doğa",s:"Kurbağalar hangi hayvan sınıfına aittir?",o:["Memeliler","Sürüngenler","İki yaşamlılar","Balıklar"],d:2,a:"Kurbağalar hem karada hem suda yaşayan iki yaşamlılardır."}',
'{k:"Doğa",s:"Hangi hayvan yumurtlayarak çoğalır?",o:["Kedi","Köpek","Tavuk","İnek"],d:2,a:"Tavuklar yumurtlayarak çoğalan kuşlardır."}',
'{k:"Doğa",s:"Bitkiler havadan hangi gazı alır?",o:["Oksijen","Azot","Karbondioksit","Helyum"],d:2,a:"Bitkiler fotosentez için havadan karbondioksit alır."}',
'{k:"Doğa",s:"Hangi mevsimde ağaçlar yapraklarını döker?",o:["İlkbahar","Yaz","Sonbahar","Kış"],d:2,a:"Sonbaharda yaprak döken ağaçlar yapraklarını bırakır."}',
'{k:"Doğa",s:"Arılar ne üretir?",o:["Süt","Yumurta","Bal","İpek"],d:2,a:"Arılar çiçeklerden topladıkları nektarla bal üretir."}',
'{k:"Doğa",s:"Hangi hayvan gece aktiftir?",o:["Tavuk","Baykuş","Serçe","Güvercin"],d:1,a:"Baykuşlar gece aktif olan kuşlardır."}',
'{k:"Doğa",s:"Balıklar nasıl nefes alır?",o:["Burunla","Ağızla","Solungaçla","Deriyle"],d:2,a:"Balıklar sudaki oksijeni solungaçlarıyla alır."}',
'{k:"Doğa",s:"Hangi böcek ışık üretir?",o:["Arı","Ateş böceği","Karınca","Uğur böceği"],d:1,a:"Ateş böcekleri biolüminesans ile ışık üretir."}',
'{k:"Doğa",s:"En büyük kara hayvanı hangisidir?",o:["Gergedan","Zürafa","Fil","Su aygırı"],d:2,a:"Afrika fili karada yaşayan en büyük hayvandır."}',
'{k:"Doğa",s:"Hangi hayvan kabuğunu sırtında taşır?",o:["Kirpi","Kaplumbağa","Kertenkele","Yılan"],d:1,a:"Kaplumbağalar kabuklarını sırtlarında taşır."}',
'{k:"Doğa",s:"Hangi kuş uçamaz?",o:["Kartal","Deve kuşu","Şahin","Papağan"],d:1,a:"Deve kuşu uçamayan en büyük kuştur."}',
'{k:"Doğa",s:"Tırtıl büyüyünce ne olur?",o:["Böcek","Kelebek","Arı","Sinek"],d:1,a:"Tırtıllar başkalaşım geçirerek kelebeğe dönüşür."}',
'{k:"Doğa",s:"Hangi hayvanın boynuzu vardır?",o:["Kedi","Tavşan","Geyik","Tilki"],d:2,a:"Geyikler boynuzlu hayvanlardır."}',
'{k:"Doğa",s:"Karada ve suda yaşayan hayvanlara ne denir?",o:["Memeliler","Amfibiler","Sürüngenler","Kuşlar"],d:1,a:"Amfibiler hem karada hem suda yaşar."}',
'{k:"Doğa",s:"Hangi hayvan bal yapar?",o:["Karınca","Arı","Kelebek","Sinek"],d:1,a:"Bal arıları çiçek nektarından bal üretir."}',
'{k:"Bilim",s:"Suyun donma noktası kaç derecedir?",o:["10","0","-10","5"],d:1,a:"Saf su 0 derecede donar."}',
'{k:"Bilim",s:"Hangi gezegen Güneşe en yakındır?",o:["Venüs","Merkür","Mars","Dünya"],d:1,a:"Merkür Güneşe en yakın gezegendir."}',
'{k:"Bilim",s:"Gökkuşağında kaç renk vardır?",o:["5","6","7","8"],d:2,a:"Gökkuşağında 7 renk bulunur."}',
'{k:"Bilim",s:"Hangi organ kanı pompalar?",o:["Beyin","Kalp","Böbrek","Akciğer"],d:1,a:"Kalp kanı vücuda pompalayan organdır."}',
'{k:"Bilim",s:"Bitkilerin yeşil olmasını sağlayan madde nedir?",o:["Vitamin","Protein","Klorofil","Mineral"],d:2,a:"Klorofil bitkilere yeşil rengini verir."}',
'{k:"Bilim",s:"Ay Dünya nın nesidir?",o:["Gezegeni","Yıldızı","Uydusu","Güneşi"],d:2,a:"Ay Dünya nın doğal uydusudur."}',
'{k:"Bilim",s:"Ses hangi ortamda yayılamaz?",o:["Suda","Havada","Demirde","Boşlukta"],d:3,a:"Ses boşlukta yayılamaz."}',
'{k:"Bilim",s:"Hangi vitamin güneşten alınır?",o:["A vitamini","B vitamini","C vitamini","D vitamini"],d:3,a:"D vitamini güneş ışığı ile sentezlenir."}',
'{k:"Bilim",s:"Dünya nın şekli neye benzer?",o:["Küp","Küre","Silindir","Dikdörtgen"],d:1,a:"Dünya kutuplardan basık küre şeklindedir."}',
'{k:"Bilim",s:"Termometre ne ölçer?",o:["Ağırlık","Uzunluk","Sıcaklık","Hız"],d:2,a:"Termometre sıcaklık ölçen alettir."}',
'{k:"Bilim",s:"Dünya kendi etrafında kaç saatte döner?",o:["12 saat","24 saat","36 saat","48 saat"],d:1,a:"Dünya kendi ekseni etrafında 24 saatte döner."}',
'{k:"Bilim",s:"Mıknatıs hangi metali çeker?",o:["Altın","Bakır","Demir","Alüminyum"],d:2,a:"Mıknatıs demir ve çelik gibi metalleri çeker."}',
'{k:"Bilim",s:"Bulutlar neden oluşur?",o:["Tozdan","Su buharından","Dumandan","Rüzgardan"],d:1,a:"Bulutlar su buharının yoğunlaşmasıyla oluşur."}',
'{k:"Bilim",s:"Güneş sistemimizdeki en büyük gezegen hangisidir?",o:["Satürn","Jüpiter","Uranüs","Neptün"],d:1,a:"Jüpiter güneş sisteminin en büyük gezegenidir."}',
'{k:"Bilim",s:"Işık mı ses mi daha hızlıdır?",o:["Ses","Eşit hız","Işık","Ortama bağlı"],d:2,a:"Işık sesten çok daha hızlıdır."}',
'{k:"Coğrafya",s:"Türkiye nin en büyük gölü hangisidir?",o:["Tuz Gölü","Van Gölü","Beyşehir Gölü","Burdur Gölü"],d:1,a:"Van Gölü Türkiye nin en büyük gölüdür."}',
'{k:"Coğrafya",s:"Hangi kıtada penguen yaşar?",o:["Avrupa","Asya","Antarktika","Afrika"],d:2,a:"Penguenler çoğunlukla Antarktikada yaşar."}',
'{k:"Coğrafya",s:"Dünyanın en büyük okyanusu hangisidir?",o:["Atlas","Hint","Büyük Okyanus","Kuzey Buz"],d:2,a:"Büyük Okyanus dünyanın en büyük okyanusudur."}',
'{k:"Coğrafya",s:"Nil Nehri hangi kıtadadır?",o:["Asya","Avrupa","Afrika","Amerika"],d:2,a:"Nil Nehri Afrika kıtasındadır."}',
'{k:"Coğrafya",s:"Türkiye kaç coğrafi bölgeye ayrılır?",o:["5","6","7","8"],d:2,a:"Türkiye 7 coğrafi bölgeye ayrılmıştır."}',
'{k:"Coğrafya",s:"Everest Dağı hangi kıtadadır?",o:["Avrupa","Afrika","Asya","Amerika"],d:2,a:"Everest Dağı Asya kıtasında Nepal-Çin sınırındadır."}',
'{k:"Coğrafya",s:"Hangi deniz Türkiye nin kuzeyindedir?",o:["Akdeniz","Ege","Karadeniz","Marmara"],d:2,a:"Karadeniz Türkiye nin kuzey kıyısında yer alır."}',
'{k:"Coğrafya",s:"Amazon Ormanları hangi kıtadadır?",o:["Afrika","Asya","Güney Amerika","Avustralya"],d:2,a:"Amazon yağmur ormanları Güney Amerikadadır."}',
'{k:"Coğrafya",s:"Dünyanın en küçük kıtası hangisidir?",o:["Avrupa","Antarktika","Avustralya","Afrika"],d:2,a:"Avustralya dünyanın en küçük kıtasıdır."}',
'{k:"Başkentler",s:"Japonya nın başkenti neresidir?",o:["Osaka","Tokyo","Kyoto","Hiroshima"],d:1,a:"Tokyo Japonya nın başkentidir."}',
'{k:"Başkentler",s:"Brezilya nın başkenti neresidir?",o:["Rio de Janeiro","Sao Paulo","Brasilia","Salvador"],d:2,a:"Brasilia Brezilya nın başkentidir."}',
'{k:"Başkentler",s:"Avustralya nın başkenti neresidir?",o:["Sydney","Melbourne","Canberra","Brisbane"],d:2,a:"Canberra Avustralya nın başkentidir."}',
'{k:"Başkentler",s:"Kanada nın başkenti neresidir?",o:["Toronto","Vancouver","Montreal","Ottawa"],d:3,a:"Ottawa Kanada nın başkentidir."}',
'{k:"Başkentler",s:"Hindistan ın başkenti neresidir?",o:["Mumbai","Yeni Delhi","Kalküta","Bangalore"],d:1,a:"Yeni Delhi Hindistan ın başkentidir."}',
'{k:"Başkentler",s:"Güney Kore nin başkenti neresidir?",o:["Busan","Seul","Incheon","Daegu"],d:1,a:"Seul Güney Kore nin başkentidir."}',
'{k:"Başkentler",s:"Norveç in başkenti neresidir?",o:["Stockholm","Helsinki","Oslo","Kopenhag"],d:2,a:"Oslo Norveç in başkentidir."}',
'{k:"Başkentler",s:"Arjantin in başkenti neresidir?",o:["Santiago","Lima","Buenos Aires","Bogota"],d:2,a:"Buenos Aires Arjantin in başkentidir."}',
'{k:"Başkentler",s:"Tayland ın başkenti neresidir?",o:["Hanoi","Bangkok","Jakarta","Manila"],d:1,a:"Bangkok Tayland ın başkentidir."}',
'{k:"Türkiye",s:"Türkiye nin en yüksek dağı hangisidir?",o:["Uludağ","Erciyes","Ağrı Dağı","Süphan Dağı"],d:2,a:"Ağrı Dağı 5137 m ile Türkiye nin en yüksek dağıdır."}',
'{k:"Türkiye",s:"Kapadokya hangi şehirdedir?",o:["Konya","Nevşehir","Kayseri","Aksaray"],d:1,a:"Kapadokya bölgesi ağırlıklı olarak Nevşehir ilindedir."}',
'{k:"Türkiye",s:"Türk bayrağında hangi simgeler vardır?",o:["Güneş ve yıldız","Ay ve yıldız","Yıldız ve çizgi","Hilal ve güneş"],d:1,a:"Türk bayrağında kırmızı zemin üzerinde beyaz ay ve yıldız bulunur."}',
'{k:"Türkiye",s:"Pamukkale hangi ilde bulunur?",o:["Muğla","Denizli","Aydın","Antalya"],d:1,a:"Pamukkale travertenleri Denizli ilinde yer alır."}',
'{k:"Türkiye",s:"Türkiye nin en uzun nehri hangisidir?",o:["Sakarya","Fırat","Kızılırmak","Dicle"],d:2,a:"Kızılırmak 1355 km ile Türkiye nin en uzun nehridir."}',
'{k:"Türkiye",s:"Efes Antik Kenti hangi ilde bulunur?",o:["İzmir","Aydın","Muğla","Antalya"],d:0,a:"Efes Antik Kenti İzmir in Selçuk ilçesindedir."}',
'{k:"Türkiye",s:"Sümela Manastırı hangi ildedir?",o:["Artvin","Rize","Trabzon","Giresun"],d:2,a:"Sümela Manastırı Trabzon un Maçka ilçesindedir."}',
'{k:"Türkiye",s:"Türkiye nin en büyük adası hangisidir?",o:["Bozcaada","Gökçeada","Büyükada","Akdamar"],d:1,a:"Gökçeada Türkiye nin en büyük adasıdır."}',
'{k:"Türkiye",s:"Nemrut Dağı hangi ildedir?",o:["Malatya","Adıyaman","Elazığ","Diyarbakır"],d:1,a:"Nemrut Dağı ve dev heykelleri Adıyaman ilindedir."}',
'{k:"Türkiye",s:"Aspendos Antik Tiyatrosu hangi ildedir?",o:["Mersin","Antalya","İzmir","Muğla"],d:1,a:"Aspendos Antalya nın Serik ilçesindedir."}',
'{k:"Türkiye",s:"Mardin hangi bölgemizdedir?",o:["Akdeniz","Güneydoğu Anadolu","Doğu Anadolu","İç Anadolu"],d:1,a:"Mardin Güneydoğu Anadolu Bölgesindedir."}',
'{k:"Türkiye",s:"Gelibolu Yarımadası hangi ildedir?",o:["Tekirdağ","Edirne","Çanakkale","Balıkesir"],d:2,a:"Gelibolu Yarımadası Çanakkale ilinde yer alır."}',
'{k:"Türkiye",s:"Göbeklitepe hangi ilde bulunur?",o:["Mardin","Diyarbakır","Şanlıurfa","Gaziantep"],d:2,a:"Göbeklitepe dünyanın en eski tapınağı olarak Şanlıurfadadır."}',
'{k:"Türkiye",s:"Türkiye nin en kalabalık şehri hangisidir?",o:["Ankara","İzmir","İstanbul","Bursa"],d:2,a:"İstanbul 15 milyonu aşan nüfusuyla en kalabalık şehirdir."}',
'{k:"Türkiye",s:"Hattuşaş Antik Kenti hangi ildedir?",o:["Çorum","Yozgat","Amasya","Tokat"],d:0,a:"Hitit başkenti Hattuşaş Çorum un Boğazkale ilçesindedir."}',
'{k:"Türkiye",s:"Safranbolu hangi ile bağlıdır?",o:["Kastamonu","Bartın","Karabük","Çankırı"],d:2,a:"Safranbolu Karabük iline bağlı tarihi ilçedir."}',
'{k:"Türkiye",s:"Türkiye nin kaç ili vardır?",o:["79","80","81","82"],d:2,a:"Türkiye 81 ilden oluşmaktadır."}',
'{k:"Türkiye",s:"Çanakkale Boğazı hangi denizleri birleştirir?",o:["Karadeniz-Akdeniz","Ege-Marmara","Marmara-Karadeniz","Akdeniz-Ege"],d:1,a:"Çanakkale Boğazı Ege Denizi ile Marmara Denizini birleştirir."}',
'{k:"Türkiye",s:"Anadolu nun en eski uygarlığı hangisidir?",o:["Romalılar","Hititler","Osmanlılar","Selçuklular"],d:1,a:"Hititler Anadolu nun en eski büyük uygarlıklarından biridir."}',
'{k:"Spor",s:"Futbolda bir takımda kaç oyuncu sahada bulunur?",o:["9","10","11","12"],d:2,a:"Futbolda her takımdan 11 oyuncu sahada bulunur."}',
'{k:"Spor",s:"Olimpiyat Oyunları kaç yılda bir yapılır?",o:["2 yıl","3 yıl","4 yıl","5 yıl"],d:2,a:"Yaz Olimpiyatları 4 yılda bir düzenlenir."}',
'{k:"Spor",s:"Basketbolda bir takımda kaç oyuncu sahadadır?",o:["4","5","6","7"],d:1,a:"Basketbolda her takımdan 5 oyuncu sahada bulunur."}',
'{k:"Spor",s:"Voleybolda bir takımda kaç oyuncu sahadadır?",o:["5","6","7","8"],d:1,a:"Voleybolda her takımdan 6 oyuncu sahada bulunur."}',
'{k:"Spor",s:"Hangi spor dalında raket kullanılır?",o:["Futbol","Basketbol","Tenis","Yüzme"],d:2,a:"Teniste raket ile top vurulur."}',
'{k:"Spor",s:"FIFA Dünya Kupası kaç yılda bir yapılır?",o:["2 yıl","3 yıl","4 yıl","5 yıl"],d:2,a:"FIFA Dünya Kupası 4 yılda bir düzenlenir."}',
'{k:"Spor",s:"Yüzmede hangi stil en hızlıdır?",o:["Kurbağalama","Sırtüstü","Kelebek","Serbest stil"],d:3,a:"Serbest stil en hızlı yüzme stilidir."}',
'{k:"Spor",s:"Maraton kaç kilometredir?",o:["21 km","30 km","42 km","50 km"],d:2,a:"Maraton 42.195 km uzunluğunda bir koşu yarışıdır."}',
'{k:"Spor",s:"Türkiye nin milli sporu hangisidir?",o:["Futbol","Güreş","Okçuluk","Cirit"],d:1,a:"Yağlı güreş Türkiye nin geleneksel milli sporudur."}',
'{k:"Spor",s:"Olimpiyat halkalarında kaç halka vardır?",o:["3","4","5","6"],d:2,a:"Olimpiyat sembolünde 5 kıtayı temsil eden 5 halka bulunur."}',
'{k:"Spor",s:"Kırkpınar güreşleri nerede yapılır?",o:["İstanbul","Edirne","Bursa","Antalya"],d:1,a:"Kırkpınar yağlı güreşleri her yıl Edirne de düzenlenir."}',
'{k:"Spor",s:"Hangi spor dalında file kullanılır?",o:["Futbol","Voleybol","Güreş","Atletizm"],d:1,a:"Voleybol sahanın ortasında file ile oynanır."}',
'{k:"Spor",s:"Atletizmde 100 metre koşusu ne tür bir yarıştır?",o:["Uzun mesafe","Orta mesafe","Sprint","Dayanıklılık"],d:2,a:"100 metre sprint kısa mesafe yarışıdır."}',
'{k:"Spor",s:"Buz hokeyi hangi yüzeyde oynanır?",o:["Çim","Toprak","Buz","Ahşap"],d:2,a:"Buz hokeyi buz üzerinde oynanan bir spordur."}',
'{k:"Spor",s:"Jimnastikte yer hareketleri hangi alanda yapılır?",o:["Ring","Minder","Havuz","Pist"],d:1,a:"Jimnastikte yer hareketleri minder üzerinde yapılır."}',
'{k:"Spor",s:"Kayak sporu hangi mevsimde yapılır?",o:["İlkbahar","Yaz","Sonbahar","Kış"],d:3,a:"Kayak kış mevsiminde karlı dağlarda yapılan bir spordur."}',
'{k:"Spor",s:"Masa tenisinde kullanılan alete ne denir?",o:["Raket","Sopa","Tokmak","Kürek"],d:0,a:"Masa tenisinde raket kullanılır."}',
'{k:"Spor",s:"Golf topunu koymaya çalıştığımız çukura ne denir?",o:["Gol","Basket","Delik","Kale"],d:2,a:"Golfte top deliğe sokulur."}',
'{k:"Spor",s:"Okçulukta hedefe ne denir?",o:["Kale","Pota","Nişangah","Hedef tahtası"],d:3,a:"Okçulukta okların atıldığı dairesel hedefe hedef tahtası denir."}',
'{k:"Spor",s:"Dalış sporunda ayağa ne takılır?",o:["Çorap","Palet","Bot","Kanat"],d:1,a:"Dalış sporunda ayağa palet takılır."}',
'{k:"Spor",s:"Hangi spor aletinde ip kullanılır?",o:["İp atlama","Gülle atma","Disk atma","Cirit atma"],d:0,a:"İp atlama sporunda ip kullanılır."}',
'{k:"Matematik",s:"12 + 15 kaç eder?",o:["25","26","27","28"],d:2,a:"12 + 15 = 27 dir."}',
'{k:"Matematik",s:"Bir düzinede kaç tane vardır?",o:["6","10","12","24"],d:2,a:"Bir düzine 12 adettir."}',
'{k:"Matematik",s:"Üçgenin kaç kenarı vardır?",o:["2","3","4","5"],d:1,a:"Üçgenin 3 kenarı vardır."}',
'{k:"Matematik",s:"50 nin yarısı kaçtır?",o:["20","25","30","35"],d:1,a:"50 nin yarısı 25 tir."}',
'{k:"Matematik",s:"6 x 7 kaç eder?",o:["36","42","48","54"],d:1,a:"6 x 7 = 42 dir."}',
'{k:"Matematik",s:"Bir karede kaç köşe vardır?",o:["2","3","4","5"],d:2,a:"Karenin 4 köşesi vardır."}',
'{k:"Matematik",s:"100 - 37 kaç eder?",o:["57","63","67","73"],d:1,a:"100 - 37 = 63 tür."}',
'{k:"Matematik",s:"8 x 8 kaç eder?",o:["56","62","64","72"],d:2,a:"8 x 8 = 64 tür."}',
'{k:"Matematik",s:"Bir saat kaç dakikadır?",o:["30","45","60","90"],d:2,a:"Bir saat 60 dakikadır."}',
'{k:"Matematik",s:"1 kilometre kaç metredir?",o:["100","500","1000","10000"],d:2,a:"1 kilometre 1000 metredir."}',
'{k:"Matematik",s:"Çift sayılar hangileridir?",o:["1 3 5","2 4 6","1 2 3","3 6 9"],d:1,a:"2 4 6 gibi 2 ye tam bölünen sayılar çift sayılardır."}',
'{k:"Matematik",s:"Bir yılda kaç hafta vardır?",o:["48","50","52","54"],d:2,a:"Bir yılda 52 hafta vardır."}',
'{k:"Matematik",s:"Üçgenin iç açıları toplamı kaç derecedir?",o:["90","120","180","360"],d:2,a:"Üçgenin iç açıları toplamı 180 derecedir."}',
'{k:"Matematik",s:"Bir dakika kaç saniyedir?",o:["30","45","60","100"],d:2,a:"Bir dakika 60 saniyedir."}',
'{k:"Matematik",s:"9 x 9 kaç eder?",o:["72","81","90","99"],d:1,a:"9 x 9 = 81 dir."}',
'{k:"Matematik",s:"Bir dikdörtgenin kaç kenarı vardır?",o:["3","4","5","6"],d:1,a:"Dikdörtgenin 4 kenarı vardır."}',
'{k:"Matematik",s:"25 x 4 kaç eder?",o:["80","90","100","120"],d:2,a:"25 x 4 = 100 dür."}',
'{k:"Matematik",s:"1 ton kaç kilogramdır?",o:["100","500","1000","10000"],d:2,a:"1 ton 1000 kilogramdır."}',
'{k:"Matematik",s:"1 litre kaç mililitredir?",o:["10","100","1000","10000"],d:2,a:"1 litre 1000 mililitredir."}',
'{k:"Matematik",s:"Sıfır tek mi çift mi sayıdır?",o:["Tek","Çift","Hiçbiri","İkisi de"],d:1,a:"Sıfır çift sayıdır çünkü 2 ye tam bölünür."}',
'{k:"Matematik",s:"Beşgenin kaç kenarı vardır?",o:["4","5","6","7"],d:1,a:"Beşgenin 5 kenarı vardır."}',
'{k:"Matematik",s:"7 x 6 kaç eder?",o:["36","42","48","54"],d:1,a:"7 x 6 = 42 dir."}',
'{k:"Matematik",s:"Pi sayısının yaklaşık değeri kaçtır?",o:["2.14","3.14","4.14","5.14"],d:1,a:"Pi sayısı yaklaşık 3.14 tür."}',
'{k:"Matematik",s:"144 ün karekökü kaçtır?",o:["10","11","12","13"],d:2,a:"12 x 12 = 144 karekökü 12 dir."}',
'{k:"Matematik",s:"Çemberin çevresi neyle hesaplanır?",o:["a x b","2 pi r","pi r kare","a kare + b kare"],d:1,a:"Çemberin çevresi 2 pi r formülüyle bulunur."}',
'{k:"Deyimler",s:"Göz boyamak ne anlama gelir?",o:["Güzel görmek","Aldatmak","Boyamak","Bakmak"],d:1,a:"Göz boyamak gerçeği gizleyerek iyi göstermeye çalışmak demektir."}',
'{k:"Deyimler",s:"Kulak misafiri olmak ne demektir?",o:["Kulağı ağrımak","Gizlice dinlemek","İyi duymak","Yardım etmek"],d:1,a:"Kulak misafiri olmak istemeden başkalarının konuşmasını duymaktır."}',
'{k:"Deyimler",s:"Baş tacı etmek ne anlama gelir?",o:["Taç giydirmek","Çok değer vermek","Kızmak","Başa geçmek"],d:1,a:"Bir kişiye çok değer vermek saygı göstermek demektir."}',
'{k:"Deyimler",s:"Dört gözle beklemek ne demektir?",o:["Gözlük takmak","Sabırsızca beklemek","Uzun süre bakmak","Görmemek"],d:1,a:"Bir şeyi sabırsızlıkla ve heyecanla beklemektir."}',
'{k:"Deyimler",s:"Ağzı açık kalmak ne anlama gelir?",o:["Konuşamamak","Çok şaşırmak","Uykusu gelmek","Acıkmak"],d:1,a:"Bir şeye çok şaşırmak hayrete düşmek demektir."}',
'{k:"Deyimler",s:"İğne ile kuyu kazmak ne demektir?",o:["Su aramak","Çok zor bir işi sabırla yapmak","Kuyu kazmak","Terzilik yapmak"],d:1,a:"Çok zor ve uzun sürecek bir işi sabırla yapmak demektir."}',
'{k:"Deyimler",s:"El üstünde tutmak ne anlama gelir?",o:["Taşımak","Çok değer vermek","İtmek","Uzaklaştırmak"],d:1,a:"Bir kişiye çok değer verip onu önemli kılmak demektir."}',
'{k:"Deyimler",s:"Gözden düşmek ne demektir?",o:["Düşmek","İtibar kaybetmek","Görmemek","Bayılmak"],d:1,a:"Birinin gözünde değerini ve itibarını kaybetmek demektir."}',
'{k:"Deyimler",s:"Burnundan kıl aldırmamak ne demektir?",o:["Temiz olmak","Çok sinirli ve geçimsiz olmak","Hasta olmak","Mutlu olmak"],d:1,a:"Çok huysuz ve geçimsiz olmak kimsenin lafını dinlememek demektir."}',
'{k:"Deyimler",s:"Yüzü gülmek ne anlama gelir?",o:["Gülmek","Mutlu ve sevinçli olmak","Şaka yapmak","Komik olmak"],d:1,a:"Mutlu ve memnun olduğu yüzünden belli olmak demektir."}',
'{k:"Deyimler",s:"Kol kanat germek ne demektir?",o:["Uçmak","Korumak ve yardım etmek","Kolları açmak","Dans etmek"],d:1,a:"Birini korumak ona sahip çıkmak ve yardım etmek demektir."}',
'{k:"Deyimler",s:"Devede kulak kalmak ne demektir?",o:["Deveye binmek","Çok az ve yetersiz kalmak","Kulak ağrısı","Hayvanları sevmek"],d:1,a:"Yapılanın çok az ve yetersiz kalması demektir."}',
'{k:"Deyimler",s:"Yüreği ağzına gelmek ne demektir?",o:["Hasta olmak","Çok korkmak","Yemek yemek","Sevinmek"],d:1,a:"Çok korkmak heyecandan yüreğinin yerinden çıkacakmış gibi hissetmek demektir."}',
'{k:"Deyimler",s:"Dil dökmek ne anlama gelir?",o:["Konuşmak","Birini ikna etmek için çok konuşmak","Yemek pişirmek","Şarkı söylemek"],d:1,a:"Birini ikna etmek veya kandırmak için çok ve etkili konuşmak demektir."}',
'{k:"Deyimler",s:"Tüyleri diken diken olmak ne demektir?",o:["Üşümek","Çok etkilenmek veya korkmak","Terleme","Uyumak"],d:1,a:"Korku heyecan veya hayretten çok etkilenmek demektir."}',
'{k:"Deyimler",s:"Parmak ısırmak ne demektir?",o:["Parmağını yemek","Çok şaşırmak veya pişman olmak","Acıkmak","Düşünmek"],d:1,a:"Çok şaşırmak veya pişmanlık duymak demektir."}',
'{k:"Deyimler",s:"Gözü kara olmak ne anlama gelir?",o:["Görmemek","Hiçbir şeyden korkmamak","Kör olmak","Ağlamak"],d:1,a:"Sonuçlarını düşünmeden cesurca davranmak demektir."}',
'{k:"Deyimler",s:"Etekleri zil çalmak ne demektir?",o:["Müzik yapmak","Çok sevinmek","Dans etmek","Etek giymek"],d:1,a:"Çok sevinmek mutluluktan uçmak demektir."}',
'{k:"Deyimler",s:"Çam devirmek ne anlama gelir?",o:["Ağaç kesmek","Büyük bir hata yapmak","Ormanda gezmek","Yardım etmek"],d:1,a:"Toplum içinde büyük bir gaf yapmak demektir."}',
'{k:"Deyimler",s:"Kaşla göz arasında ne demektir?",o:["Yüze bakmak","Çok kısa sürede fark ettirmeden","Makyaj yapmak","Gülümsemek"],d:1,a:"Çok kısa bir sürede kimse fark etmeden bir işi yapmak demektir."}',
'{k:"Deyimler",s:"Kılı kırk yarmak ne anlama gelir?",o:["Berber olmak","Çok titiz ve detaycı olmak","Saç kesmek","Temizlik yapmak"],d:1,a:"Bir işi son derece titiz ve özenli şekilde yapmak demektir."}',
'{k:"Deyimler",s:"Saman altından su yürütmek ne demektir?",o:["Çiftçilik","Gizlice iş çevirmek","Su taşımak","Tarla sulamak"],d:1,a:"Gizli gizli kimseye belli etmeden işler çevirmek demektir."}',
'{k:"Deyimler",s:"Taşı sıksa suyunu çıkarır ne anlama gelir?",o:["Güçlü olmak","Çok cimri olmak","Taş kırmak","Su bulmak"],d:1,a:"Çok cimri olan parasını hiç harcamayan kişi için kullanılır."}',
'{k:"Deyimler",s:"Pişmiş aşa su katmak ne demektir?",o:["Yemek yapmak","Olmuş işi bozmaya çalışmak","Su içmek","Yardım etmek"],d:1,a:"Olmuş bitmiş bir işi bozmaya çalışmak demektir."}',
'{k:"Deyimler",s:"Abayı yakmak ne demektir?",o:["Ateş yakmak","Birine aşık olmak","Ütü yapmak","Kızmak"],d:1,a:"Birine çok aşık olmak tutkuyla bağlanmak demektir."}',
'{k:"Atasözleri",s:"Damlaya damlaya göl olur ne anlatır?",o:["Su birikir","Azla yetinmek lazım","Küçük birikimler büyük sonuç verir","Göl oluşumu"],d:2,a:"Küçük küçük biriktirilen şeyler zamanla büyük sonuçlar doğurur."}',
'{k:"Atasözleri",s:"Sakla samanı gelir zamanı ne demektir?",o:["Saman topla","Her şeyin lazım olacağı gün gelir","Hayvanlara yem ver","Temizlik yap"],d:1,a:"Bugün gereksiz gibi görünen şeylerin bir gün lazım olacağını anlatır."}',
'{k:"Atasözleri",s:"Ağaç yaşken eğilir ne anlatır?",o:["Ağaçlar eğilir","İnsan küçükken eğitilir","Ağaç kesmek","Rüzgar eser"],d:1,a:"Eğitim küçük yaşta verilmelidir."}',
'{k:"Atasözleri",s:"Bir elin nesi var iki elin sesi var ne demektir?",o:["Müzik yapmak","Birlik güç demektir","El çırpmak","Parmak saymak"],d:1,a:"İş birliği yaparak daha güçlü sonuçlar elde edilir."}',
'{k:"Atasözleri",s:"Yuvarlanan taş yosun tutmaz ne anlatır?",o:["Taşlar yuvarlanır","Sürekli yer değiştiren tutunmaz","Doğa güzeldir","Taş toplama"],d:1,a:"Sürekli iş veya yer değiştiren kişi bir yerde tutunamaz."}',
'{k:"Atasözleri",s:"Gülme komşuna gelir başına ne demektir?",o:["Komşuyla gülmek","Başkasına gülme sana da gelebilir","Eğlenmek","Şaka yapmak"],d:1,a:"Başkalarının kötü durumuna gülme aynı şey sana da olabilir."}',
'{k:"Atasözleri",s:"Acele işe şeytan karışır ne anlatır?",o:["Şeytan kötüdür","Acele edilen iş hatalı olur","Hızlı koşmak","İşe gitmek"],d:1,a:"Acele yapılan işlerde hata yapılma olasılığı yüksektir."}',
'{k:"Atasözleri",s:"Komşu komşunun külüne muhtaçtır ne demektir?",o:["Kül toplamak","İnsanlar birbirine ihtiyaç duyar","Ateş yakmak","Temizlik yapmak"],d:1,a:"İnsanlar en küçük şeyde bile birbirine muhtaç olabilir."}',
'{k:"Atasözleri",s:"Ak akçe kara gün içindir ne demektir?",o:["Para biriktirmek","Zor günler için tasarruf et","Siyah beyaz","Harcamak"],d:1,a:"Zor zamanlar için önceden tasarruf yapılmalıdır."}',
'{k:"Atasözleri",s:"İşleyen demir ışıldar ne anlatır?",o:["Demir parlar","Çalışan insan gelişir","Metal işleme","Fabrika"],d:1,a:"Sürekli çalışan emek veren kişi gelişir ve başarılı olur."}',
'{k:"Atasözleri",s:"Bakarsan bağ olur bakmazsan dağ olur ne demektir?",o:["Bahçe işleri","İlgilenirsen güzel ilgilenmezsen bozulur","Dağa çıkmak","Üzüm toplamak"],d:1,a:"Bir işle ilgilenirsen verimli olur ihmal edersen bozulur."}',
'{k:"Atasözleri",s:"Ayağını yorganına göre uzat ne anlatır?",o:["Uyumak","Harcamayı gelirine göre yap","Yorgan almak","Uzanmak"],d:1,a:"İmkanların ölçüsünde harcama yap."}',
'{k:"Atasözleri",s:"Dost kara günde belli olur ne demektir?",o:["Kara günler kötüdür","Gerçek dost zor zamanda yanında olur","Arkadaş edinmek","Gece gezmek"],d:1,a:"Gerçek dostluk zor zamanlarda belli olur."}',
'{k:"Atasözleri",s:"Bal tutan parmağını yalar ne anlatır?",o:["Bal yemek","İşin başındaki kişi fayda sağlar","Temizlik","Parmak saymak"],d:1,a:"Değerli bir işin başında olan kişi bundan pay çıkarır."}',
'{k:"Atasözleri",s:"Atı alan Üsküdarı geçti ne demektir?",o:["At yarışı","Fırsatı kaçırmak","Üsküdara gitmek","Ata binmek"],d:1,a:"Fırsat kaçmıştır artık yapılacak bir şey kalmamıştır."}',
'{k:"Atasözleri",s:"Her yokuşun bir inişi vardır ne anlatır?",o:["Dağ tırmanışı","Zor günlerin ardından iyi günler gelir","Yol yapmak","Araba sürmek"],d:1,a:"Zorluklar sonsuza dek sürmez her sıkıntının bir sonu vardır."}',
'{k:"Atasözleri",s:"Mum dibine ışık vermez ne demektir?",o:["Mum söner","Yakındakilere faydası olmaz","Karanlık olur","Mum yakmak"],d:1,a:"Kişi en yakınındakilere yardım edemeyebilir."}',
'{k:"Atasözleri",s:"Sütten ağzı yanan yoğurdu üfleyerek yer ne anlatır?",o:["Yoğurt yemek","Kötü tecrübe yaşayan aşırı tedbirli olur","Süt içmek","Yemek yapmak"],d:1,a:"Daha önce kötü deneyim yaşayan kişi aşırı temkinli davranır."}',
'{k:"Atasözleri",s:"Tatlı dil yılanı deliğinden çıkarır ne anlatır?",o:["Yılan avlamak","Güzel konuşma her kapıyı açar","Şeker yemek","Delik kazmak"],d:1,a:"Güzel ve nazik konuşmayla en zor insanlar bile ikna edilebilir."}',
'{k:"Atasözleri",s:"Bugünün işini yarına bırakma ne demektir?",o:["Yarın tatil","İşlerini zamanında yap","Uyumak lazım","Erken kalkmak"],d:1,a:"İşleri ertelemeden zamanında bitirmek gerekir."}',
'{k:"Atasözleri",s:"El elden üstündür ne anlatır?",o:["El sıkmak","Her zaman daha iyisi vardır","Yardım etmek","Parmak saymak"],d:1,a:"Ne kadar iyi olursan ol senden daha iyisi mutlaka vardır."}',
'{k:"Atasözleri",s:"Körle yatan şaşı kalkar ne demektir?",o:["Uyumak","Kötü arkadaş kötü alışkanlık verir","Doktor olmak","Yardım etmek"],d:1,a:"Kötü çevreyle vakit geçiren kişi onlardan olumsuz etkilenir."}',
'{k:"Atasözleri",s:"Yazın başı pişenin kışın aşı pişer ne anlatır?",o:["Yemek pişirmek","Önceden hazırlık yapan sonra rahat eder","Mevsimler","Güneşte kalmak"],d:1,a:"Zamanında çalışıp hazırlık yapan kişi sonra sıkıntı çekmez."}',
'{k:"Atasözleri",s:"Minareyi çalan kılıfını hazırlar ne demektir?",o:["Minare yapmak","Büyük iş yapan önceden tedbir alır","Kılıf dikmek","Cami inşaatı"],d:1,a:"Büyük bir iş yapmaya kalkan kişi sonucuna da hazırlıklı olmalıdır."}',
'{k:"Atasözleri",s:"Bana dokunmayan yılan bin yaşasın ne anlatır?",o:["Yılanları sevmek","Bencilce düşünmek","Hayvanları korumak","Doğa sevgisi"],d:1,a:"Kendi başına gelmediği sürece başkalarının sorunuyla ilgilenmemek."}',
'{k:"Tarih",s:"Cumhuriyet ne zaman ilan edildi?",o:["1920","1921","1923","1924"],d:2,a:"Türkiye Cumhuriyeti 29 Ekim 1923 te ilan edilmiştir."}',
]

import os
filepath = os.path.join("c:", os.sep, "Users", "safir", "OneDrive", "Masaüstü", "SmartCampusAI", "views", "_by_ilkokul.txt")

with open(filepath, "a", encoding="utf-8") as f:
    for q in questions:
        f.write(q + "\n")

# Count and verify
with open(filepath, "r", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip().startswith("{k:")]
    print(f"Total: {len(lines)}")
    cats = {}
    for l in lines:
        cat = l.split('"')[1]
        cats[cat] = cats.get(cat, 0) + 1
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")
