#!/usr/bin/env python3
"""Generate remaining lise questions - part 2"""
import os

questions = [
# Tarih +6 (to 50)
'{k:"Tarih",s:"Müdafaa-i Hukuk Cemiyetleri ne amaçla kuruldu?",o:["Ticaret","İşgallere karşı direniş","Eğitim","Tarım"],d:1,a:"Müdafaa-i Hukuk Cemiyetleri işgallere karşı halkın haklarını savunmak için kurulmuştur."}',
'{k:"Tarih",s:"Misak-ı Milli hangi yılda kabul edildi?",o:["1918","1919","1920","1921"],d:2,a:"Misak-ı Milli 28 Ocak 1920 de son Osmanlı Meclisinde kabul edilmiştir."}',
'{k:"Tarih",s:"Takrir-i Sükun Kanunu ne amaçla çıkarıldı?",o:["Ekonomi","İç güvenlik ve muhalefeti bastırma","Eğitim","Sağlık"],d:1,a:"Takrir-i Sükun Kanunu 1925 te Şeyh Said isyanı sonrası çıkarılmıştır."}',
'{k:"Tarih",s:"Osmanlıda Divan-ı Hümayun ne işe yarardı?",o:["Askeri karargah","Devlet yönetim kurulu","Mahkeme","Ticaret odası"],d:1,a:"Divan-ı Hümayun Osmanlı Devletinin en yüksek yönetim organıydı."}',
'{k:"Tarih",s:"Coğrafi Keşifler hangi yüzyılda yoğunlaştı?",o:["13. yy","14. yy","15. yy","17. yy"],d:2,a:"Coğrafi Keşifler 15. ve 16. yüzyıllarda yoğunlaşmıştır."}',
'{k:"Tarih",s:"Osmanlıda Tımar sistemi neyi ifade eder?",o:["Ticaret","Toprak yönetim sistemi","Eğitim","Denizcilik"],d:1,a:"Tımar sistemi devlete ait toprakların sipahilere verildiği askeri-tarımsal düzendir."}',
# Coğrafya +24 (to 50)
'{k:"Coğrafya",s:"Türkiye nin en büyük ovası hangisidir?",o:["Çukurova","Konya Ovası","Bafra Ovası","Muş Ovası"],d:1,a:"Konya Ovası Türkiye nin en geniş ovasıdır."}',
'{k:"Coğrafya",s:"Plato ile ova arasındaki fark nedir?",o:["Boyut","Plato yüksekte düz alan ova alçakta","Renk","İklim"],d:1,a:"Plato yüksek ve düz araziyken ova alçak ve düz alanları ifade eder."}',
'{k:"Coğrafya",s:"Sübtropikal iklim kuşağı nerelerde görülür?",o:["Kutuplar","Ekvator","Dönenceler civarı","Kuzey Kutup Dairesi"],d:2,a:"Sübtropikal iklim tropikal kuşak ile ılıman kuşak arasında dönenceler civarında görülür."}',
'{k:"Coğrafya",s:"Karstik göl nasıl oluşur?",o:["Volkanla","Kireçtaşının erimesiyle oluşan çukurda","Buzulla","Heyelanla"],d:1,a:"Karstik göl kireçtaşının erimesiyle oluşan çukurlarda su birikmesiyle meydana gelir."}',
'{k:"Coğrafya",s:"Set gölü nasıl oluşur?",o:["Depremle","Heyelan veya lav akıntısıyla nehrin önünün kapanması","Rüzgarla","Buzulla"],d:1,a:"Set gölü heyelan lav akıntısı veya birikinti ile nehir yatağının önünün kapanmasıyla oluşur."}',
'{k:"Coğrafya",s:"Türkiye de Akdeniz iklimi nerelerde görülür?",o:["Karadeniz kıyıları","Akdeniz ve Ege kıyıları","İç Anadolu","Doğu Anadolu"],d:1,a:"Akdeniz iklimi Akdeniz ve Ege kıyılarında görülür."}',
'{k:"Coğrafya",s:"Tuzluluk oranı en yüksek deniz hangisidir?",o:["Akdeniz","Karadeniz","Lut Gölü (Ölü Deniz)","Kızıldeniz"],d:2,a:"Ölü Deniz (Lut Gölü) dünyanın tuzluluk oranı en yüksek su kütlesidir."}',
'{k:"Coğrafya",s:"Delta ovaları hangi özelliğe sahiptir?",o:["Kurak","Alüvyon bakımından zengin verimli","Dağlık","Volkanik"],d:1,a:"Delta ovaları nehirlerin alüvyon biriktirmesiyle oluşan çok verimli alanlardır."}',
'{k:"Coğrafya",s:"Türkiye de en önemli krom yatakları nerededir?",o:["Batı Anadolu","Güneydoğu ve İç Anadolu","Karadeniz","Ege"],d:1,a:"Krom yatakları Elazığ Eskişehir ve Güneydoğu Anadolu da yoğunlaşmıştır."}',
'{k:"Coğrafya",s:"Dünyanın en yağışlı yeri neresidir?",o:["Amazon","Cherrapunji Hindistan","Kongo","Borneo"],d:1,a:"Hindistan daki Cherrapunji (Mawsynram) dünyanın en yağışlı yeri olarak bilinir."}',
'{k:"Coğrafya",s:"Graben nedir?",o:["Dağ","Fay hatları arasında çökmüş alan","Volkan","Plato"],d:1,a:"Graben iki fay hattı arasında çökmüş tektonik çukurluktur."}',
'{k:"Coğrafya",s:"Horst nedir?",o:["Çukur","Fay hatları arasında yükselmiş alan","Göl","Ova"],d:1,a:"Horst iki fay hattı arasında yükselmiş bloktur."}',
'{k:"Coğrafya",s:"Bor madeni en çok hangi ülkede bulunur?",o:["ABD","Rusya","Türkiye","Çin"],d:2,a:"Türkiye dünya bor rezervlerinin yaklaşık yüzde 73 üne sahiptir."}',
'{k:"Coğrafya",s:"Maki bitki örtüsü nerelerde görülür?",o:["Kurak bölgeler","Akdeniz iklim kuşağı","Tropikal bölge","Kutuplar"],d:1,a:"Maki Akdeniz ikliminin hüküm sürdüğü yerlerde görülen bodur ağaç ve çalılıklardır."}',
'{k:"Coğrafya",s:"Türkiye nin en uzun sınırı hangi ülkeyledir?",o:["Irak","İran","Suriye","Bulgaristan"],d:2,a:"Türkiye nin en uzun kara sınırı Suriye iledir."}',
'{k:"Coğrafya",s:"Beşeri coğrafya neyi inceler?",o:["Fiziki arazi","İnsan ve mekan ilişkisi","Hava durumu","Kayaçlar"],d:1,a:"Beşeri coğrafya insanların mekanla ilişkisini nüfus yerleşme ekonomi gibi konuları inceler."}',
'{k:"Coğrafya",s:"Sıcak çöl ikliminin en belirgin özelliği nedir?",o:["Çok yağışlı","Gece-gündüz sıcaklık farkı çok yüksek","Ilıman","Nemli"],d:1,a:"Sıcak çöllerde gece-gündüz sıcaklık farkı 40-50 dereceyi bulabilir."}',
'{k:"Coğrafya",s:"Dalmaçya tipi kıyı nasıl oluşur?",o:["Akarsu erozyonuyla","Dağların kıyıya paralel uzanıp vadilerin deniz suyu altında kalmasıyla","Volkanla","Buzulla"],d:1,a:"Dalmaçya tipi kıyı dağların kıyıya paralel uzandığı ve vadilerin suyla dolduğu kıyılardır."}',
'{k:"Coğrafya",s:"Ria tipi kıyı nasıl oluşur?",o:["Volkanla","Akarsu vadilerinin deniz suyu altında kalmasıyla","Rüzgarla","Buzulla"],d:1,a:"Ria tipi kıyı akarsu vadilerinin deniz seviyesi yükselmesiyle suyla dolmasıyla oluşur."}',
'{k:"Coğrafya",s:"Fjord tipi kıyı nasıl oluşur?",o:["Volkanla","Buzul vadilerinin suyla dolmasıyla","Rüzgarla","Akarsuyla"],d:1,a:"Fjord tipi kıyılar buzul vadilerinin deniz suyu ile dolmasıyla oluşan derin girintilerdir."}',
'{k:"Coğrafya",s:"Skyer (şist) hangi kayaç türüne aittir?",o:["Magmatik","Tortul","Başkalaşım (metamorfik)","Volkanik"],d:2,a:"Şist başkalaşım (metamorfik) kayaçlardandır."}',
'{k:"Coğrafya",s:"Türkiye de jeotermal enerji potansiyeli en yüksek bölge hangisidir?",o:["Karadeniz","Ege","İç Anadolu","Doğu Anadolu"],d:1,a:"Ege Bölgesi fay hatları nedeniyle Türkiye nin en yüksek jeotermal enerji potansiyeline sahiptir."}',
# Bilim +24 (to 50)
'{k:"Bilim",s:"Termodinamiğin ikinci yasası neyi belirtir?",o:["Enerji korunur","Entropi sürekli artar","Sıcaklık sabit kalır","Basınç azalır"],d:1,a:"Termodinamiğin ikinci yasası kapalı bir sistemde entropinin sürekli arttığını belirtir."}',
'{k:"Bilim",s:"Genelleştirilmiş görelilik kuramı neyi açıklar?",o:["Atomlar","Kütlenin uzay-zamanı bükmesi ve kütleçekim","Işık hızı","Elektrik"],d:1,a:"Einstein in genel görelilik kuramı kütleçekimi uzay-zamanın bükülmesi olarak açıklar."}',
'{k:"Bilim",s:"Higgs bozonu niçin önemlidir?",o:["Enerji üretimi","Parçacıklara kütle kazandıran mekanizma","Işık hızı","Nükleer enerji"],d:1,a:"Higgs bozonu parçacıklara kütlelerini kazandıran Higgs alanıyla ilişkili parçacıktır."}',
'{k:"Bilim",s:"Karanlık madde ne demektir?",o:["Siyah delik","Gözlemlenemeyen ama çekim etkisi olan madde","Kara enerji","Nötron"],d:1,a:"Karanlık madde gözlemlenemeyen ancak kütleçekim etkisiyle varlığı bilinen maddedir."}',
'{k:"Bilim",s:"Genetik mühendisliği ne amaçla kullanılır?",o:["Araba üretimi","Canlıların genlerini değiştirme","Maden arama","Havayolu"],d:1,a:"Genetik mühendisliği canlıların DNA sını değiştirmek için kullanılır."}',
'{k:"Bilim",s:"Redoks tepkimesi nedir?",o:["Asit-baz","Elektron alışverişi tepkimesi","Nükleer","Fisyon"],d:1,a:"Redoks tepkimesi elektron alışverişinin (yükseltgenme-indirgenme) olduğu tepkimedir."}',
'{k:"Bilim",s:"Hücre zarı hangi moleküllerden oluşur?",o:["Karbonhidrat","Fosfolipid çift tabaka","Sadece protein","Nükleik asit"],d:1,a:"Hücre zarı fosfolipid çift tabakasından ve proteinlerden oluşur."}',
'{k:"Bilim",s:"Kuvantum dolanıklık nedir?",o:["Elektrik","İki parçacığın birbirine bağlı kuantum durumu","Çekim kuvveti","Manyetik alan"],d:1,a:"Kuantum dolanıklık iki parçacığın mesafeden bağımsız olarak birbirine bağlı davranmasıdır."}',
'{k:"Bilim",s:"Proton kütle birimi olarak kaç amu dur?",o:["0.5","1","2","4"],d:1,a:"Protonun kütlesi yaklaşık 1 atom kütle birimi (amu) dir."}',
'{k:"Bilim",s:"Standart Modelde kaç temel kuvvet vardır?",o:["2","3","4","5"],d:2,a:"Standart Modelde 4 temel kuvvet vardır: kütle çekim elektromanyetik güçlü ve zayıf nükleer."}',
'{k:"Bilim",s:"Antibiyotikler neye karşı etkilidir?",o:["Virüslere","Bakterilere","Mantarlara","Parazitlere"],d:1,a:"Antibiyotikler bakterilere karşı etkili ilaçlardır virüslere karşı etkisizdir."}',
'{k:"Bilim",s:"İzotop ne demektir?",o:["Farklı element","Aynı elementin farklı nötron sayılı türleri","Bileşik","Alaşım"],d:1,a:"İzotoplar aynı elementin farklı nötron sayısına sahip türleridir."}',
'{k:"Bilim",s:"Schrodinger denklemi neyi tanımlar?",o:["Çekim kuvveti","Kuantum mekaniğinde dalga fonksiyonu","Işık hızı","Ses dalgası"],d:1,a:"Schrodinger denklemi kuantum mekaniğinde parçacığın dalga fonksiyonunu tanımlar."}',
'{k:"Bilim",s:"Fotosentezde ışık tepkimeleri nerede gerçekleşir?",o:["Mitokondri","Tilakoid zarında","Hücre çekirdeğinde","Ribozomda"],d:1,a:"Fotosentezin ışık tepkimeleri kloroplastın tilakoid zarında gerçekleşir."}',
'{k:"Bilim",s:"Krebs döngüsü nerede gerçekleşir?",o:["Sitoplazma","Hücre zarı","Mitokondri matriks","Çekirdek"],d:2,a:"Krebs döngüsü mitokondrinin matriksinde gerçekleşen metabolik döngüdür."}',
'{k:"Bilim",s:"Nötrinonun özelliği nedir?",o:["Ağır parçacık","Çok küçük kütleli zayıf etkileşimli parçacık","Protondan büyük","Yüklü parçacık"],d:1,a:"Nötrino çok küçük kütleli nötr ve maddeyle çok zayıf etkileşen parçacıktır."}',
'{k:"Bilim",s:"Manyetik rezonans görüntüleme (MR) hangi prensiple çalışır?",o:["X ışını","Manyetik alan ve radyo dalgası","Ultrason","Lazer"],d:1,a:"MR güçlü manyetik alan ve radyo dalgaları kullanarak vücuttaki hidrojen atomlarını görüntüler."}',
'{k:"Bilim",s:"Plazma ne tür bir maddedir?",o:["Katı","Sıvı","Gaz","Maddenin dördüncü hali"],d:3,a:"Plazma iyonize gaz olarak bilinen maddenin dördüncü halidir."}',
'{k:"Bilim",s:"Supernova nedir?",o:["Yeni gezegen","Büyük bir yıldızın patlayarak parlaması","Kara delik","Kuasar"],d:1,a:"Supernova büyük bir yıldızın ömrünün sonunda patlayarak muazzam parlaklıkla parlamasıdır."}',
'{k:"Bilim",s:"Elektroliz ne demektir?",o:["Isıyla ayrışma","Elektrik akımıyla bileşikleri ayrıştırma","Nükleer parçalanma","Yanma"],d:1,a:"Elektroliz elektrik akımı kullanarak bileşikleri bileşenlerine ayırma işlemidir."}',
'{k:"Bilim",s:"Allotropi ne demektir?",o:["Farklı element","Aynı elementin farklı fiziksel yapıları","İzotop","Bileşik"],d:1,a:"Allotropi aynı elementin farklı fiziksel yapılarda bulunmasıdır (elmas ve grafit gibi)."}',
'{k:"Bilim",s:"Le Chatelier prensibi neyi ifade eder?",o:["Enerji korunumu","Denge sistemi değişikliğe karşı tepki verir","Kütle korunumu","Entropi artışı"],d:1,a:"Le Chatelier prensibi dengedeki bir sisteme dışarıdan etki yapıldığında sistemin bu etkiyi azaltacak yönde tepki verdiğini belirtir."}',
'{k:"Bilim",s:"pH skalasında 1 ne anlama gelir?",o:["Nötr","Güçlü asit","Güçlü baz","Saf su"],d:1,a:"pH 1 çok güçlü asidik çözeltiyi ifade eder."}',
'{k:"Bilim",s:"Süperiletkenlik ne demektir?",o:["Normal iletim","Sıfır direnç ile elektrik iletimi","Yüksek direnç","Isı iletimi"],d:1,a:"Süperiletkenlik belirli sıcaklıkların altında bir malzemenin sıfır elektrik direnci göstermesidir."}',
# Doğa (50)
'{k:"Doğa",s:"Biyom nedir?",o:["Tek tür","Benzer iklim ve bitki örtüsüne sahip geniş ekosistem","Hayvan grubu","Toprak türü"],d:1,a:"Biyom benzer iklim koşullarına ve bitki örtüsüne sahip büyük ekolojik bölgedir."}',
'{k:"Doğa",s:"Tropik yağmur ormanlarının en önemli özelliği nedir?",o:["Düşük nem","Yüksek biyolojik çeşitlilik","Soğuk iklim","Az yağış"],d:1,a:"Tropik yağmur ormanları dünyanın en yüksek biyolojik çeşitliliğine sahip biyomlardır."}',
'{k:"Doğa",s:"Ötrofikasyon ne demektir?",o:["Oksijen artışı","Göl ve nehirlerde aşırı besin maddesi birikimi","Kuraklık","Erozyon"],d:1,a:"Ötrofikasyon su kütlelerinde aşırı besin maddesi birikimi sonucu alg patlaması ve oksijen azalmasıdır."}',
'{k:"Doğa",s:"Endemik tür ne demektir?",o:["Yaygın tür","Sadece belirli bir bölgede yaşayan tür","Göçmen tür","Nesli tükenmiş tür"],d:1,a:"Endemik tür yalnızca belirli bir coğrafi bölgede doğal olarak yaşayan türdür."}',
'{k:"Doğa",s:"Karbon ayak izi ne demektir?",o:["Ayak izi","Bireyin veya kuruluşun ürettiği sera gazı miktarı","Karbon elementi","Toprak izi"],d:1,a:"Karbon ayak izi bir faaliyetin doğrudan ve dolaylı olarak ürettiği sera gazı miktarıdır."}',
'{k:"Doğa",s:"Biyoçeşitlilik kaybının en büyük nedeni nedir?",o:["Doğal afetler","Habitat tahribatı","Volkanlar","Depremler"],d:1,a:"Habitat tahribatı ve parçalanması biyoçeşitlilik kaybının en büyük nedenidir."}',
'{k:"Doğa",s:"Kırmızı Liste ne demektir?",o:["Alışveriş listesi","IUCN nesli tehlike altındaki türler listesi","Yasaklı maddeler","Tehlikeli bölgeler"],d:1,a:"IUCN Kırmızı Liste nesli tehlike altındaki türlerin uluslararası sınıflandırma listesidir."}',
'{k:"Doğa",s:"İstilacı tür ne demektir?",o:["Yerli tür","Yabancı ortamda hızla yayılıp zarar veren tür","Göçmen tür","Endemik tür"],d:1,a:"İstilacı tür doğal ortamının dışına yayılarak ekosisteme zarar veren türdür."}',
'{k:"Doğa",s:"Permakültür ne demektir?",o:["Gübreleme","Doğaya uyumlu sürdürülebilir tarım sistemi","Endüstriyel tarım","Monokültür"],d:1,a:"Permakültür doğal ekosistemleri taklit eden sürdürülebilir tarım ve yaşam tasarım sistemidir."}',
'{k:"Doğa",s:"Okyanusların asitlenmesi neyin sonucudur?",o:["Volkanik aktivite","CO2 emiliminin artması","Rüzgar","Gel-git"],d:1,a:"Okyanuslar atmosferden artan CO2 yi emerek asitlenir ve mercan resifleri tehlikeye girer."}',
'{k:"Doğa",s:"Azot döngüsünde azot fiksasyonu ne demektir?",o:["Azotun yok olması","Atmosferik azotun biyolojik kullanılabilir forma dönüşmesi","Azot gazı üretimi","Amonyak yıkımı"],d:1,a:"Azot fiksasyonu atmosferdeki N2 nin bitkilerin kullanabileceği forma dönüştürülmesidir."}',
'{k:"Doğa",s:"Mercan ağarması neden olur?",o:["Soğuk su","Deniz suyunun ısınmasıyla simbiyotik alglerin kaybı","Kirlilik","Tuzluluk"],d:1,a:"Mercan ağarması su sıcaklığının artmasıyla mercanların simbiyotik alglerini kaybetmesidir."}',
'{k:"Doğa",s:"Suksesyon ne demektir?",o:["Ölüm","Bir ekosistemde zamanla tür kompozisyonunun değişmesi","Göç","Avcılık"],d:1,a:"Suksesyon bir ekosistemin zamanla tür kompozisyonu ve yapısının değişim sürecidir."}',
'{k:"Doğa",s:"Ticari avcılığın en büyük kurbanı hangi hayvan grubudur?",o:["Kuşlar","Deniz memelileri ve balıklar","Sürüngenler","Böcekler"],d:1,a:"Ticari avcılık özellikle deniz memelileri ve balıkları tehdit etmektedir."}',
'{k:"Doğa",s:"Yenilenebilir enerji kaynakları hangileridir?",o:["Kömür petrol","Güneş rüzgar hidroelektrik","Doğalgaz","Uranyum"],d:1,a:"Güneş rüzgar ve hidroelektrik yenilenebilir enerji kaynaklarıdır."}',
'{k:"Doğa",s:"Ozon deliğinin en büyük nedeni nedir?",o:["CO2","CFC gazları","Metan","Su buharı"],d:1,a:"Kloroflorokarbon (CFC) gazları ozon tabakasının incelmesinin en büyük nedenidir."}',
'{k:"Doğa",s:"Mangrove ormanları neden önemlidir?",o:["Kereste","Kıyı koruma ve biyoçeşitlilik","Süs bitkisi","Yakacak"],d:1,a:"Mangrove ormanları kıyıları fırtınadan korur ve zengin biyoçeşitliliğe ev sahipliği yapar."}',
'{k:"Doğa",s:"Toprak kirliliğinin en büyük nedeni nedir?",o:["Rüzgar","Tarım kimyasalları ve sanayi atıkları","Yağmur","Güneş"],d:1,a:"Pestisit gübre ve endüstriyel atıklar toprak kirliliğinin en büyük nedenleridir."}',
'{k:"Doğa",s:"Su ayak izi ne demektir?",o:["Ayak yıkama","Bir ürünün üretimi için harcanan toplam su","Yağmur ölçümü","Nehir akışı"],d:1,a:"Su ayak izi bir ürün veya hizmetin üretimi için doğrudan ve dolaylı kullanılan toplam su miktarıdır."}',
'{k:"Doğa",s:"Ekolojik niş ne demektir?",o:["Yuva","Bir türün ekosistemdeki rolü ve yaşam tarzı","Göç yolu","Bölge sınırı"],d:1,a:"Ekolojik niş bir türün ekosistemi içindeki rolü beslenme tarzı ve yaşam koşullarını tanımlar."}',
'{k:"Doğa",s:"Biyokütle enerjisi nedir?",o:["Nükleer","Organik maddelerden elde edilen enerji","Fosil yakıt","Jeotermal"],d:1,a:"Biyokütle enerjisi bitki ve hayvan kaynaklı organik maddelerden elde edilen enerjidir."}',
'{k:"Doğa",s:"Yer altı sularının kirlenmesi neye yol açar?",o:["Deprem","İçme suyu kıtlığı ve toprak kirliliği","Volkan","Sel"],d:1,a:"Yer altı sularının kirlenmesi içme suyu kaynaklarını ve tarım alanlarını tehdit eder."}',
'{k:"Doğa",s:"Paris İklim Anlaşması ne amaçlar?",o:["Ticaret","Küresel sıcaklık artışını 1.5 derece ile sınırlama","Savaş","Eğitim"],d:1,a:"Paris Anlaşması küresel sıcaklık artışını sanayi öncesine göre 1.5 derece ile sınırlamayı hedefler."}',
'{k:"Doğa",s:"Sürdürülebilir kalkınma ne demektir?",o:["Hızlı büyüme","Bugünün ihtiyaçlarını gelecek nesilleri tehlikeye atmadan karşılama","Sanayi devrimi","Doğal kaynak tüketimi"],d:1,a:"Sürdürülebilir kalkınma gelecek nesillerin ihtiyaçlarını karşılayabilme kapasitesini tehlikeye atmadan bugünün ihtiyaçlarını karşılamaktır."}',
'{k:"Doğa",s:"Atık su arıtma tesisleri ne yapar?",o:["Su üretir","Kirli suyu temizleyerek doğaya güvenle geri verir","Su depolar","Su ısıtır"],d:1,a:"Atık su arıtma tesisleri evsel ve endüstriyel atık suları arıtarak çevreye zarar vermeden doğaya geri kazandırır."}',
'{k:"Doğa",s:"Gen bankası ne amaçla kurulur?",o:["Para saklamak","Bitki ve hayvan genetik materyalini korumak","İlaç üretmek","Gıda depolamak"],d:1,a:"Gen bankaları bitki tohumları ve hayvan genetik materyallerini gelecek nesiller için korumak amacıyla kurulur."}',
'{k:"Doğa",s:"Ekosistem hizmetleri ne demektir?",o:["İnternet","Doğanın insanlara sağladığı faydalar","Bankacılık","Telekomünikasyon"],d:1,a:"Ekosistem hizmetleri tozlaşma su arıtma karbon tutma gibi doğanın insanlara sağladığı faydalardır."}',
'{k:"Doğa",s:"Biyolojik göstergeler ne işe yarar?",o:["Termometre","Çevre kalitesini ölçmek için belirli canlı türleri","Pusula","Harita"],d:1,a:"Biyolojik göstergeler çevre kalitesinin değerlendirilmesinde kullanılan belirli canlı türleridir."}',
'{k:"Doğa",s:"Sera etkisi olmasa Dünya ortalama sıcaklığı kaç olurdu?",o:["-18 derece","0 derece","15 derece","25 derece"],d:0,a:"Sera etkisi olmasa Dünya nın ortalama sıcaklığı yaklaşık -18 derece olurdu."}',
'{k:"Doğa",s:"Karbon nötr ne demektir?",o:["Karbon yok","Üretilen karbonun eşit miktarda dengelenmesi","Karbon elementinin nötr olması","Karbon kırılması"],d:1,a:"Karbon nötr atmosfere salınan karbonun eşit miktarda azaltılması veya dengelenmesidir."}',
# Başkentler (50)
'{k:"Başkentler",s:"Kazakistan ın başkenti neresidir?",o:["Almatı","Astana","Bişkek","Taşkent"],d:1,a:"Astana Kazakistan ın başkentidir."}',
'{k:"Başkentler",s:"Özbekistan ın başkenti neresidir?",o:["Bişkek","Astana","Taşkent","Dışanbe"],d:2,a:"Taşkent Özbekistan ın başkentidir."}',
'{k:"Başkentler",s:"Türkmenistan ın başkenti neresidir?",o:["Aşkabat","Taşkent","Bişkek","Dışanbe"],d:0,a:"Aşkabat Türkmenistan ın başkentidir."}',
'{k:"Başkentler",s:"Kırgızistan ın başkenti neresidir?",o:["Taşkent","Astana","Bişkek","Aşkabat"],d:2,a:"Bişkek Kırgızistan ın başkentidir."}',
'{k:"Başkentler",s:"Tacikistan ın başkenti neresidir?",o:["Taşkent","Bişkek","Astana","Dışanbe"],d:3,a:"Dışanbe Tacikistan ın başkentidir."}',
'{k:"Başkentler",s:"Ermenistan ın başkenti neresidir?",o:["Tiflis","Bakü","Erivan","Tahran"],d:2,a:"Erivan Ermenistan ın başkentidir."}',
'{k:"Başkentler",s:"Sri Lanka nın başkenti neresidir?",o:["Kolombo","Sri Jayewardenepura Kotte","Kandy","Galle"],d:1,a:"Sri Lanka nın resmi başkenti Sri Jayewardenepura Kotte dir."}',
'{k:"Başkentler",s:"Nepal in başkenti neresidir?",o:["Katmandu","Dakka","Thimphu","Colombo"],d:0,a:"Katmandu Nepal in başkentidir."}',
'{k:"Başkentler",s:"Bhutan ın başkenti neresidir?",o:["Katmandu","Thimphu","Dakka","Yangon"],d:1,a:"Thimphu Bhutan ın başkentidir."}',
'{k:"Başkentler",s:"Bangladeş in başkenti neresidir?",o:["Kalküta","Mumbai","Dakka","Chittagong"],d:2,a:"Dakka Bangladeş in başkentidir."}',
'{k:"Başkentler",s:"Kamboçya nın başkenti neresidir?",o:["Vientiane","Phnom Penh","Hanoi","Jakarta"],d:1,a:"Phnom Penh Kamboçya nın başkentidir."}',
'{k:"Başkentler",s:"Laos un başkenti neresidir?",o:["Phnom Penh","Vientiane","Bangkok","Hanoi"],d:1,a:"Vientiane Laos un başkentidir."}',
'{k:"Başkentler",s:"Etiyopya nın başkenti neresidir?",o:["Nairobi","Addis Ababa","Mogadişu","Kampala"],d:1,a:"Addis Ababa Etiyopya nın başkentidir."}',
'{k:"Başkentler",s:"Gana nın başkenti neresidir?",o:["Lagos","Accra","Dakar","Abidjan"],d:1,a:"Accra Gana nın başkentidir."}',
'{k:"Başkentler",s:"Senegal in başkenti neresidir?",o:["Accra","Bamako","Dakar","Conakry"],d:2,a:"Dakar Senegal in başkentidir."}',
'{k:"Başkentler",s:"Libya nın başkenti neresidir?",o:["Tunus","Trablus","Kahire","Cezayir"],d:1,a:"Trablus Libya nın başkentidir."}',
'{k:"Başkentler",s:"Cezayir in başkenti neresidir?",o:["Tunus","Rabat","Trablus","Cezayir"],d:3,a:"Cezayir şehri Cezayir in başkentidir."}',
'{k:"Başkentler",s:"Fas ın başkenti neresidir?",o:["Kazablanka","Marakeş","Rabat","Fes"],d:2,a:"Rabat Fas ın başkentidir."}',
'{k:"Başkentler",s:"Tunus un başkenti neresidir?",o:["Tunus","Trablus","Kahire","Rabat"],d:0,a:"Tunus şehri Tunus un başkentidir."}',
'{k:"Başkentler",s:"Tanzanya nın başkenti neresidir?",o:["Nairobi","Dar es Salaam","Dodoma","Kampala"],d:2,a:"Dodoma Tanzanya nın resmi başkentidir."}',
'{k:"Başkentler",s:"Uganda nın başkenti neresidir?",o:["Nairobi","Kampala","Kigali","Bujumbura"],d:1,a:"Kampala Uganda nın başkentidir."}',
'{k:"Başkentler",s:"Küba nın eski adı ile bilinen başkenti neresidir?",o:["Havana","Santiago","Trinidad","Varadero"],d:0,a:"Havana Küba nın başkentidir."}',
'{k:"Başkentler",s:"Paraguay ın başkenti neresidir?",o:["Montevideo","Buenos Aires","Asuncion","La Paz"],d:2,a:"Asuncion Paraguay ın başkentidir."}',
'{k:"Başkentler",s:"Uruguay ın başkenti neresidir?",o:["Asuncion","Montevideo","Buenos Aires","Brasilia"],d:1,a:"Montevideo Uruguay ın başkentidir."}',
'{k:"Başkentler",s:"Bolivya nın anayasal başkenti neresidir?",o:["La Paz","Sucre","Santa Cruz","Cochabamba"],d:1,a:"Sucre Bolivya nın anayasal başkenti La Paz ise yönetim başkentidir."}',
'{k:"Başkentler",s:"Ekvador ın başkenti neresidir?",o:["Lima","Quito","Bogota","Guayaquil"],d:1,a:"Quito Ekvador ın başkentidir."}',
'{k:"Başkentler",s:"Venezuela nın başkenti neresidir?",o:["Bogota","Caracas","Lima","Quito"],d:1,a:"Caracas Venezuela nın başkentidir."}',
'{k:"Başkentler",s:"Panama nın başkenti neresidir?",o:["San Jose","Panama City","Managua","Tegucigalpa"],d:1,a:"Panama City Panama nın başkentidir."}',
'{k:"Başkentler",s:"Kosta Rika nın başkenti neresidir?",o:["Panama City","San Jose","Managua","Guatemala City"],d:1,a:"San Jose Kosta Rika nın başkentidir."}',
'{k:"Başkentler",s:"İzlanda nın başkenti neresidir?",o:["Oslo","Reykjavik","Helsinki","Kopenhag"],d:1,a:"Reykjavik İzlanda nın başkentidir."}',
'{k:"Başkentler",s:"Malta nın başkenti neresidir?",o:["Valletta","Napoli","Atina","Nicosia"],d:0,a:"Valletta Malta nın başkentidir."}',
'{k:"Başkentler",s:"KKTC nin başkenti neresidir?",o:["Limasol","Girne","Lefkoşa","Magusa"],d:2,a:"Lefkoşa KKTC nin başkentidir."}',
'{k:"Başkentler",s:"Kosova nın başkenti neresidir?",o:["Belgrad","Tiran","Priştine","Üsküp"],d:2,a:"Priştine Kosova nın başkentidir."}',
'{k:"Başkentler",s:"Karadağ ın başkenti neresidir?",o:["Belgrad","Podgorica","Tiran","Sarajevo"],d:1,a:"Podgorica Karadağ ın başkentidir."}',
'{k:"Başkentler",s:"Lüksemburg un başkenti neresidir?",o:["Brüksel","Lüksemburg","Amsterdam","Bern"],d:1,a:"Lüksemburg şehri Lüksemburg un başkentidir."}',
'{k:"Başkentler",s:"Liechtenstein in başkenti neresidir?",o:["Bern","Vaduz","Zürih","Cenevre"],d:1,a:"Vaduz Liechtenstein in başkentidir."}',
'{k:"Başkentler",s:"Andorra nın başkenti neresidir?",o:["Andorra la Vella","Madrid","Lizbon","Toulouse"],d:0,a:"Andorra la Vella Andorra nın başkentidir."}',
'{k:"Başkentler",s:"San Marino nun başkenti neresidir?",o:["Roma","San Marino","Vatikan","Napoli"],d:1,a:"San Marino şehri San Marino nun başkentidir."}',
'{k:"Başkentler",s:"Monako nın başkenti neresidir?",o:["Nice","Monako","Marsilya","Cannes"],d:1,a:"Monako şehir-devleti olarak başkenti kendisidir."}',
'{k:"Başkentler",s:"Fiji nin başkenti neresidir?",o:["Suva","Nadi","Port Moresby","Honiara"],d:0,a:"Suva Fiji nin başkentidir."}',
# Türkiye (50) - kısa yazıyorum
'{k:"Türkiye",s:"Türkiye GDP ye göre dünyanın kaçıncı büyük ekonomisidir?",o:["10-15","15-20","20-25","25-30"],d:1,a:"Türkiye GDP ye göre dünyanın yaklaşık 17-19. büyük ekonomisidir."}',
'{k:"Türkiye",s:"Bosphorus kelimesi ne anlama gelir?",o:["Dar geçit","İnek geçidi","Deniz yolu","Köprü"],d:1,a:"Bosphorus Yunanca inek geçidi anlamına gelir."}',
'{k:"Türkiye",s:"Türkiye nin ilk nükleer santralı nerede inşa edilmektedir?",o:["Sinop","Mersin Akkuyu","İstanbul","Edirne"],d:1,a:"Akkuyu Nükleer Santrali Mersin de inşa edilmektedir."}',
'{k:"Türkiye",s:"Mimar Sinan ın kalfalık eseri hangisidir?",o:["Selimiye","Süleymaniye","Şehzadebaşı","Sultanahmet"],d:1,a:"Süleymaniye Camii Mimar Sinan ın kalfalık eseridir."}',
'{k:"Türkiye",s:"Mimar Sinan ın çıraklık eseri hangisidir?",o:["Selimiye","Süleymaniye","Şehzadebaşı","Sultanahmet"],d:2,a:"Şehzadebaşı Camii Mimar Sinan ın çıraklık eseridir."}',
'{k:"Türkiye",s:"Türkiye de UNESCO listesindeki ilk alan hangisidir?",o:["Pamukkale","İstanbul Tarihi Alanları","Göreme","Divriği"],d:3,a:"Divriği Ulu Camii ve Darüşşifası 1985 te UNESCO listesine alınan ilk Türk eseridir."}',
'{k:"Türkiye",s:"Marmaray hangi yılda hizmete açıldı?",o:["2010","2013","2016","2019"],d:1,a:"Marmaray 29 Ekim 2013 te hizmete açılmıştır."}',
'{k:"Türkiye",s:"Yavuz Sultan Selim Köprüsü hangi yılda açıldı?",o:["2014","2016","2018","2020"],d:1,a:"Yavuz Sultan Selim Köprüsü 2016 yılında açılmıştır."}',
'{k:"Türkiye",s:"Türkiye de en çok ihracat yapılan sektör hangisidir?",o:["Tarım","Otomotiv","Tekstil","Madencilik"],d:1,a:"Otomotiv sektörü Türkiye nin en büyük ihracat kalemidir."}',
'{k:"Türkiye",s:"Çatalhöyük kaç yıl öncesine tarihlenir?",o:["3000","5000","7000","9000"],d:3,a:"Çatalhöyük yaklaşık 9000 yıl öncesine tarihlenen dünyanın en eski yerleşim yerlerinden biridir."}',
'{k:"Türkiye",s:"Türkiye nin en uzun tüneli hangisidir?",o:["Marmaray","Ovit","İlgaz","Avrasya"],d:1,a:"Ovit Tüneli 14.3 km ile Türkiye nin en uzun karayolu tünelidir."}',
'{k:"Türkiye",s:"İstanbul Havalimanı hangi yılda tam kapasiteyle açıldı?",o:["2017","2018","2019","2020"],d:2,a:"İstanbul Havalimanı 2019 yılında tam kapasiteyle hizmete açılmıştır."}',
'{k:"Türkiye",s:"Van Gölü neden tuzlu ve sodalıdır?",o:["Denizle bağlantılı","Volkanik kayaçlardan çözünen mineraller","İnsan kirliliği","Rüzgar"],d:1,a:"Van Gölü çevresindeki volkanik kayaçlardan çözünen mineraller nedeniyle tuzlu ve sodalıdır."}',
'{k:"Türkiye",s:"Efes teki Artemis Tapınağı dünyanın yedi harikasından biri midir?",o:["Evet","Hayır","Belirsiz","Tartışmalı"],d:0,a:"Artemis Tapınağı Antik Dünyanın Yedi Harikasından biridir."}',
'{k:"Türkiye",s:"Osmanlı döneminde İstanbul a ne ad verilirdi?",o:["Byzantium","Konstantinopolis","Dersaadet","Hepsi"],d:3,a:"İstanbul tarih boyunca Byzantium Konstantinopolis ve Dersaadet gibi isimlerle anılmıştır."}',
'{k:"Türkiye",s:"Türkiye nin en büyük suni gölü hangisidir?",o:["Keban","Atatürk Baraj Gölü","Hirfanlı","Karakaya"],d:1,a:"Atatürk Baraj Gölü Türkiye nin en büyük yapay gölüdür."}',
'{k:"Türkiye",s:"Anadolu Medeniyetleri Müzesi hangi ildedir?",o:["İstanbul","Ankara","İzmir","Antalya"],d:1,a:"Anadolu Medeniyetleri Müzesi Ankara dadır."}',
'{k:"Türkiye",s:"Türkiye de ilk demir yolu hattı nerede yapıldı?",o:["İstanbul","İzmir-Aydın","Ankara","Adana"],d:1,a:"Türkiye nin ilk demir yolu hattı 1856 da İzmir-Aydın arasında yapılmıştır."}',
'{k:"Türkiye",s:"Türkiye de zeytinyağı üretiminde birinci il hangisidir?",o:["İzmir","Aydın","Balıkesir","Muğla"],d:2,a:"Balıkesir Türkiye de zeytinyağı üretiminde en önde gelen illerdendir."}',
'{k:"Türkiye",s:"Türkiye nin en büyük limanı hangisidir?",o:["İzmir","Mersin","İstanbul Ambarlı","Antalya"],d:2,a:"İstanbul Ambarlı Limanı Türkiye nin en büyük konteyner limanıdır."}',
'{k:"Türkiye",s:"Diyarbakır Surları hangi döneme aittir?",o:["Osmanlı","Roma","Selçuklu","Cumhuriyet"],d:1,a:"Diyarbakır Surları Roma dönemine ait olup UNESCO Dünya Mirası listesindedir."}',
'{k:"Türkiye",s:"Kapadokya da peribacaları hangi kayaçtan oluşmuştur?",o:["Granit","Mermer","Tüf","Bazalt"],d:2,a:"Peribacaları volkanik tüf kayacının aşınmasıyla oluşmuştur."}',
'{k:"Türkiye",s:"Türkiye nin en büyük ticaret ortağı hangi ülkedir?",o:["ABD","Rusya","Almanya","Çin"],d:2,a:"Almanya Türkiye nin en büyük ticaret ortaklarından biridir."}',
'{k:"Türkiye",s:"Türkiye de kaç tane UNESCO Dünya Mirası alanı vardır?",o:["10","15","21","30"],d:2,a:"Türkiye 2024 itibarıyla 21 UNESCO Dünya Mirası alanına sahiptir."}',
'{k:"Türkiye",s:"Avrasya Tüneli hangi boğazın altından geçer?",o:["Çanakkale","İstanbul","Kerç","Süveyş"],d:1,a:"Avrasya Tüneli İstanbul Boğazı nın altından geçen karayolu tünelidir."}',
'{k:"Türkiye",s:"Troya Savaşı efsanesi hangi ilde geçer?",o:["İzmir","Çanakkale","Balıkesir","Bursa"],d:1,a:"Troya antik kenti ve savaş efsanesi Çanakkale ilinde geçmektedir."}',
# Spor (50)
'{k:"Spor",s:"Olimpiyatlarda en çok altın madalya kazanan sporcu kimdir?",o:["Usain Bolt","Michael Phelps","Carl Lewis","Jesse Owens"],d:1,a:"Michael Phelps 23 altın madalya ile olimpiyat tarihinin en başarılı sporcusudur."}',
'{k:"Spor",s:"FIFA Dünya Kupası ilk kez hangi ülkede düzenlendi?",o:["Brezilya","İtalya","Uruguay","İngiltere"],d:2,a:"İlk FIFA Dünya Kupası 1930 da Uruguay da düzenlenmiştir."}',
'{k:"Spor",s:"Olimpiyat ateşi ilk kez nerede yakıldı?",o:["Atina 1896","Amsterdam 1928","Berlin 1936","Londra 1948"],d:1,a:"Olimpiyat ateşi ilk kez 1928 Amsterdam Olimpiyatlarında yakılmıştır."}',
'{k:"Spor",s:"Roger Federer hangi spor dalında ünlüdür?",o:["Golf","Tenis","Badminton","Masa tenisi"],d:1,a:"Roger Federer tenis tarihinin en büyük oyuncularından biridir."}',
'{k:"Spor",s:"Decathlon kaç branştan oluşur?",o:["5","8","10","12"],d:2,a:"Decathlon (onlu yarışma) 10 atletizm branşından oluşur."}',
'{k:"Spor",s:"Yelken sporunda kullanılan teknelere ne denir?",o:["Gemi","Kayık","Yat","Tekne sınıflarına göre değişir"],d:3,a:"Yelken sporunda tekne sınıflarına göre Laser Finn Optimist gibi farklı isimler kullanılır."}',
'{k:"Spor",s:"Grand Slam tenis turnuvalarından biri değil hangisi?",o:["Wimbledon","Roland Garros","US Open","Miami Open"],d:3,a:"Miami Open Grand Slam turnuvası değildir. Grand Slamler: Avustralya Roland Garros Wimbledon US Open."}',
'{k:"Spor",s:"Beşiktaş JK hangi yılda kurulmuştur?",o:["1899","1903","1905","1907"],d:1,a:"Beşiktaş JK 1903 yılında kurulmuştur."}',
'{k:"Spor",s:"Galatasaray SK hangi yılda kurulmuştur?",o:["1899","1903","1905","1907"],d:2,a:"Galatasaray SK 1905 yılında kurulmuştur."}',
'{k:"Spor",s:"Fenerbahçe SK hangi yılda kurulmuştur?",o:["1899","1903","1905","1907"],d:3,a:"Fenerbahçe SK 1907 yılında kurulmuştur."}',
'{k:"Spor",s:"E-spor hangi tür yarışmadır?",o:["Atletizm","Elektronik oyun yarışması","Masa oyunu","Kart oyunu"],d:1,a:"E-spor profesyonel elektronik oyun yarışmalarıdır."}',
'{k:"Spor",s:"Bir kriket maçında wicket ne demektir?",o:["Top","Kaleci","Üç tahta çubuk ve üzerindeki çıtalar","Saha"],d:2,a:"Wicket kriket te korucunun arkasındaki üç tahta çubuk ve üzerindeki çıtalardır."}',
'{k:"Spor",s:"Ironman yarışı hangi sporlardan oluşur?",o:["Koşu bisiklet","Yüzme bisiklet koşu","Kayak atış","Yüzme güreş"],d:1,a:"Ironman 3.8 km yüzme 180 km bisiklet ve 42.2 km koşudan oluşan ultra triatlon yarışıdır."}',
'{k:"Spor",s:"Doping nedir?",o:["Spor malzemesi","Performans artırıcı yasaklı madde kullanımı","Antrenman yöntemi","Beslenme planı"],d:1,a:"Doping sporcuların performanslarını artırmak için yasaklı madde kullanmasıdır."}',
'{k:"Spor",s:"VAR sistemi ne işe yarar?",o:["Skor takibi","Video ile hakem kararlarının incelenmesi","Bilet satışı","Antrenman planı"],d:1,a:"VAR Video Yardımcı Hakem sistemi tartışmalı pozisyonların video ile incelenmesidir."}',
'{k:"Spor",s:"Türkiye hangi yılda Avrupa Şampiyonası üçüncüsü oldu?",o:["2000","2002","2008","2012"],d:2,a:"Türkiye 2008 Avrupa Şampiyonasında yarı finale çıkarak üçüncü olmuştur."}',
'{k:"Spor",s:"2002 Dünya Kupasında Türkiye kaçıncı oldu?",o:["Birinci","İkinci","Üçüncü","Dördüncü"],d:2,a:"Türkiye 2002 Dünya Kupasında üçüncülük kazanmıştır."}',
'{k:"Spor",s:"Naim Süleymanoğlu hangi spor dalında olimpiyat şampiyonu oldu?",o:["Güreş","Halter","Boks","Judo"],d:1,a:"Naim Süleymanoğlu halter dalında 3 kez olimpiyat şampiyonu olmuştur."}',
'{k:"Spor",s:"Olimpiyatlarda hangi spor dalı ilk kez 2020 Tokyo da yer aldı?",o:["Karate","Kriket","Rugby","Golf"],d:0,a:"Karate ilk kez 2020 Tokyo Olimpiyatlarında yer almıştır."}',
'{k:"Spor",s:"ATP ve WTA hangi sporun organizasyonlarıdır?",o:["Futbol","Tenis","Basketbol","Voleybol"],d:1,a:"ATP (erkekler) ve WTA (kadınlar) profesyonel tenisin ana organizasyonlarıdır."}',
'{k:"Spor",s:"Biatlon hangi iki sporu birleştirir?",o:["Yüzme koşu","Kros kayak ve atıcılık","Bisiklet koşu","Güreş boks"],d:1,a:"Biatlon kros kayak ve tüfekle atıcılığı birleştiren kış sporudur."}',
'{k:"Spor",s:"Bir boks maçında raunt kaç dakikadır?",o:["2","3","4","5"],d:1,a:"Profesyonel boksta her raunt 3 dakikadır."}',
'{k:"Spor",s:"Dünya Atletizm Şampiyonası ilk kez nerede yapıldı?",o:["Atina","Helsinki","Berlin","Tokyo"],d:1,a:"İlk Dünya Atletizm Şampiyonası 1983 te Helsinki de yapılmıştır."}',
'{k:"Spor",s:"Kendo hangi ülkenin dövüş sanatıdır?",o:["Çin","Kore","Japonya","Vietnam"],d:2,a:"Kendo Japonya nın geleneksel kılıç sanatıdır."}',
'{k:"Spor",s:"Polo maçında kaç chukker oynanır?",o:["2","4","6","8"],d:2,a:"Polo maçında genellikle 6 chukker oynanır her biri 7 dakikadır."}',
# Matematik (50)
'{k:"Matematik",s:"Logaritma ne demektir?",o:["Çarpma işlemi","Üs alma işleminin tersi","Bölme işlemi","Toplama işlemi"],d:1,a:"Logaritma üs alma işleminin tersidir log_b(x)=y demek b^y=x demektir."}',
'{k:"Matematik",s:"sin 30 derece kaçtır?",o:["0","0.5","0.707","1"],d:1,a:"sin 30 derece = 0.5 tir."}',
'{k:"Matematik",s:"cos 60 derece kaçtır?",o:["0","0.5","0.707","1"],d:1,a:"cos 60 derece = 0.5 tir."}',
'{k:"Matematik",s:"tan 45 derece kaçtır?",o:["0","0.5","1","Tanımsız"],d:2,a:"tan 45 derece = 1 dir."}',
'{k:"Matematik",s:"e sayısı yaklaşık kaçtır?",o:["1.414","2.718","3.14","1.618"],d:1,a:"Euler sayısı e yaklaşık 2.718 dir."}',
'{k:"Matematik",s:"Altın oran yaklaşık kaçtır?",o:["1.414","2.718","3.14","1.618"],d:3,a:"Altın oran (phi) yaklaşık 1.618 dir."}',
'{k:"Matematik",s:"Türev neyi ifade eder?",o:["Alan","Bir fonksiyonun anlık değişim hızı","Toplam","Ortalama"],d:1,a:"Türev bir fonksiyonun belirli bir noktadaki anlık değişim hızını ifade eder."}',
'{k:"Matematik",s:"İntegral neyi hesaplar?",o:["Eğim","Bir eğri altında kalan alan","Hız","Açı"],d:1,a:"Belirli integral bir eğri altında kalan alanı hesaplar."}',
'{k:"Matematik",s:"Permütasyon ile kombinasyon arasındaki fark nedir?",o:["Fark yok","Permütasyonda sıra önemli kombinasyonda değil","Aynı formül","Biri toplama biri çarpma"],d:1,a:"Permütasyonda sıra önemlidir kombinasyonda sıra önemsizdir."}',
'{k:"Matematik",s:"Bir kürenin hacmi nasıl hesaplanır?",o:["pi r kare","4/3 pi r kup","2 pi r","pi r kare h"],d:1,a:"Kürenin hacmi 4/3 x pi x r kup formülüyle hesaplanır."}',
'{k:"Matematik",s:"Bir matrisin determinantı sıfır ise ne anlama gelir?",o:["Tersi var","Tersi yoktur (tekil matris)","Birim matris","Simetrik"],d:1,a:"Determinantı sıfır olan matris tekil matristir ve tersi yoktur."}',
'{k:"Matematik",s:"Kompleks sayıda i neyi ifade eder?",o:["1","0","-1 in karekökü","Pi"],d:2,a:"i sanal birimdir ve -1 in karekökü olarak tanımlanır."}',
'{k:"Matematik",s:"Olasılıkta bağımsız olay ne demektir?",o:["Birbirini etkileyen","Birinin sonucu diğerini etkilemeyen","Aynı anda olan","Sıralı"],d:1,a:"Bağımsız olaylarda birinin sonucu diğerinin olasılığını etkilemez."}',
'{k:"Matematik",s:"Normal dağılımda ortalamadan 1 standart sapma içinde verinin yüzdesi kaçtır?",o:["50%","68%","95%","99%"],d:1,a:"Normal dağılımda verinin yaklaşık yüzde 68 i ortalamadan 1 standart sapma içindedir."}',
'{k:"Matematik",s:"Polinom nedir?",o:["Tek terimli","Değişkenlerin kuvvetlerinden oluşan cebirsel ifade","Kesir","Logaritma"],d:1,a:"Polinom değişkenlerin negatif olmayan tam sayı kuvvetleri ve katsayılardan oluşan ifadedir."}',
'{k:"Matematik",s:"Limit kavramı neyi ifade eder?",o:["Son nokta","Fonksiyonun bir noktaya yaklaşırken aldığı değer","İlk nokta","Orta nokta"],d:1,a:"Limit bir fonksiyonun bağımsız değişkeni belirli bir değere yaklaşırken aldığı değeri ifade eder."}',
'{k:"Matematik",s:"Pisagor üçlüsü hangisidir?",o:["2 3 4","3 4 5","4 5 6","5 6 7"],d:1,a:"3 4 5 bir Pisagor üçlüsüdür çünkü 9+16=25 dir."}',
'{k:"Matematik",s:"10 faktöriyel (10!) yaklaşık kaçtır?",o:["100000","362880","3628800","1000000"],d:2,a:"10! = 10x9x8x7x6x5x4x3x2x1 = 3628800 dür."}',
'{k:"Matematik",s:"Geometrik dizi nedir?",o:["Sabit fark","Her terim öncekinin sabit katı","Rastgele","Fibonacci"],d:1,a:"Geometrik dizide her terim bir önceki terimin sabit bir sayıyla çarpılmasıyla elde edilir."}',
'{k:"Matematik",s:"Aritmetik dizi nedir?",o:["Sabit oran","Her terim öncekine sabit sayı eklenmesi","Rastgele","Üstel"],d:1,a:"Aritmetik dizide ardışık terimler arasındaki fark sabittir."}',
'{k:"Matematik",s:"Euler formülü e^(i*pi) + 1 kaça eşittir?",o:["1","0","-1","Pi"],d:1,a:"Euler formülüne göre e^(i*pi) + 1 = 0 dır."}',
'{k:"Matematik",s:"İrrasyonel sayı nedir?",o:["Tam sayı","Kesir olarak yazılamayan sayı","Negatif sayı","Çift sayı"],d:1,a:"İrrasyonel sayılar kesir olarak yazılamayan sayılardır (pi kök 2 gibi)."}',
'{k:"Matematik",s:"Vektör ile skaler arasındaki fark nedir?",o:["Fark yok","Vektör büyüklük ve yön skaler sadece büyüklük","Biri sayı biri harf","Biri pozitif biri negatif"],d:1,a:"Vektör hem büyüklük hem yön içerirken skaler sadece büyüklük ifade eder."}',
'{k:"Matematik",s:"Sinüs teoremi ne ifade eder?",o:["a/sinA = b/sinB = c/sinC","a^2=b^2+c^2","sin^2+cos^2=1","tan=sin/cos"],d:0,a:"Sinüs teoremi üçgenin kenarlarının karşı açılarının sinüsleriyle orantılı olduğunu gösterir."}',
'{k:"Matematik",s:"Kosinüs teoremi ne ifade eder?",o:["Sinüs kuralı","a^2 = b^2 + c^2 - 2bc cosA","tan kuralı","Alan formülü"],d:1,a:"Kosinüs teoremi herhangi bir üçgende kenarlar ve açılar arasındaki ilişkiyi verir."}',
# Deyimler (50)
'{k:"Deyimler",s:"Araba devrilince yol gösteren çok olur ne demektir?",o:["Trafik kuralı","İş işten geçtikten sonra akıl veren çok olur","Araba tamiri","Yol yapımı"],d:1,a:"Olay olduktan sonra akıl verip ne yapılması gerektiğini söyleyen çok olur."}',
'{k:"Deyimler",s:"Ayıkla pirincin taşını ne demektir?",o:["Pirinç temizlemek","Çok zor ve karmaşık bir durumu ifade eder","Yemek pişirmek","Tarla işi"],d:1,a:"İçinden çıkılması çok zor karmaşık bir durumu ifade eder."}',
'{k:"Deyimler",s:"Balık baştan kokar ne demektir?",o:["Balık pişirmek","Bozukluk yöneticiden başlar","Denize gitmek","Balık avlamak"],d:1,a:"Bir toplulukta bozukluk ve sorunlar önce yöneticiden başlar."}',
'{k:"Deyimler",s:"Dolap çevirmek ne demektir?",o:["Çamaşır yıkamak","Gizli entrikalar yapmak","Dans etmek","Mobilya taşımak"],d:1,a:"Gizlice hile ve entrika yapmak demektir."}',
'{k:"Deyimler",s:"Feleğin çemberinden geçmek ne demektir?",o:["Jimnastik","Çok sıkıntı ve zorluk çekmek","Sirk gösterisi","Halka geçirmek"],d:1,a:"Çok acı ve zorluk çekerek deneyim kazanmak demektir."}',
'{k:"Deyimler",s:"Hamam böceği gibi her yere girmek ne demektir?",o:["Temizlik","Her işe burnunu sokmak","Böcek ilaçlama","Seyahat"],d:1,a:"Her yere sokulup her işe burnunu sokan kişi için kullanılır."}',
'{k:"Deyimler",s:"İt ürür kervan yürür ne demektir?",o:["Hayvan bakımı","Kararlı olan eleştirilere aldırmaz","Seyahat","Avcılık"],d:1,a:"Amacına kararlı olan kişi boş eleştirilere aldırmaz yoluna devam eder."}',
'{k:"Deyimler",s:"Karınca kararınca ne demektir?",o:["Karınca bilgisi","Gücü ve imkanı ölçüsünde","Küçük iş","Böcek bilimi"],d:1,a:"Kendi gücü ve imkanı ölçüsünde elinden geldiğince demektir."}',
'{k:"Deyimler",s:"Kırk yılda bir ne demektir?",o:["40 yıl","Çok nadiren","Her gün","Bazen"],d:1,a:"Çok seyrek çok nadiren olan şeyler için kullanılır."}',
'{k:"Deyimler",s:"Mangalda kül bırakmamak ne demektir?",o:["Mangal yakmak","Çok kurnaz ve sinsi olmak","Temizlik","Yemek pişirmek"],d:1,a:"Çok kurnaz ve sinsi olmak hiçbir iz bırakmamak demektir."}',
'{k:"Deyimler",s:"Nalıncı keseri gibi kendine yontmak ne demektir?",o:["Marangozluk","Her şeyi kendi çıkarına göre yapmak","Ağaç işi","Taş yontmak"],d:1,a:"Her şeyi kendi çıkarına uygun hale getirmek demektir."}',
'{k:"Deyimler",s:"Öğretmene küsmekle cahil kalınır ne demektir?",o:["Okula gitmek","Kırgınlıkla kendine zarar verirsin","Öğretmenlik","Sınav"],d:1,a:"Sana faydası olan kişiye küsmek sadece sana zarar verir."}',
'{k:"Deyimler",s:"Söz gümüşse sükut altındır ne demektir?",o:["Metal fiyatları","Bazen susmak konuşmaktan değerlidir","Altın almak","Gümüş satmak"],d:1,a:"Bazen konuşmak yerine susmak daha değerli ve akıllıcadır."}',
'{k:"Deyimler",s:"Taş yerinde ağırdır ne demektir?",o:["Taş taşımak","İnsan kendi yerinde değerlidir","Ağırlık ölçmek","Dağ tırmanmak"],d:1,a:"İnsan kendi bulunduğu yerde kendi konumunda değerlidir."}',
'{k:"Deyimler",s:"Üzüm yemek ne anlama gelir (deyim olarak)?",o:["Meyve yemek","Asıl amacı bilmeden taklit etmek","Bağ bakmak","Şarap yapmak"],d:1,a:"Asıl amacı anlamadan sadece sonucuyla ilgilenmek (bağcıyı dövmek değil üzüm yemek)."}',
'{k:"Deyimler",s:"Yel kayadan ne koparır ne demektir?",o:["Rüzgar","Güçlü kişi küçük saldırıdan etkilenmez","Dağ tırmanma","Hava durumu"],d:1,a:"Güçlü ve dayanıklı kişi küçük saldırı ve eleştirilerden etkilenmez."}',
'{k:"Deyimler",s:"Zaman herşeyin ilacıdır ne demektir?",o:["İlaç almak","Zamanla acılar diner sorunlar çözülür","Saat almak","Doktor olmak"],d:1,a:"Zamanla acılar azalır yaralar iyileşir sorunlar çözüme kavuşur."}',
'{k:"Deyimler",s:"Aba altından sopa göstermek ne demektir?",o:["Kıyafet","Gizlice tehdit etmek","Spor yapmak","Hediye vermek"],d:1,a:"Belli etmeden üstü kapalı bir şekilde tehdit etmek demektir."}',
'{k:"Deyimler",s:"Dikine gitmek ne demektir?",o:["Yokuş çıkmak","İnatla kendi bildiğini yapmak","Yüzmek","Koşmak"],d:1,a:"Hiç kimsenin sözünü dinlemeyip inatla kendi bildiğini yapmak demektir."}',
'{k:"Deyimler",s:"Çıban başı olmak ne demektir?",o:["Hastalanmak","Sorunların kaynağı olmak","Doktor olmak","İlaç almak"],d:1,a:"Sorunların ve kötülüklerin asıl kaynağı ve sebebi olmak demektir."}',
'{k:"Deyimler",s:"Kaşık düşmanı ne demektir?",o:["Kaşık toplayan","Yemek konusunda seçici olan","Yemek yemek","Bulaşık yıkamak"],d:1,a:"Yemek seçen yemek konusunda çok titiz olan kişi için kullanılır."}',
'{k:"Deyimler",s:"Çuvaldızı kendine iğneyi başkasına batırmak ne demektir?",o:["Terzilik","Önce kendini eleştir sonra başkasını","Dikiş dikmek","İğne toplamak"],d:1,a:"Eleştiriye önce kendinden başlamak daha sonra başkalarını eleştirmek gerektiğini anlatır."}',
'{k:"Deyimler",s:"Kesenin ağzını açmak ne demektir?",o:["Çanta açmak","Para harcamaya başlamak","Alışveriş","Cüzdan almak"],d:1,a:"Cömertçe para harcamaya başlamak demektir."}',
'{k:"Deyimler",s:"Devlet kuşu konmak ne demektir?",o:["Kuş bakmak","Büyük bir şansa erişmek","Avcılık","Parkta gezmek"],d:1,a:"Büyük bir talih ve şansa erişmek beklenmedik bir fırsat yakalamak demektir."}',
'{k:"Deyimler",s:"Üç aşağı beş yukarı ne demektir?",o:["Matematik","Aşağı yukarı yaklaşık","Merdiven çıkmak","Asansör"],d:1,a:"Tam olarak olmasa da yaklaşık olarak aşağı yukarı demektir."}',
# Atasözleri (50)
'{k:"Atasözleri",s:"Bilgi güçtür kimin sözüdür?",o:["Aristoteles","Francis Bacon","Newton","Platon"],d:1,a:"Bilgi güçtür sözü Francis Bacon a atfedilir."}',
'{k:"Atasözleri",s:"Her şeyin başı sağlık ne anlatır?",o:["Hastane","Sağlık tüm değerlerin temelidir","Spor","Doktor"],d:1,a:"Sağlık olmadan hiçbir şeyin değeri yoktur en önemli şey sağlıktır."}',
'{k:"Atasözleri",s:"Korkak bezirgan ne kar ne zarar eder ne demektir?",o:["Ticaret","Risk almayan kazanamaz","Korkmak","Kaçmak"],d:1,a:"Risk almayan kişi ne kazanır ne kaybeder yani hiçbir ilerleme kaydedemez."}',
'{k:"Atasözleri",s:"Dimyata pirince giderken evdeki bulgurdan olmak ne anlatır?",o:["Pirinç almak","Daha fazlasını isterken elindekini de kaybetmek","Yemek pişirmek","Seyahat"],d:1,a:"Daha fazlasını elde etmeye çalışırken elindekini de kaybetmeyi anlatır."}',
'{k:"Atasözleri",s:"Havlamak ile ısırmak bir değildir ne demektir?",o:["Köpek eğitimi","Tehdit eden her zaman yapamaz","Hayvan bakımı","Veteriner"],d:1,a:"Tehdit eden lafla söyleyen her zaman eyleme geçemez."}',
'{k:"Atasözleri",s:"İki cambaz bir ipte oynamaz ne anlatır?",o:["Sirk","İki rakip aynı yerde barınamaz","Jimnastik","Akrobasi"],d:1,a:"Aynı alanda iki güçlü rakip bir arada barınamaz."}',
'{k:"Atasözleri",s:"Kendi göbeğini kendin kes ne demektir?",o:["Doktorluk","Sorunlarını kendin çöz başkasını bekleme","Ameliyat","İlk yardım"],d:1,a:"Kendi sorunlarını kendin çöz başkalarından yardım bekleme."}',
'{k:"Atasözleri",s:"Mum yanmasa ışık vermez ne anlatır?",o:["Mum yakmak","Emek vermeden sonuç alınamaz","Karanlık","Elektrik"],d:1,a:"Bir şey elde etmek için emek fedakarlık ve çaba gerekir."}',
'{k:"Atasözleri",s:"Ne ekersen onu biçersin ne demektir?",o:["Tarım","Yaptıklarının sonuçlarıyla karşılaşırsın","Hasat","Ekim"],d:1,a:"İyi veya kötü ne yaparsan sonucuyla kendin karşılaşırsın."}',
'{k:"Atasözleri",s:"Otuz bir günde kırk haramileri ne anlatır?",o:["Masal","Her gün yeni bir sorunla karşılaşmak","Sayı saymak","Hırsızlık"],d:1,a:"Sürekli olarak yeni sorunlar ve sıkıntılarla karşılaşmak demektir."}',
'{k:"Atasözleri",s:"Parayı veren düdüğü çalar ne demektir?",o:["Müzik","Gücü ve parası olan istediğini yaptırır","Düdük almak","Konser"],d:1,a:"Para ve güç sahibi olan istediğini yaptırabilir karar verici odur."}',
'{k:"Atasözleri",s:"Sürüden ayrılan koyunu kurt kapar ne anlatır?",o:["Hayvancılık","Topluluktan ayrılan tehlikeye düşer","Çoban olmak","Kurt avı"],d:1,a:"Topluluktan ayrılıp yalnız kalan kişi tehlikelere karşı savunmasız kalır."}',
'{k:"Atasözleri",s:"Terzi kendi söküğünü dikemez ne demektir?",o:["Terzilik","Uzman bile kendi sorununu çözemeyebilir","Dikiş dikmek","Kumaş kesmek"],d:1,a:"Bir konuda uzman olan kişi bile kendi sorunlarını çözmekte zorlanabilir."}',
'{k:"Atasözleri",s:"Ucuz etin yahnisi yavan olur ne anlatır?",o:["Yemek tarifi","Kalitesiz malzeme kalitesiz sonuç verir","Et almak","Aşçılık"],d:1,a:"Düşük kaliteli malzeme veya ucuz iş kalitesiz sonuç doğurur."}',
'{k:"Atasözleri",s:"Vakit nakittir ne demektir?",o:["Saat almak","Zaman çok değerlidir boşa harcanmamalı","Para saymak","Banka"],d:1,a:"Zaman para kadar değerlidir verimli kullanılmalıdır."}',
'{k:"Atasözleri",s:"Yılan hikayesi ne demektir?",o:["Hayvan bilimi","Bir türlü bitmeyen iş veya anlatım","Masal okumak","Yılan avlamak"],d:1,a:"Bir türlü bitmeyen sonu gelmeyen uzun ve sıkıcı iş veya anlatım demektir."}',
'{k:"Atasözleri",s:"Zorla güzellik olmaz ne anlatır?",o:["Güzellik bakımı","İsteksiz yapılan iş iyi sonuç vermez","Makyaj","Estetik"],d:1,a:"Gönüllü olmayan zorla yaptırılan hiçbir iş güzel ve kaliteli olmaz."}',
'{k:"Atasözleri",s:"Alet işler el övünür ne demektir?",o:["Alet satmak","İyi araç gereç başarıyı artırır","Tamir","Fabrika"],d:1,a:"Doğru aletlerle çalışan kişi daha iyi sonuç alır."}',
'{k:"Atasözleri",s:"Cahile söz anlatmak deveye hendek atlatmaktan zordur ne anlatır?",o:["Deve bakımı","Bilgisiz kişiye bir şey anlatmak çok zordur","Hendek kazmak","Hayvanat bahçesi"],d:1,a:"Bilgisiz ve inatçı bir kişiye bir şeyi anlatmak veya kabul ettirmek çok zordur."}',
'{k:"Atasözleri",s:"Deli ile damda oturma ya o seni iter ya sen onu ne demektir?",o:["İnşaat","Akılsız kişiyle iş yapmak tehlikelidir","Çatı tamiri","Yükseklik korkusu"],d:1,a:"Aklı başında olmayan kişiyle iş birliği yapmak tehlikelidir eninde sonunda sorun çıkar."}',
'{k:"Atasözleri",s:"Elinin hamuruyla erkek işine karışma ne anlatır?",o:["Yemek yapmak","Bilmediğin işe karışma","Hamur yoğurmak","Fırın"],d:1,a:"Bilmediğin ve uzmanlığın olmayan işlere karışma demektir."}',
'{k:"Atasözleri",s:"Güvenme varlığa düşersin darlığa ne demektir?",o:["Zenginlik","Sahip olduklarına güvenip savurganlık yapma","Banka","Yatırım"],d:1,a:"Elindeki varlığa güvenip savurganlık yaparsan bir gün darlığa düşebilirsin."}',
'{k:"Atasözleri",s:"Her gece karanlık olmaz ne anlatır?",o:["Astronomi","Kötü günler sona erer","Gece lambası","Uyumak"],d:1,a:"Her zorluk geçicidir kötü günlerin ardından iyi günler gelir."}',
'{k:"Atasözleri",s:"İnsanı tanımak kolay anlamak zordur ne demektir?",o:["Psikoloji","İnsanı dışından görmek kolay içini anlamak zordur","Fotoğrafçılık","Resim"],d:1,a:"İnsanın dış görünüşünü bilmek kolaydır ama gerçek karakterini anlamak çok zordur."}',
'{k:"Atasözleri",s:"Kadıya mülk (ev) geçmez ne anlatır?",o:["Gayrimenkul","Geçici görevdekine sürekli mal verilmez","Kadı olmak","Ev almak"],d:1,a:"Geçici bir görevde bulunan kişiye kalıcı bir mülk verilmez."}',
]

filepath = os.path.join("c:", os.sep, "Users", "safir", "OneDrive", "Masaüstü", "SmartCampusAI", "views", "_by_lise.txt")

with open(filepath, "a", encoding="utf-8") as f:
    for q in questions:
        f.write(q + "\n")

with open(filepath, "r", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip().startswith("{k:")]
    print(f"Total: {len(lines)}")
    cats = {}
    for l in lines:
        cat = l.split('"')[1]
        cats[cat] = cats.get(cat, 0) + 1
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")
