"""
KDG Interaktif - Pre-A1 (Okul Oncesi) Genisletilmis Veri Seti
20 konu x ~12 kelime = ~300+ kelime + dilbilgisi + diyalog + okuma + quiz
"""

DATA_PREA1 = {
    "label": "Pre-A1 (Okul Oncesi)",
    "vocab": [
        # ── 1. Hayvanlar (15) ──
        {"topic": "Hayvanlar", "emoji": "\U0001f43e", "words": [
            {"en": "Cat", "de": "Katze", "fr": "Chat", "it": "Gatto", "es": "Gato", "tr": "Kedi", "img": "\U0001f431"},
            {"en": "Dog", "de": "Hund", "fr": "Chien", "it": "Cane", "es": "Perro", "tr": "Kopek", "img": "\U0001f436"},
            {"en": "Bird", "de": "Vogel", "fr": "Oiseau", "it": "Uccello", "es": "Pajaro", "tr": "Kus", "img": "\U0001f426"},
            {"en": "Fish", "de": "Fisch", "fr": "Poisson", "it": "Pesce", "es": "Pez", "tr": "Balik", "img": "\U0001f41f"},
            {"en": "Rabbit", "de": "Kaninchen", "fr": "Lapin", "it": "Coniglio", "es": "Conejo", "tr": "Tavsan", "img": "\U0001f430"},
            {"en": "Horse", "de": "Pferd", "fr": "Cheval", "it": "Cavallo", "es": "Caballo", "tr": "At", "img": "\U0001f434"},
            {"en": "Cow", "de": "Kuh", "fr": "Vache", "it": "Mucca", "es": "Vaca", "tr": "Inek", "img": "\U0001f42e"},
            {"en": "Sheep", "de": "Schaf", "fr": "Mouton", "it": "Pecora", "es": "Oveja", "tr": "Koyun", "img": "\U0001f411"},
            {"en": "Duck", "de": "Ente", "fr": "Canard", "it": "Anatra", "es": "Pato", "tr": "Ordek", "img": "\U0001f986"},
            {"en": "Bear", "de": "Bar", "fr": "Ours", "it": "Orso", "es": "Oso", "tr": "Ayi", "img": "\U0001f43b"},
            {"en": "Lion", "de": "Lowe", "fr": "Lion", "it": "Leone", "es": "Leon", "tr": "Aslan", "img": "\U0001f981"},
            {"en": "Elephant", "de": "Elefant", "fr": "Elephant", "it": "Elefante", "es": "Elefante", "tr": "Fil", "img": "\U0001f418"},
            {"en": "Monkey", "de": "Affe", "fr": "Singe", "it": "Scimmia", "es": "Mono", "tr": "Maymun", "img": "\U0001f435"},
            {"en": "Butterfly", "de": "Schmetterling", "fr": "Papillon", "it": "Farfalla", "es": "Mariposa", "tr": "Kelebek", "img": "\U0001f98b"},
            {"en": "Frog", "de": "Frosch", "fr": "Grenouille", "it": "Rana", "es": "Rana", "tr": "Kurbaga", "img": "\U0001f438"},
        ]},
        # ── 2. Renkler (12) ──
        {"topic": "Renkler", "emoji": "\U0001f3a8", "words": [
            {"en": "Red", "de": "Rot", "fr": "Rouge", "it": "Rosso", "es": "Rojo", "tr": "Kirmizi", "img": "\U0001f534"},
            {"en": "Blue", "de": "Blau", "fr": "Bleu", "it": "Blu", "es": "Azul", "tr": "Mavi", "img": "\U0001f535"},
            {"en": "Yellow", "de": "Gelb", "fr": "Jaune", "it": "Giallo", "es": "Amarillo", "tr": "Sari", "img": "\U0001f7e1"},
            {"en": "Green", "de": "Grun", "fr": "Vert", "it": "Verde", "es": "Verde", "tr": "Yesil", "img": "\U0001f7e2"},
            {"en": "Orange", "de": "Orange", "fr": "Orange", "it": "Arancione", "es": "Naranja", "tr": "Turuncu", "img": "\U0001f7e0"},
            {"en": "Purple", "de": "Lila", "fr": "Violet", "it": "Viola", "es": "Morado", "tr": "Mor", "img": "\U0001f7e3"},
            {"en": "Pink", "de": "Rosa", "fr": "Rose", "it": "Rosa", "es": "Rosa", "tr": "Pembe", "img": "\U0001f338"},
            {"en": "Black", "de": "Schwarz", "fr": "Noir", "it": "Nero", "es": "Negro", "tr": "Siyah", "img": "\u26ab"},
            {"en": "White", "de": "Weiss", "fr": "Blanc", "it": "Bianco", "es": "Blanco", "tr": "Beyaz", "img": "\u26aa"},
            {"en": "Brown", "de": "Braun", "fr": "Marron", "it": "Marrone", "es": "Marron", "tr": "Kahverengi", "img": "\U0001f7e4"},
            {"en": "Gray", "de": "Grau", "fr": "Gris", "it": "Grigio", "es": "Gris", "tr": "Gri", "img": "\U0001f532"},
            {"en": "Gold", "de": "Gold", "fr": "Or", "it": "Oro", "es": "Oro", "tr": "Altin", "img": "\U0001f31f"},
        ]},
        # ── 3. Sayilar 1-20 (15 secilmis) ──
        {"topic": "Sayilar", "emoji": "\U0001f522", "words": [
            {"en": "One", "de": "Eins", "fr": "Un", "it": "Uno", "es": "Uno", "tr": "Bir", "img": "1\ufe0f\u20e3"},
            {"en": "Two", "de": "Zwei", "fr": "Deux", "it": "Due", "es": "Dos", "tr": "Iki", "img": "2\ufe0f\u20e3"},
            {"en": "Three", "de": "Drei", "fr": "Trois", "it": "Tre", "es": "Tres", "tr": "Uc", "img": "3\ufe0f\u20e3"},
            {"en": "Four", "de": "Vier", "fr": "Quatre", "it": "Quattro", "es": "Cuatro", "tr": "Dort", "img": "4\ufe0f\u20e3"},
            {"en": "Five", "de": "Funf", "fr": "Cinq", "it": "Cinque", "es": "Cinco", "tr": "Bes", "img": "5\ufe0f\u20e3"},
            {"en": "Six", "de": "Sechs", "fr": "Six", "it": "Sei", "es": "Seis", "tr": "Alti", "img": "6\ufe0f\u20e3"},
            {"en": "Seven", "de": "Sieben", "fr": "Sept", "it": "Sette", "es": "Siete", "tr": "Yedi", "img": "7\ufe0f\u20e3"},
            {"en": "Eight", "de": "Acht", "fr": "Huit", "it": "Otto", "es": "Ocho", "tr": "Sekiz", "img": "8\ufe0f\u20e3"},
            {"en": "Nine", "de": "Neun", "fr": "Neuf", "it": "Nove", "es": "Nueve", "tr": "Dokuz", "img": "9\ufe0f\u20e3"},
            {"en": "Ten", "de": "Zehn", "fr": "Dix", "it": "Dieci", "es": "Diez", "tr": "On", "img": "\U0001f51f"},
            {"en": "Eleven", "de": "Elf", "fr": "Onze", "it": "Undici", "es": "Once", "tr": "On bir", "img": "\U0001f522"},
            {"en": "Twelve", "de": "Zwolf", "fr": "Douze", "it": "Dodici", "es": "Doce", "tr": "On iki", "img": "\U0001f522"},
            {"en": "Fifteen", "de": "Funfzehn", "fr": "Quinze", "it": "Quindici", "es": "Quince", "tr": "On bes", "img": "\U0001f522"},
            {"en": "Twenty", "de": "Zwanzig", "fr": "Vingt", "it": "Venti", "es": "Veinte", "tr": "Yirmi", "img": "\U0001f522"},
            {"en": "Zero", "de": "Null", "fr": "Zero", "it": "Zero", "es": "Cero", "tr": "Sifir", "img": "0\ufe0f\u20e3"},
        ]},
        # ── 4. Aile (12) ──
        {"topic": "Aile", "emoji": "\U0001f468\u200d\U0001f469\u200d\U0001f467", "words": [
            {"en": "Mother", "de": "Mutter", "fr": "Mere", "it": "Madre", "es": "Madre", "tr": "Anne", "img": "\U0001f469"},
            {"en": "Father", "de": "Vater", "fr": "Pere", "it": "Padre", "es": "Padre", "tr": "Baba", "img": "\U0001f468"},
            {"en": "Sister", "de": "Schwester", "fr": "Soeur", "it": "Sorella", "es": "Hermana", "tr": "Kiz Kardes", "img": "\U0001f467"},
            {"en": "Brother", "de": "Bruder", "fr": "Frere", "it": "Fratello", "es": "Hermano", "tr": "Erkek Kardes", "img": "\U0001f466"},
            {"en": "Baby", "de": "Baby", "fr": "Bebe", "it": "Bambino", "es": "Bebe", "tr": "Bebek", "img": "\U0001f476"},
            {"en": "Grandmother", "de": "Grossmutter", "fr": "Grand-mere", "it": "Nonna", "es": "Abuela", "tr": "Buyukanne", "img": "\U0001f475"},
            {"en": "Grandfather", "de": "Grossvater", "fr": "Grand-pere", "it": "Nonno", "es": "Abuelo", "tr": "Buyukbaba", "img": "\U0001f474"},
            {"en": "Family", "de": "Familie", "fr": "Famille", "it": "Famiglia", "es": "Familia", "tr": "Aile", "img": "\U0001f46a"},
            {"en": "Uncle", "de": "Onkel", "fr": "Oncle", "it": "Zio", "es": "Tio", "tr": "Amca", "img": "\U0001f468"},
            {"en": "Aunt", "de": "Tante", "fr": "Tante", "it": "Zia", "es": "Tia", "tr": "Teyze", "img": "\U0001f469"},
            {"en": "Cousin", "de": "Cousin", "fr": "Cousin", "it": "Cugino", "es": "Primo", "tr": "Kuzen", "img": "\U0001f9d1"},
            {"en": "Friend", "de": "Freund", "fr": "Ami", "it": "Amico", "es": "Amigo", "tr": "Arkadas", "img": "\U0001f91d"},
        ]},
        # ── 5. Yiyecekler (15) ──
        {"topic": "Yiyecekler", "emoji": "\U0001f34e", "words": [
            {"en": "Bread", "de": "Brot", "fr": "Pain", "it": "Pane", "es": "Pan", "tr": "Ekmek", "img": "\U0001f35e"},
            {"en": "Milk", "de": "Milch", "fr": "Lait", "it": "Latte", "es": "Leche", "tr": "Sut", "img": "\U0001f95b"},
            {"en": "Water", "de": "Wasser", "fr": "Eau", "it": "Acqua", "es": "Agua", "tr": "Su", "img": "\U0001f4a7"},
            {"en": "Egg", "de": "Ei", "fr": "Oeuf", "it": "Uovo", "es": "Huevo", "tr": "Yumurta", "img": "\U0001f95a"},
            {"en": "Cheese", "de": "Kase", "fr": "Fromage", "it": "Formaggio", "es": "Queso", "tr": "Peynir", "img": "\U0001f9c0"},
            {"en": "Rice", "de": "Reis", "fr": "Riz", "it": "Riso", "es": "Arroz", "tr": "Pirinc", "img": "\U0001f35a"},
            {"en": "Soup", "de": "Suppe", "fr": "Soupe", "it": "Zuppa", "es": "Sopa", "tr": "Corba", "img": "\U0001f35c"},
            {"en": "Cake", "de": "Kuchen", "fr": "Gateau", "it": "Torta", "es": "Pastel", "tr": "Pasta", "img": "\U0001f370"},
            {"en": "Pizza", "de": "Pizza", "fr": "Pizza", "it": "Pizza", "es": "Pizza", "tr": "Pizza", "img": "\U0001f355"},
            {"en": "Chicken", "de": "Huhn", "fr": "Poulet", "it": "Pollo", "es": "Pollo", "tr": "Tavuk", "img": "\U0001f357"},
            {"en": "Ice cream", "de": "Eiscreme", "fr": "Glace", "it": "Gelato", "es": "Helado", "tr": "Dondurma", "img": "\U0001f368"},
            {"en": "Cookie", "de": "Keks", "fr": "Biscuit", "it": "Biscotto", "es": "Galleta", "tr": "Kurabiye", "img": "\U0001f36a"},
            {"en": "Honey", "de": "Honig", "fr": "Miel", "it": "Miele", "es": "Miel", "tr": "Bal", "img": "\U0001f36f"},
            {"en": "Butter", "de": "Butter", "fr": "Beurre", "it": "Burro", "es": "Mantequilla", "tr": "Tereyagi", "img": "\U0001f9c8"},
            {"en": "Juice", "de": "Saft", "fr": "Jus", "it": "Succo", "es": "Jugo", "tr": "Meyve suyu", "img": "\U0001f9c3"},
        ]},
        # ── 6. Meyveler (12) ──
        {"topic": "Meyveler", "emoji": "\U0001f347", "words": [
            {"en": "Apple", "de": "Apfel", "fr": "Pomme", "it": "Mela", "es": "Manzana", "tr": "Elma", "img": "\U0001f34e"},
            {"en": "Banana", "de": "Banane", "fr": "Banane", "it": "Banana", "es": "Platano", "tr": "Muz", "img": "\U0001f34c"},
            {"en": "Strawberry", "de": "Erdbeere", "fr": "Fraise", "it": "Fragola", "es": "Fresa", "tr": "Cilek", "img": "\U0001f353"},
            {"en": "Grape", "de": "Traube", "fr": "Raisin", "it": "Uva", "es": "Uva", "tr": "Uzum", "img": "\U0001f347"},
            {"en": "Orange", "de": "Orange", "fr": "Orange", "it": "Arancia", "es": "Naranja", "tr": "Portakal", "img": "\U0001f34a"},
            {"en": "Watermelon", "de": "Wassermelone", "fr": "Pasteque", "it": "Anguria", "es": "Sandia", "tr": "Karpuz", "img": "\U0001f349"},
            {"en": "Cherry", "de": "Kirsche", "fr": "Cerise", "it": "Ciliegia", "es": "Cereza", "tr": "Kiraz", "img": "\U0001f352"},
            {"en": "Peach", "de": "Pfirsich", "fr": "Peche", "it": "Pesca", "es": "Melocoton", "tr": "Seftali", "img": "\U0001f351"},
            {"en": "Pear", "de": "Birne", "fr": "Poire", "it": "Pera", "es": "Pera", "tr": "Armut", "img": "\U0001f350"},
            {"en": "Lemon", "de": "Zitrone", "fr": "Citron", "it": "Limone", "es": "Limon", "tr": "Limon", "img": "\U0001f34b"},
            {"en": "Pineapple", "de": "Ananas", "fr": "Ananas", "it": "Ananas", "es": "Pina", "tr": "Ananas", "img": "\U0001f34d"},
            {"en": "Melon", "de": "Melone", "fr": "Melon", "it": "Melone", "es": "Melon", "tr": "Kavun", "img": "\U0001f348"},
        ]},
        # ── 7. Vucut (15) ──
        {"topic": "Vucut", "emoji": "\U0001f9d1", "words": [
            {"en": "Head", "de": "Kopf", "fr": "Tete", "it": "Testa", "es": "Cabeza", "tr": "Bas", "img": "\U0001f9d1"},
            {"en": "Hand", "de": "Hand", "fr": "Main", "it": "Mano", "es": "Mano", "tr": "El", "img": "\u270b"},
            {"en": "Eye", "de": "Auge", "fr": "Oeil", "it": "Occhio", "es": "Ojo", "tr": "Goz", "img": "\U0001f441\ufe0f"},
            {"en": "Ear", "de": "Ohr", "fr": "Oreille", "it": "Orecchio", "es": "Oreja", "tr": "Kulak", "img": "\U0001f442"},
            {"en": "Nose", "de": "Nase", "fr": "Nez", "it": "Naso", "es": "Nariz", "tr": "Burun", "img": "\U0001f443"},
            {"en": "Mouth", "de": "Mund", "fr": "Bouche", "it": "Bocca", "es": "Boca", "tr": "Agiz", "img": "\U0001f444"},
            {"en": "Foot", "de": "Fuss", "fr": "Pied", "it": "Piede", "es": "Pie", "tr": "Ayak", "img": "\U0001f9b6"},
            {"en": "Arm", "de": "Arm", "fr": "Bras", "it": "Braccio", "es": "Brazo", "tr": "Kol", "img": "\U0001f4aa"},
            {"en": "Leg", "de": "Bein", "fr": "Jambe", "it": "Gamba", "es": "Pierna", "tr": "Bacak", "img": "\U0001f9b5"},
            {"en": "Finger", "de": "Finger", "fr": "Doigt", "it": "Dito", "es": "Dedo", "tr": "Parmak", "img": "\U0001f446"},
            {"en": "Hair", "de": "Haar", "fr": "Cheveux", "it": "Capelli", "es": "Cabello", "tr": "Sac", "img": "\U0001f487"},
            {"en": "Tooth", "de": "Zahn", "fr": "Dent", "it": "Dente", "es": "Diente", "tr": "Dis", "img": "\U0001f9b7"},
            {"en": "Knee", "de": "Knie", "fr": "Genou", "it": "Ginocchio", "es": "Rodilla", "tr": "Diz", "img": "\U0001f9b5"},
            {"en": "Shoulder", "de": "Schulter", "fr": "Epaule", "it": "Spalla", "es": "Hombro", "tr": "Omuz", "img": "\U0001f933"},
            {"en": "Stomach", "de": "Bauch", "fr": "Ventre", "it": "Stomaco", "es": "Estomago", "tr": "Karin", "img": "\U0001f930"},
        ]},
        # ── 8. Giysiler (12) ──
        {"topic": "Giysiler", "emoji": "\U0001f455", "words": [
            {"en": "Shirt", "de": "Hemd", "fr": "Chemise", "it": "Camicia", "es": "Camisa", "tr": "Gomlek", "img": "\U0001f455"},
            {"en": "Pants", "de": "Hose", "fr": "Pantalon", "it": "Pantaloni", "es": "Pantalones", "tr": "Pantolon", "img": "\U0001f456"},
            {"en": "Shoes", "de": "Schuhe", "fr": "Chaussures", "it": "Scarpe", "es": "Zapatos", "tr": "Ayakkabi", "img": "\U0001f45f"},
            {"en": "Hat", "de": "Hut", "fr": "Chapeau", "it": "Cappello", "es": "Sombrero", "tr": "Sapka", "img": "\U0001f3a9"},
            {"en": "Coat", "de": "Mantel", "fr": "Manteau", "it": "Cappotto", "es": "Abrigo", "tr": "Mont", "img": "\U0001f9e5"},
            {"en": "Dress", "de": "Kleid", "fr": "Robe", "it": "Vestito", "es": "Vestido", "tr": "Elbise", "img": "\U0001f457"},
            {"en": "Socks", "de": "Socken", "fr": "Chaussettes", "it": "Calzini", "es": "Calcetines", "tr": "Corap", "img": "\U0001f9e6"},
            {"en": "Scarf", "de": "Schal", "fr": "Echarpe", "it": "Sciarpa", "es": "Bufanda", "tr": "Atki", "img": "\U0001f9e3"},
            {"en": "Skirt", "de": "Rock", "fr": "Jupe", "it": "Gonna", "es": "Falda", "tr": "Etek", "img": "\U0001f458"},
            {"en": "Gloves", "de": "Handschuhe", "fr": "Gants", "it": "Guanti", "es": "Guantes", "tr": "Eldiven", "img": "\U0001f9e4"},
            {"en": "Boots", "de": "Stiefel", "fr": "Bottes", "it": "Stivali", "es": "Botas", "tr": "Cizme", "img": "\U0001f462"},
            {"en": "Sweater", "de": "Pullover", "fr": "Pull", "it": "Maglione", "es": "Sueter", "tr": "Kazak", "img": "\U0001f9e5"},
        ]},
        # ── 9. Oyuncaklar (10) ──
        {"topic": "Oyuncaklar", "emoji": "\U0001f9f8", "words": [
            {"en": "Ball", "de": "Ball", "fr": "Balle", "it": "Palla", "es": "Pelota", "tr": "Top", "img": "\u26bd"},
            {"en": "Doll", "de": "Puppe", "fr": "Poupee", "it": "Bambola", "es": "Muneca", "tr": "Bebek", "img": "\U0001f38e"},
            {"en": "Car", "de": "Auto", "fr": "Voiture", "it": "Macchina", "es": "Coche", "tr": "Araba", "img": "\U0001f697"},
            {"en": "Teddy bear", "de": "Teddybar", "fr": "Ours en peluche", "it": "Orsacchiotto", "es": "Osito de peluche", "tr": "Oyuncak ayi", "img": "\U0001f9f8"},
            {"en": "Puzzle", "de": "Puzzle", "fr": "Puzzle", "it": "Puzzle", "es": "Rompecabezas", "tr": "Yapboz", "img": "\U0001f9e9"},
            {"en": "Blocks", "de": "Bausteine", "fr": "Blocs", "it": "Mattoncini", "es": "Bloques", "tr": "Bloklar", "img": "\U0001f9f1"},
            {"en": "Kite", "de": "Drachen", "fr": "Cerf-volant", "it": "Aquilone", "es": "Cometa", "tr": "Ucurtma", "img": "\U0001fa81"},
            {"en": "Robot", "de": "Roboter", "fr": "Robot", "it": "Robot", "es": "Robot", "tr": "Robot", "img": "\U0001f916"},
            {"en": "Train", "de": "Zug", "fr": "Train", "it": "Treno", "es": "Tren", "tr": "Tren", "img": "\U0001f682"},
            {"en": "Balloon", "de": "Luftballon", "fr": "Ballon", "it": "Palloncino", "es": "Globo", "tr": "Balon", "img": "\U0001f388"},
        ]},
        # ── 10. Ev Esyalari (12) ──
        {"topic": "Ev Esyalari", "emoji": "\U0001f3e0", "words": [
            {"en": "Table", "de": "Tisch", "fr": "Table", "it": "Tavolo", "es": "Mesa", "tr": "Masa", "img": "\U0001f4cb"},
            {"en": "Chair", "de": "Stuhl", "fr": "Chaise", "it": "Sedia", "es": "Silla", "tr": "Sandalye", "img": "\U0001fa91"},
            {"en": "Bed", "de": "Bett", "fr": "Lit", "it": "Letto", "es": "Cama", "tr": "Yatak", "img": "\U0001f6cf\ufe0f"},
            {"en": "Door", "de": "Tur", "fr": "Porte", "it": "Porta", "es": "Puerta", "tr": "Kapi", "img": "\U0001f6aa"},
            {"en": "Window", "de": "Fenster", "fr": "Fenetre", "it": "Finestra", "es": "Ventana", "tr": "Pencere", "img": "\U0001fa9f"},
            {"en": "Lamp", "de": "Lampe", "fr": "Lampe", "it": "Lampada", "es": "Lampara", "tr": "Lamba", "img": "\U0001f4a1"},
            {"en": "Television", "de": "Fernseher", "fr": "Television", "it": "Televisione", "es": "Television", "tr": "Televizyon", "img": "\U0001f4fa"},
            {"en": "Clock", "de": "Uhr", "fr": "Horloge", "it": "Orologio", "es": "Reloj", "tr": "Saat", "img": "\U0001f570\ufe0f"},
            {"en": "Mirror", "de": "Spiegel", "fr": "Miroir", "it": "Specchio", "es": "Espejo", "tr": "Ayna", "img": "\U0001fa9e"},
            {"en": "Telephone", "de": "Telefon", "fr": "Telephone", "it": "Telefono", "es": "Telefono", "tr": "Telefon", "img": "\u260e\ufe0f"},
            {"en": "Key", "de": "Schlussel", "fr": "Cle", "it": "Chiave", "es": "Llave", "tr": "Anahtar", "img": "\U0001f511"},
            {"en": "Cup", "de": "Tasse", "fr": "Tasse", "it": "Tazza", "es": "Taza", "tr": "Bardak", "img": "\u2615"},
        ]},
        # ── 11. Doga (10) ──
        {"topic": "Doga", "emoji": "\U0001f333", "words": [
            {"en": "Sun", "de": "Sonne", "fr": "Soleil", "it": "Sole", "es": "Sol", "tr": "Gunes", "img": "\u2600\ufe0f"},
            {"en": "Moon", "de": "Mond", "fr": "Lune", "it": "Luna", "es": "Luna", "tr": "Ay", "img": "\U0001f319"},
            {"en": "Star", "de": "Stern", "fr": "Etoile", "it": "Stella", "es": "Estrella", "tr": "Yildiz", "img": "\u2b50"},
            {"en": "Tree", "de": "Baum", "fr": "Arbre", "it": "Albero", "es": "Arbol", "tr": "Agac", "img": "\U0001f333"},
            {"en": "Flower", "de": "Blume", "fr": "Fleur", "it": "Fiore", "es": "Flor", "tr": "Cicek", "img": "\U0001f33b"},
            {"en": "Rain", "de": "Regen", "fr": "Pluie", "it": "Pioggia", "es": "Lluvia", "tr": "Yagmur", "img": "\U0001f327\ufe0f"},
            {"en": "Snow", "de": "Schnee", "fr": "Neige", "it": "Neve", "es": "Nieve", "tr": "Kar", "img": "\u2744\ufe0f"},
            {"en": "Cloud", "de": "Wolke", "fr": "Nuage", "it": "Nuvola", "es": "Nube", "tr": "Bulut", "img": "\u2601\ufe0f"},
            {"en": "Rainbow", "de": "Regenbogen", "fr": "Arc-en-ciel", "it": "Arcobaleno", "es": "Arcoiris", "tr": "Gokkusagi", "img": "\U0001f308"},
            {"en": "Mountain", "de": "Berg", "fr": "Montagne", "it": "Montagna", "es": "Montana", "tr": "Dag", "img": "\u26f0\ufe0f"},
        ]},
        # ── 12. Tasitlar (10) ──
        {"topic": "Tasitlar", "emoji": "\U0001f697", "words": [
            {"en": "Car", "de": "Auto", "fr": "Voiture", "it": "Macchina", "es": "Coche", "tr": "Araba", "img": "\U0001f697"},
            {"en": "Bus", "de": "Bus", "fr": "Bus", "it": "Autobus", "es": "Autobus", "tr": "Otobus", "img": "\U0001f68c"},
            {"en": "Bicycle", "de": "Fahrrad", "fr": "Velo", "it": "Bicicletta", "es": "Bicicleta", "tr": "Bisiklet", "img": "\U0001f6b2"},
            {"en": "Airplane", "de": "Flugzeug", "fr": "Avion", "it": "Aereo", "es": "Avion", "tr": "Ucak", "img": "\u2708\ufe0f"},
            {"en": "Ship", "de": "Schiff", "fr": "Bateau", "it": "Nave", "es": "Barco", "tr": "Gemi", "img": "\U0001f6a2"},
            {"en": "Train", "de": "Zug", "fr": "Train", "it": "Treno", "es": "Tren", "tr": "Tren", "img": "\U0001f686"},
            {"en": "Helicopter", "de": "Hubschrauber", "fr": "Helicoptere", "it": "Elicottero", "es": "Helicoptero", "tr": "Helikopter", "img": "\U0001f681"},
            {"en": "Truck", "de": "Lastwagen", "fr": "Camion", "it": "Camion", "es": "Camion", "tr": "Kamyon", "img": "\U0001f69a"},
            {"en": "Motorcycle", "de": "Motorrad", "fr": "Moto", "it": "Moto", "es": "Motocicleta", "tr": "Motosiklet", "img": "\U0001f3cd\ufe0f"},
            {"en": "Ambulance", "de": "Krankenwagen", "fr": "Ambulance", "it": "Ambulanza", "es": "Ambulancia", "tr": "Ambulans", "img": "\U0001f691"},
        ]},
        # ── 13. Sebzeler (12) ── [NEW]
        {"topic": "Sebzeler", "emoji": "\U0001f966", "words": [
            {"en": "Tomato", "de": "Tomate", "fr": "Tomate", "it": "Pomodoro", "es": "Tomate", "tr": "Domates", "img": "\U0001f345"},
            {"en": "Potato", "de": "Kartoffel", "fr": "Pomme de terre", "it": "Patata", "es": "Papa", "tr": "Patates", "img": "\U0001f954"},
            {"en": "Onion", "de": "Zwiebel", "fr": "Oignon", "it": "Cipolla", "es": "Cebolla", "tr": "Sogan", "img": "\U0001f9c5"},
            {"en": "Carrot", "de": "Karotte", "fr": "Carotte", "it": "Carota", "es": "Zanahoria", "tr": "Havuc", "img": "\U0001f955"},
            {"en": "Cucumber", "de": "Gurke", "fr": "Concombre", "it": "Cetriolo", "es": "Pepino", "tr": "Salatalik", "img": "\U0001f952"},
            {"en": "Pepper", "de": "Paprika", "fr": "Poivron", "it": "Peperone", "es": "Pimiento", "tr": "Biber", "img": "\U0001fad1"},
            {"en": "Lettuce", "de": "Salat", "fr": "Laitue", "it": "Lattuga", "es": "Lechuga", "tr": "Marul", "img": "\U0001f96c"},
            {"en": "Corn", "de": "Mais", "fr": "Mais", "it": "Mais", "es": "Maiz", "tr": "Misir", "img": "\U0001f33d"},
            {"en": "Pea", "de": "Erbse", "fr": "Petit pois", "it": "Pisello", "es": "Guisante", "tr": "Bezelye", "img": "\U0001f96c"},
            {"en": "Garlic", "de": "Knoblauch", "fr": "Ail", "it": "Aglio", "es": "Ajo", "tr": "Sarimsak", "img": "\U0001f9c4"},
            {"en": "Mushroom", "de": "Pilz", "fr": "Champignon", "it": "Fungo", "es": "Champiñon", "tr": "Mantar", "img": "\U0001f344"},
            {"en": "Broccoli", "de": "Brokkoli", "fr": "Brocoli", "it": "Broccolo", "es": "Brocoli", "tr": "Brokoli", "img": "\U0001f966"},
        ]},
        # ── 14. Mevsimler/Hava (12) ── [NEW]
        {"topic": "Mevsimler ve Hava", "emoji": "\U0001f326\ufe0f", "words": [
            {"en": "Spring", "de": "Fruhling", "fr": "Printemps", "it": "Primavera", "es": "Primavera", "tr": "Ilkbahar", "img": "\U0001f338"},
            {"en": "Summer", "de": "Sommer", "fr": "Ete", "it": "Estate", "es": "Verano", "tr": "Yaz", "img": "\u2600\ufe0f"},
            {"en": "Autumn", "de": "Herbst", "fr": "Automne", "it": "Autunno", "es": "Otono", "tr": "Sonbahar", "img": "\U0001f342"},
            {"en": "Winter", "de": "Winter", "fr": "Hiver", "it": "Inverno", "es": "Invierno", "tr": "Kis", "img": "\u2744\ufe0f"},
            {"en": "Sunny", "de": "Sonnig", "fr": "Ensoleille", "it": "Soleggiato", "es": "Soleado", "tr": "Gunesli", "img": "\u2600\ufe0f"},
            {"en": "Rainy", "de": "Regnerisch", "fr": "Pluvieux", "it": "Piovoso", "es": "Lluvioso", "tr": "Yagmurlu", "img": "\U0001f327\ufe0f"},
            {"en": "Cloudy", "de": "Wolkig", "fr": "Nuageux", "it": "Nuvoloso", "es": "Nublado", "tr": "Bulutlu", "img": "\u2601\ufe0f"},
            {"en": "Snowy", "de": "Schneereich", "fr": "Neigeux", "it": "Nevoso", "es": "Nevado", "tr": "Karli", "img": "\U0001f328\ufe0f"},
            {"en": "Windy", "de": "Windig", "fr": "Venteux", "it": "Ventoso", "es": "Ventoso", "tr": "Ruzgarli", "img": "\U0001f32c\ufe0f"},
            {"en": "Hot", "de": "Heiss", "fr": "Chaud", "it": "Caldo", "es": "Caliente", "tr": "Sicak", "img": "\U0001f321\ufe0f"},
            {"en": "Cold", "de": "Kalt", "fr": "Froid", "it": "Freddo", "es": "Frio", "tr": "Soguk", "img": "\U0001f9ca"},
            {"en": "Warm", "de": "Warm", "fr": "Tiede", "it": "Tiepido", "es": "Templado", "tr": "Ilik", "img": "\U0001f31e"},
        ]},
        # ── 15. Mutfak Esyalari (12) ── [NEW]
        {"topic": "Mutfak Esyalari", "emoji": "\U0001f37d\ufe0f", "words": [
            {"en": "Plate", "de": "Teller", "fr": "Assiette", "it": "Piatto", "es": "Plato", "tr": "Tabak", "img": "\U0001f37d\ufe0f"},
            {"en": "Glass", "de": "Glas", "fr": "Verre", "it": "Bicchiere", "es": "Vaso", "tr": "Bardak", "img": "\U0001f95b"},
            {"en": "Spoon", "de": "Loffel", "fr": "Cuillere", "it": "Cucchiaio", "es": "Cuchara", "tr": "Kasik", "img": "\U0001f944"},
            {"en": "Fork", "de": "Gabel", "fr": "Fourchette", "it": "Forchetta", "es": "Tenedor", "tr": "Catal", "img": "\U0001f374"},
            {"en": "Knife", "de": "Messer", "fr": "Couteau", "it": "Coltello", "es": "Cuchillo", "tr": "Bicak", "img": "\U0001f52a"},
            {"en": "Cup", "de": "Tasse", "fr": "Tasse", "it": "Tazza", "es": "Taza", "tr": "Fincan", "img": "\u2615"},
            {"en": "Pot", "de": "Topf", "fr": "Casserole", "it": "Pentola", "es": "Olla", "tr": "Tencere", "img": "\U0001f372"},
            {"en": "Pan", "de": "Pfanne", "fr": "Poele", "it": "Padella", "es": "Sarten", "tr": "Tava", "img": "\U0001f373"},
            {"en": "Bowl", "de": "Schussel", "fr": "Bol", "it": "Ciotola", "es": "Cuenco", "tr": "Kase", "img": "\U0001f963"},
            {"en": "Napkin", "de": "Serviette", "fr": "Serviette", "it": "Tovagliolo", "es": "Servilleta", "tr": "Pecete", "img": "\U0001f9fb"},
            {"en": "Tray", "de": "Tablett", "fr": "Plateau", "it": "Vassoio", "es": "Bandeja", "tr": "Tepsi", "img": "\U0001f37d\ufe0f"},
            {"en": "Bottle", "de": "Flasche", "fr": "Bouteille", "it": "Bottiglia", "es": "Botella", "tr": "Sise", "img": "\U0001f37c"},
        ]},
        # ── 16. Banyo (10) ── [NEW]
        {"topic": "Banyo", "emoji": "\U0001f6c1", "words": [
            {"en": "Soap", "de": "Seife", "fr": "Savon", "it": "Sapone", "es": "Jabon", "tr": "Sabun", "img": "\U0001f9fc"},
            {"en": "Towel", "de": "Handtuch", "fr": "Serviette", "it": "Asciugamano", "es": "Toalla", "tr": "Havlu", "img": "\U0001f9f4"},
            {"en": "Mirror", "de": "Spiegel", "fr": "Miroir", "it": "Specchio", "es": "Espejo", "tr": "Ayna", "img": "\U0001fa9e"},
            {"en": "Toothbrush", "de": "Zahnburste", "fr": "Brosse a dents", "it": "Spazzolino", "es": "Cepillo de dientes", "tr": "Dis fircasi", "img": "\U0001faa5"},
            {"en": "Toothpaste", "de": "Zahnpasta", "fr": "Dentifrice", "it": "Dentifricio", "es": "Pasta de dientes", "tr": "Dis macunu", "img": "\U0001f9f4"},
            {"en": "Shampoo", "de": "Shampoo", "fr": "Shampooing", "it": "Shampoo", "es": "Champu", "tr": "Sampuan", "img": "\U0001f9f4"},
            {"en": "Bathtub", "de": "Badewanne", "fr": "Baignoire", "it": "Vasca da bagno", "es": "Banera", "tr": "Kuvet", "img": "\U0001f6c1"},
            {"en": "Shower", "de": "Dusche", "fr": "Douche", "it": "Doccia", "es": "Ducha", "tr": "Dus", "img": "\U0001f6bf"},
            {"en": "Toilet", "de": "Toilette", "fr": "Toilettes", "it": "Gabinetto", "es": "Inodoro", "tr": "Tuvalet", "img": "\U0001f6bd"},
            {"en": "Comb", "de": "Kamm", "fr": "Peigne", "it": "Pettine", "es": "Peine", "tr": "Tarak", "img": "\U0001f9b0"},
        ]},
        # ── 17. Okul Malzemeleri (12) ── [NEW]
        {"topic": "Okul Malzemeleri", "emoji": "\u270f\ufe0f", "words": [
            {"en": "Pencil", "de": "Bleistift", "fr": "Crayon", "it": "Matita", "es": "Lapiz", "tr": "Kalem", "img": "\u270f\ufe0f"},
            {"en": "Ruler", "de": "Lineal", "fr": "Regle", "it": "Righello", "es": "Regla", "tr": "Cetvel", "img": "\U0001f4cf"},
            {"en": "Eraser", "de": "Radiergummi", "fr": "Gomme", "it": "Gomma", "es": "Borrador", "tr": "Silgi", "img": "\U0001f9f9"},
            {"en": "Scissors", "de": "Schere", "fr": "Ciseaux", "it": "Forbici", "es": "Tijeras", "tr": "Makas", "img": "\u2702\ufe0f"},
            {"en": "Glue", "de": "Kleber", "fr": "Colle", "it": "Colla", "es": "Pegamento", "tr": "Yapistirici", "img": "\U0001f4ce"},
            {"en": "Crayon", "de": "Wachsmalstift", "fr": "Crayon de cire", "it": "Pastello a cera", "es": "Crayon", "tr": "Boya kalemi", "img": "\U0001f58d\ufe0f"},
            {"en": "Notebook", "de": "Heft", "fr": "Cahier", "it": "Quaderno", "es": "Cuaderno", "tr": "Defter", "img": "\U0001f4d3"},
            {"en": "Backpack", "de": "Rucksack", "fr": "Sac a dos", "it": "Zaino", "es": "Mochila", "tr": "Sirt cantasi", "img": "\U0001f392"},
            {"en": "Chalk", "de": "Kreide", "fr": "Craie", "it": "Gesso", "es": "Tiza", "tr": "Tebessir", "img": "\U0001f58d\ufe0f"},
            {"en": "Blackboard", "de": "Tafel", "fr": "Tableau", "it": "Lavagna", "es": "Pizarra", "tr": "Kara tahta", "img": "\U0001f4dd"},
            {"en": "Paper", "de": "Papier", "fr": "Papier", "it": "Carta", "es": "Papel", "tr": "Kagit", "img": "\U0001f4c4"},
            {"en": "Paint", "de": "Farbe", "fr": "Peinture", "it": "Pittura", "es": "Pintura", "tr": "Boya", "img": "\U0001f3a8"},
        ]},
        # ── 18. Meyve Ek (10) ── [NEW]
        {"topic": "Meyve Ek", "emoji": "\U0001f349", "words": [
            {"en": "Watermelon", "de": "Wassermelone", "fr": "Pasteque", "it": "Anguria", "es": "Sandia", "tr": "Karpuz", "img": "\U0001f349"},
            {"en": "Melon", "de": "Melone", "fr": "Melon", "it": "Melone", "es": "Melon", "tr": "Kavun", "img": "\U0001f348"},
            {"en": "Peach", "de": "Pfirsich", "fr": "Peche", "it": "Pesca", "es": "Melocoton", "tr": "Seftali", "img": "\U0001f351"},
            {"en": "Cherry", "de": "Kirsche", "fr": "Cerise", "it": "Ciliegia", "es": "Cereza", "tr": "Kiraz", "img": "\U0001f352"},
            {"en": "Plum", "de": "Pflaume", "fr": "Prune", "it": "Prugna", "es": "Ciruela", "tr": "Erik", "img": "\U0001f351"},
            {"en": "Pear", "de": "Birne", "fr": "Poire", "it": "Pera", "es": "Pera", "tr": "Armut", "img": "\U0001f350"},
            {"en": "Lemon", "de": "Zitrone", "fr": "Citron", "it": "Limone", "es": "Limon", "tr": "Limon", "img": "\U0001f34b"},
            {"en": "Pineapple", "de": "Ananas", "fr": "Ananas", "it": "Ananas", "es": "Pina", "tr": "Ananas", "img": "\U0001f34d"},
            {"en": "Mango", "de": "Mango", "fr": "Mangue", "it": "Mango", "es": "Mango", "tr": "Mango", "img": "\U0001f96d"},
            {"en": "Coconut", "de": "Kokosnuss", "fr": "Noix de coco", "it": "Cocco", "es": "Coco", "tr": "Hindistancevizi", "img": "\U0001f965"},
        ]},
        # ── 19. Bocekler (10) ── [NEW]
        {"topic": "Bocekler", "emoji": "\U0001f41b", "words": [
            {"en": "Ant", "de": "Ameise", "fr": "Fourmi", "it": "Formica", "es": "Hormiga", "tr": "Karinca", "img": "\U0001f41c"},
            {"en": "Bee", "de": "Biene", "fr": "Abeille", "it": "Ape", "es": "Abeja", "tr": "Ari", "img": "\U0001f41d"},
            {"en": "Spider", "de": "Spinne", "fr": "Araignee", "it": "Ragno", "es": "Arana", "tr": "Orumcek", "img": "\U0001f577\ufe0f"},
            {"en": "Fly", "de": "Fliege", "fr": "Mouche", "it": "Mosca", "es": "Mosca", "tr": "Sinek", "img": "\U0001fab0"},
            {"en": "Mosquito", "de": "Mucke", "fr": "Moustique", "it": "Zanzara", "es": "Mosquito", "tr": "Sivrisinek", "img": "\U0001f99f"},
            {"en": "Ladybug", "de": "Marienkafer", "fr": "Coccinelle", "it": "Coccinella", "es": "Mariquita", "tr": "Ugur bocegi", "img": "\U0001f41e"},
            {"en": "Dragonfly", "de": "Libelle", "fr": "Libellule", "it": "Libellula", "es": "Libelula", "tr": "Yusufcuk", "img": "\U0001f41b"},
            {"en": "Grasshopper", "de": "Heuschrecke", "fr": "Sauterelle", "it": "Cavalletta", "es": "Saltamontes", "tr": "Cekirge", "img": "\U0001f997"},
            {"en": "Caterpillar", "de": "Raupe", "fr": "Chenille", "it": "Bruco", "es": "Oruga", "tr": "Tirtil", "img": "\U0001f41b"},
            {"en": "Snail", "de": "Schnecke", "fr": "Escargot", "it": "Lumaca", "es": "Caracol", "tr": "Salyangoz", "img": "\U0001f40c"},
        ]},
        # ── 20. Sekiller (10) ── [NEW]
        {"topic": "Sekiller", "emoji": "\U0001f534", "words": [
            {"en": "Circle", "de": "Kreis", "fr": "Cercle", "it": "Cerchio", "es": "Circulo", "tr": "Daire", "img": "\u26aa"},
            {"en": "Square", "de": "Quadrat", "fr": "Carre", "it": "Quadrato", "es": "Cuadrado", "tr": "Kare", "img": "\U0001f7e7"},
            {"en": "Triangle", "de": "Dreieck", "fr": "Triangle", "it": "Triangolo", "es": "Triangulo", "tr": "Ucgen", "img": "\U0001f53a"},
            {"en": "Rectangle", "de": "Rechteck", "fr": "Rectangle", "it": "Rettangolo", "es": "Rectangulo", "tr": "Dikdortgen", "img": "\U0001f7e8"},
            {"en": "Star", "de": "Stern", "fr": "Etoile", "it": "Stella", "es": "Estrella", "tr": "Yildiz", "img": "\u2b50"},
            {"en": "Heart", "de": "Herz", "fr": "Coeur", "it": "Cuore", "es": "Corazon", "tr": "Kalp", "img": "\u2764\ufe0f"},
            {"en": "Diamond", "de": "Raute", "fr": "Losange", "it": "Rombo", "es": "Rombo", "tr": "Elmas", "img": "\U0001f537"},
            {"en": "Oval", "de": "Oval", "fr": "Ovale", "it": "Ovale", "es": "Ovalo", "tr": "Oval", "img": "\U0001f536"},
            {"en": "Pentagon", "de": "Funfeck", "fr": "Pentagone", "it": "Pentagono", "es": "Pentagono", "tr": "Besgen", "img": "\u2b1f"},
            {"en": "Hexagon", "de": "Sechseck", "fr": "Hexagone", "it": "Esagono", "es": "Hexagono", "tr": "Altigen", "img": "\u2b22"},
        ]},
    ],
    # ════════════════════════════════════════
    # GRAMMAR (10 kural x 5 ornek)
    # ════════════════════════════════════════
    "grammar": [
        # 1. Bu ne? / What is this?
        {"title": "Bu ne? / What is this?", "rule_tr": "This is a ___.", "examples": [
            {"en": "This is a cat.", "de": "Das ist eine Katze.", "fr": "C'est un chat.", "it": "Questo e un gatto.", "es": "Esto es un gato.", "tr": "Bu bir kedi."},
            {"en": "This is a dog.", "de": "Das ist ein Hund.", "fr": "C'est un chien.", "it": "Questo e un cane.", "es": "Esto es un perro.", "tr": "Bu bir kopek."},
            {"en": "This is a book.", "de": "Das ist ein Buch.", "fr": "C'est un livre.", "it": "Questo e un libro.", "es": "Esto es un libro.", "tr": "Bu bir kitap."},
            {"en": "This is an apple.", "de": "Das ist ein Apfel.", "fr": "C'est une pomme.", "it": "Questa e una mela.", "es": "Esto es una manzana.", "tr": "Bu bir elma."},
            {"en": "This is a flower.", "de": "Das ist eine Blume.", "fr": "C'est une fleur.", "it": "Questo e un fiore.", "es": "Esto es una flor.", "tr": "Bu bir cicek."},
        ], "exercises": [
            {"prompt": "This is a ___.", "answer": "cat", "hint": "Kedi", "img": "\U0001f431"},
            {"prompt": "This is a ___.", "answer": "dog", "hint": "Kopek", "img": "\U0001f436"},
            {"prompt": "This is a ___.", "answer": "bird", "hint": "Kus", "img": "\U0001f426"},
            {"prompt": "This is an ___.", "answer": "apple", "hint": "Elma", "img": "\U0001f34e"},
            {"prompt": "This is a ___.", "answer": "fish", "hint": "Balik", "img": "\U0001f41f"},
        ]},
        # 2. Renkler / Colors
        {"title": "Renkler / Colors", "rule_tr": "It is ___. (renk)", "examples": [
            {"en": "It is red.", "de": "Es ist rot.", "fr": "C'est rouge.", "it": "E rosso.", "es": "Es rojo.", "tr": "Kirmizi."},
            {"en": "It is blue.", "de": "Es ist blau.", "fr": "C'est bleu.", "it": "E blu.", "es": "Es azul.", "tr": "Mavi."},
            {"en": "It is green.", "de": "Es ist grun.", "fr": "C'est vert.", "it": "E verde.", "es": "Es verde.", "tr": "Yesil."},
            {"en": "It is yellow.", "de": "Es ist gelb.", "fr": "C'est jaune.", "it": "E giallo.", "es": "Es amarillo.", "tr": "Sari."},
            {"en": "It is white.", "de": "Es ist weiss.", "fr": "C'est blanc.", "it": "E bianco.", "es": "Es blanco.", "tr": "Beyaz."},
        ], "exercises": [
            {"prompt": "The apple is ___.", "answer": "red", "hint": "Kirmizi"},
            {"prompt": "The sky is ___.", "answer": "blue", "hint": "Mavi"},
            {"prompt": "The grass is ___.", "answer": "green", "hint": "Yesil"},
            {"prompt": "The sun is ___.", "answer": "yellow", "hint": "Sari"},
            {"prompt": "The snow is ___.", "answer": "white", "hint": "Beyaz"},
        ]},
        # 3. Sayilar / Counting
        {"title": "Sayilar / Counting", "rule_tr": "I have ___ (sayi + isim)", "examples": [
            {"en": "I have two cats.", "de": "Ich habe zwei Katzen.", "fr": "J'ai deux chats.", "it": "Ho due gatti.", "es": "Tengo dos gatos.", "tr": "Iki kedim var."},
            {"en": "I have three apples.", "de": "Ich habe drei Apfel.", "fr": "J'ai trois pommes.", "it": "Ho tre mele.", "es": "Tengo tres manzanas.", "tr": "Uc elmam var."},
            {"en": "I have one brother.", "de": "Ich habe einen Bruder.", "fr": "J'ai un frere.", "it": "Ho un fratello.", "es": "Tengo un hermano.", "tr": "Bir erkek kardesim var."},
            {"en": "I have five fingers.", "de": "Ich habe funf Finger.", "fr": "J'ai cinq doigts.", "it": "Ho cinque dita.", "es": "Tengo cinco dedos.", "tr": "Bes parmak var."},
            {"en": "I have four books.", "de": "Ich habe vier Bucher.", "fr": "J'ai quatre livres.", "it": "Ho quattro libri.", "es": "Tengo cuatro libros.", "tr": "Dort kitabim var."},
        ], "exercises": [
            {"prompt": "I have ___ cats. (2)", "answer": "two", "hint": "Iki"},
            {"prompt": "I have ___ apples. (3)", "answer": "three", "hint": "Uc"},
            {"prompt": "I have ___ dog. (1)", "answer": "one", "hint": "Bir"},
            {"prompt": "I have ___ eyes. (2)", "answer": "two", "hint": "Iki"},
            {"prompt": "I have ___ fingers. (10)", "answer": "ten", "hint": "On"},
        ]},
        # 4. Buyuk/Kucuk / Big/Small
        {"title": "Buyuk/Kucuk / Big/Small", "rule_tr": "The ___ is big/small.", "examples": [
            {"en": "The cat is big.", "de": "Die Katze ist gross.", "fr": "Le chat est grand.", "it": "Il gatto e grande.", "es": "El gato es grande.", "tr": "Kedi buyuk."},
            {"en": "The dog is small.", "de": "Der Hund ist klein.", "fr": "Le chien est petit.", "it": "Il cane e piccolo.", "es": "El perro es pequeno.", "tr": "Kopek kucuk."},
            {"en": "The elephant is big.", "de": "Der Elefant ist gross.", "fr": "L'elephant est grand.", "it": "L'elefante e grande.", "es": "El elefante es grande.", "tr": "Fil buyuk."},
            {"en": "The frog is small.", "de": "Der Frosch ist klein.", "fr": "La grenouille est petite.", "it": "La rana e piccola.", "es": "La rana es pequena.", "tr": "Kurbaga kucuk."},
            {"en": "The house is big.", "de": "Das Haus ist gross.", "fr": "La maison est grande.", "it": "La casa e grande.", "es": "La casa es grande.", "tr": "Ev buyuk."},
        ], "exercises": [
            {"prompt": "The elephant is ___.", "answer": "big", "hint": "Buyuk", "img": "\U0001f418"},
            {"prompt": "The mouse is ___.", "answer": "small", "hint": "Kucuk", "img": "\U0001f42d"},
            {"prompt": "The lion is ___.", "answer": "big", "hint": "Buyuk", "img": "\U0001f981"},
            {"prompt": "The butterfly is ___.", "answer": "small", "hint": "Kucuk", "img": "\U0001f98b"},
            {"prompt": "The tree is ___.", "answer": "big", "hint": "Buyuk", "img": "\U0001f333"},
        ]},
        # 5. Var/Yok - There is/There isn't [NEW]
        {"title": "Var/Yok - There is/There isn't", "rule_tr": "There is a ___ / There isn't a ___", "examples": [
            {"en": "There is a cat.", "de": "Da ist eine Katze.", "fr": "Il y a un chat.", "it": "C'e un gatto.", "es": "Hay un gato.", "tr": "Bir kedi var."},
            {"en": "There isn't a dog.", "de": "Da ist kein Hund.", "fr": "Il n'y a pas de chien.", "it": "Non c'e un cane.", "es": "No hay un perro.", "tr": "Kopek yok."},
            {"en": "There is a ball on the table.", "de": "Da ist ein Ball auf dem Tisch.", "fr": "Il y a une balle sur la table.", "it": "C'e una palla sul tavolo.", "es": "Hay una pelota en la mesa.", "tr": "Masada bir top var."},
            {"en": "There isn't a bird in the tree.", "de": "Da ist kein Vogel im Baum.", "fr": "Il n'y a pas d'oiseau dans l'arbre.", "it": "Non c'e un uccello sull'albero.", "es": "No hay un pajaro en el arbol.", "tr": "Agacta kus yok."},
            {"en": "There is milk in the glass.", "de": "Da ist Milch im Glas.", "fr": "Il y a du lait dans le verre.", "it": "C'e del latte nel bicchiere.", "es": "Hay leche en el vaso.", "tr": "Bardakta sut var."},
        ], "exercises": [
            {"prompt": "There ___ a cat. (var)", "answer": "is", "hint": "Var"},
            {"prompt": "There ___ a dog. (yok)", "answer": "isn't", "hint": "Yok"},
            {"prompt": "There ___ two birds.", "answer": "are", "hint": "Var (cogul)"},
            {"prompt": "There ___ a book on the table.", "answer": "is", "hint": "Var"},
            {"prompt": "There ___ any milk.", "answer": "isn't", "hint": "Yok"},
        ]},
        # 6. Cogul - Plurals [NEW]
        {"title": "Cogul / Plurals", "rule_tr": "cat -> cats, dog -> dogs, child -> children", "examples": [
            {"en": "One cat, two cats.", "de": "Eine Katze, zwei Katzen.", "fr": "Un chat, deux chats.", "it": "Un gatto, due gatti.", "es": "Un gato, dos gatos.", "tr": "Bir kedi, iki kedi."},
            {"en": "One dog, three dogs.", "de": "Ein Hund, drei Hunde.", "fr": "Un chien, trois chiens.", "it": "Un cane, tre cani.", "es": "Un perro, tres perros.", "tr": "Bir kopek, uc kopek."},
            {"en": "One child, four children.", "de": "Ein Kind, vier Kinder.", "fr": "Un enfant, quatre enfants.", "it": "Un bambino, quattro bambini.", "es": "Un nino, cuatro ninos.", "tr": "Bir cocuk, dort cocuk."},
            {"en": "One fish, five fish.", "de": "Ein Fisch, funf Fische.", "fr": "Un poisson, cinq poissons.", "it": "Un pesce, cinque pesci.", "es": "Un pez, cinco peces.", "tr": "Bir balik, bes balik."},
            {"en": "One apple, six apples.", "de": "Ein Apfel, sechs Apfel.", "fr": "Une pomme, six pommes.", "it": "Una mela, sei mele.", "es": "Una manzana, seis manzanas.", "tr": "Bir elma, alti elma."},
        ], "exercises": [
            {"prompt": "One cat, two ___.", "answer": "cats", "hint": "Kediler"},
            {"prompt": "One dog, three ___.", "answer": "dogs", "hint": "Kopekler"},
            {"prompt": "One book, five ___.", "answer": "books", "hint": "Kitaplar"},
            {"prompt": "One child, two ___.", "answer": "children", "hint": "Cocuklar"},
            {"prompt": "One box, four ___.", "answer": "boxes", "hint": "Kutular"},
        ]},
        # 7. Sahiplik - My/Your/His [NEW]
        {"title": "Sahiplik / My, Your, His", "rule_tr": "My (benim) / Your (senin) / His (onun-erkek) / Her (onun-kadin)", "examples": [
            {"en": "This is my cat.", "de": "Das ist meine Katze.", "fr": "C'est mon chat.", "it": "Questo e il mio gatto.", "es": "Este es mi gato.", "tr": "Bu benim kedim."},
            {"en": "This is your dog.", "de": "Das ist dein Hund.", "fr": "C'est ton chien.", "it": "Questo e il tuo cane.", "es": "Este es tu perro.", "tr": "Bu senin kopegin."},
            {"en": "This is his ball.", "de": "Das ist sein Ball.", "fr": "C'est son ballon.", "it": "Questa e la sua palla.", "es": "Esta es su pelota.", "tr": "Bu onun topu."},
            {"en": "This is her doll.", "de": "Das ist ihre Puppe.", "fr": "C'est sa poupee.", "it": "Questa e la sua bambola.", "es": "Esta es su muneca.", "tr": "Bu onun bebegi."},
            {"en": "This is our house.", "de": "Das ist unser Haus.", "fr": "C'est notre maison.", "it": "Questa e la nostra casa.", "es": "Esta es nuestra casa.", "tr": "Bu bizim evimiz."},
        ], "exercises": [
            {"prompt": "___ cat is white. (benim)", "answer": "My", "hint": "Benim"},
            {"prompt": "___ dog is big. (senin)", "answer": "Your", "hint": "Senin"},
            {"prompt": "___ ball is red. (onun-erkek)", "answer": "His", "hint": "Onun (erkek)"},
            {"prompt": "___ doll is new. (onun-kadin)", "answer": "Her", "hint": "Onun (kadin)"},
            {"prompt": "___ house is big. (bizim)", "answer": "Our", "hint": "Bizim"},
        ]},
        # 8. Eylemler - I can see/hear/touch [NEW]
        {"title": "Eylemler / I can see, hear, touch", "rule_tr": "I can see/hear/touch ___.", "examples": [
            {"en": "I can see a bird.", "de": "Ich kann einen Vogel sehen.", "fr": "Je peux voir un oiseau.", "it": "Posso vedere un uccello.", "es": "Puedo ver un pajaro.", "tr": "Bir kus gorebiliyorum."},
            {"en": "I can hear music.", "de": "Ich kann Musik horen.", "fr": "Je peux entendre de la musique.", "it": "Posso sentire la musica.", "es": "Puedo escuchar musica.", "tr": "Muzik duyabiliyorum."},
            {"en": "I can touch the flower.", "de": "Ich kann die Blume beruhren.", "fr": "Je peux toucher la fleur.", "it": "Posso toccare il fiore.", "es": "Puedo tocar la flor.", "tr": "Cicege dokunabiliyorum."},
            {"en": "I can see the sun.", "de": "Ich kann die Sonne sehen.", "fr": "Je peux voir le soleil.", "it": "Posso vedere il sole.", "es": "Puedo ver el sol.", "tr": "Gunesi gorebiliyorum."},
            {"en": "I can hear the rain.", "de": "Ich kann den Regen horen.", "fr": "Je peux entendre la pluie.", "it": "Posso sentire la pioggia.", "es": "Puedo escuchar la lluvia.", "tr": "Yagmuru duyabiliyorum."},
        ], "exercises": [
            {"prompt": "I can ___ a bird. (gormek)", "answer": "see", "hint": "Gormek"},
            {"prompt": "I can ___ music. (duymak)", "answer": "hear", "hint": "Duymak"},
            {"prompt": "I can ___ the cat. (dokunmak)", "answer": "touch", "hint": "Dokunmak"},
            {"prompt": "I can ___ the moon. (gormek)", "answer": "see", "hint": "Gormek"},
            {"prompt": "I can ___ the bell. (duymak)", "answer": "hear", "hint": "Duymak"},
        ]},
        # 9. Nerede? - Where is the...? [NEW]
        {"title": "Nerede? / Where is the...?", "rule_tr": "Where is the ___? It is on/in/under ___.", "examples": [
            {"en": "Where is the cat? It is on the chair.", "de": "Wo ist die Katze? Sie ist auf dem Stuhl.", "fr": "Ou est le chat? Il est sur la chaise.", "it": "Dov'e il gatto? E sulla sedia.", "es": "Donde esta el gato? Esta en la silla.", "tr": "Kedi nerede? Sandalyenin uzerinde."},
            {"en": "Where is the ball? It is under the table.", "de": "Wo ist der Ball? Er ist unter dem Tisch.", "fr": "Ou est la balle? Elle est sous la table.", "it": "Dov'e la palla? E sotto il tavolo.", "es": "Donde esta la pelota? Esta debajo de la mesa.", "tr": "Top nerede? Masanin altinda."},
            {"en": "Where is the book? It is in the bag.", "de": "Wo ist das Buch? Es ist in der Tasche.", "fr": "Ou est le livre? Il est dans le sac.", "it": "Dov'e il libro? E nella borsa.", "es": "Donde esta el libro? Esta en la bolsa.", "tr": "Kitap nerede? Cantanin icinde."},
            {"en": "Where is the dog? It is in the garden.", "de": "Wo ist der Hund? Er ist im Garten.", "fr": "Ou est le chien? Il est dans le jardin.", "it": "Dov'e il cane? E nel giardino.", "es": "Donde esta el perro? Esta en el jardin.", "tr": "Kopek nerede? Bahcede."},
            {"en": "Where is the bird? It is on the tree.", "de": "Wo ist der Vogel? Er ist auf dem Baum.", "fr": "Ou est l'oiseau? Il est sur l'arbre.", "it": "Dov'e l'uccello? E sull'albero.", "es": "Donde esta el pajaro? Esta en el arbol.", "tr": "Kus nerede? Agacin uzerinde."},
        ], "exercises": [
            {"prompt": "Where is the cat? It is ___ the chair.", "answer": "on", "hint": "Uzerinde"},
            {"prompt": "Where is the ball? It is ___ the table.", "answer": "under", "hint": "Altinda"},
            {"prompt": "Where is the book? It is ___ the bag.", "answer": "in", "hint": "Icinde"},
            {"prompt": "Where is the fish? It is ___ the water.", "answer": "in", "hint": "Icinde"},
            {"prompt": "Where is the bird? It is ___ the tree.", "answer": "on", "hint": "Uzerinde"},
        ]},
        # 10. Sevmek/Sevmemek - I like/I don't like [NEW]
        {"title": "Sevmek/Sevmemek / I like, I don't like", "rule_tr": "I like ___ / I don't like ___.", "examples": [
            {"en": "I like cats.", "de": "Ich mag Katzen.", "fr": "J'aime les chats.", "it": "Mi piacciono i gatti.", "es": "Me gustan los gatos.", "tr": "Kedileri severim."},
            {"en": "I don't like spiders.", "de": "Ich mag keine Spinnen.", "fr": "Je n'aime pas les araignees.", "it": "Non mi piacciono i ragni.", "es": "No me gustan las aranas.", "tr": "Orumcekleri sevmem."},
            {"en": "I like ice cream.", "de": "Ich mag Eiscreme.", "fr": "J'aime la glace.", "it": "Mi piace il gelato.", "es": "Me gusta el helado.", "tr": "Dondurmayi severim."},
            {"en": "I don't like soup.", "de": "Ich mag keine Suppe.", "fr": "Je n'aime pas la soupe.", "it": "Non mi piace la zuppa.", "es": "No me gusta la sopa.", "tr": "Corbayi sevmem."},
            {"en": "I like summer.", "de": "Ich mag den Sommer.", "fr": "J'aime l'ete.", "it": "Mi piace l'estate.", "es": "Me gusta el verano.", "tr": "Yazi severim."},
        ], "exercises": [
            {"prompt": "I ___ cats. (sevmek)", "answer": "like", "hint": "Sevmek"},
            {"prompt": "I don't ___ snakes.", "answer": "like", "hint": "Sevmek (olumsuz)"},
            {"prompt": "I ___ pizza.", "answer": "like", "hint": "Sevmek"},
            {"prompt": "I don't ___ rain.", "answer": "like", "hint": "Sevmek (olumsuz)"},
            {"prompt": "I ___ my family.", "answer": "like", "hint": "Sevmek"},
        ]},
    ],
    # ════════════════════════════════════════
    # DIALOGUES (8 diyalog x 6-8 satir)
    # ════════════════════════════════════════
    "dialogues": [
        # 1. Selamlasma
        {"title": "Selamlasma", "lines": [
            {"speaker": "A", "en": "Hello!", "de": "Hallo!", "fr": "Bonjour!", "it": "Ciao!", "es": "Hola!", "tr": "Merhaba!"},
            {"speaker": "B", "en": "Hi! How are you?", "de": "Hallo! Wie geht es dir?", "fr": "Salut! Comment vas-tu?", "it": "Ciao! Come stai?", "es": "Hola! Como estas?", "tr": "Selam! Nasilsin?"},
            {"speaker": "A", "en": "I am fine, thank you.", "de": "Mir geht es gut, danke.", "fr": "Je vais bien, merci.", "it": "Sto bene, grazie.", "es": "Estoy bien, gracias.", "tr": "Iyiyim, tesekkurler."},
            {"speaker": "B", "en": "I am fine too.", "de": "Mir geht es auch gut.", "fr": "Je vais bien aussi.", "it": "Anch'io sto bene.", "es": "Yo tambien estoy bien.", "tr": "Ben de iyiyim."},
            {"speaker": "A", "en": "See you later!", "de": "Bis spater!", "fr": "A plus tard!", "it": "A dopo!", "es": "Hasta luego!", "tr": "Sonra gorusuruz!"},
            {"speaker": "B", "en": "Goodbye!", "de": "Auf Wiedersehen!", "fr": "Au revoir!", "it": "Arrivederci!", "es": "Adios!", "tr": "Hosca kal!"},
        ]},
        # 2. Tanisma
        {"title": "Tanisma", "lines": [
            {"speaker": "A", "en": "What is your name?", "de": "Wie heisst du?", "fr": "Comment tu t'appelles?", "it": "Come ti chiami?", "es": "Como te llamas?", "tr": "Adin ne?"},
            {"speaker": "B", "en": "My name is Ali.", "de": "Ich heisse Ali.", "fr": "Je m'appelle Ali.", "it": "Mi chiamo Ali.", "es": "Me llamo Ali.", "tr": "Benim adim Ali."},
            {"speaker": "A", "en": "Nice to meet you, Ali!", "de": "Freut mich, Ali!", "fr": "Enchante, Ali!", "it": "Piacere, Ali!", "es": "Encantado, Ali!", "tr": "Tanistigima memnun oldum, Ali!"},
            {"speaker": "B", "en": "Nice to meet you too!", "de": "Mich auch!", "fr": "Enchante aussi!", "it": "Piacere mio!", "es": "Igualmente!", "tr": "Ben de memnun oldum!"},
            {"speaker": "A", "en": "How old are you?", "de": "Wie alt bist du?", "fr": "Quel age as-tu?", "it": "Quanti anni hai?", "es": "Cuantos anos tienes?", "tr": "Kac yasindasin?"},
            {"speaker": "B", "en": "I am six years old.", "de": "Ich bin sechs Jahre alt.", "fr": "J'ai six ans.", "it": "Ho sei anni.", "es": "Tengo seis anos.", "tr": "Alti yasindayim."},
            {"speaker": "A", "en": "Me too! Let's be friends.", "de": "Ich auch! Lass uns Freunde sein.", "fr": "Moi aussi! Soyons amis.", "it": "Anch'io! Facciamo amicizia.", "es": "Yo tambien! Seamos amigos.", "tr": "Ben de! Arkadas olalim."},
            {"speaker": "B", "en": "Yes! We are friends now.", "de": "Ja! Wir sind jetzt Freunde.", "fr": "Oui! Nous sommes amis maintenant.", "it": "Si! Ora siamo amici.", "es": "Si! Ahora somos amigos.", "tr": "Evet! Artik arkadasiz."},
        ]},
        # 3. Sinifta
        {"title": "Sinifta", "lines": [
            {"speaker": "Teacher", "en": "Good morning, children!", "de": "Guten Morgen, Kinder!", "fr": "Bonjour, les enfants!", "it": "Buongiorno, bambini!", "es": "Buenos dias, ninos!", "tr": "Gunaydin, cocuklar!"},
            {"speaker": "Children", "en": "Good morning, teacher!", "de": "Guten Morgen, Lehrerin!", "fr": "Bonjour, maitresse!", "it": "Buongiorno, maestra!", "es": "Buenos dias, profesora!", "tr": "Gunaydin, ogretmenim!"},
            {"speaker": "Teacher", "en": "What color is this?", "de": "Welche Farbe ist das?", "fr": "Quelle couleur est-ce?", "it": "Che colore e questo?", "es": "Que color es este?", "tr": "Bu ne renk?"},
            {"speaker": "Student", "en": "It is red!", "de": "Es ist rot!", "fr": "C'est rouge!", "it": "E rosso!", "es": "Es rojo!", "tr": "Kirmizi!"},
            {"speaker": "Teacher", "en": "Very good! And this?", "de": "Sehr gut! Und das?", "fr": "Tres bien! Et celui-ci?", "it": "Molto bene! E questo?", "es": "Muy bien! Y este?", "tr": "Cok guzel! Peki bu?"},
            {"speaker": "Student", "en": "It is blue!", "de": "Es ist blau!", "fr": "C'est bleu!", "it": "E blu!", "es": "Es azul!", "tr": "Mavi!"},
            {"speaker": "Teacher", "en": "Excellent! Well done!", "de": "Ausgezeichnet! Gut gemacht!", "fr": "Excellent! Bien fait!", "it": "Eccellente! Ben fatto!", "es": "Excelente! Bien hecho!", "tr": "Harika! Aferin!"},
        ]},
        # 4. Parkta [NEW]
        {"title": "Parkta", "lines": [
            {"speaker": "A", "en": "Let's go to the park!", "de": "Lass uns in den Park gehen!", "fr": "Allons au parc!", "it": "Andiamo al parco!", "es": "Vamos al parque!", "tr": "Parka gidelim!"},
            {"speaker": "B", "en": "Great! I want to play.", "de": "Toll! Ich will spielen.", "fr": "Super! Je veux jouer.", "it": "Ottimo! Voglio giocare.", "es": "Genial! Quiero jugar.", "tr": "Harika! Oynamak istiyorum."},
            {"speaker": "A", "en": "Look! There is a swing.", "de": "Schau! Da ist eine Schaukel.", "fr": "Regarde! Il y a une balancoire.", "it": "Guarda! C'e un'altalena.", "es": "Mira! Hay un columpio.", "tr": "Bak! Bir salincak var."},
            {"speaker": "B", "en": "I like the swing!", "de": "Ich mag die Schaukel!", "fr": "J'aime la balancoire!", "it": "Mi piace l'altalena!", "es": "Me gusta el columpio!", "tr": "Salincagi seviyorum!"},
            {"speaker": "A", "en": "Can you see the butterfly?", "de": "Kannst du den Schmetterling sehen?", "fr": "Tu vois le papillon?", "it": "Riesci a vedere la farfalla?", "es": "Puedes ver la mariposa?", "tr": "Kelebegi gorebiliyor musun?"},
            {"speaker": "B", "en": "Yes! It is very beautiful.", "de": "Ja! Er ist sehr schon.", "fr": "Oui! Il est tres beau.", "it": "Si! E molto bella.", "es": "Si! Es muy bonita.", "tr": "Evet! Cok guzel."},
            {"speaker": "A", "en": "I love the park!", "de": "Ich liebe den Park!", "fr": "J'adore le parc!", "it": "Adoro il parco!", "es": "Me encanta el parque!", "tr": "Parki seviyorum!"},
        ]},
        # 5. Dogum gunu partisi [NEW]
        {"title": "Dogum Gunu Partisi", "lines": [
            {"speaker": "A", "en": "Happy birthday!", "de": "Alles Gute zum Geburtstag!", "fr": "Joyeux anniversaire!", "it": "Buon compleanno!", "es": "Feliz cumpleanos!", "tr": "Dogum gunun kutlu olsun!"},
            {"speaker": "B", "en": "Thank you! I am five today.", "de": "Danke! Ich bin heute funf.", "fr": "Merci! J'ai cinq ans aujourd'hui.", "it": "Grazie! Oggi compio cinque anni.", "es": "Gracias! Hoy cumplo cinco.", "tr": "Tesekkurler! Bugun bes yasindayim."},
            {"speaker": "A", "en": "Here is a present for you.", "de": "Hier ist ein Geschenk fur dich.", "fr": "Voici un cadeau pour toi.", "it": "Ecco un regalo per te.", "es": "Aqui tienes un regalo.", "tr": "Sana bir hediye."},
            {"speaker": "B", "en": "Wow! Thank you so much!", "de": "Wow! Vielen Dank!", "fr": "Waouh! Merci beaucoup!", "it": "Wow! Grazie mille!", "es": "Guau! Muchas gracias!", "tr": "Vay! Cok tesekkurler!"},
            {"speaker": "A", "en": "Do you want some cake?", "de": "Mochtest du etwas Kuchen?", "fr": "Tu veux du gateau?", "it": "Vuoi della torta?", "es": "Quieres pastel?", "tr": "Biraz pasta ister misin?"},
            {"speaker": "B", "en": "Yes, please! I love cake.", "de": "Ja, bitte! Ich liebe Kuchen.", "fr": "Oui, s'il te plait! J'adore le gateau.", "it": "Si, per favore! Adoro la torta.", "es": "Si, por favor! Me encanta el pastel.", "tr": "Evet, lutfen! Pastiyi cok severim."},
            {"speaker": "A", "en": "Let's sing and dance!", "de": "Lass uns singen und tanzen!", "fr": "Chantons et dansons!", "it": "Cantiamo e balliamo!", "es": "Cantemos y bailemos!", "tr": "Sarki soyleyelim ve dans edelim!"},
        ]},
        # 6. Markette [NEW]
        {"title": "Markette", "lines": [
            {"speaker": "Mother", "en": "We need some milk.", "de": "Wir brauchen etwas Milch.", "fr": "Nous avons besoin de lait.", "it": "Abbiamo bisogno di latte.", "es": "Necesitamos leche.", "tr": "Biraz sute ihtiyacimiz var."},
            {"speaker": "Child", "en": "Can I have a banana?", "de": "Kann ich eine Banane haben?", "fr": "Puis-je avoir une banane?", "it": "Posso avere una banana?", "es": "Puedo tener un platano?", "tr": "Bir muz alabilir miyim?"},
            {"speaker": "Mother", "en": "Yes, of course.", "de": "Ja, naturlich.", "fr": "Oui, bien sur.", "it": "Si, certo.", "es": "Si, claro.", "tr": "Evet, tabii ki."},
            {"speaker": "Child", "en": "Look! There are apples.", "de": "Schau! Da sind Apfel.", "fr": "Regarde! Il y a des pommes.", "it": "Guarda! Ci sono delle mele.", "es": "Mira! Hay manzanas.", "tr": "Bak! Elmalar var."},
            {"speaker": "Mother", "en": "Good. We need three apples.", "de": "Gut. Wir brauchen drei Apfel.", "fr": "Bien. Nous avons besoin de trois pommes.", "it": "Bene. Ci servono tre mele.", "es": "Bien. Necesitamos tres manzanas.", "tr": "Guzel. Uc elmaya ihtiyacimiz var."},
            {"speaker": "Child", "en": "One, two, three! Here you are.", "de": "Eins, zwei, drei! Bitte schon.", "fr": "Un, deux, trois! Voici.", "it": "Uno, due, tre! Ecco.", "es": "Uno, dos, tres! Aqui tienes.", "tr": "Bir, iki, uc! Buyurun."},
            {"speaker": "Mother", "en": "Thank you! You are a good helper.", "de": "Danke! Du bist ein guter Helfer.", "fr": "Merci! Tu es un bon aide.", "it": "Grazie! Sei un bravo aiutante.", "es": "Gracias! Eres un buen ayudante.", "tr": "Tesekkurler! Iyi bir yardimcisin."},
        ]},
        # 7. Hayvanlarda (Hayvanat Bahcesi) [NEW]
        {"title": "Hayvanat Bahcesinde", "lines": [
            {"speaker": "A", "en": "Look! There is a lion!", "de": "Schau! Da ist ein Lowe!", "fr": "Regarde! Il y a un lion!", "it": "Guarda! C'e un leone!", "es": "Mira! Hay un leon!", "tr": "Bak! Bir aslan var!"},
            {"speaker": "B", "en": "It is very big!", "de": "Er ist sehr gross!", "fr": "Il est tres grand!", "it": "E molto grande!", "es": "Es muy grande!", "tr": "Cok buyuk!"},
            {"speaker": "A", "en": "I can see an elephant too.", "de": "Ich kann auch einen Elefanten sehen.", "fr": "Je peux voir un elephant aussi.", "it": "Posso vedere anche un elefante.", "es": "Puedo ver un elefante tambien.", "tr": "Bir fil de gorebiliyorum."},
            {"speaker": "B", "en": "The elephant is my favorite animal.", "de": "Der Elefant ist mein Lieblingstier.", "fr": "L'elephant est mon animal prefere.", "it": "L'elefante e il mio animale preferito.", "es": "El elefante es mi animal favorito.", "tr": "Fil benim en sevdigim hayvan."},
            {"speaker": "A", "en": "Where is the monkey?", "de": "Wo ist der Affe?", "fr": "Ou est le singe?", "it": "Dov'e la scimmia?", "es": "Donde esta el mono?", "tr": "Maymun nerede?"},
            {"speaker": "B", "en": "The monkey is on the tree!", "de": "Der Affe ist auf dem Baum!", "fr": "Le singe est sur l'arbre!", "it": "La scimmia e sull'albero!", "es": "El mono esta en el arbol!", "tr": "Maymun agacin uzerinde!"},
            {"speaker": "A", "en": "How funny! I love the zoo.", "de": "Wie lustig! Ich liebe den Zoo.", "fr": "C'est drole! J'adore le zoo.", "it": "Che divertente! Adoro lo zoo.", "es": "Que gracioso! Me encanta el zoo.", "tr": "Ne komik! Hayvanat bahcesini seviyorum."},
        ]},
        # 8. Oyun oynama [NEW]
        {"title": "Oyun Oynama", "lines": [
            {"speaker": "A", "en": "Do you want to play?", "de": "Willst du spielen?", "fr": "Tu veux jouer?", "it": "Vuoi giocare?", "es": "Quieres jugar?", "tr": "Oynamak ister misin?"},
            {"speaker": "B", "en": "Yes! What can we play?", "de": "Ja! Was konnen wir spielen?", "fr": "Oui! A quoi peut-on jouer?", "it": "Si! A cosa possiamo giocare?", "es": "Si! A que podemos jugar?", "tr": "Evet! Ne oynayabiliriz?"},
            {"speaker": "A", "en": "Let's play with the ball.", "de": "Lass uns mit dem Ball spielen.", "fr": "Jouons avec la balle.", "it": "Giochiamo con la palla.", "es": "Juguemos con la pelota.", "tr": "Topla oynayalim."},
            {"speaker": "B", "en": "I like the ball! It is red.", "de": "Ich mag den Ball! Er ist rot.", "fr": "J'aime la balle! Elle est rouge.", "it": "Mi piace la palla! E rossa.", "es": "Me gusta la pelota! Es roja.", "tr": "Topu seviyorum! Kirmizi."},
            {"speaker": "A", "en": "I can throw the ball.", "de": "Ich kann den Ball werfen.", "fr": "Je peux lancer la balle.", "it": "Posso lanciare la palla.", "es": "Puedo lanzar la pelota.", "tr": "Topu atabilirim."},
            {"speaker": "B", "en": "And I can catch it!", "de": "Und ich kann ihn fangen!", "fr": "Et je peux l'attraper!", "it": "E io posso prenderla!", "es": "Y yo puedo atraparla!", "tr": "Ben de yakalayabilirim!"},
            {"speaker": "A", "en": "This is fun! Let's play more.", "de": "Das macht Spass! Lass uns mehr spielen.", "fr": "C'est amusant! Jouons encore.", "it": "E divertente! Giochiamo ancora.", "es": "Es divertido! Juguemos mas.", "tr": "Bu eglenceli! Daha fazla oynayalim."},
        ]},
    ],
    # ════════════════════════════════════════
    # READING (5 passage x 3 soru)
    # ════════════════════════════════════════
    "reading": [
        {
            "title": "My Family",
            "text": {
                "en": "I have a mother and a father. I have one sister. Her name is Elif. We have a cat. The cat is white. I love my family.",
                "de": "Ich habe eine Mutter und einen Vater. Ich habe eine Schwester. Sie heisst Elif. Wir haben eine Katze. Die Katze ist weiss. Ich liebe meine Familie.",
                "fr": "J'ai une mere et un pere. J'ai une soeur. Elle s'appelle Elif. Nous avons un chat. Le chat est blanc. J'aime ma famille.",
                "it": "Ho una madre e un padre. Ho una sorella. Si chiama Elif. Abbiamo un gatto. Il gatto e bianco. Amo la mia famiglia.",
                "es": "Tengo una madre y un padre. Tengo una hermana. Se llama Elif. Tenemos un gato. El gato es blanco. Amo a mi familia.",
                "tr": "Bir annem ve bir babam var. Bir kiz kardesim var. Adi Elif. Bir kedimiz var. Kedi beyaz. Ailemi seviyorum.",
            },
            "questions": [
                {"q_tr": "Kiz kardesin adi ne?", "options": ["Elif", "Ayse", "Zeynep"], "answer": 0},
                {"q_tr": "Kedi ne renk?", "options": ["Siyah", "Beyaz", "Kahverengi"], "answer": 1},
                {"q_tr": "Ailede kac cocuk var?", "options": ["1", "2", "3"], "answer": 1},
            ],
        },
        {
            "title": "My Day",
            "text": {
                "en": "I wake up in the morning. I eat bread and drink milk. I go to school. I play with my friends. I come home. I eat dinner. I go to bed. Good night!",
                "de": "Ich wache morgens auf. Ich esse Brot und trinke Milch. Ich gehe in die Schule. Ich spiele mit meinen Freunden. Ich komme nach Hause. Ich esse Abendessen. Ich gehe ins Bett. Gute Nacht!",
                "fr": "Je me reveille le matin. Je mange du pain et je bois du lait. Je vais a l'ecole. Je joue avec mes amis. Je rentre a la maison. Je dine. Je vais au lit. Bonne nuit!",
                "it": "Mi sveglio la mattina. Mangio pane e bevo latte. Vado a scuola. Gioco con i miei amici. Torno a casa. Ceno. Vado a letto. Buonanotte!",
                "es": "Me despierto por la manana. Como pan y bebo leche. Voy a la escuela. Juego con mis amigos. Vuelvo a casa. Ceno. Me voy a la cama. Buenas noches!",
                "tr": "Sabah uyaniyorum. Ekmek yiyorum ve sut iciyorum. Okula gidiyorum. Arkadaslarimla oynuyorum. Eve geliyorum. Aksam yemegi yiyorum. Yataga gidiyorum. Iyi geceler!",
            },
            "questions": [
                {"q_tr": "Sabah ne yiyor?", "options": ["Ekmek", "Pasta", "Pizza"], "answer": 0},
                {"q_tr": "Sabah ne iciyor?", "options": ["Su", "Sut", "Meyve suyu"], "answer": 1},
                {"q_tr": "Okulda ne yapiyor?", "options": ["Uyuyor", "Arkadaslariyla oynuyor", "Televizyon izliyor"], "answer": 1},
            ],
        },
        # 3. My School [NEW]
        {
            "title": "My School",
            "text": {
                "en": "My school is big. I have a teacher. Her name is Mrs. Ayse. I have many friends at school. We have pencils and notebooks. We draw pictures. We sing songs. I like my school very much.",
                "de": "Meine Schule ist gross. Ich habe eine Lehrerin. Sie heisst Frau Ayse. Ich habe viele Freunde in der Schule. Wir haben Bleistifte und Hefte. Wir zeichnen Bilder. Wir singen Lieder. Ich mag meine Schule sehr.",
                "fr": "Mon ecole est grande. J'ai une maitresse. Elle s'appelle Madame Ayse. J'ai beaucoup d'amis a l'ecole. Nous avons des crayons et des cahiers. Nous dessinons des images. Nous chantons des chansons. J'aime beaucoup mon ecole.",
                "it": "La mia scuola e grande. Ho un'insegnante. Si chiama signora Ayse. Ho molti amici a scuola. Abbiamo matite e quaderni. Disegniamo immagini. Cantiamo canzoni. Mi piace molto la mia scuola.",
                "es": "Mi escuela es grande. Tengo una profesora. Se llama senora Ayse. Tengo muchos amigos en la escuela. Tenemos lapices y cuadernos. Dibujamos imagenes. Cantamos canciones. Me gusta mucho mi escuela.",
                "tr": "Okulum buyuk. Bir ogretmenim var. Adi Ayse ogretmen. Okulda bircok arkadasim var. Kalemlerimiz ve defterlerimiz var. Resimler ciziyoruz. Sarkilar soyluyoruz. Okulumu cok seviyorum.",
            },
            "questions": [
                {"q_tr": "Ogretmenin adi ne?", "options": ["Elif", "Ayse", "Zeynep"], "answer": 1},
                {"q_tr": "Okulda ne yapiyorlar?", "options": ["Uyuyorlar", "Resim ciziyorlar", "Televizyon izliyorlar"], "answer": 1},
                {"q_tr": "Okul nasil?", "options": ["Kucuk", "Buyuk", "Eski"], "answer": 1},
            ],
        },
        # 4. A Day at the Zoo [NEW]
        {
            "title": "A Day at the Zoo",
            "text": {
                "en": "Today I go to the zoo. I can see many animals. There is a big elephant. There are two lions. The monkeys are funny. They are on the trees. I like the birds. They are very colorful. The zoo is fun!",
                "de": "Heute gehe ich in den Zoo. Ich kann viele Tiere sehen. Da ist ein grosser Elefant. Da sind zwei Lowen. Die Affen sind lustig. Sie sind auf den Baumen. Ich mag die Vogel. Sie sind sehr bunt. Der Zoo macht Spass!",
                "fr": "Aujourd'hui je vais au zoo. Je peux voir beaucoup d'animaux. Il y a un grand elephant. Il y a deux lions. Les singes sont droles. Ils sont sur les arbres. J'aime les oiseaux. Ils sont tres colores. Le zoo est amusant!",
                "it": "Oggi vado allo zoo. Posso vedere molti animali. C'e un grande elefante. Ci sono due leoni. Le scimmie sono divertenti. Sono sugli alberi. Mi piacciono gli uccelli. Sono molto colorati. Lo zoo e divertente!",
                "es": "Hoy voy al zoologico. Puedo ver muchos animales. Hay un elefante grande. Hay dos leones. Los monos son divertidos. Estan en los arboles. Me gustan los pajaros. Son muy coloridos. El zoologico es divertido!",
                "tr": "Bugun hayvanat bahcesine gidiyorum. Bircok hayvan gorebiliyorum. Buyuk bir fil var. Iki aslan var. Maymunlar komik. Agaclarin uzerindeler. Kuslari seviyorum. Cok renkli. Hayvanat bahcesi eglenceli!",
            },
            "questions": [
                {"q_tr": "Kac tane aslan var?", "options": ["1", "2", "3"], "answer": 1},
                {"q_tr": "Maymunlar nasil?", "options": ["Uzgun", "Komik", "Kizgin"], "answer": 1},
                {"q_tr": "Kuslar nasil?", "options": ["Buyuk", "Kucuk", "Renkli"], "answer": 2},
            ],
        },
        # 5. My Birthday [NEW]
        {
            "title": "My Birthday",
            "text": {
                "en": "Today is my birthday. I am six years old. My mother makes a cake. The cake is chocolate. My friends come to my house. We play games. We eat cake and drink juice. I get many presents. I am very happy. It is the best day!",
                "de": "Heute ist mein Geburtstag. Ich bin sechs Jahre alt. Meine Mutter macht einen Kuchen. Der Kuchen ist Schokolade. Meine Freunde kommen zu mir nach Hause. Wir spielen Spiele. Wir essen Kuchen und trinken Saft. Ich bekomme viele Geschenke. Ich bin sehr glucklich. Es ist der beste Tag!",
                "fr": "Aujourd'hui c'est mon anniversaire. J'ai six ans. Ma mere fait un gateau. Le gateau est au chocolat. Mes amis viennent chez moi. Nous jouons a des jeux. Nous mangeons du gateau et buvons du jus. Je recois beaucoup de cadeaux. Je suis tres content. C'est le meilleur jour!",
                "it": "Oggi e il mio compleanno. Ho sei anni. Mia madre fa una torta. La torta e al cioccolato. I miei amici vengono a casa mia. Giochiamo. Mangiamo torta e beviamo succo. Ricevo molti regali. Sono molto felice. E il giorno migliore!",
                "es": "Hoy es mi cumpleanos. Tengo seis anos. Mi madre hace un pastel. El pastel es de chocolate. Mis amigos vienen a mi casa. Jugamos juegos. Comemos pastel y bebemos jugo. Recibo muchos regalos. Estoy muy feliz. Es el mejor dia!",
                "tr": "Bugun benim dogum gunum. Alti yasindayim. Annem bir pasta yapiyor. Pasta cikolatali. Arkadaslarim evimize geliyor. Oyunlar oynuyoruz. Pasta yiyoruz ve meyve suyu iciyoruz. Bircok hediye aliyorum. Cok mutluyum. En guzel gun!",
            },
            "questions": [
                {"q_tr": "Kac yasina giriyor?", "options": ["5", "6", "7"], "answer": 1},
                {"q_tr": "Pasta ne cesit?", "options": ["Cilekli", "Cikolatali", "Vanilyali"], "answer": 1},
                {"q_tr": "Ne iciyorlar?", "options": ["Sut", "Su", "Meyve suyu"], "answer": 2},
            ],
        },
    ],
    # ════════════════════════════════════════
    # QUIZ (30 soru)
    # ════════════════════════════════════════
    "quiz": [
        # Original 15
        {"type": "mc", "q_tr": "'Kedi' Ingilizcede ne demek?", "options": ["Dog", "Cat", "Bird", "Fish"], "answer": 1},
        {"type": "mc", "q_tr": "'Blue' Turkcede ne demek?", "options": ["Kirmizi", "Yesil", "Mavi", "Sari"], "answer": 2},
        {"type": "tf", "q_tr": "'Apple' = 'Elma' dogru mu?", "answer": True},
        {"type": "mc", "q_tr": "'Three' hangi sayi?", "options": ["2", "3", "4", "5"], "answer": 1},
        {"type": "tf", "q_tr": "'Hund' Almancada 'kedi' demek.", "answer": False},
        {"type": "mc", "q_tr": "'Mere' Fransizca ne demek?", "options": ["Baba", "Anne", "Kardes", "Bebek"], "answer": 1},
        {"type": "mc", "q_tr": "Ispanyolcada 'Rojo' ne renk?", "options": ["Mavi", "Yesil", "Kirmizi", "Sari"], "answer": 2},
        {"type": "tf", "q_tr": "'Latte' Italyancada 'sut' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Cinq' Fransizca kac?", "options": ["3", "4", "5", "6"], "answer": 2},
        {"type": "mc", "q_tr": "'Wasser' Almancada ne demek?", "options": ["Sut", "Su", "Ekmek", "Peynir"], "answer": 1},
        {"type": "fill", "q_tr": "'Kopek' Ingilizcede ___ demek.", "answer": "Dog"},
        {"type": "mc", "q_tr": "'Soleil' Fransizca ne demek?", "options": ["Ay", "Yildiz", "Gunes", "Bulut"], "answer": 2},
        {"type": "tf", "q_tr": "'Farfalla' Italyancada 'kelebek' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Schmetterling' Almancada ne demek?", "options": ["Kurbaga", "Kelebek", "Kus", "Balik"], "answer": 1},
        {"type": "mc", "q_tr": "'Avion' Fransizca/Ispanyolca ne demek?", "options": ["Gemi", "Tren", "Ucak", "Araba"], "answer": 2},
        # New 15
        {"type": "mc", "q_tr": "'Tomate' Almancada ne demek?", "options": ["Patates", "Domates", "Havuc", "Sogan"], "answer": 1},
        {"type": "tf", "q_tr": "'Concombre' Fransizca 'salatalik' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Primavera' Italyanca/Ispanyolca hangi mevsim?", "options": ["Yaz", "Kis", "Ilkbahar", "Sonbahar"], "answer": 2},
        {"type": "mc", "q_tr": "'Spoon' Turkcede ne demek?", "options": ["Catal", "Bicak", "Kasik", "Tabak"], "answer": 2},
        {"type": "fill", "q_tr": "'Sabun' Ingilizcede ___ demek.", "answer": "Soap"},
        {"type": "mc", "q_tr": "'Zahnburste' Almancada ne demek?", "options": ["Dis macunu", "Dis fircasi", "Sampuan", "Havlu"], "answer": 1},
        {"type": "tf", "q_tr": "'Crayon' Fransizca 'kalem' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Circle' Turkcede ne demek?", "options": ["Kare", "Ucgen", "Daire", "Yildiz"], "answer": 2},
        {"type": "mc", "q_tr": "'Ameise' Almancada ne demek?", "options": ["Ari", "Karinca", "Sinek", "Orumcek"], "answer": 1},
        {"type": "tf", "q_tr": "'Coccinella' Italyancada 'ugur bocegi' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Mango' Fransizca nasil soylenir?", "options": ["Mangue", "Mango", "Mangua", "Manga"], "answer": 0},
        {"type": "mc", "q_tr": "'Kokosnuss' Almancada ne demek?", "options": ["Ananas", "Muz", "Hindistancevizi", "Kavun"], "answer": 2},
        {"type": "fill", "q_tr": "'Kalp' Ingilizcede ___ demek.", "answer": "Heart"},
        {"type": "mc", "q_tr": "'Windy' Turkcede ne demek?", "options": ["Gunesli", "Ruzgarli", "Yagmurlu", "Karli"], "answer": 1},
        {"type": "tf", "q_tr": "'Forbici' Italyancada 'makas' demek.", "answer": True},
    ],
}
