"""
KDG Interaktif - A1 Basic (1-2. Sinif) Genisletilmis Veri Seti
20 konu x ~15 kelime = ~300+ kelime + dilbilgisi + diyalog + okuma + quiz
"""

DATA_A1 = {
    "label": "A1 Basic (1-2. Sinif)",
    "vocab": [
        # ── 1. Sinif Esyalari (15) ──
        {"topic": "Sinif Esyalari", "emoji": "\U0001f4da", "words": [
            {"en": "Book", "de": "Buch", "fr": "Livre", "it": "Libro", "es": "Libro", "tr": "Kitap", "img": "\U0001f4d6"},
            {"en": "Pencil", "de": "Bleistift", "fr": "Crayon", "it": "Matita", "es": "Lapiz", "tr": "Kalem", "img": "\u270f\ufe0f"},
            {"en": "Eraser", "de": "Radiergummi", "fr": "Gomme", "it": "Gomma", "es": "Borrador", "tr": "Silgi", "img": "\U0001f9f9"},
            {"en": "Bag", "de": "Tasche", "fr": "Sac", "it": "Borsa", "es": "Bolsa", "tr": "Canta", "img": "\U0001f392"},
            {"en": "Ruler", "de": "Lineal", "fr": "Regle", "it": "Righello", "es": "Regla", "tr": "Cetvel", "img": "\U0001f4cf"},
            {"en": "Desk", "de": "Schreibtisch", "fr": "Bureau", "it": "Scrivania", "es": "Escritorio", "tr": "Sira", "img": "\U0001f4bc"},
            {"en": "Chair", "de": "Stuhl", "fr": "Chaise", "it": "Sedia", "es": "Silla", "tr": "Sandalye", "img": "\U0001fa91"},
            {"en": "Notebook", "de": "Heft", "fr": "Cahier", "it": "Quaderno", "es": "Cuaderno", "tr": "Defter", "img": "\U0001f4d3"},
            {"en": "Pen", "de": "Kugelschreiber", "fr": "Stylo", "it": "Penna", "es": "Boligrafo", "tr": "Tukenmez kalem", "img": "\U0001f58a\ufe0f"},
            {"en": "Scissors", "de": "Schere", "fr": "Ciseaux", "it": "Forbici", "es": "Tijeras", "tr": "Makas", "img": "\u2702\ufe0f"},
            {"en": "Glue", "de": "Kleber", "fr": "Colle", "it": "Colla", "es": "Pegamento", "tr": "Yapistirici", "img": "\U0001f4ce"},
            {"en": "Blackboard", "de": "Tafel", "fr": "Tableau", "it": "Lavagna", "es": "Pizarra", "tr": "Kara tahta", "img": "\U0001f4dd"},
            {"en": "Chalk", "de": "Kreide", "fr": "Craie", "it": "Gesso", "es": "Tiza", "tr": "Tebessir", "img": "\U0001f58d\ufe0f"},
            {"en": "Map", "de": "Karte", "fr": "Carte", "it": "Mappa", "es": "Mapa", "tr": "Harita", "img": "\U0001f5fa\ufe0f"},
            {"en": "Computer", "de": "Computer", "fr": "Ordinateur", "it": "Computer", "es": "Computadora", "tr": "Bilgisayar", "img": "\U0001f4bb"},
        ]},
        # ── 2. Okul (12) ──
        {"topic": "Okul", "emoji": "\U0001f3eb", "words": [
            {"en": "Teacher", "de": "Lehrer", "fr": "Professeur", "it": "Insegnante", "es": "Profesor", "tr": "Ogretmen", "img": "\U0001f468\u200d\U0001f3eb"},
            {"en": "Student", "de": "Schuler", "fr": "Eleve", "it": "Studente", "es": "Estudiante", "tr": "Ogrenci", "img": "\U0001f393"},
            {"en": "Classroom", "de": "Klassenzimmer", "fr": "Salle de classe", "it": "Aula", "es": "Aula", "tr": "Sinif", "img": "\U0001f3eb"},
            {"en": "School", "de": "Schule", "fr": "Ecole", "it": "Scuola", "es": "Escuela", "tr": "Okul", "img": "\U0001f3e2"},
            {"en": "Playground", "de": "Spielplatz", "fr": "Cour de recreation", "it": "Parco giochi", "es": "Patio de recreo", "tr": "Oyun bahcesi", "img": "\U0001f3a0"},
            {"en": "Library", "de": "Bibliothek", "fr": "Bibliotheque", "it": "Biblioteca", "es": "Biblioteca", "tr": "Kutuphane", "img": "\U0001f4da"},
            {"en": "Homework", "de": "Hausaufgabe", "fr": "Devoirs", "it": "Compiti", "es": "Tarea", "tr": "Odev", "img": "\U0001f4dd"},
            {"en": "Lesson", "de": "Unterricht", "fr": "Lecon", "it": "Lezione", "es": "Leccion", "tr": "Ders", "img": "\U0001f4d6"},
            {"en": "Exam", "de": "Prufung", "fr": "Examen", "it": "Esame", "es": "Examen", "tr": "Sinav", "img": "\U0001f4dd"},
            {"en": "Break", "de": "Pause", "fr": "Pause", "it": "Pausa", "es": "Descanso", "tr": "Teneffus", "img": "\u23f8\ufe0f"},
            {"en": "Bell", "de": "Glocke", "fr": "Cloche", "it": "Campana", "es": "Campana", "tr": "Zil", "img": "\U0001f514"},
            {"en": "Principal", "de": "Direktor", "fr": "Directeur", "it": "Preside", "es": "Director", "tr": "Mudur", "img": "\U0001f468\u200d\U0001f4bc"},
        ]},
        # ── 3. Meslekler (15) ──
        {"topic": "Meslekler", "emoji": "\U0001f468\u200d\u2695\ufe0f", "words": [
            {"en": "Doctor", "de": "Arzt", "fr": "Medecin", "it": "Medico", "es": "Medico", "tr": "Doktor", "img": "\U0001f468\u200d\u2695\ufe0f"},
            {"en": "Nurse", "de": "Krankenschwester", "fr": "Infirmiere", "it": "Infermiera", "es": "Enfermera", "tr": "Hemsire", "img": "\U0001f469\u200d\u2695\ufe0f"},
            {"en": "Police officer", "de": "Polizist", "fr": "Policier", "it": "Poliziotto", "es": "Policia", "tr": "Polis", "img": "\U0001f46e"},
            {"en": "Firefighter", "de": "Feuerwehrmann", "fr": "Pompier", "it": "Pompiere", "es": "Bombero", "tr": "Itfaiyeci", "img": "\U0001f468\u200d\U0001f692"},
            {"en": "Farmer", "de": "Bauer", "fr": "Fermier", "it": "Contadino", "es": "Granjero", "tr": "Ciftci", "img": "\U0001f468\u200d\U0001f33e"},
            {"en": "Cook", "de": "Koch", "fr": "Cuisinier", "it": "Cuoco", "es": "Cocinero", "tr": "Asci", "img": "\U0001f468\u200d\U0001f373"},
            {"en": "Driver", "de": "Fahrer", "fr": "Chauffeur", "it": "Autista", "es": "Conductor", "tr": "Sofor", "img": "\U0001f468\u200d\U0001f4bc"},
            {"en": "Pilot", "de": "Pilot", "fr": "Pilote", "it": "Pilota", "es": "Piloto", "tr": "Pilot", "img": "\U0001f468\u200d\u2708\ufe0f"},
            {"en": "Singer", "de": "Sanger", "fr": "Chanteur", "it": "Cantante", "es": "Cantante", "tr": "Sarkici", "img": "\U0001f3a4"},
            {"en": "Painter", "de": "Maler", "fr": "Peintre", "it": "Pittore", "es": "Pintor", "tr": "Ressam", "img": "\U0001f3a8"},
            {"en": "Dentist", "de": "Zahnarzt", "fr": "Dentiste", "it": "Dentista", "es": "Dentista", "tr": "Dis doktoru", "img": "\U0001f9b7"},
            {"en": "Vet", "de": "Tierarzt", "fr": "Veterinaire", "it": "Veterinario", "es": "Veterinario", "tr": "Veteriner", "img": "\U0001f429"},
            {"en": "Engineer", "de": "Ingenieur", "fr": "Ingenieur", "it": "Ingegnere", "es": "Ingeniero", "tr": "Muhendis", "img": "\U0001f477"},
            {"en": "Astronaut", "de": "Astronaut", "fr": "Astronaute", "it": "Astronauta", "es": "Astronauta", "tr": "Astronot", "img": "\U0001f468\u200d\U0001f680"},
            {"en": "Baker", "de": "Backer", "fr": "Boulanger", "it": "Panettiere", "es": "Panadero", "tr": "Firinci", "img": "\U0001f35e"},
        ]},
        # ── 4. Spor (12) ──
        {"topic": "Spor", "emoji": "\u26bd", "words": [
            {"en": "Football", "de": "Fussball", "fr": "Football", "it": "Calcio", "es": "Futbol", "tr": "Futbol", "img": "\u26bd"},
            {"en": "Basketball", "de": "Basketball", "fr": "Basket-ball", "it": "Pallacanestro", "es": "Baloncesto", "tr": "Basketbol", "img": "\U0001f3c0"},
            {"en": "Swimming", "de": "Schwimmen", "fr": "Natation", "it": "Nuoto", "es": "Natacion", "tr": "Yuzme", "img": "\U0001f3ca"},
            {"en": "Running", "de": "Laufen", "fr": "Course", "it": "Corsa", "es": "Correr", "tr": "Kosma", "img": "\U0001f3c3"},
            {"en": "Tennis", "de": "Tennis", "fr": "Tennis", "it": "Tennis", "es": "Tenis", "tr": "Tenis", "img": "\U0001f3be"},
            {"en": "Volleyball", "de": "Volleyball", "fr": "Volley-ball", "it": "Pallavolo", "es": "Voleibol", "tr": "Voleybol", "img": "\U0001f3d0"},
            {"en": "Cycling", "de": "Radfahren", "fr": "Cyclisme", "it": "Ciclismo", "es": "Ciclismo", "tr": "Bisiklet", "img": "\U0001f6b4"},
            {"en": "Dancing", "de": "Tanzen", "fr": "Danse", "it": "Danza", "es": "Baile", "tr": "Dans", "img": "\U0001f483"},
            {"en": "Gymnastics", "de": "Turnen", "fr": "Gymnastique", "it": "Ginnastica", "es": "Gimnasia", "tr": "Jimnastik", "img": "\U0001f938"},
            {"en": "Skiing", "de": "Skifahren", "fr": "Ski", "it": "Sci", "es": "Esqui", "tr": "Kayak", "img": "\u26f7\ufe0f"},
            {"en": "Table tennis", "de": "Tischtennis", "fr": "Tennis de table", "it": "Ping pong", "es": "Tenis de mesa", "tr": "Masa tenisi", "img": "\U0001f3d3"},
            {"en": "Jumping", "de": "Springen", "fr": "Saut", "it": "Salto", "es": "Salto", "tr": "Ziplama", "img": "\U0001f93e"},
        ]},
        # ── 5. Hobiler (12) ──
        {"topic": "Hobiler", "emoji": "\U0001f3a8", "words": [
            {"en": "Drawing", "de": "Zeichnen", "fr": "Dessin", "it": "Disegno", "es": "Dibujo", "tr": "Resim yapma", "img": "\U0001f3a8"},
            {"en": "Reading", "de": "Lesen", "fr": "Lecture", "it": "Lettura", "es": "Lectura", "tr": "Okuma", "img": "\U0001f4d6"},
            {"en": "Singing", "de": "Singen", "fr": "Chant", "it": "Canto", "es": "Canto", "tr": "Sarki soyleme", "img": "\U0001f3a4"},
            {"en": "Playing", "de": "Spielen", "fr": "Jouer", "it": "Giocare", "es": "Jugar", "tr": "Oynamak", "img": "\U0001f3ae"},
            {"en": "Cooking", "de": "Kochen", "fr": "Cuisine", "it": "Cucina", "es": "Cocinar", "tr": "Yemek yapma", "img": "\U0001f373"},
            {"en": "Gardening", "de": "Gartenarbeit", "fr": "Jardinage", "it": "Giardinaggio", "es": "Jardineria", "tr": "Bahcecilik", "img": "\U0001f331"},
            {"en": "Painting", "de": "Malen", "fr": "Peinture", "it": "Pittura", "es": "Pintura", "tr": "Boyama", "img": "\U0001f58c\ufe0f"},
            {"en": "Writing", "de": "Schreiben", "fr": "Ecriture", "it": "Scrittura", "es": "Escritura", "tr": "Yazma", "img": "\u270d\ufe0f"},
            {"en": "Fishing", "de": "Angeln", "fr": "Peche", "it": "Pesca", "es": "Pesca", "tr": "Balik tutma", "img": "\U0001f3a3"},
            {"en": "Photography", "de": "Fotografie", "fr": "Photographie", "it": "Fotografia", "es": "Fotografia", "tr": "Fotograf cekmek", "img": "\U0001f4f7"},
            {"en": "Collecting", "de": "Sammeln", "fr": "Collectionner", "it": "Collezionare", "es": "Coleccionar", "tr": "Koleksiyon yapma", "img": "\U0001f4e6"},
            {"en": "Camping", "de": "Zelten", "fr": "Camping", "it": "Campeggio", "es": "Acampar", "tr": "Kamp", "img": "\U0001f3d5\ufe0f"},
        ]},
        # ── 6. Gunler/Aylar (15) ──
        {"topic": "Gunler ve Aylar", "emoji": "\U0001f4c5", "words": [
            {"en": "Monday", "de": "Montag", "fr": "Lundi", "it": "Lunedi", "es": "Lunes", "tr": "Pazartesi", "img": "\U0001f4c5"},
            {"en": "Tuesday", "de": "Dienstag", "fr": "Mardi", "it": "Martedi", "es": "Martes", "tr": "Sali", "img": "\U0001f4c5"},
            {"en": "Wednesday", "de": "Mittwoch", "fr": "Mercredi", "it": "Mercoledi", "es": "Miercoles", "tr": "Carsamba", "img": "\U0001f4c5"},
            {"en": "Thursday", "de": "Donnerstag", "fr": "Jeudi", "it": "Giovedi", "es": "Jueves", "tr": "Persembe", "img": "\U0001f4c5"},
            {"en": "Friday", "de": "Freitag", "fr": "Vendredi", "it": "Venerdi", "es": "Viernes", "tr": "Cuma", "img": "\U0001f4c5"},
            {"en": "Saturday", "de": "Samstag", "fr": "Samedi", "it": "Sabato", "es": "Sabado", "tr": "Cumartesi", "img": "\U0001f4c5"},
            {"en": "Sunday", "de": "Sonntag", "fr": "Dimanche", "it": "Domenica", "es": "Domingo", "tr": "Pazar", "img": "\U0001f4c5"},
            {"en": "January", "de": "Januar", "fr": "Janvier", "it": "Gennaio", "es": "Enero", "tr": "Ocak", "img": "\u2744\ufe0f"},
            {"en": "March", "de": "Marz", "fr": "Mars", "it": "Marzo", "es": "Marzo", "tr": "Mart", "img": "\U0001f331"},
            {"en": "June", "de": "Juni", "fr": "Juin", "it": "Giugno", "es": "Junio", "tr": "Haziran", "img": "\u2600\ufe0f"},
            {"en": "September", "de": "September", "fr": "Septembre", "it": "Settembre", "es": "Septiembre", "tr": "Eylul", "img": "\U0001f342"},
            {"en": "December", "de": "Dezember", "fr": "Decembre", "it": "Dicembre", "es": "Diciembre", "tr": "Aralik", "img": "\U0001f384"},
            {"en": "Today", "de": "Heute", "fr": "Aujourd'hui", "it": "Oggi", "es": "Hoy", "tr": "Bugun", "img": "\U0001f4c6"},
            {"en": "Tomorrow", "de": "Morgen", "fr": "Demain", "it": "Domani", "es": "Manana", "tr": "Yarin", "img": "\u27a1\ufe0f"},
            {"en": "Yesterday", "de": "Gestern", "fr": "Hier", "it": "Ieri", "es": "Ayer", "tr": "Dun", "img": "\u2b05\ufe0f"},
        ]},
        # ── 7. Hava Durumu (12) ──
        {"topic": "Hava Durumu", "emoji": "\u2600\ufe0f", "words": [
            {"en": "Sunny", "de": "Sonnig", "fr": "Ensoleille", "it": "Soleggiato", "es": "Soleado", "tr": "Gunesli", "img": "\u2600\ufe0f"},
            {"en": "Rainy", "de": "Regnerisch", "fr": "Pluvieux", "it": "Piovoso", "es": "Lluvioso", "tr": "Yagmurlu", "img": "\U0001f327\ufe0f"},
            {"en": "Cloudy", "de": "Wolkig", "fr": "Nuageux", "it": "Nuvoloso", "es": "Nublado", "tr": "Bulutlu", "img": "\u2601\ufe0f"},
            {"en": "Snowy", "de": "Schneereich", "fr": "Neigeux", "it": "Nevoso", "es": "Nevado", "tr": "Karli", "img": "\U0001f328\ufe0f"},
            {"en": "Windy", "de": "Windig", "fr": "Venteux", "it": "Ventoso", "es": "Ventoso", "tr": "Ruzgarli", "img": "\U0001f32c\ufe0f"},
            {"en": "Hot", "de": "Heiss", "fr": "Chaud", "it": "Caldo", "es": "Caliente", "tr": "Sicak", "img": "\U0001f321\ufe0f"},
            {"en": "Cold", "de": "Kalt", "fr": "Froid", "it": "Freddo", "es": "Frio", "tr": "Soguk", "img": "\U0001f9ca"},
            {"en": "Warm", "de": "Warm", "fr": "Tiede", "it": "Tiepido", "es": "Templado", "tr": "Ilik", "img": "\U0001f31e"},
            {"en": "Foggy", "de": "Neblig", "fr": "Brumeux", "it": "Nebbioso", "es": "Neblinoso", "tr": "Sisli", "img": "\U0001f32b\ufe0f"},
            {"en": "Stormy", "de": "Sturmisch", "fr": "Orageux", "it": "Tempestoso", "es": "Tormentoso", "tr": "Firtinali", "img": "\u26c8\ufe0f"},
            {"en": "Spring", "de": "Fruhling", "fr": "Printemps", "it": "Primavera", "es": "Primavera", "tr": "Ilkbahar", "img": "\U0001f338"},
            {"en": "Summer", "de": "Sommer", "fr": "Ete", "it": "Estate", "es": "Verano", "tr": "Yaz", "img": "\U0001f3d6\ufe0f"},
        ]},
        # ── 8. Mekanlar (15) ──
        {"topic": "Mekanlar", "emoji": "\U0001f3e0", "words": [
            {"en": "House", "de": "Haus", "fr": "Maison", "it": "Casa", "es": "Casa", "tr": "Ev", "img": "\U0001f3e0"},
            {"en": "Park", "de": "Park", "fr": "Parc", "it": "Parco", "es": "Parque", "tr": "Park", "img": "\U0001f3de\ufe0f"},
            {"en": "Hospital", "de": "Krankenhaus", "fr": "Hopital", "it": "Ospedale", "es": "Hospital", "tr": "Hastane", "img": "\U0001f3e5"},
            {"en": "Market", "de": "Markt", "fr": "Marche", "it": "Mercato", "es": "Mercado", "tr": "Market", "img": "\U0001f6d2"},
            {"en": "Restaurant", "de": "Restaurant", "fr": "Restaurant", "it": "Ristorante", "es": "Restaurante", "tr": "Restoran", "img": "\U0001f37d\ufe0f"},
            {"en": "Bakery", "de": "Backerei", "fr": "Boulangerie", "it": "Panetteria", "es": "Panaderia", "tr": "Firin", "img": "\U0001f35e"},
            {"en": "Pharmacy", "de": "Apotheke", "fr": "Pharmacie", "it": "Farmacia", "es": "Farmacia", "tr": "Eczane", "img": "\U0001f48a"},
            {"en": "Cinema", "de": "Kino", "fr": "Cinema", "it": "Cinema", "es": "Cine", "tr": "Sinema", "img": "\U0001f3ac"},
            {"en": "Museum", "de": "Museum", "fr": "Musee", "it": "Museo", "es": "Museo", "tr": "Muze", "img": "\U0001f3db\ufe0f"},
            {"en": "Zoo", "de": "Zoo", "fr": "Zoo", "it": "Zoo", "es": "Zoologico", "tr": "Hayvanat bahcesi", "img": "\U0001f981"},
            {"en": "Airport", "de": "Flughafen", "fr": "Aeroport", "it": "Aeroporto", "es": "Aeropuerto", "tr": "Havaalani", "img": "\u2708\ufe0f"},
            {"en": "Beach", "de": "Strand", "fr": "Plage", "it": "Spiaggia", "es": "Playa", "tr": "Plaj", "img": "\U0001f3d6\ufe0f"},
            {"en": "Garden", "de": "Garten", "fr": "Jardin", "it": "Giardino", "es": "Jardin", "tr": "Bahce", "img": "\U0001f33b"},
            {"en": "Station", "de": "Bahnhof", "fr": "Gare", "it": "Stazione", "es": "Estacion", "tr": "Istasyon", "img": "\U0001f689"},
            {"en": "Mosque", "de": "Moschee", "fr": "Mosquee", "it": "Moschea", "es": "Mezquita", "tr": "Cami", "img": "\U0001f54c"},
        ]},
        # ── 9. Yiyecek/Icecek (15) ──
        {"topic": "Yiyecek ve Icecek", "emoji": "\U0001f354", "words": [
            {"en": "Sandwich", "de": "Sandwich", "fr": "Sandwich", "it": "Panino", "es": "Sandwich", "tr": "Sandvic", "img": "\U0001f96a"},
            {"en": "Salad", "de": "Salat", "fr": "Salade", "it": "Insalata", "es": "Ensalada", "tr": "Salata", "img": "\U0001f957"},
            {"en": "Hamburger", "de": "Hamburger", "fr": "Hamburger", "it": "Hamburger", "es": "Hamburguesa", "tr": "Hamburger", "img": "\U0001f354"},
            {"en": "French fries", "de": "Pommes frites", "fr": "Frites", "it": "Patatine fritte", "es": "Papas fritas", "tr": "Patates kizartmasi", "img": "\U0001f35f"},
            {"en": "Chocolate", "de": "Schokolade", "fr": "Chocolat", "it": "Cioccolato", "es": "Chocolate", "tr": "Cikolata", "img": "\U0001f36b"},
            {"en": "Tea", "de": "Tee", "fr": "The", "it": "Te", "es": "Te", "tr": "Cay", "img": "\U0001f375"},
            {"en": "Lemonade", "de": "Limonade", "fr": "Limonade", "it": "Limonata", "es": "Limonada", "tr": "Limonata", "img": "\U0001f34b"},
            {"en": "Pasta", "de": "Nudeln", "fr": "Pates", "it": "Pasta", "es": "Pasta", "tr": "Makarna", "img": "\U0001f35d"},
            {"en": "Fish", "de": "Fisch", "fr": "Poisson", "it": "Pesce", "es": "Pescado", "tr": "Balik", "img": "\U0001f41f"},
            {"en": "Tomato", "de": "Tomate", "fr": "Tomate", "it": "Pomodoro", "es": "Tomate", "tr": "Domates", "img": "\U0001f345"},
            {"en": "Potato", "de": "Kartoffel", "fr": "Pomme de terre", "it": "Patata", "es": "Papa", "tr": "Patates", "img": "\U0001f954"},
            {"en": "Carrot", "de": "Karotte", "fr": "Carotte", "it": "Carota", "es": "Zanahoria", "tr": "Havuc", "img": "\U0001f955"},
            {"en": "Corn", "de": "Mais", "fr": "Mais", "it": "Mais", "es": "Maiz", "tr": "Misir", "img": "\U0001f33d"},
            {"en": "Yogurt", "de": "Joghurt", "fr": "Yaourt", "it": "Yogurt", "es": "Yogur", "tr": "Yogurt", "img": "\U0001f95b"},
            {"en": "Breakfast", "de": "Fruhstuck", "fr": "Petit-dejeuner", "it": "Colazione", "es": "Desayuno", "tr": "Kahvalti", "img": "\U0001f373"},
        ]},
        # ── 10. Ev Odalari (12) ──
        {"topic": "Ev Odalari", "emoji": "\U0001f6cb\ufe0f", "words": [
            {"en": "Kitchen", "de": "Kuche", "fr": "Cuisine", "it": "Cucina", "es": "Cocina", "tr": "Mutfak", "img": "\U0001f373"},
            {"en": "Bedroom", "de": "Schlafzimmer", "fr": "Chambre", "it": "Camera da letto", "es": "Dormitorio", "tr": "Yatak odasi", "img": "\U0001f6cf\ufe0f"},
            {"en": "Bathroom", "de": "Badezimmer", "fr": "Salle de bain", "it": "Bagno", "es": "Bano", "tr": "Banyo", "img": "\U0001f6c1"},
            {"en": "Living room", "de": "Wohnzimmer", "fr": "Salon", "it": "Soggiorno", "es": "Sala de estar", "tr": "Oturma odasi", "img": "\U0001f6cb\ufe0f"},
            {"en": "Dining room", "de": "Esszimmer", "fr": "Salle a manger", "it": "Sala da pranzo", "es": "Comedor", "tr": "Yemek odasi", "img": "\U0001f37d\ufe0f"},
            {"en": "Balcony", "de": "Balkon", "fr": "Balcon", "it": "Balcone", "es": "Balcon", "tr": "Balkon", "img": "\U0001f3e0"},
            {"en": "Garage", "de": "Garage", "fr": "Garage", "it": "Garage", "es": "Garaje", "tr": "Garaj", "img": "\U0001f697"},
            {"en": "Stairs", "de": "Treppe", "fr": "Escalier", "it": "Scale", "es": "Escalera", "tr": "Merdiven", "img": "\U0001fa9c"},
            {"en": "Roof", "de": "Dach", "fr": "Toit", "it": "Tetto", "es": "Techo", "tr": "Cati", "img": "\U0001f3e0"},
            {"en": "Floor", "de": "Boden", "fr": "Sol", "it": "Pavimento", "es": "Suelo", "tr": "Zemin", "img": "\U0001f3e0"},
            {"en": "Ceiling", "de": "Decke", "fr": "Plafond", "it": "Soffitto", "es": "Techo", "tr": "Tavan", "img": "\U0001f3e0"},
            {"en": "Hall", "de": "Flur", "fr": "Couloir", "it": "Corridoio", "es": "Pasillo", "tr": "Koridor", "img": "\U0001f6aa"},
        ]},
        # ── 11. Duygular (12) ──
        {"topic": "Duygular", "emoji": "\U0001f60a", "words": [
            {"en": "Happy", "de": "Glucklich", "fr": "Content", "it": "Felice", "es": "Feliz", "tr": "Mutlu", "img": "\U0001f60a"},
            {"en": "Sad", "de": "Traurig", "fr": "Triste", "it": "Triste", "es": "Triste", "tr": "Uzgun", "img": "\U0001f622"},
            {"en": "Angry", "de": "Wutend", "fr": "En colere", "it": "Arrabbiato", "es": "Enfadado", "tr": "Kizgin", "img": "\U0001f620"},
            {"en": "Scared", "de": "Angstlich", "fr": "Effraye", "it": "Spaventato", "es": "Asustado", "tr": "Korkmus", "img": "\U0001f628"},
            {"en": "Tired", "de": "Mude", "fr": "Fatigue", "it": "Stanco", "es": "Cansado", "tr": "Yorgun", "img": "\U0001f634"},
            {"en": "Hungry", "de": "Hungrig", "fr": "Affame", "it": "Affamato", "es": "Hambriento", "tr": "Ac", "img": "\U0001f924"},
            {"en": "Thirsty", "de": "Durstig", "fr": "Assoiffe", "it": "Assetato", "es": "Sediento", "tr": "Susamis", "img": "\U0001f4a7"},
            {"en": "Excited", "de": "Aufgeregt", "fr": "Excite", "it": "Eccitato", "es": "Emocionado", "tr": "Heyecanli", "img": "\U0001f929"},
            {"en": "Surprised", "de": "Uberrascht", "fr": "Surpris", "it": "Sorpreso", "es": "Sorprendido", "tr": "Saskin", "img": "\U0001f632"},
            {"en": "Bored", "de": "Gelangweilt", "fr": "Ennuye", "it": "Annoiato", "es": "Aburrido", "tr": "Sikilan", "img": "\U0001f971"},
            {"en": "Shy", "de": "Schuchtern", "fr": "Timide", "it": "Timido", "es": "Timido", "tr": "Utangac", "img": "\U0001f633"},
            {"en": "Proud", "de": "Stolz", "fr": "Fier", "it": "Orgoglioso", "es": "Orgulloso", "tr": "Gururlu", "img": "\U0001f60e"},
        ]},
        # ── 12. Sifatlar (15) ──
        {"topic": "Sifatlar", "emoji": "\U0001f4a1", "words": [
            {"en": "Big", "de": "Gross", "fr": "Grand", "it": "Grande", "es": "Grande", "tr": "Buyuk", "img": "\U0001f418"},
            {"en": "Small", "de": "Klein", "fr": "Petit", "it": "Piccolo", "es": "Pequeno", "tr": "Kucuk", "img": "\U0001f42d"},
            {"en": "Long", "de": "Lang", "fr": "Long", "it": "Lungo", "es": "Largo", "tr": "Uzun", "img": "\U0001f4cf"},
            {"en": "Short", "de": "Kurz", "fr": "Court", "it": "Corto", "es": "Corto", "tr": "Kisa", "img": "\U0001f4cf"},
            {"en": "Fast", "de": "Schnell", "fr": "Rapide", "it": "Veloce", "es": "Rapido", "tr": "Hizli", "img": "\U0001f3ce\ufe0f"},
            {"en": "Slow", "de": "Langsam", "fr": "Lent", "it": "Lento", "es": "Lento", "tr": "Yavas", "img": "\U0001f422"},
            {"en": "New", "de": "Neu", "fr": "Nouveau", "it": "Nuovo", "es": "Nuevo", "tr": "Yeni", "img": "\u2728"},
            {"en": "Old", "de": "Alt", "fr": "Vieux", "it": "Vecchio", "es": "Viejo", "tr": "Eski", "img": "\U0001f4dc"},
            {"en": "Beautiful", "de": "Schon", "fr": "Beau", "it": "Bello", "es": "Hermoso", "tr": "Guzel", "img": "\U0001f338"},
            {"en": "Ugly", "de": "Hasslich", "fr": "Laid", "it": "Brutto", "es": "Feo", "tr": "Cirkin", "img": "\U0001f47a"},
            {"en": "Heavy", "de": "Schwer", "fr": "Lourd", "it": "Pesante", "es": "Pesado", "tr": "Agir", "img": "\U0001f4a6"},
            {"en": "Light", "de": "Leicht", "fr": "Leger", "it": "Leggero", "es": "Ligero", "tr": "Hafif", "img": "\U0001f4a8"},
            {"en": "Clean", "de": "Sauber", "fr": "Propre", "it": "Pulito", "es": "Limpio", "tr": "Temiz", "img": "\u2728"},
            {"en": "Dirty", "de": "Schmutzig", "fr": "Sale", "it": "Sporco", "es": "Sucio", "tr": "Kirli", "img": "\U0001f4a9"},
            {"en": "Strong", "de": "Stark", "fr": "Fort", "it": "Forte", "es": "Fuerte", "tr": "Guclu", "img": "\U0001f4aa"},
        ]},
        # ── 13. Teknoloji Temel (15) ── [NEW]
        {"topic": "Teknoloji Temel", "emoji": "\U0001f4bb", "words": [
            {"en": "Computer", "de": "Computer", "fr": "Ordinateur", "it": "Computer", "es": "Computadora", "tr": "Bilgisayar", "img": "\U0001f4bb"},
            {"en": "Phone", "de": "Telefon", "fr": "Telephone", "it": "Telefono", "es": "Telefono", "tr": "Telefon", "img": "\U0001f4f1"},
            {"en": "Tablet", "de": "Tablet", "fr": "Tablette", "it": "Tablet", "es": "Tableta", "tr": "Tablet", "img": "\U0001f4f1"},
            {"en": "TV", "de": "Fernseher", "fr": "Television", "it": "Televisione", "es": "Television", "tr": "Televizyon", "img": "\U0001f4fa"},
            {"en": "Radio", "de": "Radio", "fr": "Radio", "it": "Radio", "es": "Radio", "tr": "Radyo", "img": "\U0001f4fb"},
            {"en": "Camera", "de": "Kamera", "fr": "Camera", "it": "Fotocamera", "es": "Camara", "tr": "Kamera", "img": "\U0001f4f7"},
            {"en": "Internet", "de": "Internet", "fr": "Internet", "it": "Internet", "es": "Internet", "tr": "Internet", "img": "\U0001f310"},
            {"en": "Email", "de": "E-Mail", "fr": "E-mail", "it": "Email", "es": "Correo electronico", "tr": "E-posta", "img": "\U0001f4e7"},
            {"en": "App", "de": "App", "fr": "Application", "it": "Applicazione", "es": "Aplicacion", "tr": "Uygulama", "img": "\U0001f4f2"},
            {"en": "Game", "de": "Spiel", "fr": "Jeu", "it": "Gioco", "es": "Juego", "tr": "Oyun", "img": "\U0001f3ae"},
            {"en": "Video", "de": "Video", "fr": "Video", "it": "Video", "es": "Video", "tr": "Video", "img": "\U0001f4f9"},
            {"en": "Music", "de": "Musik", "fr": "Musique", "it": "Musica", "es": "Musica", "tr": "Muzik", "img": "\U0001f3b5"},
            {"en": "Photo", "de": "Foto", "fr": "Photo", "it": "Foto", "es": "Foto", "tr": "Fotograf", "img": "\U0001f4f8"},
            {"en": "Mouse", "de": "Maus", "fr": "Souris", "it": "Mouse", "es": "Raton", "tr": "Fare", "img": "\U0001f5b1\ufe0f"},
            {"en": "Keyboard", "de": "Tastatur", "fr": "Clavier", "it": "Tastiera", "es": "Teclado", "tr": "Klavye", "img": "\u2328\ufe0f"},
        ]},
        # ── 14. Muzik Aletleri (10) ── [NEW]
        {"topic": "Muzik Aletleri", "emoji": "\U0001f3b5", "words": [
            {"en": "Piano", "de": "Klavier", "fr": "Piano", "it": "Pianoforte", "es": "Piano", "tr": "Piyano", "img": "\U0001f3b9"},
            {"en": "Guitar", "de": "Gitarre", "fr": "Guitare", "it": "Chitarra", "es": "Guitarra", "tr": "Gitar", "img": "\U0001f3b8"},
            {"en": "Drums", "de": "Schlagzeug", "fr": "Batterie", "it": "Batteria", "es": "Bateria", "tr": "Davul", "img": "\U0001f941"},
            {"en": "Violin", "de": "Geige", "fr": "Violon", "it": "Violino", "es": "Violin", "tr": "Keman", "img": "\U0001f3bb"},
            {"en": "Flute", "de": "Flote", "fr": "Flute", "it": "Flauto", "es": "Flauta", "tr": "Flut", "img": "\U0001f3b5"},
            {"en": "Trumpet", "de": "Trompete", "fr": "Trompette", "it": "Tromba", "es": "Trompeta", "tr": "Trompet", "img": "\U0001f3ba"},
            {"en": "Saxophone", "de": "Saxophon", "fr": "Saxophone", "it": "Sassofono", "es": "Saxofon", "tr": "Saksafon", "img": "\U0001f3b7"},
            {"en": "Harp", "de": "Harfe", "fr": "Harpe", "it": "Arpa", "es": "Arpa", "tr": "Arp", "img": "\U0001f3b5"},
            {"en": "Accordion", "de": "Akkordeon", "fr": "Accordeon", "it": "Fisarmonica", "es": "Acordeon", "tr": "Akordiyon", "img": "\U0001f3b5"},
            {"en": "Tambourine", "de": "Tamburin", "fr": "Tambourin", "it": "Tamburello", "es": "Pandereta", "tr": "Tef", "img": "\U0001f941"},
        ]},
        # ── 15. Ulkeler (12) ── [NEW]
        {"topic": "Ulkeler", "emoji": "\U0001f30d", "words": [
            {"en": "Turkey", "de": "Turkei", "fr": "Turquie", "it": "Turchia", "es": "Turquia", "tr": "Turkiye", "img": "\U0001f1f9\U0001f1f7"},
            {"en": "Germany", "de": "Deutschland", "fr": "Allemagne", "it": "Germania", "es": "Alemania", "tr": "Almanya", "img": "\U0001f1e9\U0001f1ea"},
            {"en": "France", "de": "Frankreich", "fr": "France", "it": "Francia", "es": "Francia", "tr": "Fransa", "img": "\U0001f1eb\U0001f1f7"},
            {"en": "Italy", "de": "Italien", "fr": "Italie", "it": "Italia", "es": "Italia", "tr": "Italya", "img": "\U0001f1ee\U0001f1f9"},
            {"en": "Spain", "de": "Spanien", "fr": "Espagne", "it": "Spagna", "es": "Espana", "tr": "Ispanya", "img": "\U0001f1ea\U0001f1f8"},
            {"en": "England", "de": "England", "fr": "Angleterre", "it": "Inghilterra", "es": "Inglaterra", "tr": "Ingiltere", "img": "\U0001f1ec\U0001f1e7"},
            {"en": "USA", "de": "USA", "fr": "Etats-Unis", "it": "Stati Uniti", "es": "Estados Unidos", "tr": "Amerika", "img": "\U0001f1fa\U0001f1f8"},
            {"en": "Japan", "de": "Japan", "fr": "Japon", "it": "Giappone", "es": "Japon", "tr": "Japonya", "img": "\U0001f1ef\U0001f1f5"},
            {"en": "China", "de": "China", "fr": "Chine", "it": "Cina", "es": "China", "tr": "Cin", "img": "\U0001f1e8\U0001f1f3"},
            {"en": "Russia", "de": "Russland", "fr": "Russie", "it": "Russia", "es": "Rusia", "tr": "Rusya", "img": "\U0001f1f7\U0001f1fa"},
            {"en": "Brazil", "de": "Brasilien", "fr": "Bresil", "it": "Brasile", "es": "Brasil", "tr": "Brezilya", "img": "\U0001f1e7\U0001f1f7"},
            {"en": "Egypt", "de": "Agypten", "fr": "Egypte", "it": "Egitto", "es": "Egipto", "tr": "Misir", "img": "\U0001f1ea\U0001f1ec"},
        ]},
        # ── 16. Diller (10) ── [NEW]
        {"topic": "Diller", "emoji": "\U0001f5e3\ufe0f", "words": [
            {"en": "Turkish", "de": "Turkisch", "fr": "Turc", "it": "Turco", "es": "Turco", "tr": "Turkce", "img": "\U0001f1f9\U0001f1f7"},
            {"en": "English", "de": "Englisch", "fr": "Anglais", "it": "Inglese", "es": "Ingles", "tr": "Ingilizce", "img": "\U0001f1ec\U0001f1e7"},
            {"en": "German", "de": "Deutsch", "fr": "Allemand", "it": "Tedesco", "es": "Aleman", "tr": "Almanca", "img": "\U0001f1e9\U0001f1ea"},
            {"en": "French", "de": "Franzosisch", "fr": "Francais", "it": "Francese", "es": "Frances", "tr": "Fransizca", "img": "\U0001f1eb\U0001f1f7"},
            {"en": "Italian", "de": "Italienisch", "fr": "Italien", "it": "Italiano", "es": "Italiano", "tr": "Italyanca", "img": "\U0001f1ee\U0001f1f9"},
            {"en": "Spanish", "de": "Spanisch", "fr": "Espagnol", "it": "Spagnolo", "es": "Espanol", "tr": "Ispanyolca", "img": "\U0001f1ea\U0001f1f8"},
            {"en": "Arabic", "de": "Arabisch", "fr": "Arabe", "it": "Arabo", "es": "Arabe", "tr": "Arapca", "img": "\U0001f1f8\U0001f1e6"},
            {"en": "Chinese", "de": "Chinesisch", "fr": "Chinois", "it": "Cinese", "es": "Chino", "tr": "Cince", "img": "\U0001f1e8\U0001f1f3"},
            {"en": "Japanese", "de": "Japanisch", "fr": "Japonais", "it": "Giapponese", "es": "Japones", "tr": "Japonca", "img": "\U0001f1ef\U0001f1f5"},
            {"en": "Russian", "de": "Russisch", "fr": "Russe", "it": "Russo", "es": "Ruso", "tr": "Rusca", "img": "\U0001f1f7\U0001f1fa"},
        ]},
        # ── 17. Restoran (12) ── [NEW]
        {"topic": "Restoran", "emoji": "\U0001f37d\ufe0f", "words": [
            {"en": "Menu", "de": "Speisekarte", "fr": "Menu", "it": "Menu", "es": "Menu", "tr": "Menu", "img": "\U0001f4cb"},
            {"en": "Order", "de": "Bestellung", "fr": "Commande", "it": "Ordine", "es": "Pedido", "tr": "Siparis", "img": "\U0001f4dd"},
            {"en": "Bill", "de": "Rechnung", "fr": "Addition", "it": "Conto", "es": "Cuenta", "tr": "Hesap", "img": "\U0001f4b0"},
            {"en": "Waiter", "de": "Kellner", "fr": "Serveur", "it": "Cameriere", "es": "Camarero", "tr": "Garson", "img": "\U0001f468\u200d\U0001f373"},
            {"en": "Table", "de": "Tisch", "fr": "Table", "it": "Tavolo", "es": "Mesa", "tr": "Masa", "img": "\U0001f37d\ufe0f"},
            {"en": "Chair", "de": "Stuhl", "fr": "Chaise", "it": "Sedia", "es": "Silla", "tr": "Sandalye", "img": "\U0001fa91"},
            {"en": "Breakfast", "de": "Fruhstuck", "fr": "Petit-dejeuner", "it": "Colazione", "es": "Desayuno", "tr": "Kahvalti", "img": "\U0001f373"},
            {"en": "Lunch", "de": "Mittagessen", "fr": "Dejeuner", "it": "Pranzo", "es": "Almuerzo", "tr": "Ogle yemegi", "img": "\U0001f35d"},
            {"en": "Dinner", "de": "Abendessen", "fr": "Diner", "it": "Cena", "es": "Cena", "tr": "Aksam yemegi", "img": "\U0001f37d\ufe0f"},
            {"en": "Dessert", "de": "Nachtisch", "fr": "Dessert", "it": "Dolce", "es": "Postre", "tr": "Tatli", "img": "\U0001f370"},
            {"en": "Drink", "de": "Getrank", "fr": "Boisson", "it": "Bevanda", "es": "Bebida", "tr": "Icecek", "img": "\U0001f964"},
            {"en": "Soup", "de": "Suppe", "fr": "Soupe", "it": "Zuppa", "es": "Sopa", "tr": "Corba", "img": "\U0001f35c"},
        ]},
        # ── 18. Ulasim (12) ── [NEW]
        {"topic": "Ulasim", "emoji": "\U0001f68c", "words": [
            {"en": "Car", "de": "Auto", "fr": "Voiture", "it": "Macchina", "es": "Coche", "tr": "Araba", "img": "\U0001f697"},
            {"en": "Bus", "de": "Bus", "fr": "Bus", "it": "Autobus", "es": "Autobus", "tr": "Otobus", "img": "\U0001f68c"},
            {"en": "Train", "de": "Zug", "fr": "Train", "it": "Treno", "es": "Tren", "tr": "Tren", "img": "\U0001f686"},
            {"en": "Plane", "de": "Flugzeug", "fr": "Avion", "it": "Aereo", "es": "Avion", "tr": "Ucak", "img": "\u2708\ufe0f"},
            {"en": "Ship", "de": "Schiff", "fr": "Bateau", "it": "Nave", "es": "Barco", "tr": "Gemi", "img": "\U0001f6a2"},
            {"en": "Bicycle", "de": "Fahrrad", "fr": "Velo", "it": "Bicicletta", "es": "Bicicleta", "tr": "Bisiklet", "img": "\U0001f6b2"},
            {"en": "Motorcycle", "de": "Motorrad", "fr": "Moto", "it": "Moto", "es": "Motocicleta", "tr": "Motosiklet", "img": "\U0001f3cd\ufe0f"},
            {"en": "Taxi", "de": "Taxi", "fr": "Taxi", "it": "Taxi", "es": "Taxi", "tr": "Taksi", "img": "\U0001f695"},
            {"en": "Subway", "de": "U-Bahn", "fr": "Metro", "it": "Metropolitana", "es": "Metro", "tr": "Metro", "img": "\U0001f687"},
            {"en": "Tram", "de": "Strassenbahn", "fr": "Tramway", "it": "Tram", "es": "Tranvia", "tr": "Tramvay", "img": "\U0001f68a"},
            {"en": "Helicopter", "de": "Hubschrauber", "fr": "Helicoptere", "it": "Elicottero", "es": "Helicoptero", "tr": "Helikopter", "img": "\U0001f681"},
            {"en": "Boat", "de": "Boot", "fr": "Bateau", "it": "Barca", "es": "Bote", "tr": "Kayik", "img": "\u26f5"},
        ]},
        # ── 19. Park ve Bahce (10) ── [NEW]
        {"topic": "Park ve Bahce", "emoji": "\U0001f333", "words": [
            {"en": "Tree", "de": "Baum", "fr": "Arbre", "it": "Albero", "es": "Arbol", "tr": "Agac", "img": "\U0001f333"},
            {"en": "Flower", "de": "Blume", "fr": "Fleur", "it": "Fiore", "es": "Flor", "tr": "Cicek", "img": "\U0001f33b"},
            {"en": "Grass", "de": "Gras", "fr": "Herbe", "it": "Erba", "es": "Cesped", "tr": "Cimen", "img": "\U0001f33f"},
            {"en": "Bench", "de": "Bank", "fr": "Banc", "it": "Panchina", "es": "Banco", "tr": "Bank", "img": "\U0001fa91"},
            {"en": "Fountain", "de": "Brunnen", "fr": "Fontaine", "it": "Fontana", "es": "Fuente", "tr": "Cesme", "img": "\u26f2"},
            {"en": "Swing", "de": "Schaukel", "fr": "Balancoire", "it": "Altalena", "es": "Columpio", "tr": "Salincak", "img": "\U0001f3a0"},
            {"en": "Slide", "de": "Rutsche", "fr": "Toboggan", "it": "Scivolo", "es": "Tobogan", "tr": "Kaydırak", "img": "\U0001f6dd"},
            {"en": "Ball", "de": "Ball", "fr": "Balle", "it": "Palla", "es": "Pelota", "tr": "Top", "img": "\u26bd"},
            {"en": "Kite", "de": "Drachen", "fr": "Cerf-volant", "it": "Aquilone", "es": "Cometa", "tr": "Ucurtma", "img": "\U0001fa81"},
            {"en": "Butterfly", "de": "Schmetterling", "fr": "Papillon", "it": "Farfalla", "es": "Mariposa", "tr": "Kelebek", "img": "\U0001f98b"},
        ]},
        # ── 20. Saglik Temel (10) ── [NEW]
        {"topic": "Saglik Temel", "emoji": "\U0001f3e5", "words": [
            {"en": "Doctor", "de": "Arzt", "fr": "Medecin", "it": "Medico", "es": "Medico", "tr": "Doktor", "img": "\U0001f468\u200d\u2695\ufe0f"},
            {"en": "Nurse", "de": "Krankenschwester", "fr": "Infirmiere", "it": "Infermiera", "es": "Enfermera", "tr": "Hemsire", "img": "\U0001f469\u200d\u2695\ufe0f"},
            {"en": "Hospital", "de": "Krankenhaus", "fr": "Hopital", "it": "Ospedale", "es": "Hospital", "tr": "Hastane", "img": "\U0001f3e5"},
            {"en": "Medicine", "de": "Medizin", "fr": "Medicament", "it": "Medicina", "es": "Medicina", "tr": "Ilac", "img": "\U0001f48a"},
            {"en": "Sick", "de": "Krank", "fr": "Malade", "it": "Malato", "es": "Enfermo", "tr": "Hasta", "img": "\U0001f912"},
            {"en": "Healthy", "de": "Gesund", "fr": "En bonne sante", "it": "Sano", "es": "Sano", "tr": "Saglikli", "img": "\U0001f4aa"},
            {"en": "Headache", "de": "Kopfschmerzen", "fr": "Mal de tete", "it": "Mal di testa", "es": "Dolor de cabeza", "tr": "Bas agrisi", "img": "\U0001f915"},
            {"en": "Fever", "de": "Fieber", "fr": "Fievre", "it": "Febbre", "es": "Fiebre", "tr": "Ates", "img": "\U0001f321\ufe0f"},
            {"en": "Cough", "de": "Husten", "fr": "Toux", "it": "Tosse", "es": "Tos", "tr": "Oksuruk", "img": "\U0001f637"},
            {"en": "Cold", "de": "Erkaltung", "fr": "Rhume", "it": "Raffreddore", "es": "Resfriado", "tr": "Soguk alginligi", "img": "\U0001f927"},
        ]},
    ],
    # ════════════════════════════════════════
    # GRAMMAR (10 kural x 5 ornek)
    # ════════════════════════════════════════
    "grammar": [
        # 1. I am / You are / He is
        {"title": "I am / You are / He is", "rule_tr": "I am + sifat | You are + sifat | He/She is + sifat", "examples": [
            {"en": "I am happy.", "de": "Ich bin glucklich.", "fr": "Je suis content.", "it": "Sono felice.", "es": "Estoy feliz.", "tr": "Ben mutluyum."},
            {"en": "You are tall.", "de": "Du bist gross.", "fr": "Tu es grand.", "it": "Sei alto.", "es": "Eres alto.", "tr": "Sen uzunsun."},
            {"en": "He is a student.", "de": "Er ist ein Schuler.", "fr": "Il est un eleve.", "it": "Lui e uno studente.", "es": "El es un estudiante.", "tr": "O bir ogrenci."},
            {"en": "She is my sister.", "de": "Sie ist meine Schwester.", "fr": "Elle est ma soeur.", "it": "Lei e mia sorella.", "es": "Ella es mi hermana.", "tr": "O benim kiz kardesim."},
            {"en": "We are friends.", "de": "Wir sind Freunde.", "fr": "Nous sommes amis.", "it": "Siamo amici.", "es": "Somos amigos.", "tr": "Biz arkadasiz."},
        ], "exercises": [
            {"prompt": "I ___ happy.", "answer": "am", "hint": "olmak (ben)"},
            {"prompt": "You ___ my friend.", "answer": "are", "hint": "olmak (sen)"},
            {"prompt": "She ___ a teacher.", "answer": "is", "hint": "olmak (o-kadin)"},
            {"prompt": "We ___ students.", "answer": "are", "hint": "olmak (biz)"},
            {"prompt": "He ___ tired.", "answer": "is", "hint": "olmak (o-erkek)"},
        ]},
        # 2. a / an
        {"title": "Articles: a / an", "rule_tr": "a + unsuz ile baslayan | an + unlu ile baslayan", "examples": [
            {"en": "This is a book.", "de": "Das ist ein Buch.", "fr": "C'est un livre.", "it": "Questo e un libro.", "es": "Esto es un libro.", "tr": "Bu bir kitap."},
            {"en": "This is an apple.", "de": "Das ist ein Apfel.", "fr": "C'est une pomme.", "it": "Questa e una mela.", "es": "Esto es una manzana.", "tr": "Bu bir elma."},
            {"en": "I see a dog.", "de": "Ich sehe einen Hund.", "fr": "Je vois un chien.", "it": "Vedo un cane.", "es": "Veo un perro.", "tr": "Bir kopek goruyorum."},
            {"en": "She has an umbrella.", "de": "Sie hat einen Regenschirm.", "fr": "Elle a un parapluie.", "it": "Lei ha un ombrello.", "es": "Ella tiene un paraguas.", "tr": "Onun bir semsiyesi var."},
            {"en": "There is a cat.", "de": "Da ist eine Katze.", "fr": "Il y a un chat.", "it": "C'e un gatto.", "es": "Hay un gato.", "tr": "Bir kedi var."},
        ], "exercises": [
            {"prompt": "This is ___ cat.", "answer": "a", "hint": "c unsuz"},
            {"prompt": "This is ___ elephant.", "answer": "an", "hint": "e unlu"},
            {"prompt": "This is ___ orange.", "answer": "an", "hint": "o unlu"},
            {"prompt": "I have ___ pencil.", "answer": "a", "hint": "p unsuz"},
            {"prompt": "She is ___ artist.", "answer": "an", "hint": "a unlu"},
        ]},
        # 3. I have / He has
        {"title": "I have / He has", "rule_tr": "I/You/We/They have | He/She/It has", "examples": [
            {"en": "I have a dog.", "de": "Ich habe einen Hund.", "fr": "J'ai un chien.", "it": "Ho un cane.", "es": "Tengo un perro.", "tr": "Bir kopegim var."},
            {"en": "He has a cat.", "de": "Er hat eine Katze.", "fr": "Il a un chat.", "it": "Lui ha un gatto.", "es": "El tiene un gato.", "tr": "Onun bir kedisi var."},
            {"en": "We have two books.", "de": "Wir haben zwei Bucher.", "fr": "Nous avons deux livres.", "it": "Abbiamo due libri.", "es": "Tenemos dos libros.", "tr": "Iki kitabimiz var."},
            {"en": "She has blue eyes.", "de": "Sie hat blaue Augen.", "fr": "Elle a les yeux bleus.", "it": "Lei ha gli occhi blu.", "es": "Ella tiene ojos azules.", "tr": "Onun mavi gozleri var."},
            {"en": "They have a garden.", "de": "Sie haben einen Garten.", "fr": "Ils ont un jardin.", "it": "Loro hanno un giardino.", "es": "Ellos tienen un jardin.", "tr": "Onlarin bir bahcesi var."},
        ], "exercises": [
            {"prompt": "I ___ a pencil.", "answer": "have", "hint": "sahip olmak (ben)"},
            {"prompt": "She ___ a red dress.", "answer": "has", "hint": "sahip olmak (o-kadin)"},
            {"prompt": "We ___ three cats.", "answer": "have", "hint": "sahip olmak (biz)"},
            {"prompt": "He ___ a bicycle.", "answer": "has", "hint": "sahip olmak (o-erkek)"},
            {"prompt": "They ___ many friends.", "answer": "have", "hint": "sahip olmak (onlar)"},
        ]},
        # 4. I like / I don't like
        {"title": "I like / I don't like", "rule_tr": "I like + isim/fiil | I don't like + isim/fiil", "examples": [
            {"en": "I like cats.", "de": "Ich mag Katzen.", "fr": "J'aime les chats.", "it": "Mi piacciono i gatti.", "es": "Me gustan los gatos.", "tr": "Kedileri severim."},
            {"en": "I don't like spiders.", "de": "Ich mag keine Spinnen.", "fr": "Je n'aime pas les araignees.", "it": "Non mi piacciono i ragni.", "es": "No me gustan las aranas.", "tr": "Orumcekleri sevmem."},
            {"en": "She likes drawing.", "de": "Sie mag Zeichnen.", "fr": "Elle aime dessiner.", "it": "A lei piace disegnare.", "es": "A ella le gusta dibujar.", "tr": "Resim yapmayi sever."},
            {"en": "He likes football.", "de": "Er mag Fussball.", "fr": "Il aime le football.", "it": "A lui piace il calcio.", "es": "A el le gusta el futbol.", "tr": "Futbolu sever."},
            {"en": "We like ice cream.", "de": "Wir mogen Eiscreme.", "fr": "Nous aimons la glace.", "it": "Ci piace il gelato.", "es": "Nos gusta el helado.", "tr": "Dondurmayı severiz."},
        ], "exercises": [
            {"prompt": "I ___ cats. (sevmek)", "answer": "like", "hint": "sevmek"},
            {"prompt": "I don't ___ snakes.", "answer": "like", "hint": "sevmek (olumsuz)"},
            {"prompt": "She ___ reading.", "answer": "likes", "hint": "sevmek (o-kadin)"},
            {"prompt": "He ___ swimming.", "answer": "likes", "hint": "sevmek (o-erkek)"},
            {"prompt": "We ___ pizza.", "answer": "like", "hint": "sevmek (biz)"},
        ]},
        # 5. There is / There are
        {"title": "There is / There are", "rule_tr": "There is + tekil | There are + cogul", "examples": [
            {"en": "There is a cat on the table.", "de": "Es gibt eine Katze auf dem Tisch.", "fr": "Il y a un chat sur la table.", "it": "C'e un gatto sul tavolo.", "es": "Hay un gato en la mesa.", "tr": "Masanin uzerinde bir kedi var."},
            {"en": "There are two birds in the tree.", "de": "Es gibt zwei Vogel im Baum.", "fr": "Il y a deux oiseaux dans l'arbre.", "it": "Ci sono due uccelli sull'albero.", "es": "Hay dos pajaros en el arbol.", "tr": "Agacta iki kus var."},
            {"en": "There is a book on the desk.", "de": "Es gibt ein Buch auf dem Schreibtisch.", "fr": "Il y a un livre sur le bureau.", "it": "C'e un libro sulla scrivania.", "es": "Hay un libro en el escritorio.", "tr": "Siranin uzerinde bir kitap var."},
            {"en": "There are three apples.", "de": "Es gibt drei Apfel.", "fr": "Il y a trois pommes.", "it": "Ci sono tre mele.", "es": "Hay tres manzanas.", "tr": "Uc elma var."},
            {"en": "There is a park near my house.", "de": "Es gibt einen Park in der Nahe meines Hauses.", "fr": "Il y a un parc pres de ma maison.", "it": "C'e un parco vicino a casa mia.", "es": "Hay un parque cerca de mi casa.", "tr": "Evimin yakininda bir park var."},
        ], "exercises": [
            {"prompt": "There ___ a cat. (tekil)", "answer": "is", "hint": "var (tekil)"},
            {"prompt": "There ___ two dogs. (cogul)", "answer": "are", "hint": "var (cogul)"},
            {"prompt": "There ___ a book on the table.", "answer": "is", "hint": "var (tekil)"},
            {"prompt": "There ___ five students.", "answer": "are", "hint": "var (cogul)"},
            {"prompt": "There ___ one teacher.", "answer": "is", "hint": "var (tekil)"},
        ]},
        # 6. Like + verb-ing [NEW]
        {"title": "Like + verb-ing", "rule_tr": "I like + fiil-ing (I like swimming)", "examples": [
            {"en": "I like swimming.", "de": "Ich schwimme gern.", "fr": "J'aime nager.", "it": "Mi piace nuotare.", "es": "Me gusta nadar.", "tr": "Yuzmeyi severim."},
            {"en": "She likes reading books.", "de": "Sie liest gern Bucher.", "fr": "Elle aime lire des livres.", "it": "A lei piace leggere libri.", "es": "A ella le gusta leer libros.", "tr": "Kitap okumayi sever."},
            {"en": "He likes playing football.", "de": "Er spielt gern Fussball.", "fr": "Il aime jouer au football.", "it": "A lui piace giocare a calcio.", "es": "A el le gusta jugar al futbol.", "tr": "Futbol oynamayi sever."},
            {"en": "We like singing songs.", "de": "Wir singen gern Lieder.", "fr": "Nous aimons chanter des chansons.", "it": "Ci piace cantare canzoni.", "es": "Nos gusta cantar canciones.", "tr": "Sarki soylemeyi severiz."},
            {"en": "They like drawing pictures.", "de": "Sie zeichnen gern Bilder.", "fr": "Ils aiment dessiner des images.", "it": "A loro piace disegnare.", "es": "A ellos les gusta dibujar.", "tr": "Resim cizmeyi severler."},
        ], "exercises": [
            {"prompt": "I like ___. (yuzmek)", "answer": "swimming", "hint": "swim + ing"},
            {"prompt": "She likes ___. (okumak)", "answer": "reading", "hint": "read + ing"},
            {"prompt": "He likes ___. (oynamak)", "answer": "playing", "hint": "play + ing"},
            {"prompt": "We like ___. (sarkı soyleme)", "answer": "singing", "hint": "sing + ing"},
            {"prompt": "They like ___. (dans etmek)", "answer": "dancing", "hint": "dance + ing"},
        ]},
        # 7. Prepositions of time [NEW]
        {"title": "Prepositions of time: at, on, in", "rule_tr": "at + saat | on + gun | in + ay/mevsim/yil", "examples": [
            {"en": "I wake up at seven o'clock.", "de": "Ich wache um sieben Uhr auf.", "fr": "Je me reveille a sept heures.", "it": "Mi sveglio alle sette.", "es": "Me despierto a las siete.", "tr": "Saat yedide uyaniyorum."},
            {"en": "I go to school on Monday.", "de": "Ich gehe am Montag in die Schule.", "fr": "Je vais a l'ecole le lundi.", "it": "Vado a scuola il lunedi.", "es": "Voy a la escuela el lunes.", "tr": "Pazartesi gunu okula gidiyorum."},
            {"en": "My birthday is in June.", "de": "Mein Geburtstag ist im Juni.", "fr": "Mon anniversaire est en juin.", "it": "Il mio compleanno e a giugno.", "es": "Mi cumpleanos es en junio.", "tr": "Dogum gunum haziranda."},
            {"en": "We play outside in summer.", "de": "Wir spielen im Sommer draussen.", "fr": "Nous jouons dehors en ete.", "it": "Giochiamo fuori in estate.", "es": "Jugamos afuera en verano.", "tr": "Yazin disarida oynariz."},
            {"en": "I eat lunch at twelve.", "de": "Ich esse um zwolf zu Mittag.", "fr": "Je dejeune a midi.", "it": "Pranzo alle dodici.", "es": "Almuerzo a las doce.", "tr": "Saat on ikide ogle yemegi yiyorum."},
        ], "exercises": [
            {"prompt": "I wake up ___ seven o'clock.", "answer": "at", "hint": "saat"},
            {"prompt": "We go to school ___ Monday.", "answer": "on", "hint": "gun"},
            {"prompt": "It is cold ___ winter.", "answer": "in", "hint": "mevsim"},
            {"prompt": "My birthday is ___ March.", "answer": "in", "hint": "ay"},
            {"prompt": "I go to bed ___ nine.", "answer": "at", "hint": "saat"},
        ]},
        # 8. Imperatives [NEW]
        {"title": "Imperatives / Emir Cumleleri", "rule_tr": "Fiil + ! (Open! Don't run!)", "examples": [
            {"en": "Open the door!", "de": "Offne die Tur!", "fr": "Ouvre la porte!", "it": "Apri la porta!", "es": "Abre la puerta!", "tr": "Kapiyi ac!"},
            {"en": "Close the window!", "de": "Schliess das Fenster!", "fr": "Ferme la fenetre!", "it": "Chiudi la finestra!", "es": "Cierra la ventana!", "tr": "Pencereyi kapat!"},
            {"en": "Don't run!", "de": "Lauf nicht!", "fr": "Ne cours pas!", "it": "Non correre!", "es": "No corras!", "tr": "Kosma!"},
            {"en": "Sit down, please!", "de": "Setz dich, bitte!", "fr": "Assieds-toi, s'il te plait!", "it": "Siediti, per favore!", "es": "Sientate, por favor!", "tr": "Otur, lutfen!"},
            {"en": "Don't touch that!", "de": "Fass das nicht an!", "fr": "Ne touche pas ca!", "it": "Non toccare quello!", "es": "No toques eso!", "tr": "Ona dokunma!"},
        ], "exercises": [
            {"prompt": "___ the door! (acmak)", "answer": "Open", "hint": "Acmak"},
            {"prompt": "___ the window! (kapatmak)", "answer": "Close", "hint": "Kapatmak"},
            {"prompt": "Don't ___! (kosmak)", "answer": "run", "hint": "Kosmak"},
            {"prompt": "___ down! (oturmak)", "answer": "Sit", "hint": "Oturmak"},
            {"prompt": "Don't ___ that! (dokunmak)", "answer": "touch", "hint": "Dokunmak"},
        ]},
        # 9. Adverbs of frequency [NEW]
        {"title": "Adverbs of frequency", "rule_tr": "always / usually / sometimes / never", "examples": [
            {"en": "I always brush my teeth.", "de": "Ich putze mir immer die Zahne.", "fr": "Je me brosse toujours les dents.", "it": "Mi lavo sempre i denti.", "es": "Siempre me cepillo los dientes.", "tr": "Her zaman dislerimi firçalarim."},
            {"en": "She usually walks to school.", "de": "Sie geht normalerweise zu Fuss zur Schule.", "fr": "Elle va habituellement a l'ecole a pied.", "it": "Di solito va a scuola a piedi.", "es": "Ella generalmente camina a la escuela.", "tr": "Genellikle okula yuruyerek gider."},
            {"en": "We sometimes go to the park.", "de": "Wir gehen manchmal in den Park.", "fr": "Nous allons parfois au parc.", "it": "A volte andiamo al parco.", "es": "A veces vamos al parque.", "tr": "Bazen parka gideriz."},
            {"en": "He never eats vegetables.", "de": "Er isst nie Gemuse.", "fr": "Il ne mange jamais de legumes.", "it": "Non mangia mai verdure.", "es": "El nunca come verduras.", "tr": "Hic sebze yemez."},
            {"en": "I often read books.", "de": "Ich lese oft Bucher.", "fr": "Je lis souvent des livres.", "it": "Leggo spesso libri.", "es": "A menudo leo libros.", "tr": "Sik sik kitap okurum."},
        ], "exercises": [
            {"prompt": "I ___ brush my teeth. (her zaman)", "answer": "always", "hint": "Her zaman"},
            {"prompt": "She ___ walks to school. (genellikle)", "answer": "usually", "hint": "Genellikle"},
            {"prompt": "We ___ go to the park. (bazen)", "answer": "sometimes", "hint": "Bazen"},
            {"prompt": "He ___ eats fish. (hicbir zaman)", "answer": "never", "hint": "Hicbir zaman"},
            {"prompt": "I ___ read books. (sik sik)", "answer": "often", "hint": "Sik sik"},
        ]},
        # 10. Object pronouns [NEW]
        {"title": "Object pronouns", "rule_tr": "me / you / him / her / it / us / them", "examples": [
            {"en": "Give me the book.", "de": "Gib mir das Buch.", "fr": "Donne-moi le livre.", "it": "Dammi il libro.", "es": "Dame el libro.", "tr": "Bana kitabi ver."},
            {"en": "I can see you.", "de": "Ich kann dich sehen.", "fr": "Je peux te voir.", "it": "Ti posso vedere.", "es": "Puedo verte.", "tr": "Seni gorebiliyorum."},
            {"en": "She likes him.", "de": "Sie mag ihn.", "fr": "Elle l'aime.", "it": "A lei piace lui.", "es": "A ella le gusta el.", "tr": "Onu sever. (erkek)"},
            {"en": "I love her.", "de": "Ich liebe sie.", "fr": "Je l'aime.", "it": "La amo.", "es": "La quiero.", "tr": "Onu seviyorum. (kadin)"},
            {"en": "Help us, please!", "de": "Hilf uns, bitte!", "fr": "Aide-nous, s'il te plait!", "it": "Aiutaci, per favore!", "es": "Ayudanos, por favor!", "tr": "Bize yardim et, lutfen!"},
        ], "exercises": [
            {"prompt": "Give ___ the ball. (bana)", "answer": "me", "hint": "Bana"},
            {"prompt": "I can see ___. (seni)", "answer": "you", "hint": "Seni"},
            {"prompt": "She likes ___. (onu-erkek)", "answer": "him", "hint": "Onu (erkek)"},
            {"prompt": "I love ___. (onu-kadin)", "answer": "her", "hint": "Onu (kadin)"},
            {"prompt": "Help ___! (bize)", "answer": "us", "hint": "Bize"},
        ]},
    ],
    # ════════════════════════════════════════
    # DIALOGUES (8 diyalog x 6-8 satir)
    # ════════════════════════════════════════
    "dialogues": [
        # 1. Sinifta
        {"title": "Sinifta", "lines": [
            {"speaker": "Teacher", "en": "Good morning, class!", "de": "Guten Morgen, Klasse!", "fr": "Bonjour, la classe!", "it": "Buongiorno, classe!", "es": "Buenos dias, clase!", "tr": "Gunaydin, sinif!"},
            {"speaker": "Students", "en": "Good morning, teacher!", "de": "Guten Morgen, Lehrer!", "fr": "Bonjour, professeur!", "it": "Buongiorno, insegnante!", "es": "Buenos dias, profesor!", "tr": "Gunaydin, ogretmen!"},
            {"speaker": "Teacher", "en": "Open your books, please.", "de": "Offnet bitte eure Bucher.", "fr": "Ouvrez vos livres, s'il vous plait.", "it": "Aprite i vostri libri, per favore.", "es": "Abran sus libros, por favor.", "tr": "Lutfen kitaplarinizi acin."},
            {"speaker": "Student", "en": "Which page, teacher?", "de": "Welche Seite, Lehrer?", "fr": "Quelle page, professeur?", "it": "Quale pagina, insegnante?", "es": "Que pagina, profesor?", "tr": "Hangi sayfa, ogretmen?"},
            {"speaker": "Teacher", "en": "Page ten.", "de": "Seite zehn.", "fr": "Page dix.", "it": "Pagina dieci.", "es": "Pagina diez.", "tr": "Sayfa on."},
            {"speaker": "Student", "en": "Can I ask a question?", "de": "Kann ich eine Frage stellen?", "fr": "Puis-je poser une question?", "it": "Posso fare una domanda?", "es": "Puedo hacer una pregunta?", "tr": "Bir soru sorabilir miyim?"},
            {"speaker": "Teacher", "en": "Of course! Go ahead.", "de": "Naturlich! Frag ruhig.", "fr": "Bien sur! Allez-y.", "it": "Certo! Prego.", "es": "Claro! Adelante.", "tr": "Tabii ki! Buyurun."},
        ]},
        # 2. Markette
        {"title": "Markette", "lines": [
            {"speaker": "Mother", "en": "We need some apples.", "de": "Wir brauchen ein paar Apfel.", "fr": "Nous avons besoin de pommes.", "it": "Abbiamo bisogno di mele.", "es": "Necesitamos manzanas.", "tr": "Biraz elmaya ihtiyacimiz var."},
            {"speaker": "Child", "en": "Can I have chocolate?", "de": "Kann ich Schokolade haben?", "fr": "Puis-je avoir du chocolat?", "it": "Posso avere del cioccolato?", "es": "Puedo tener chocolate?", "tr": "Cikolata alabilir miyim?"},
            {"speaker": "Mother", "en": "Yes, but only one.", "de": "Ja, aber nur eine.", "fr": "Oui, mais un seul.", "it": "Si, ma solo uno.", "es": "Si, pero solo uno.", "tr": "Evet, ama sadece bir tane."},
            {"speaker": "Child", "en": "Thank you, Mom!", "de": "Danke, Mama!", "fr": "Merci, Maman!", "it": "Grazie, Mamma!", "es": "Gracias, Mama!", "tr": "Tesekkurler, Anne!"},
            {"speaker": "Mother", "en": "How much is this?", "de": "Wie viel kostet das?", "fr": "Combien ca coute?", "it": "Quanto costa?", "es": "Cuanto cuesta?", "tr": "Bu ne kadar?"},
            {"speaker": "Seller", "en": "It is two lira.", "de": "Es kostet zwei Lira.", "fr": "C'est deux lira.", "it": "Costa due lire.", "es": "Son dos liras.", "tr": "Iki lira."},
            {"speaker": "Mother", "en": "Here you are.", "de": "Bitte schon.", "fr": "Voici.", "it": "Ecco a lei.", "es": "Aqui tiene.", "tr": "Buyurun."},
            {"speaker": "Seller", "en": "Thank you! Goodbye.", "de": "Danke! Auf Wiedersehen.", "fr": "Merci! Au revoir.", "it": "Grazie! Arrivederci.", "es": "Gracias! Adios.", "tr": "Tesekkurler! Hosca kalin."},
        ]},
        # 3. Parkta
        {"title": "Parkta", "lines": [
            {"speaker": "Ali", "en": "Let's go to the park!", "de": "Lass uns in den Park gehen!", "fr": "Allons au parc!", "it": "Andiamo al parco!", "es": "Vamos al parque!", "tr": "Parka gidelim!"},
            {"speaker": "Elif", "en": "Great idea! What can we do?", "de": "Tolle Idee! Was konnen wir machen?", "fr": "Bonne idee! Que peut-on faire?", "it": "Ottima idea! Cosa possiamo fare?", "es": "Buena idea! Que podemos hacer?", "tr": "Harika fikir! Ne yapabiliriz?"},
            {"speaker": "Ali", "en": "We can play football.", "de": "Wir konnen Fussball spielen.", "fr": "Nous pouvons jouer au football.", "it": "Possiamo giocare a calcio.", "es": "Podemos jugar al futbol.", "tr": "Futbol oynayabiliriz."},
            {"speaker": "Elif", "en": "I like football! Let's go.", "de": "Ich mag Fussball! Los geht's.", "fr": "J'aime le football! Allons-y.", "it": "Mi piace il calcio! Andiamo.", "es": "Me gusta el futbol! Vamos.", "tr": "Futbolu severim! Hadi gidelim."},
            {"speaker": "Ali", "en": "Look! There is a dog.", "de": "Schau! Da ist ein Hund.", "fr": "Regarde! Il y a un chien.", "it": "Guarda! C'e un cane.", "es": "Mira! Hay un perro.", "tr": "Bak! Bir kopek var."},
            {"speaker": "Elif", "en": "It is so cute! Can I pet it?", "de": "Es ist so suss! Darf ich es streicheln?", "fr": "Il est si mignon! Puis-je le caresser?", "it": "E cosi carino! Posso accarezzarlo?", "es": "Es tan lindo! Puedo acariciarlo?", "tr": "Cok tatli! Onu sevebilir miyim?"},
            {"speaker": "Ali", "en": "Yes, it looks friendly.", "de": "Ja, es sieht freundlich aus.", "fr": "Oui, il a l'air gentil.", "it": "Si, sembra amichevole.", "es": "Si, parece amigable.", "tr": "Evet, dost gorunuyor."},
        ]},
        # 4. Restoranda [NEW]
        {"title": "Restoranda", "lines": [
            {"speaker": "Waiter", "en": "Welcome! Here is the menu.", "de": "Willkommen! Hier ist die Speisekarte.", "fr": "Bienvenue! Voici le menu.", "it": "Benvenuti! Ecco il menu.", "es": "Bienvenidos! Aqui esta el menu.", "tr": "Hosgeldiniz! Buyurun menu."},
            {"speaker": "Father", "en": "Thank you. What do you want?", "de": "Danke. Was mochtest du?", "fr": "Merci. Qu'est-ce que tu veux?", "it": "Grazie. Cosa vuoi?", "es": "Gracias. Que quieres?", "tr": "Tesekkurler. Ne istersin?"},
            {"speaker": "Child", "en": "I want a hamburger, please.", "de": "Ich mochte einen Hamburger, bitte.", "fr": "Je veux un hamburger, s'il vous plait.", "it": "Voglio un hamburger, per favore.", "es": "Quiero una hamburguesa, por favor.", "tr": "Hamburger istiyorum, lutfen."},
            {"speaker": "Father", "en": "And I want pasta.", "de": "Und ich mochte Nudeln.", "fr": "Et moi, je veux des pates.", "it": "E io voglio la pasta.", "es": "Y yo quiero pasta.", "tr": "Ben de makarna istiyorum."},
            {"speaker": "Waiter", "en": "What would you like to drink?", "de": "Was mochten Sie trinken?", "fr": "Que voulez-vous boire?", "it": "Cosa volete bere?", "es": "Que les gustaria beber?", "tr": "Ne icmek istersiniz?"},
            {"speaker": "Child", "en": "Lemonade, please!", "de": "Limonade, bitte!", "fr": "Limonade, s'il vous plait!", "it": "Limonata, per favore!", "es": "Limonada, por favor!", "tr": "Limonata, lutfen!"},
            {"speaker": "Waiter", "en": "Coming right up!", "de": "Kommt sofort!", "fr": "Ca arrive tout de suite!", "it": "Arriva subito!", "es": "Enseguida!", "tr": "Hemen geliyor!"},
        ]},
        # 5. Hastanede [NEW]
        {"title": "Hastanede", "lines": [
            {"speaker": "Doctor", "en": "Hello! How are you feeling?", "de": "Hallo! Wie fuhlen Sie sich?", "fr": "Bonjour! Comment vous sentez-vous?", "it": "Ciao! Come ti senti?", "es": "Hola! Como te sientes?", "tr": "Merhaba! Kendinizi nasil hissediyorsunuz?"},
            {"speaker": "Child", "en": "I have a headache.", "de": "Ich habe Kopfschmerzen.", "fr": "J'ai mal a la tete.", "it": "Ho mal di testa.", "es": "Tengo dolor de cabeza.", "tr": "Basim agriyor."},
            {"speaker": "Doctor", "en": "Do you have a fever?", "de": "Haben Sie Fieber?", "fr": "Avez-vous de la fievre?", "it": "Hai la febbre?", "es": "Tienes fiebre?", "tr": "Atesin var mi?"},
            {"speaker": "Child", "en": "Yes, I feel hot.", "de": "Ja, mir ist heiss.", "fr": "Oui, j'ai chaud.", "it": "Si, mi sento caldo.", "es": "Si, siento calor.", "tr": "Evet, sicak hissediyorum."},
            {"speaker": "Doctor", "en": "Take this medicine.", "de": "Nehmen Sie diese Medizin.", "fr": "Prenez ce medicament.", "it": "Prendi questa medicina.", "es": "Toma esta medicina.", "tr": "Bu ilaci alin."},
            {"speaker": "Mother", "en": "Thank you, doctor.", "de": "Danke, Doktor.", "fr": "Merci, docteur.", "it": "Grazie, dottore.", "es": "Gracias, doctor.", "tr": "Tesekkurler, doktor."},
            {"speaker": "Doctor", "en": "Rest well and drink water!", "de": "Ruhen Sie sich aus und trinken Sie Wasser!", "fr": "Reposez-vous bien et buvez de l'eau!", "it": "Riposati bene e bevi acqua!", "es": "Descansa bien y bebe agua!", "tr": "Iyi dinlenin ve su icin!"},
        ]},
        # 6. Muzik Dersinde [NEW]
        {"title": "Muzik Dersinde", "lines": [
            {"speaker": "Teacher", "en": "Today we learn about instruments.", "de": "Heute lernen wir uber Instrumente.", "fr": "Aujourd'hui nous apprenons les instruments.", "it": "Oggi impariamo gli strumenti.", "es": "Hoy aprendemos sobre instrumentos.", "tr": "Bugun muzik aletlerini ogreniyoruz."},
            {"speaker": "Student A", "en": "I can play the piano!", "de": "Ich kann Klavier spielen!", "fr": "Je sais jouer du piano!", "it": "So suonare il pianoforte!", "es": "Se tocar el piano!", "tr": "Piyano calabiliyorum!"},
            {"speaker": "Student B", "en": "I like the guitar.", "de": "Ich mag die Gitarre.", "fr": "J'aime la guitare.", "it": "Mi piace la chitarra.", "es": "Me gusta la guitarra.", "tr": "Gitari seviyorum."},
            {"speaker": "Teacher", "en": "Very good! What about the violin?", "de": "Sehr gut! Was ist mit der Geige?", "fr": "Tres bien! Et le violon?", "it": "Molto bene! E il violino?", "es": "Muy bien! Y el violin?", "tr": "Cok guzel! Peki keman?"},
            {"speaker": "Student A", "en": "The violin is beautiful.", "de": "Die Geige ist schon.", "fr": "Le violon est beau.", "it": "Il violino e bello.", "es": "El violin es hermoso.", "tr": "Keman cok guzel."},
            {"speaker": "Teacher", "en": "Let's sing a song together!", "de": "Lasst uns zusammen ein Lied singen!", "fr": "Chantons une chanson ensemble!", "it": "Cantiamo una canzone insieme!", "es": "Cantemos una cancion juntos!", "tr": "Hep birlikte bir sarki soyleyelim!"},
        ]},
        # 7. Otobuste [NEW]
        {"title": "Otobuste", "lines": [
            {"speaker": "A", "en": "Excuse me, does this bus go to school?", "de": "Entschuldigung, fahrt dieser Bus zur Schule?", "fr": "Excusez-moi, ce bus va a l'ecole?", "it": "Scusi, questo autobus va a scuola?", "es": "Disculpe, este autobus va a la escuela?", "tr": "Afedersiniz, bu otobus okula gidiyor mu?"},
            {"speaker": "Driver", "en": "Yes, it does. Please sit down.", "de": "Ja. Bitte setzen Sie sich.", "fr": "Oui. Asseyez-vous, s'il vous plait.", "it": "Si. Si sieda, per favore.", "es": "Si. Sientese, por favor.", "tr": "Evet, gidiyor. Lutfen oturun."},
            {"speaker": "A", "en": "Thank you! How many stops?", "de": "Danke! Wie viele Haltestellen?", "fr": "Merci! Combien d'arrets?", "it": "Grazie! Quante fermate?", "es": "Gracias! Cuantas paradas?", "tr": "Tesekkurler! Kac durak?"},
            {"speaker": "Driver", "en": "Three stops.", "de": "Drei Haltestellen.", "fr": "Trois arrets.", "it": "Tre fermate.", "es": "Tres paradas.", "tr": "Uc durak."},
            {"speaker": "A", "en": "Is this my stop?", "de": "Ist das meine Haltestelle?", "fr": "C'est mon arret?", "it": "E la mia fermata?", "es": "Es mi parada?", "tr": "Burada mi inecegim?"},
            {"speaker": "Driver", "en": "Yes, this is your stop. Goodbye!", "de": "Ja, das ist Ihre Haltestelle. Auf Wiedersehen!", "fr": "Oui, c'est votre arret. Au revoir!", "it": "Si, e la sua fermata. Arrivederci!", "es": "Si, es su parada. Adios!", "tr": "Evet, burada inin. Hosca kalin!"},
        ]},
        # 8. Spor Gunu [NEW]
        {"title": "Spor Gunu", "lines": [
            {"speaker": "Teacher", "en": "Today is sports day!", "de": "Heute ist Sporttag!", "fr": "Aujourd'hui c'est le jour du sport!", "it": "Oggi e la giornata dello sport!", "es": "Hoy es dia de deportes!", "tr": "Bugun spor gunu!"},
            {"speaker": "Ali", "en": "I want to play basketball.", "de": "Ich will Basketball spielen.", "fr": "Je veux jouer au basket.", "it": "Voglio giocare a pallacanestro.", "es": "Quiero jugar al baloncesto.", "tr": "Basketbol oynamak istiyorum."},
            {"speaker": "Elif", "en": "I like running. Can I run?", "de": "Ich laufe gern. Kann ich laufen?", "fr": "J'aime courir. Puis-je courir?", "it": "Mi piace correre. Posso correre?", "es": "Me gusta correr. Puedo correr?", "tr": "Kosmayi seviyorum. Kosabilir miyim?"},
            {"speaker": "Teacher", "en": "Of course! Everyone can choose.", "de": "Naturlich! Jeder kann wahlen.", "fr": "Bien sur! Chacun peut choisir.", "it": "Certo! Ognuno puo scegliere.", "es": "Claro! Cada uno puede elegir.", "tr": "Tabii ki! Herkes secebilir."},
            {"speaker": "Ali", "en": "I scored a goal!", "de": "Ich habe ein Tor geschossen!", "fr": "J'ai marque un but!", "it": "Ho segnato un gol!", "es": "Marque un gol!", "tr": "Gol attim!"},
            {"speaker": "Elif", "en": "I won the race!", "de": "Ich habe das Rennen gewonnen!", "fr": "J'ai gagne la course!", "it": "Ho vinto la corsa!", "es": "Gane la carrera!", "tr": "Yarisi kazandim!"},
            {"speaker": "Teacher", "en": "Well done, everyone! Great job!", "de": "Gut gemacht, alle! Tolle Arbeit!", "fr": "Bravo a tous! Bon travail!", "it": "Bravi tutti! Ottimo lavoro!", "es": "Bien hecho, todos! Buen trabajo!", "tr": "Aferin herkese! Harika is!"},
        ]},
    ],
    # ════════════════════════════════════════
    # READING (5 passage x 3 soru)
    # ════════════════════════════════════════
    "reading": [
        {
            "title": "My School",
            "text": {
                "en": "I go to school every day. My school is big. I have many friends. My teacher is kind. I like reading and drawing. My favorite subject is art. There are twenty students in my class. We have a big playground.",
                "de": "Ich gehe jeden Tag in die Schule. Meine Schule ist gross. Ich habe viele Freunde. Mein Lehrer ist nett. Ich lese und zeichne gern. Mein Lieblingsfach ist Kunst. Es gibt zwanzig Schuler in meiner Klasse. Wir haben einen grossen Spielplatz.",
                "fr": "Je vais a l'ecole tous les jours. Mon ecole est grande. J'ai beaucoup d'amis. Mon professeur est gentil. J'aime lire et dessiner. Ma matiere preferee est l'art. Il y a vingt eleves dans ma classe. Nous avons une grande cour de recreation.",
                "it": "Vado a scuola ogni giorno. La mia scuola e grande. Ho molti amici. Il mio insegnante e gentile. Mi piace leggere e disegnare. La mia materia preferita e l'arte. Ci sono venti studenti nella mia classe. Abbiamo un grande parco giochi.",
                "es": "Voy a la escuela todos los dias. Mi escuela es grande. Tengo muchos amigos. Mi profesor es amable. Me gusta leer y dibujar. Mi materia favorita es el arte. Hay veinte estudiantes en mi clase. Tenemos un gran patio de recreo.",
                "tr": "Her gun okula giderim. Okulum buyuk. Bircok arkadasim var. Ogretmenim iyi. Okumak ve resim yapmak seviyorum. En sevdigim ders resim. Sinifimda yirmi ogrenci var. Buyuk bir oyun bahcemiz var.",
            },
            "questions": [
                {"q_tr": "Okul nasil?", "options": ["Kucuk", "Buyuk", "Eski"], "answer": 1},
                {"q_tr": "En sevdigi ders ne?", "options": ["Matematik", "Muzik", "Resim"], "answer": 2},
                {"q_tr": "Sinifta kac ogrenci var?", "options": ["10", "15", "20"], "answer": 2},
            ],
        },
        {
            "title": "My Hobbies",
            "text": {
                "en": "My name is Cem. I am seven years old. I like many things. I like drawing pictures. I like playing football with my friends. I also like reading books. On Saturday, I go to the park. I don't like rainy days because I can't play outside.",
                "de": "Ich heisse Cem. Ich bin sieben Jahre alt. Ich mag viele Dinge. Ich zeichne gern Bilder. Ich spiele gern Fussball mit meinen Freunden. Ich lese auch gern Bucher. Am Samstag gehe ich in den Park. Ich mag keine Regentage, weil ich nicht draussen spielen kann.",
                "fr": "Je m'appelle Cem. J'ai sept ans. J'aime beaucoup de choses. J'aime dessiner des images. J'aime jouer au football avec mes amis. J'aime aussi lire des livres. Le samedi, je vais au parc. Je n'aime pas les jours de pluie parce que je ne peux pas jouer dehors.",
                "it": "Mi chiamo Cem. Ho sette anni. Mi piacciono molte cose. Mi piace disegnare. Mi piace giocare a calcio con i miei amici. Mi piace anche leggere libri. Il sabato vado al parco. Non mi piacciono i giorni di pioggia perche non posso giocare fuori.",
                "es": "Me llamo Cem. Tengo siete anos. Me gustan muchas cosas. Me gusta dibujar. Me gusta jugar al futbol con mis amigos. Tambien me gusta leer libros. El sabado voy al parque. No me gustan los dias de lluvia porque no puedo jugar afuera.",
                "tr": "Benim adim Cem. Yedi yasindayim. Bircok seyi severim. Resim cizmeyi severim. Arkadaslarimla futbol oynamayi severim. Kitap okumayi da severim. Cumartesi gunu parka giderim. Yagmurlu gunleri sevmem cunku disarida oynayamam.",
            },
            "questions": [
                {"q_tr": "Cem kac yasinda?", "options": ["6", "7", "8"], "answer": 1},
                {"q_tr": "Cumartesi nereye gidiyor?", "options": ["Okula", "Parka", "Markete"], "answer": 1},
                {"q_tr": "Neden yagmurlu gunleri sevmiyor?", "options": ["Uykusu geliyor", "Disarida oynayamiyor", "Evi seviyor"], "answer": 1},
            ],
        },
        # 3. My Best Friend [NEW]
        {
            "title": "My Best Friend",
            "text": {
                "en": "My best friend is Zeynep. She is eight years old. She has brown hair and green eyes. She likes swimming and singing. We go to the same school. We always sit together in class. She is very kind and funny. I am happy because she is my friend.",
                "de": "Meine beste Freundin ist Zeynep. Sie ist acht Jahre alt. Sie hat braune Haare und grune Augen. Sie schwimmt und singt gern. Wir gehen in die gleiche Schule. Wir sitzen immer zusammen im Unterricht. Sie ist sehr nett und lustig. Ich bin froh, dass sie meine Freundin ist.",
                "fr": "Ma meilleure amie est Zeynep. Elle a huit ans. Elle a les cheveux bruns et les yeux verts. Elle aime nager et chanter. Nous allons a la meme ecole. Nous nous asseyons toujours ensemble en classe. Elle est tres gentille et drole. Je suis content parce qu'elle est mon amie.",
                "it": "La mia migliore amica e Zeynep. Ha otto anni. Ha i capelli marroni e gli occhi verdi. Le piace nuotare e cantare. Andiamo alla stessa scuola. Ci sediamo sempre insieme in classe. E molto gentile e divertente. Sono felice perche e la mia amica.",
                "es": "Mi mejor amiga es Zeynep. Tiene ocho anos. Tiene el cabello marron y los ojos verdes. Le gusta nadar y cantar. Vamos a la misma escuela. Siempre nos sentamos juntos en clase. Es muy amable y divertida. Estoy feliz porque es mi amiga.",
                "tr": "En iyi arkadasim Zeynep. Sekiz yasinda. Kahverengi saclari ve yesil gozleri var. Yuzmeyi ve sarki soylemeyi sever. Ayni okula gidiyoruz. Sinifta hep yan yana oturuyoruz. Cok iyi ve komik biri. Arkadasim oldugu icin mutluyum.",
            },
            "questions": [
                {"q_tr": "Zeynep kac yasinda?", "options": ["7", "8", "9"], "answer": 1},
                {"q_tr": "Zeynep ne yapmaktan hoslanir?", "options": ["Kosmak ve resim yapmak", "Yuzmek ve sarki soylemek", "Okumak ve yazmak"], "answer": 1},
                {"q_tr": "Zeynep nasil biri?", "options": ["Utangac ve sessiz", "Iyi ve komik", "Kizgin ve uzgun"], "answer": 1},
            ],
        },
        # 4. A Trip to the City [NEW]
        {
            "title": "A Trip to the City",
            "text": {
                "en": "Last Saturday, we went to the city. We took the bus. First, we went to the museum. Then, we had lunch at a restaurant. I ate a sandwich and drank lemonade. After lunch, we went to the cinema. The movie was very funny. It was a great day!",
                "de": "Letzten Samstag sind wir in die Stadt gefahren. Wir haben den Bus genommen. Zuerst sind wir ins Museum gegangen. Dann haben wir in einem Restaurant zu Mittag gegessen. Ich habe ein Sandwich gegessen und Limonade getrunken. Nach dem Mittagessen sind wir ins Kino gegangen. Der Film war sehr lustig. Es war ein toller Tag!",
                "fr": "Samedi dernier, nous sommes alles en ville. Nous avons pris le bus. D'abord, nous sommes alles au musee. Ensuite, nous avons dejeune au restaurant. J'ai mange un sandwich et bu de la limonade. Apres le dejeuner, nous sommes alles au cinema. Le film etait tres drole. C'etait une belle journee!",
                "it": "Sabato scorso siamo andati in citta. Abbiamo preso l'autobus. Prima siamo andati al museo. Poi abbiamo pranzato al ristorante. Ho mangiato un panino e bevuto limonata. Dopo pranzo siamo andati al cinema. Il film era molto divertente. E stata una bella giornata!",
                "es": "El sabado pasado fuimos a la ciudad. Tomamos el autobus. Primero fuimos al museo. Luego almorzamos en un restaurante. Comi un sandwich y bebi limonada. Despues del almuerzo fuimos al cine. La pelicula fue muy divertida. Fue un gran dia!",
                "tr": "Gecen cumartesi sehre gittik. Otobuse bindik. Once muzeye gittik. Sonra bir restoranda ogle yemegi yedik. Sandvic yedim ve limonata ictim. Ogle yemeginden sonra sinemaya gittik. Film cok komikti. Harika bir gundi!",
            },
            "questions": [
                {"q_tr": "Sehre nasil gittiler?", "options": ["Arabayla", "Otobusle", "Trenle"], "answer": 1},
                {"q_tr": "Restoranda ne yedi?", "options": ["Pizza", "Hamburger", "Sandvic"], "answer": 2},
                {"q_tr": "Sinemada film nasıldi?", "options": ["Uzucu", "Komik", "Sikici"], "answer": 1},
            ],
        },
        # 5. The Four Seasons [NEW]
        {
            "title": "The Four Seasons",
            "text": {
                "en": "There are four seasons in a year. In spring, flowers grow and birds sing. Summer is hot and sunny. We swim in the sea. In autumn, the leaves fall from the trees. They are yellow, orange, and red. Winter is cold and snowy. We make snowmen. I like all the seasons!",
                "de": "Es gibt vier Jahreszeiten im Jahr. Im Fruhling wachsen Blumen und Vogel singen. Der Sommer ist heiss und sonnig. Wir schwimmen im Meer. Im Herbst fallen die Blatter von den Baumen. Sie sind gelb, orange und rot. Der Winter ist kalt und schneereich. Wir bauen Schneemanner. Ich mag alle Jahreszeiten!",
                "fr": "Il y a quatre saisons dans l'annee. Au printemps, les fleurs poussent et les oiseaux chantent. L'ete est chaud et ensoleille. Nous nageons dans la mer. En automne, les feuilles tombent des arbres. Elles sont jaunes, orange et rouges. L'hiver est froid et neigeux. Nous faisons des bonhommes de neige. J'aime toutes les saisons!",
                "it": "Ci sono quattro stagioni in un anno. In primavera i fiori crescono e gli uccelli cantano. L'estate e calda e soleggiata. Nuotiamo nel mare. In autunno le foglie cadono dagli alberi. Sono gialle, arancioni e rosse. L'inverno e freddo e nevoso. Facciamo pupazzi di neve. Mi piacciono tutte le stagioni!",
                "es": "Hay cuatro estaciones en un ano. En primavera, las flores crecen y los pajaros cantan. El verano es caliente y soleado. Nadamos en el mar. En otono, las hojas caen de los arboles. Son amarillas, naranjas y rojas. El invierno es frio y nevado. Hacemos municos de nieve. Me gustan todas las estaciones!",
                "tr": "Bir yilda dort mevsim var. Ilkbaharda cicekler acar ve kuslar oter. Yaz sicak ve guneslidir. Denizde yuzeriz. Sonbaharda yapraklar agaclardan duser. Sari, turuncu ve kirmizidir. Kis soguk ve karlidir. Kardan adam yapariz. Tum mevsimleri severim!",
            },
            "questions": [
                {"q_tr": "Ilkbaharda ne olur?", "options": ["Kar yagar", "Cicekler acar", "Yapraklar duser"], "answer": 1},
                {"q_tr": "Yazin ne yaparlar?", "options": ["Kardan adam yaparlar", "Denizde yuzerler", "Yaprak toplarlar"], "answer": 1},
                {"q_tr": "Sonbaharda yapraklar ne renk olur?", "options": ["Yesil ve mavi", "Sari, turuncu ve kirmizi", "Beyaz ve gri"], "answer": 1},
            ],
        },
    ],
    # ════════════════════════════════════════
    # QUIZ (30 soru)
    # ════════════════════════════════════════
    "quiz": [
        # Original 15
        {"type": "mc", "q_tr": "'Pencil' Turkcede ne demek?", "options": ["Kitap", "Kalem", "Silgi", "Cetvel"], "answer": 1},
        {"type": "tf", "q_tr": "'I am' = 'Ben ...im/im' dogru mu?", "answer": True},
        {"type": "mc", "q_tr": "'Auge' Almancada ne demek?", "options": ["Kulak", "Burun", "Goz", "Agiz"], "answer": 2},
        {"type": "mc", "q_tr": "'Chaussures' Fransizca ne demek?", "options": ["Gomlek", "Sapka", "Elbise", "Ayakkabi"], "answer": 3},
        {"type": "tf", "q_tr": "'an' unlu harfle baslayan kelimelerden once gelir.", "answer": True},
        {"type": "mc", "q_tr": "'Testa' Italyanca ne demek?", "options": ["El", "Bas", "Ayak", "Kol"], "answer": 1},
        {"type": "mc", "q_tr": "'Zapatos' Ispanyolca ne demek?", "options": ["Corap", "Mont", "Ayakkabi", "Sapka"], "answer": 2},
        {"type": "tf", "q_tr": "'He is' = 'O (erkek) ...dir' dogru mu?", "answer": True},
        {"type": "mc", "q_tr": "'Stuhl' Almancada ne demek?", "options": ["Masa", "Sandalye", "Sira", "Kitap"], "answer": 1},
        {"type": "mc", "q_tr": "'a' mi 'an' mi: ___ umbrella?", "options": ["a", "an"], "answer": 1},
        {"type": "fill", "q_tr": "'Doktor' Ingilizcede ___ demek.", "answer": "Doctor"},
        {"type": "mc", "q_tr": "'Lundi' Fransizca hangi gun?", "options": ["Sali", "Pazartesi", "Carsamba", "Cuma"], "answer": 1},
        {"type": "tf", "q_tr": "'There are' cogul isimlerle kullanilir.", "answer": True},
        {"type": "mc", "q_tr": "'Feliz' Ispanyolca ne demek?", "options": ["Uzgun", "Kizgin", "Mutlu", "Yorgun"], "answer": 2},
        {"type": "mc", "q_tr": "'She has' ne demek?", "options": ["Onun var (kadin)", "Ben var", "Sen var", "Biz var"], "answer": 0},
        # New 15
        {"type": "mc", "q_tr": "'Keyboard' Turkcede ne demek?", "options": ["Fare", "Ekran", "Klavye", "Kamera"], "answer": 2},
        {"type": "tf", "q_tr": "'Klavier' Almancada 'piyano' demek.", "answer": True},
        {"type": "mc", "q_tr": "'Turquie' Fransizca hangi ulke?", "options": ["Almanya", "Fransa", "Turkiye", "Italya"], "answer": 2},
        {"type": "mc", "q_tr": "'Deutsch' Almancada ne demek?", "options": ["Ingilizce", "Fransizca", "Almanca", "Ispanyolca"], "answer": 2},
        {"type": "fill", "q_tr": "'Garson' Ingilizcede ___ demek.", "answer": "Waiter"},
        {"type": "mc", "q_tr": "'Autobus' hangi dillerde 'otobus' demek?", "options": ["Almanca ve Italyanca", "Fransizca ve Ispanyolca", "Italyanca ve Ispanyolca", "Almanca ve Fransizca"], "answer": 2},
        {"type": "tf", "q_tr": "'I like swimming' = 'Yuzmeyi severim' dogru mu?", "answer": True},
        {"type": "mc", "q_tr": "'at' zaman edati ne icin kullanilir?", "options": ["Gunler", "Aylar", "Saatler", "Yillar"], "answer": 2},
        {"type": "mc", "q_tr": "'Medizin' Almancada ne demek?", "options": ["Doktor", "Hastane", "Ilac", "Hemsire"], "answer": 2},
        {"type": "tf", "q_tr": "'Don't run!' bir emir cumlesidir.", "answer": True},
        {"type": "mc", "q_tr": "'always' Turkcede ne demek?", "options": ["Bazen", "Hicbir zaman", "Her zaman", "Genellikle"], "answer": 2},
        {"type": "mc", "q_tr": "'Give me the book' cumslesinde 'me' ne anlama gelir?", "options": ["Ben", "Bana", "Benim", "Bende"], "answer": 1},
        {"type": "fill", "q_tr": "'Keman' Ingilizcede ___ demek.", "answer": "Violin"},
        {"type": "mc", "q_tr": "'Chitarra' Italyanca ne demek?", "options": ["Piyano", "Gitar", "Davul", "Flut"], "answer": 1},
        {"type": "tf", "q_tr": "'Primavera' Ispanyolcada 'ilkbahar' demek.", "answer": True},
    ],
}
