EXTRA_WORDS = [
    # ── technology (20) ──────────────────────────────────────────────────
    ("technology", "Bilgisayar", "Computer", "Kompyutır", "Computer", "Kompyutır", "Computer", "Kompyuter", "Computadora", "Komputadora", "Ordinateur", "Ordinatör"),
    ("technology", "İnternet", "Internet", "İntırnet", "Internet", "İntırnet", "Internet", "İnternet", "Internet", "İnternet", "Internet", "Enternet"),
    ("technology", "Telefon", "Telephone", "Telıfoun", "Telefon", "Telefon", "Telefono", "Telefono", "Teléfono", "Telefono", "Téléphone", "Telefon"),
    ("technology", "Ekran", "Screen", "Skriin", "Bildschirm", "Biltşirm", "Schermo", "Skermo", "Pantalla", "Pantaya", "Écran", "Ekran"),
    ("technology", "Yazıcı", "Printer", "Printır", "Drucker", "Drukır", "Stampante", "Stampante", "Impresora", "İmpresora", "Imprimante", "Enprimant"),
    ("technology", "Şifre", "Password", "Pasvörd", "Passwort", "Passvort", "Password", "Passvord", "Contraseña", "Kontrasenyo", "Mot de passe", "Mo dö pas"),
    ("technology", "Uygulama", "Application", "Eplikeyşın", "Anwendung", "Anvendung", "Applicazione", "Applikatsyone", "Aplicación", "Aplikasyon", "Application", "Aplikasyon"),
    ("technology", "Dosya", "File", "Fayl", "Datei", "Datay", "File", "Fayl", "Archivo", "Arçivo", "Fichier", "Fişiye"),
    ("technology", "E-posta", "Email", "İmeyl", "E-Mail", "İmeyl", "Email", "İmeyl", "Correo electrónico", "Korreo elektroniko", "Courriel", "Kuriyel"),
    ("technology", "Web sitesi", "Website", "Vebsayt", "Webseite", "Vebzaytı", "Sito web", "Sito veb", "Sitio web", "Sitiyo veb", "Site web", "Sit veb"),
    ("technology", "İndirmek", "To download", "Tu daunloud", "Herunterladen", "Heruntırladın", "Scaricare", "Skarikare", "Descargar", "Deskargar", "Télécharger", "Teleşarje"),
    ("technology", "Yüklemek", "To upload", "Tu aploud", "Hochladen", "Hohladın", "Caricare", "Karikare", "Subir", "Subir", "Téléverser", "Televörse"),
    ("technology", "Güncelleme", "Update", "Apdeyt", "Aktualisierung", "Aktualizirung", "Aggiornamento", "Accornamento", "Actualización", "Aktualisasyon", "Mise à jour", "Miz a jur"),
    ("technology", "Veri", "Data", "Deytı", "Daten", "Datın", "Dati", "Dati", "Datos", "Datos", "Données", "Done"),
    ("technology", "Ağ", "Network", "Netvörk", "Netzwerk", "Netsverk", "Rete", "Rete", "Red", "Red", "Réseau", "Rezo"),
    ("technology", "Bulut", "Cloud", "Klaud", "Cloud", "Klaud", "Cloud", "Klaud", "Nube", "Nube", "Cloud", "Klaud"),
    ("technology", "Yazılım", "Software", "Softver", "Software", "Zoftver", "Software", "Softver", "Software", "Softver", "Logiciel", "Lojisiyel"),
    ("technology", "Donanım", "Hardware", "Hardver", "Hardware", "Hardver", "Hardware", "Ardver", "Hardware", "Ardver", "Matériel", "Materiyel"),
    ("technology", "Fare", "Mouse", "Maus", "Maus", "Maus", "Mouse", "Maus", "Ratón", "Raton", "Souris", "Suri"),
    ("technology", "Klavye", "Keyboard", "Kiibord", "Tastatur", "Tastatır", "Tastiera", "Tastiyera", "Teclado", "Teklado", "Clavier", "Klaviye"),

    # ── sports (15) ──────────────────────────────────────────────────────
    ("sports", "Futbol", "Football", "Futbol", "Fußball", "Fusbal", "Calcio", "Kalço", "Fútbol", "Futbol", "Football", "Futbol"),
    ("sports", "Basketbol", "Basketball", "Basketbol", "Basketball", "Basketbal", "Pallacanestro", "Pallakanestro", "Baloncesto", "Balonsesto", "Basketball", "Basketbol"),
    ("sports", "Yüzme", "Swimming", "Sviming", "Schwimmen", "Şvimmın", "Nuoto", "Nuoto", "Natación", "Natasyon", "Natation", "Natasyon"),
    ("sports", "Koşu", "Running", "Raning", "Laufen", "Laufın", "Corsa", "Korsa", "Carrera", "Karrera", "Course", "Kurs"),
    ("sports", "Tenis", "Tennis", "Tenis", "Tennis", "Tennis", "Tennis", "Tennis", "Tenis", "Tenis", "Tennis", "Tenis"),
    ("sports", "Voleybol", "Volleyball", "Volibol", "Volleyball", "Voleybal", "Pallavolo", "Pallavolo", "Voleibol", "Boleybol", "Volleyball", "Voleybol"),
    ("sports", "Bisiklet", "Bicycle", "Baysikıl", "Fahrrad", "Farrat", "Bicicletta", "Biçikletta", "Bicicleta", "Bisikleta", "Vélo", "Velo"),
    ("sports", "Kayak", "Skiing", "Skiing", "Skifahren", "Şifarın", "Sci", "Şi", "Esquí", "Eski", "Ski", "Ski"),
    ("sports", "Boks", "Boxing", "Boksing", "Boxen", "Boksın", "Boxe", "Bokse", "Boxeo", "Bokseo", "Boxe", "Boks"),
    ("sports", "Jimnastik", "Gymnastics", "Cimnestiks", "Gymnastik", "Gümnastik", "Ginnastica", "Cinnastika", "Gimnasia", "Himnasiya", "Gymnastique", "Jimnastik"),
    ("sports", "Maç", "Match", "Meç", "Spiel", "Şpil", "Partita", "Partita", "Partido", "Partido", "Match", "Maç"),
    ("sports", "Skor", "Score", "Skor", "Punktestand", "Punktıştant", "Punteggio", "Puntecco", "Marcador", "Markador", "Score", "Skor"),
    ("sports", "Hakem", "Referee", "Refırii", "Schiedsrichter", "Şidsrihtır", "Arbitro", "Arbitro", "Árbitro", "Arbitro", "Arbitre", "Arbitr"),
    ("sports", "Antrenman", "Training", "Treyning", "Training", "Treyning", "Allenamento", "Allenamento", "Entrenamiento", "Entrenamiyento", "Entraînement", "Antrenman"),
    ("sports", "Stadyum", "Stadium", "Steydiyım", "Stadion", "Ştadiyon", "Stadio", "Stadiyo", "Estadio", "Estadiyo", "Stade", "Stad"),

    # ── music (15) ───────────────────────────────────────────────────────
    ("music", "Müzik", "Music", "Myuuzik", "Musik", "Muzik", "Musica", "Muzika", "Música", "Musika", "Musique", "Müzik"),
    ("music", "Şarkı", "Song", "Song", "Lied", "Lit", "Canzone", "Kantsone", "Canción", "Kansyon", "Chanson", "Şanson"),
    ("music", "Piyano", "Piano", "Piyano", "Klavier", "Klavir", "Pianoforte", "Piyanoforte", "Piano", "Piyano", "Piano", "Piyano"),
    ("music", "Gitar", "Guitar", "Gitar", "Gitarre", "Gitarrı", "Chitarra", "Kitarra", "Guitarra", "Gitarra", "Guitare", "Gitar"),
    ("music", "Keman", "Violin", "Vayılin", "Geige", "Gaygı", "Violino", "Viyolino", "Violín", "Biyolin", "Violon", "Viyolon"),
    ("music", "Davul", "Drum", "Dram", "Trommel", "Trommıl", "Tamburo", "Tamburo", "Tambor", "Tambor", "Tambour", "Tanbur"),
    ("music", "Konser", "Concert", "Konsırt", "Konzert", "Kontsert", "Concerto", "Konçerto", "Concierto", "Konsiyerto", "Concert", "Konser"),
    ("music", "Opera", "Opera", "Oprı", "Oper", "Opır", "Opera", "Opera", "Ópera", "Opera", "Opéra", "Opera"),
    ("music", "Dans", "Dance", "Dens", "Tanz", "Tants", "Danza", "Dantsa", "Danza", "Dansa", "Danse", "Dans"),
    ("music", "Melodi", "Melody", "Melıdi", "Melodie", "Melodi", "Melodia", "Melodiya", "Melodía", "Melodiya", "Mélodie", "Melodi"),
    ("music", "Ritim", "Rhythm", "Ridım", "Rhythmus", "Rütmus", "Ritmo", "Ritmo", "Ritmo", "Ritmo", "Rythme", "Ritm"),
    ("music", "Nota", "Note", "Nout", "Note", "Notı", "Nota", "Nota", "Nota", "Nota", "Note", "Not"),
    ("music", "Şarkıcı", "Singer", "Singır", "Sänger", "Zengır", "Cantante", "Kantante", "Cantante", "Kantante", "Chanteur", "Şantör"),
    ("music", "Orkestra", "Orchestra", "Orkıstrı", "Orchester", "Orkestır", "Orchestra", "Orkestra", "Orquesta", "Orkesta", "Orchestre", "Orkestr"),
    ("music", "Sahne", "Stage", "Steyc", "Bühne", "Bünı", "Palcoscenico", "Palkoşeniko", "Escenario", "Essenaryo", "Scène", "Sen"),

    # ── kitchen (15) ─────────────────────────────────────────────────────
    ("kitchen", "Tabak", "Plate", "Pleyt", "Teller", "Tellır", "Piatto", "Piyatto", "Plato", "Plato", "Assiette", "Asiyet"),
    ("kitchen", "Çatal", "Fork", "Fork", "Gabel", "Gabıl", "Forchetta", "Forketta", "Tenedor", "Tenedor", "Fourchette", "Furşet"),
    ("kitchen", "Bıçak", "Knife", "Nayf", "Messer", "Messır", "Coltello", "Koltello", "Cuchillo", "Kuçiyo", "Couteau", "Kuto"),
    ("kitchen", "Kaşık", "Spoon", "Spuun", "Löffel", "Löfıl", "Cucchiaio", "Kukkiyayo", "Cuchara", "Kuçara", "Cuillère", "Küiyer"),
    ("kitchen", "Bardak", "Glass", "Glas", "Glas", "Glas", "Bicchiere", "Bikkiyere", "Vaso", "Baso", "Verre", "Ver"),
    ("kitchen", "Tencere", "Pot", "Pot", "Topf", "Topf", "Pentola", "Pentola", "Olla", "Oya", "Casserole", "Kasrol"),
    ("kitchen", "Tava", "Pan", "Pen", "Pfanne", "Pfannı", "Padella", "Padella", "Sartén", "Sarten", "Poêle", "Pual"),
    ("kitchen", "Fırın", "Oven", "Avın", "Ofen", "Ofın", "Forno", "Forno", "Horno", "Orno", "Four", "Fur"),
    ("kitchen", "Ocak", "Stove", "Stouv", "Herd", "Hert", "Fornello", "Fornello", "Estufa", "Estufa", "Cuisinière", "Küiziniyer"),
    ("kitchen", "Bulaşık", "Dishes", "Dişız", "Geschirr", "Geşir", "Stoviglie", "Stovilye", "Vajilla", "Bahiya", "Vaisselle", "Vesel"),
    ("kitchen", "Peçete", "Napkin", "Nepkin", "Serviette", "Zerviyettı", "Tovagliolo", "Tovalyolo", "Servilleta", "Serviyeta", "Serviette", "Serviyet"),
    ("kitchen", "Tepsi", "Tray", "Trey", "Tablett", "Tablet", "Vassoio", "Vassoyyo", "Bandeja", "Bandeha", "Plateau", "Plato"),
    ("kitchen", "Şişe", "Bottle", "Botıl", "Flasche", "Flaşı", "Bottiglia", "Bottilya", "Botella", "Boteya", "Bouteille", "Butey"),
    ("kitchen", "Kavanoz", "Jar", "Car", "Glas", "Glas", "Barattolo", "Barattolo", "Tarro", "Tarro", "Bocal", "Bokal"),
    ("kitchen", "Süzgeç", "Strainer", "Streynır", "Sieb", "Zip", "Colino", "Kolino", "Colador", "Kolador", "Passoire", "Pasuar"),

    # ── office (15) ──────────────────────────────────────────────────────
    ("office", "Ofis", "Office", "Ofis", "Büro", "Büro", "Ufficio", "Uffiço", "Oficina", "Ofisina", "Bureau", "Büro"),
    ("office", "Toplantı", "Meeting", "Miiting", "Besprechung", "Beşprehung", "Riunione", "Riyunyone", "Reunión", "Reuniyon", "Réunion", "Reuinyon"),
    ("office", "Proje", "Project", "Procekt", "Projekt", "Proyekt", "Progetto", "Procetto", "Proyecto", "Proyekto", "Projet", "Proje"),
    ("office", "Rapor", "Report", "Ripört", "Bericht", "Beriht", "Rapporto", "Rapporto", "Informe", "İnforme", "Rapport", "Rapor"),
    ("office", "Sunum", "Presentation", "Prezenteyşın", "Präsentation", "Prezentatsyon", "Presentazione", "Prezentatsyone", "Presentación", "Presentasyon", "Présentation", "Prezantasyon"),
    ("office", "Patron", "Boss", "Bos", "Chef", "Şef", "Capo", "Kapo", "Jefe", "Hefe", "Patron", "Patron"),
    ("office", "Maaş", "Salary", "Selıri", "Gehalt", "Gehalt", "Stipendio", "Stipendiyo", "Salario", "Salaryo", "Salaire", "Saler"),
    ("office", "Sözleşme", "Contract", "Kontrekt", "Vertrag", "Fertrak", "Contratto", "Kontratto", "Contrato", "Kontrato", "Contrat", "Kontra"),
    ("office", "İzin", "Leave", "Liiv", "Urlaub", "Urlaup", "Permesso", "Permesso", "Permiso", "Permiso", "Congé", "Konje"),
    ("office", "Mesai", "Overtime", "Ouvırtaym", "Überstunden", "Übırştundın", "Straordinario", "Straordinaryo", "Horas extra", "Oras ekstra", "Heures supplémentaires", "Ör süplementer"),
    ("office", "Müdür", "Director", "Direktır", "Direktor", "Direktör", "Direttore", "Direttore", "Director", "Direktor", "Directeur", "Direktör"),
    ("office", "Sekreter", "Secretary", "Sekrıteri", "Sekretär", "Zekreter", "Segretario", "Segretaryo", "Secretario", "Sekretaryo", "Secrétaire", "Sökreter"),
    ("office", "Bütçe", "Budget", "Bacıt", "Budget", "Büdce", "Budget", "Bacet", "Presupuesto", "Presupuyesto", "Budget", "Büdje"),
    ("office", "Son teslim tarihi", "Deadline", "Dedlayn", "Frist", "Frist", "Scadenza", "Skadentsa", "Fecha límite", "Feça limite", "Date limite", "Dat limit"),
    ("office", "Hedef", "Goal", "Goul", "Ziel", "Tsil", "Obiettivo", "Obiyettivo", "Objetivo", "Obhetivo", "Objectif", "Objektif"),

    # ── colors (10) ──────────────────────────────────────────────────────
    ("colors", "Pembe", "Pink", "Pink", "Rosa", "Roza", "Rosa", "Roza", "Rosa", "Rosa", "Rose", "Roz"),
    ("colors", "Mor", "Purple", "Pörpıl", "Lila", "Lila", "Viola", "Viyola", "Morado", "Morado", "Violet", "Viole"),
    ("colors", "Turuncu", "Orange", "Orınc", "Orange", "Oranc", "Arancione", "Arançone", "Naranja", "Naranha", "Orange", "Oranç"),
    ("colors", "Gri", "Gray", "Grey", "Grau", "Grau", "Grigio", "Grico", "Gris", "Gris", "Gris", "Gri"),
    ("colors", "Bej", "Beige", "Beyj", "Beige", "Bej", "Beige", "Bej", "Beige", "Bey", "Beige", "Bej"),
    ("colors", "Lacivert", "Navy blue", "Neyvi blu", "Marineblau", "Marinıblau", "Blu navy", "Blu nevi", "Azul marino", "Asul marino", "Bleu marine", "Blö marin"),
    ("colors", "Bordo", "Burgundy", "Börgındi", "Burgunderrot", "Burgunderrot", "Bordeaux", "Bordo", "Burdeos", "Burdeos", "Bordeaux", "Bordo"),
    ("colors", "Turkuaz", "Turquoise", "Törkuaz", "Türkis", "Türkis", "Turchese", "Turkeze", "Turquesa", "Turkesa", "Turquoise", "Türkuaz"),
    ("colors", "Altın rengi", "Gold", "Gold", "Gold", "Golt", "Oro", "Oro", "Dorado", "Dorado", "Or", "Or"),
    ("colors", "Gümüş rengi", "Silver", "Silvır", "Silber", "Zilbır", "Argento", "Arcento", "Plateado", "Plateado", "Argent", "Arjan"),

    # ── emotions_extra (15) ──────────────────────────────────────────────
    ("emotions", "Gurur", "Pride", "Prayd", "Stolz", "Ştolts", "Orgoglio", "Orgolyo", "Orgullo", "Orguyo", "Fierté", "Fiyerte"),
    ("emotions", "Utanç", "Shame", "Şeym", "Scham", "Şam", "Vergogna", "Vergonya", "Vergüenza", "Bergüensa", "Honte", "Ont"),
    ("emotions", "Kıskançlık", "Jealousy", "Celısi", "Eifersucht", "Ayfırzuht", "Gelosia", "Celoziya", "Celos", "Selos", "Jalousie", "Jaluzi"),
    ("emotions", "Heyecan", "Excitement", "İksaytmınt", "Aufregung", "Aufregung", "Eccitazione", "Eççitatsyone", "Emoción", "Emosyon", "Excitation", "Eksitasyon"),
    ("emotions", "Endişe", "Anxiety", "Engzayıti", "Angst", "Angst", "Ansia", "Ansiya", "Ansiedad", "Ansiyedad", "Anxiété", "Anksiyete"),
    ("emotions", "Özlem", "Longing", "Longing", "Sehnsucht", "Zenzuht", "Nostalgia", "Nostaljiya", "Nostalgia", "Nostalhiya", "Nostalgie", "Nostalji"),
    ("emotions", "Umut", "Hope", "Houp", "Hoffnung", "Hofnung", "Speranza", "Sperantsa", "Esperanza", "Esperansa", "Espoir", "Espuar"),
    ("emotions", "Şaşkınlık", "Astonishment", "Estonişmınt", "Erstaunen", "Erştaunın", "Stupore", "Stupore", "Asombro", "Asombro", "Étonnement", "Etonman"),
    ("emotions", "Merak", "Curiosity", "Kyuriösiti", "Neugier", "Noygir", "Curiosità", "Kuriyozita", "Curiosidad", "Kuriyosidad", "Curiosité", "Küriyozite"),
    ("emotions", "Sabır", "Patience", "Peyşıns", "Geduld", "Gedult", "Pazienza", "Patsiyentsa", "Paciencia", "Pasiyensiya", "Patience", "Pasiyans"),
    ("emotions", "Öfke", "Rage", "Reyc", "Wut", "Vut", "Rabbia", "Rabbiya", "Rabia", "Rabiya", "Rage", "Raj"),
    ("emotions", "Minnet", "Gratitude", "Gretityud", "Dankbarkeit", "Dankbarkayt", "Gratitudine", "Gratitudine", "Gratitud", "Gratitud", "Gratitude", "Gratitüd"),
    ("emotions", "Huzur", "Peace", "Piis", "Frieden", "Fridın", "Pace", "Paçe", "Paz", "Pas", "Paix", "Pe"),
    ("emotions", "Neşe", "Joy", "Coy", "Freude", "Froydı", "Gioia", "Coya", "Alegría", "Alegriya", "Joie", "Jua"),
    ("emotions", "Korku", "Fear", "Fiır", "Furcht", "Furht", "Paura", "Paura", "Miedo", "Miyedo", "Peur", "Pör"),

    # ── food_extra (15) ──────────────────────────────────────────────────
    ("food", "Pilav", "Pilaf", "Pilaf", "Pilaw", "Pilav", "Pilaf", "Pilaf", "Arroz pilaf", "Arros pilaf", "Pilaf", "Pilaf"),
    ("food", "Pizza", "Pizza", "Piitsı", "Pizza", "Pittsa", "Pizza", "Pittsa", "Pizza", "Pitsa", "Pizza", "Pitsa"),
    ("food", "Hamburger", "Hamburger", "Hembögır", "Hamburger", "Hamburgır", "Hamburger", "Amburgır", "Hamburguesa", "Amburgesa", "Hamburger", "Anburgör"),
    ("food", "Sosis", "Sausage", "Sosıc", "Wurst", "Vurst", "Salsiccia", "Salsiçça", "Salchicha", "Salçiça", "Saucisse", "Sosis"),
    ("food", "Reçel", "Jam", "Cem", "Marmelade", "Marmeladı", "Marmellata", "Marmellata", "Mermelada", "Mermelada", "Confiture", "Konfitür"),
    ("food", "Biber", "Pepper", "Pepır", "Pfeffer", "Pfefır", "Pepe", "Pepe", "Pimienta", "Pimiyenta", "Poivre", "Puavr"),
    ("food", "Soğan", "Onion", "Anyın", "Zwiebel", "Tsvibıl", "Cipolla", "Çipolla", "Cebolla", "Seboya", "Oignon", "Onyon"),
    ("food", "Sarımsak", "Garlic", "Garlik", "Knoblauch", "Knoblauh", "Aglio", "Alyo", "Ajo", "Aho", "Ail", "Ay"),
    ("food", "Limon", "Lemon", "Lemın", "Zitrone", "Tsitronı", "Limone", "Limone", "Limón", "Limon", "Citron", "Sitron"),
    ("food", "Portakal", "Orange", "Orınc", "Orange", "Oranc", "Arancia", "Arança", "Naranja", "Naranha", "Orange", "Oranç"),
    ("food", "Üzüm", "Grape", "Greyp", "Traube", "Traubı", "Uva", "Uva", "Uva", "Uva", "Raisin", "Rezen"),
    ("food", "Elma", "Apple", "Epıl", "Apfel", "Apfıl", "Mela", "Mela", "Manzana", "Mansana", "Pomme", "Pom"),
    ("food", "Muz", "Banana", "Bınana", "Banane", "Bananı", "Banana", "Banana", "Plátano", "Platano", "Banane", "Banan"),
    ("food", "Çilek", "Strawberry", "Stroberi", "Erdbeere", "Ertberı", "Fragola", "Fragola", "Fresa", "Fresa", "Fraise", "Frez"),
    ("food", "Havuç", "Carrot", "Kerıt", "Karotte", "Karottı", "Carota", "Karota", "Zanahoria", "Sanaoriya", "Carotte", "Karot"),

    # ── verbs_extra (20) ─────────────────────────────────────────────────
    ("verbs", "Bulmak", "To find", "Tu faynd", "Finden", "Findın", "Trovare", "Trovare", "Encontrar", "Enkontrar", "Trouver", "Truve"),
    ("verbs", "Kaybetmek", "To lose", "Tu luuz", "Verlieren", "Ferlirın", "Perdere", "Perdere", "Perder", "Perder", "Perdre", "Perdr"),
    ("verbs", "Değiştirmek", "To change", "Tu çeync", "Ändern", "Endırn", "Cambiare", "Kambiyare", "Cambiar", "Kambiyar", "Changer", "Şanje"),
    ("verbs", "Başlamak", "To start", "Tu start", "Anfangen", "Anfangın", "Cominciare", "Kominçare", "Empezar", "Empesar", "Commencer", "Komanse"),
    ("verbs", "Bitirmek", "To finish", "Tu finiş", "Beenden", "Beendın", "Finire", "Finire", "Terminar", "Terminar", "Terminer", "Termine"),
    ("verbs", "Devam etmek", "To continue", "Tu kontinyuu", "Fortfahren", "Fortfarın", "Continuare", "Kontinuare", "Continuar", "Kontinuar", "Continuer", "Kontinüe"),
    ("verbs", "Denemek", "To try", "Tu tray", "Versuchen", "Ferzuhın", "Provare", "Provare", "Intentar", "İntentar", "Essayer", "Eseye"),
    ("verbs", "Tercih etmek", "To prefer", "Tu priför", "Bevorzugen", "Befortsugın", "Preferire", "Preferire", "Preferir", "Preferir", "Préférer", "Prefere"),
    ("verbs", "Kabul etmek", "To accept", "Tu eksept", "Akzeptieren", "Aktseptirın", "Accettare", "Aççettare", "Aceptar", "Aseptar", "Accepter", "Aksepte"),
    ("verbs", "Reddetmek", "To refuse", "Tu refyuuz", "Ablehnen", "Aplenın", "Rifiutare", "Rifyutare", "Rechazar", "Reçasar", "Refuser", "Röfüze"),
    ("verbs", "Planlamak", "To plan", "Tu plen", "Planen", "Planın", "Pianificare", "Piyanifikare", "Planificar", "Planifikar", "Planifier", "Planifiye"),
    ("verbs", "Organize etmek", "To organize", "Tu organayız", "Organisieren", "Organizirın", "Organizzare", "Organiddzare", "Organizar", "Organisar", "Organiser", "Organize"),
    ("verbs", "Kontrol etmek", "To check", "Tu çek", "Überprüfen", "Überprüfın", "Controllare", "Kontrollare", "Comprobar", "Komprobar", "Vérifier", "Verifiye"),
    ("verbs", "Tamir etmek", "To repair", "Tu riper", "Reparieren", "Reparirın", "Riparare", "Riparare", "Reparar", "Reparar", "Réparer", "Repare"),
    ("verbs", "Temizlemek", "To clean", "Tu kliin", "Reinigen", "Raynigın", "Pulire", "Pulire", "Limpiar", "Limpiyar", "Nettoyer", "Netuaye"),
    ("verbs", "Hazırlamak", "To prepare", "Tu priper", "Vorbereiten", "Forberaytın", "Preparare", "Preparare", "Preparar", "Preparar", "Préparer", "Prepare"),
    ("verbs", "Çizmek", "To draw", "Tu dro", "Zeichnen", "Tsayhnın", "Disegnare", "Dizenyare", "Dibujar", "Dibuhar", "Dessiner", "Desine"),
    ("verbs", "Satmak", "To sell", "Tu sel", "Verkaufen", "Ferkaufın", "Vendere", "Vendere", "Vender", "Bender", "Vendre", "Vandr"),
    ("verbs", "Satın almak", "To buy", "Tu bay", "Kaufen", "Kaufın", "Comprare", "Komprare", "Comprar", "Komprar", "Acheter", "Aşte"),
    ("verbs", "Ödemek", "To pay", "Tu pey", "Bezahlen", "Betsalın", "Pagare", "Pagare", "Pagar", "Pagar", "Payer", "Peye"),

    # ── nature_extra (15) ────────────────────────────────────────────────
    ("nature", "Okyanus", "Ocean", "Ouşın", "Ozean", "Otsean", "Oceano", "Oçeano", "Océano", "Oseano", "Océan", "Osean"),
    ("nature", "Volkan", "Volcano", "Volkeynou", "Vulkan", "Vulkan", "Vulcano", "Vulkano", "Volcán", "Bolkan", "Volcan", "Volkan"),
    ("nature", "Çöl", "Desert", "Dezırt", "Wüste", "Vüstı", "Deserto", "Dezerto", "Desierto", "Desiyerto", "Désert", "Dezer"),
    ("nature", "Tepe", "Hill", "Hil", "Hügel", "Hügıl", "Collina", "Kollina", "Colina", "Kolina", "Colline", "Kolin"),
    ("nature", "Kayalık", "Rock", "Rok", "Felsen", "Felsın", "Roccia", "Rocça", "Roca", "Roka", "Rocher", "Roşe"),
    ("nature", "Mağara", "Cave", "Keyv", "Höhle", "Hölı", "Grotta", "Grotta", "Cueva", "Kuyeva", "Grotte", "Grot"),
    ("nature", "Dalga", "Wave", "Veyv", "Welle", "Vellı", "Onda", "Onda", "Ola", "Ola", "Vague", "Vag"),
    ("nature", "Yarımada", "Peninsula", "Peninsulı", "Halbinsel", "Halbinzıl", "Penisola", "Penizola", "Península", "Peninsula", "Péninsule", "Penensül"),
    ("nature", "Toprak", "Soil", "Soyl", "Erde", "Erdı", "Suolo", "Suolo", "Suelo", "Suyelo", "Sol", "Sol"),
    ("nature", "Kaya", "Rock", "Rok", "Fels", "Fels", "Roccia", "Rocça", "Roca", "Roka", "Roche", "Roş"),
    ("nature", "Bitki", "Plant", "Plent", "Pflanze", "Pflantsı", "Pianta", "Piyanta", "Planta", "Planta", "Plante", "Plant"),
    ("nature", "Tohum", "Seed", "Siid", "Samen", "Zamın", "Seme", "Seme", "Semilla", "Semiya", "Graine", "Gren"),
    ("nature", "Kök", "Root", "Ruut", "Wurzel", "Vurtsıl", "Radice", "Radiçe", "Raíz", "Rais", "Racine", "Rasin"),
    ("nature", "Gökkuşağı", "Rainbow", "Reynbou", "Regenbogen", "Regınbogın", "Arcobaleno", "Arkobaleno", "Arcoíris", "Arkoiris", "Arc-en-ciel", "Ark an siyel"),
    ("nature", "Deprem", "Earthquake", "Örtkueyk", "Erdbeben", "Ertbebın", "Terremoto", "Terremoto", "Terremoto", "Terremoto", "Tremblement de terre", "Tranblöman dö ter"),

    # ── transport (15) ───────────────────────────────────────────────────
    ("transport", "Otobüs", "Bus", "Bas", "Bus", "Bus", "Autobus", "Autobus", "Autobús", "Autobus", "Bus", "Büs"),
    ("transport", "Tren", "Train", "Treyn", "Zug", "Tsug", "Treno", "Treno", "Tren", "Tren", "Train", "Tren"),
    ("transport", "Metro", "Subway", "Sabvey", "U-Bahn", "U-Ban", "Metropolitana", "Metropolitana", "Metro", "Metro", "Métro", "Metro"),
    ("transport", "Tramvay", "Tram", "Trem", "Straßenbahn", "Ştrasınban", "Tram", "Tram", "Tranvía", "Tranbiya", "Tramway", "Tramve"),
    ("transport", "Uçak", "Airplane", "Erpileyn", "Flugzeug", "Fluktsoyg", "Aereo", "Aereo", "Avión", "Abyon", "Avion", "Aviyon"),
    ("transport", "Gemi", "Ship", "Şip", "Schiff", "Şif", "Nave", "Nave", "Barco", "Barko", "Navire", "Navir"),
    ("transport", "Taksi", "Taxi", "Teksi", "Taxi", "Taksi", "Taxi", "Taksi", "Taxi", "Taksi", "Taxi", "Taksi"),
    ("transport", "Motosiklet", "Motorcycle", "Motırsaykıl", "Motorrad", "Motorrat", "Motocicletta", "Motoçikletta", "Motocicleta", "Motosikleta", "Moto", "Moto"),
    ("transport", "Araba", "Car", "Kar", "Auto", "Auto", "Macchina", "Makkina", "Coche", "Koçe", "Voiture", "Vuatür"),
    ("transport", "Kamyon", "Truck", "Trak", "Lastwagen", "Lastvagın", "Camion", "Kamiyon", "Camión", "Kamiyon", "Camion", "Kamiyon"),
    ("transport", "Helikopter", "Helicopter", "Helikoptır", "Hubschrauber", "Hubşraubır", "Elicottero", "Elikottero", "Helicóptero", "Elikoptero", "Hélicoptère", "Elikopter"),
    ("transport", "Feribot", "Ferry", "Feri", "Fähre", "Ferı", "Traghetto", "Tragetto", "Ferry", "Ferri", "Ferry", "Feri"),
    ("transport", "Liman", "Port", "Port", "Hafen", "Hafın", "Porto", "Porto", "Puerto", "Puyerto", "Port", "Por"),
    ("transport", "Otogar", "Bus station", "Bas steyşın", "Busbahnhof", "Busbanhof", "Autostazione", "Autostatsyone", "Estación de autobuses", "Estasyon de autobuses", "Gare routière", "Gar rutyer"),
    ("transport", "Bisiklet", "Bicycle", "Baysikıl", "Fahrrad", "Farrat", "Bicicletta", "Biçikletta", "Bicicleta", "Bisikleta", "Vélo", "Velo"),

    # ── materials (10) ───────────────────────────────────────────────────
    ("materials", "Ahşap", "Wood", "Vud", "Holz", "Holts", "Legno", "Lenyo", "Madera", "Madera", "Bois", "Bua"),
    ("materials", "Metal", "Metal", "Metıl", "Metall", "Metal", "Metallo", "Metallo", "Metal", "Metal", "Métal", "Metal"),
    ("materials", "Cam", "Glass", "Glas", "Glas", "Glas", "Vetro", "Vetro", "Vidrio", "Bidryo", "Verre", "Ver"),
    ("materials", "Plastik", "Plastic", "Plestik", "Plastik", "Plastik", "Plastica", "Plastika", "Plástico", "Plastiko", "Plastique", "Plastik"),
    ("materials", "Kumaş", "Fabric", "Febrik", "Stoff", "Ştof", "Tessuto", "Tessuto", "Tela", "Tela", "Tissu", "Tisü"),
    ("materials", "Deri", "Leather", "Ledır", "Leder", "Ledır", "Pelle", "Pelle", "Cuero", "Kuyero", "Cuir", "Küir"),
    ("materials", "Kağıt", "Paper", "Peypır", "Papier", "Papir", "Carta", "Karta", "Papel", "Papel", "Papier", "Papiye"),
    ("materials", "Taş", "Stone", "Stoun", "Stein", "Ştayn", "Pietra", "Piyetra", "Piedra", "Piyedra", "Pierre", "Piyer"),
    ("materials", "Kauçuk", "Rubber", "Rabır", "Gummi", "Gummi", "Gomma", "Gomma", "Caucho", "Kauço", "Caoutchouc", "Kauçu"),
    ("materials", "Seramik", "Ceramic", "Sıremik", "Keramik", "Keramik", "Ceramica", "Çeramika", "Cerámica", "Seramika", "Céramique", "Seramik"),

    # ── body_extra (10) ──────────────────────────────────────────────────
    ("body", "Saç", "Hair", "Her", "Haar", "Har", "Capelli", "Kapelli", "Cabello", "Kabeyo", "Cheveux", "Şövö"),
    ("body", "Kaş", "Eyebrow", "Aybrau", "Augenbraue", "Augınbrauı", "Sopracciglio", "Sopraççilyo", "Ceja", "Seha", "Sourcil", "Sursi"),
    ("body", "Kirpik", "Eyelash", "Aylaş", "Wimper", "Vimpır", "Ciglio", "Çilyo", "Pestaña", "Pestanya", "Cil", "Sil"),
    ("body", "Çene", "Chin", "Çin", "Kinn", "Kin", "Mento", "Mento", "Mentón", "Menton", "Menton", "Manton"),
    ("body", "Bilek", "Wrist", "Rist", "Handgelenk", "Hantgelenk", "Polso", "Polso", "Muñeca", "Munyeka", "Poignet", "Puanye"),
    ("body", "Dirsek", "Elbow", "Elbou", "Ellbogen", "Ellbogın", "Gomito", "Gomito", "Codo", "Kodo", "Coude", "Kud"),
    ("body", "Topuk", "Heel", "Hiil", "Ferse", "Ferzı", "Tallone", "Tallone", "Talón", "Talon", "Talon", "Talon"),
    ("body", "Parmak ucu", "Fingertip", "Fingırtip", "Fingerspitze", "Fingırşpitsı", "Punta del dito", "Punta del dito", "Punta del dedo", "Punta del dedo", "Bout du doigt", "Bu dü dua"),
    ("body", "Tırnak", "Nail", "Neyl", "Nagel", "Nagıl", "Unghia", "Ungiya", "Uña", "Unya", "Ongle", "Ongl"),
    ("body", "Bel", "Waist", "Veyst", "Taille", "Tayı", "Vita", "Vita", "Cintura", "Sintura", "Taille", "Tay"),

    # ── animals_extra (10) ───────────────────────────────────────────────
    ("animals", "Kurt", "Wolf", "Vulf", "Wolf", "Volf", "Lupo", "Lupo", "Lobo", "Lobo", "Loup", "Lu"),
    ("animals", "Tilki", "Fox", "Foks", "Fuchs", "Fuks", "Volpe", "Volpe", "Zorro", "Sorro", "Renard", "Rönar"),
    ("animals", "Kartal", "Eagle", "İigıl", "Adler", "Adlır", "Aquila", "Akuila", "Águila", "Agila", "Aigle", "Egl"),
    ("animals", "Kaplumbağa", "Turtle", "Törtıl", "Schildkröte", "Şiltkrötı", "Tartaruga", "Tartaruga", "Tortuga", "Tortuga", "Tortue", "Tortü"),
    ("animals", "Timsah", "Crocodile", "Krokodayl", "Krokodil", "Krokodil", "Coccodrillo", "Kokkodrillo", "Cocodrilo", "Kokodrilo", "Crocodile", "Krokodil"),
    ("animals", "Karınca", "Ant", "Ent", "Ameise", "Amayzı", "Formica", "Formika", "Hormiga", "Ormiga", "Fourmi", "Furmi"),
    ("animals", "Arı", "Bee", "Bii", "Biene", "Binı", "Ape", "Ape", "Abeja", "Abeha", "Abeille", "Abey"),
    ("animals", "Örümcek", "Spider", "Spaydır", "Spinne", "Şpinnı", "Ragno", "Ranyo", "Araña", "Aranya", "Araignée", "Arenye"),
    ("animals", "Yunus", "Dolphin", "Dolfin", "Delfin", "Delfin", "Delfino", "Delfino", "Delfín", "Delfin", "Dauphin", "Dofen"),
    ("animals", "Penguen", "Penguin", "Penguin", "Pinguin", "Pinguin", "Pinguino", "Pinguino", "Pingüino", "Pinguino", "Pingouin", "Penguen"),

    # ── places_extra (10) ────────────────────────────────────────────────
    ("places", "Havaalanı", "Airport", "Erpört", "Flughafen", "Flughafın", "Aeroporto", "Aeroporto", "Aeropuerto", "Aeropuerto", "Aéroport", "Aeropor"),
    ("places", "Eczane", "Pharmacy", "Farmısi", "Apotheke", "Apoteke", "Farmacia", "Farmaçiya", "Farmacia", "Farmasiya", "Pharmacie", "Farmasi"),
    ("places", "Spor salonu", "Gym", "Cim", "Fitnessstudio", "Fitnessştudyo", "Palestra", "Palestra", "Gimnasio", "Himnasyo", "Salle de sport", "Sal dö spor"),
    ("places", "Fırın", "Bakery", "Beykıri", "Bäckerei", "Beköray", "Panetteria", "Panetteriya", "Panadería", "Panaderiya", "Boulangerie", "Bulanjöri"),
    ("places", "Kasap", "Butcher", "Buçır", "Metzgerei", "Metsgıray", "Macelleria", "Maçelleriya", "Carnicería", "Karniseriya", "Boucherie", "Buşöri"),
    ("places", "Manav", "Greengrocer", "Griingrosır", "Gemüsehändler", "Gemüzehendlır", "Fruttivendolo", "Fruttivendolo", "Verdulería", "Berduleriya", "Primeur", "Primör"),
    ("places", "Otopark", "Parking lot", "Parking lot", "Parkplatz", "Parkplats", "Parcheggio", "Parkecco", "Aparcamiento", "Aparkamiyento", "Parking", "Parking"),
    ("places", "Köprü", "Bridge", "Bric", "Brücke", "Brükı", "Ponte", "Ponte", "Puente", "Puyente", "Pont", "Pon"),
    ("places", "Çeşme", "Fountain", "Fauntın", "Brunnen", "Brunnın", "Fontana", "Fontana", "Fuente", "Fuyente", "Fontaine", "Fonten"),
    ("places", "Kale", "Castle", "Kasıl", "Burg", "Burk", "Castello", "Kastello", "Castillo", "Kastiyo", "Château", "Şato"),

    # ── daily_extra (5) ──────────────────────────────────────────────────
    ("daily", "Acele etmeyin", "Don't rush", "Dont raş", "Keine Eile", "Kaynı Aylı", "Non si affretti", "Non si affretti", "No se apure", "No se apure", "Ne vous pressez pas", "Nö vu prese pa"),
    ("daily", "Yardıma ihtiyacım var", "I need help", "Ay niid help", "Ich brauche Hilfe", "İh brauhı Hilfı", "Ho bisogno di aiuto", "O bizonyo di ayuto", "Necesito ayuda", "Nesesito ayuda", "J'ai besoin d'aide", "Je bözuen ded"),
    ("daily", "Kaç yaşındasınız?", "How old are you?", "Hav old ar yu?", "Wie alt sind Sie?", "Vi alt zint zi?", "Quanti anni ha?", "Kuanti anni a?", "¿Cuántos años tiene?", "Kuantos anyos tiyene?", "Quel âge avez-vous ?", "Kel aj ave vu ?"),
    ("daily", "Bir şey değil", "It's nothing", "İts nathing", "Nichts zu danken", "Nihts tsu dankın", "Di niente", "Di niyente", "De nada", "De nada", "Ce n'est rien", "Sö ne riyen"),
    ("daily", "Dikkat edin", "Be careful", "Bi kerfıl", "Seien Sie vorsichtig", "Zayın zi forzıhtih", "Stia attento", "Stiya attento", "Tenga cuidado", "Tenga kuidado", "Faites attention", "Fet atansyon"),

    # ── health_extra (10) ────────────────────────────────────────────────
    ("health", "Hapşırmak", "To sneeze", "Tu sniiz", "Niesen", "Nizın", "Starnutire", "Starnutire", "Estornudar", "Estornudar", "Éternuer", "Eternüe"),
    ("health", "Baş dönmesi", "Dizziness", "Dizinis", "Schwindel", "Şvindıl", "Vertigine", "Verticine", "Mareo", "Mareo", "Vertige", "Vertij"),
    ("health", "Sargı", "Bandage", "Bendic", "Verband", "Ferbant", "Benda", "Benda", "Venda", "Benda", "Bandage", "Bandaj"),
    ("health", "Aşı", "Vaccine", "Veksiyn", "Impfung", "İmpfung", "Vaccino", "Vaççino", "Vacuna", "Bakuna", "Vaccin", "Vaksen"),
    ("health", "Röntgen", "X-ray", "Eks rey", "Röntgen", "Röntgın", "Radiografia", "Radiyografiya", "Radiografía", "Radiyografiya", "Radiographie", "Radiyografi"),
    ("health", "Ameliyat", "Surgery", "Sörcıri", "Operation", "Operatsyon", "Operazione", "Operatsyone", "Cirugía", "Siruhiya", "Chirurgie", "Şirürji"),
    ("health", "Enjeksiyon", "Injection", "İncekşın", "Injektion", "İnyektsyon", "Iniezione", "İniyetsyone", "Inyección", "İnyeksyon", "Injection", "Enjeksyon"),
    ("health", "Nabız", "Pulse", "Pals", "Puls", "Puls", "Polso", "Polso", "Pulso", "Pulso", "Pouls", "Pu"),
    ("health", "Nefes", "Breath", "Bret", "Atem", "Atım", "Respiro", "Respiro", "Respiración", "Respirasyon", "Respiration", "Respirasyon"),
    ("health", "Kırık", "Fracture", "Frekçır", "Bruch", "Bruh", "Frattura", "Frattura", "Fractura", "Fraktura", "Fracture", "Fraktür"),

    # ── adjectives_extra (10) ────────────────────────────────────────────
    ("adjectives", "Geniş", "Wide", "Vayd", "Breit", "Brayt", "Largo", "Largo", "Ancho", "Anço", "Large", "Larj"),
    ("adjectives", "Dar", "Narrow", "Nerou", "Eng", "Eng", "Stretto", "Stretto", "Estrecho", "Estreço", "Étroit", "Etrua"),
    ("adjectives", "Derin", "Deep", "Diip", "Tief", "Tif", "Profondo", "Profondo", "Profundo", "Profundo", "Profond", "Profon"),
    ("adjectives", "Sığ", "Shallow", "Şelou", "Flach", "Flah", "Poco profondo", "Poko profondo", "Poco profundo", "Poko profundo", "Peu profond", "Pö profon"),
    ("adjectives", "Yumuşak", "Soft", "Soft", "Weich", "Vayh", "Morbido", "Morbido", "Suave", "Suave", "Doux", "Du"),
    ("adjectives", "Sert", "Hard", "Hard", "Hart", "Hart", "Duro", "Duro", "Duro", "Duro", "Dur", "Dür"),
    ("adjectives", "Parlak", "Bright", "Brayt", "Hell", "Hel", "Luminoso", "Luminozo", "Brillante", "Briyante", "Brillant", "Briyan"),
    ("adjectives", "Karanlık", "Dark", "Dark", "Dunkel", "Dunkıl", "Scuro", "Skuro", "Oscuro", "Oskuro", "Sombre", "Sonbr"),
    ("adjectives", "Tatlı", "Sweet", "Sviit", "Süß", "Züs", "Dolce", "Dolçe", "Dulce", "Dulse", "Doux", "Du"),
    ("adjectives", "Acı", "Bitter", "Bitır", "Bitter", "Bittır", "Amaro", "Amaro", "Amargo", "Amargo", "Amer", "Amer"),

    # ── education_extra (10) ─────────────────────────────────────────────
    ("education", "Laboratuvar", "Laboratory", "Lebırıtori", "Labor", "Labor", "Laboratorio", "Laboratoryo", "Laboratorio", "Laboratoryo", "Laboratoire", "Laboratuar"),
    ("education", "Müdür", "Principal", "Prinsıpıl", "Schulleiter", "Şullaytır", "Preside", "Prezide", "Director", "Direktor", "Directeur", "Direktör"),
    ("education", "Burs", "Scholarship", "Skolırşip", "Stipendium", "Ştipendiyum", "Borsa di studio", "Borsa di studiyo", "Beca", "Beka", "Bourse", "Burs"),
    ("education", "Mezuniyet", "Graduation", "Grecueyşın", "Abschluss", "Apşlus", "Laurea", "Laureya", "Graduación", "Graduasyon", "Diplôme", "Diplom"),
    ("education", "Konferans", "Conference", "Konfrıns", "Konferenz", "Konferents", "Conferenza", "Konferentsa", "Conferencia", "Konferensiya", "Conférence", "Konferans"),
    ("education", "Tez", "Thesis", "Tiisis", "Abschlussarbeit", "Apşlusarbayt", "Tesi", "Tezi", "Tesis", "Tesis", "Thèse", "Tez"),
    ("education", "Dönem", "Semester", "Sımestır", "Semester", "Zemestır", "Semestre", "Semestre", "Semestre", "Semestre", "Semestre", "Sömestr"),
    ("education", "Kayıt", "Registration", "Recistreyşın", "Anmeldung", "Anmeldung", "Iscrizione", "İskritsyone", "Inscripción", "İnskripsyon", "Inscription", "Enskripsiyon"),
    ("education", "Müfredat", "Curriculum", "Kırikyulım", "Lehrplan", "Lerplan", "Curriculum", "Kurrikulum", "Plan de estudios", "Plan de estudiyos", "Programme", "Program"),
    ("education", "Araştırma", "Research", "Risörç", "Forschung", "Forşung", "Ricerca", "Riçerka", "Investigación", "İnbestigasyon", "Recherche", "Röşerş"),

    # ── clothing_extra (5) ───────────────────────────────────────────────
    ("clothing", "Kazak", "Sweater", "Svetır", "Pullover", "Pullovır", "Maglione", "Malyione", "Suéter", "Sueter", "Pull", "Pül"),
    ("clothing", "Terlik", "Slippers", "Slipırz", "Hausschuhe", "Hausşuı", "Pantofole", "Pantofole", "Zapatillas", "Sapatillas", "Pantoufles", "Pantufl"),
    ("clothing", "Mayo", "Swimsuit", "Svimsuut", "Badeanzug", "Badıantsuk", "Costume da bagno", "Kostume da banyo", "Traje de baño", "Trahe de banyo", "Maillot de bain", "Maliyo dö ben"),
    ("clothing", "Eşofman", "Tracksuit", "Treksuut", "Trainingsanzug", "Treningsantsuk", "Tuta", "Tuta", "Chándal", "Çandal", "Survêtement", "Sürvetman"),
    ("clothing", "Yelek", "Vest", "Vest", "Weste", "Vestı", "Gilet", "Cile", "Chaleco", "Çaleko", "Gilet", "Jile"),

    # ── shopping_extra (5) ───────────────────────────────────────────────
    ("shopping", "Pazar", "Market", "Markıt", "Markt", "Markt", "Mercato", "Merkato", "Mercado", "Merkado", "Marché", "Marşe"),
    ("shopping", "Taksit", "Installment", "İnstolmınt", "Ratenzahlung", "Ratıntsalung", "Rata", "Rata", "Cuota", "Kuota", "Versement", "Versöman"),
    ("shopping", "Deneme kabini", "Fitting room", "Fiting ruum", "Umkleidekabine", "Umklaydıkabinı", "Camerino", "Kamerino", "Probador", "Probador", "Cabine d'essayage", "Kabin deseyaj"),
    ("shopping", "Hediye", "Gift", "Gift", "Geschenk", "Geşenk", "Regalo", "Regalo", "Regalo", "Regalo", "Cadeau", "Kado"),
    ("shopping", "Ambalaj", "Packaging", "Pekicing", "Verpackung", "Ferpakung", "Imballaggio", "İmballacco", "Embalaje", "Embalahe", "Emballage", "Anbalaj"),

    # ── time_extra (5) ───────────────────────────────────────────────────
    ("time", "Yüzyıl", "Century", "Sençuri", "Jahrhundert", "Yarhundırt", "Secolo", "Sekolo", "Siglo", "Siglo", "Siècle", "Siyekl"),
    ("time", "Geçen hafta", "Last week", "Last viik", "Letzte Woche", "Letstı Vohı", "La settimana scorsa", "La settimana skorsa", "La semana pasada", "La semana pasada", "La semaine dernière", "La sömen dernyer"),
    ("time", "Gelecek hafta", "Next week", "Nekst viik", "Nächste Woche", "Nehstı Vohı", "La prossima settimana", "La prossima settimana", "La próxima semana", "La proksima semana", "La semaine prochaine", "La sömen proşen"),
    ("time", "Erken", "Early", "Örli", "Früh", "Frü", "Presto", "Presto", "Temprano", "Temprano", "Tôt", "To"),
    ("time", "Geç", "Late", "Leyt", "Spät", "Şpet", "Tardi", "Tardi", "Tarde", "Tarde", "Tard", "Tar"),

    # ── home_extra (5) ───────────────────────────────────────────────────
    ("home", "Balkon", "Balcony", "Belkıni", "Balkon", "Balkon", "Balcone", "Balkone", "Balcón", "Balkon", "Balcon", "Balkon"),
    ("home", "Garaj", "Garage", "Gerij", "Garage", "Garaj", "Garage", "Garaj", "Garaje", "Garahe", "Garage", "Garaj"),
    ("home", "Çatı", "Roof", "Ruuf", "Dach", "Dah", "Tetto", "Tetto", "Techo", "Teço", "Toit", "Tua"),
    ("home", "Bodrum", "Basement", "Beysmınt", "Keller", "Kellır", "Seminterrato", "Seminterrato", "Sótano", "Sotano", "Sous-sol", "Su sol"),
    ("home", "Asansör", "Elevator", "Eliveytır", "Aufzug", "Auftsug", "Ascensore", "Aşensore", "Ascensor", "Asensor", "Ascenseur", "Asansör"),

    # ── professions_extra (5) ────────────────────────────────────────────
    ("professions", "Muhasebeci", "Accountant", "Ekauntınt", "Buchhalter", "Buhhaltır", "Commercialista", "Kommerçalista", "Contador", "Kontador", "Comptable", "Kontabl"),
    ("professions", "Psikolog", "Psychologist", "Saykolıcist", "Psychologe", "Psükologe", "Psicologo", "Psikologo", "Psicólogo", "Psikologo", "Psychologue", "Psikolog"),
    ("professions", "Veteriner", "Veterinarian", "Vetırineyriyın", "Tierarzt", "Tirarst", "Veterinario", "Veterinaryo", "Veterinario", "Beterinaryo", "Vétérinaire", "Veteriner"),
    ("professions", "Tercüman", "Interpreter", "İntörprıtır", "Dolmetscher", "Dolmetşır", "Interprete", "İnterprete", "Intérprete", "İnterprete", "Interprète", "Enterpret"),
    ("professions", "Kaptan", "Captain", "Keptın", "Kapitän", "Kapiten", "Capitano", "Kapitano", "Capitán", "Kapitan", "Capitaine", "Kapiten"),
]
