# -*- coding: utf-8 -*-
"""MEB-aligned English curriculum data for Primary School (Grades 1-4).

Each grade has 36 weekly entries following the national curriculum themes.
Structure mirrors curriculum_ortaokul.py for consistency.

Unit grouping (10 units from 36 weeks via build_unit_groups):
  Unit 1: positions 0-3   (weeks 1-4)
  Unit 2: positions 4-7   (weeks 5-8)
  Unit 3: positions 8-11  (weeks 9-12)
  Unit 4: positions 12-15 (weeks 13-16)
  Unit 5: positions 16-19 (weeks 17-20)
  Unit 6: positions 20-23 (weeks 21-24)
  Unit 7: positions 24-26 (weeks 25-27)
  Unit 8: positions 27-29 (weeks 28-30)
  Unit 9: positions 30-32 (weeks 31-33)
  Unit 10: positions 33-35 (weeks 34-36)
"""

from __future__ import annotations


def _week(w, theme, theme_tr, vocab, structure, skills, categories=None):
    """Helper to build a consistent week entry."""
    return {
        "week": w,
        "theme": theme,
        "theme_tr": theme_tr,
        "vocab": vocab,
        "structure": structure,
        "skills": skills or {},
        "linked_content": {"categories": categories or []},
    }


# ══════════════════════════════════════════════════════════════════════════════
# GRADE 1 — Pre-A1 (Starter — Beginner)
# Content bank units:
#   1. Greetings & Classroom  2. My Family  3. Animals & Food
#   4. My House  5. Transport & Actions  6. School & Routines
#   7. Sports & Hobbies  8. At the Park & Shop  9. Jobs & Community
#   10. Summer & Holidays
# ══════════════════════════════════════════════════════════════════════════════

CURRICULUM_GRADE1 = [
    # ── Unit 1: Greetings & Classroom (positions 0-3, weeks 1-4) ──
    _week(1, "Greetings & Classroom", "Selamlasma ve Sinif",
          ["hello", "hi", "goodbye", "bye", "teacher", "friend", "name", "my"],
          "Hello! My name is... What's your name?",
          {"listening": "Selamlasma diyaloglarini dinler.", "speaking": "Adini soyler, selamlasir."},
          ["Selamlasma", "Okul"]),
    _week(2, "Numbers 1-10", "Sayilar 1-10",
          ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "count", "how many"],
          "How many? One, two, three...",
          {"listening": "Sayilari dinler ve tekrar eder.", "speaking": "1-10 arasi sayar."},
          ["Sayilar"]),
    _week(3, "Colours", "Renkler",
          ["red", "blue", "green", "yellow", "orange", "pink", "purple", "black", "white", "brown"],
          "What colour is it? It's red.",
          {"listening": "Renk isimlerini dinler.", "speaking": "Nesnelerin rengini soyler."},
          ["Renkler"]),
    _week(4, "My Classroom", "Sinifim",
          ["desk", "chair", "board", "book", "pencil", "bag", "door", "window", "classroom", "table"],
          "What's this? It's a desk.",
          {"listening": "Sinif esyalarini dinler.", "speaking": "Sinif esyalarini isimlendirir."},
          ["Okul"]),

    # ── Unit 2: My Family (positions 4-7, weeks 5-8) ──
    _week(5, "My Family", "Ailem",
          ["mother", "father", "sister", "brother", "baby", "family", "grandma", "grandpa", "love", "home"],
          "This is my mother. I love my family.",
          {"listening": "Aile uyelerini dinler.", "speaking": "Ailesini tanitir."},
          ["Aile"]),
    _week(6, "Family at Home", "Evde Aile",
          ["kitchen", "living room", "bedroom", "play", "cook", "watch", "together", "share", "help", "care"],
          "My mother is in the kitchen. We play together.",
          {"listening": "Evdeki aile aktivitelerini dinler.", "speaking": "Ailesiyle ne yaptigini anlatir."},
          ["Aile", "Ev"]),
    _week(7, "My Body", "Vucudum",
          ["head", "eye", "ear", "nose", "mouth", "hand", "foot", "arm", "leg", "finger"],
          "Touch your nose. This is my head.",
          {"listening": "Vucut bolumlerini dinler.", "speaking": "Vucut bolumlerini gosterir ve soyler."},
          ["Vucut"]),
    _week(8, "Feelings", "Duygular",
          ["happy", "sad", "angry", "tired", "hungry", "thirsty", "scared", "excited", "fine", "great"],
          "How are you? I'm happy.",
          {"listening": "Duygu ifadelerini dinler.", "speaking": "Nasil hissettigini soyler."},
          ["Duygular"]),

    # ── Unit 3: Animals & Food (positions 8-11, weeks 9-12) ──
    _week(9, "Animals & Food", "Hayvanlar ve Yiyecekler",
          ["cat", "dog", "bird", "fish", "rabbit", "horse", "cow", "sheep", "duck", "chicken"],
          "I like cats. It's a dog.",
          {"listening": "Hayvan isimlerini dinler.", "speaking": "Sevdigi hayvanlari soyler."},
          ["Hayvanlar"]),
    _week(10, "Farm Animals", "Ciftlik Hayvanlari",
          ["pig", "goat", "donkey", "rooster", "hen", "lamb", "barn", "farm", "feed", "milk"],
          "The cow gives milk. The rooster says cock-a-doodle-doo!",
          {"listening": "Ciftlik hayvanlarini dinler.", "speaking": "Ciftlik hayvanlarini anlatir."},
          ["Hayvanlar"]),
    _week(11, "Favourite Foods", "En Sevdigi Yiyecekler",
          ["apple", "banana", "bread", "milk", "water", "cheese", "egg", "cake", "ice cream", "juice"],
          "I like apples. Do you like milk?",
          {"listening": "Yiyecek isimlerini dinler.", "speaking": "Sevdigi yiyecekleri soyler."},
          ["Yiyecekler"]),
    _week(12, "Fruits & Vegetables", "Meyveler ve Sebzeler",
          ["orange", "grape", "strawberry", "watermelon", "cherry", "carrot", "tomato", "potato", "pear", "lemon"],
          "Do you like oranges? Yes, I do. Carrots are healthy.",
          {"listening": "Meyve ve sebze isimlerini dinler.", "speaking": "Meyve ve sebze tercihlerini soyler."},
          ["Yiyecekler"]),

    # ── Unit 4: My House (positions 12-15, weeks 13-16) ──
    _week(13, "My House", "Evim",
          ["house", "room", "kitchen", "bathroom", "bedroom", "garden", "living room", "door", "window", "roof"],
          "This is my house. I have a garden.",
          {"listening": "Ev bolumlerini dinler.", "speaking": "Evini anlatir."},
          ["Ev"]),
    _week(14, "Things in My Room", "Odamdaki Esyalar",
          ["bed", "pillow", "blanket", "lamp", "wardrobe", "toy box", "shelf", "poster", "rug", "curtain"],
          "There is a bed in my room. My toys are on the shelf.",
          {"listening": "Oda esyalarini dinler.", "speaking": "Odasini betimler."},
          ["Ev"]),
    _week(15, "Toys & Play", "Oyuncaklar ve Oyun",
          ["ball", "doll", "car", "teddy bear", "puzzle", "kite", "robot", "train", "blocks", "drum"],
          "I have a ball. What's your favourite toy?",
          {"listening": "Oyuncak isimlerini dinler.", "speaking": "Oyuncaklarini anlatir."},
          ["Oyuncaklar"]),
    _week(16, "Clothes at Home", "Evdeki Giysiler",
          ["shirt", "trousers", "shoes", "hat", "coat", "dress", "socks", "boots", "skirt", "scarf"],
          "I'm wearing a red shirt. Put on your coat!",
          {"listening": "Giysi isimlerini dinler.", "speaking": "Giydiklerini anlatir."},
          ["Giysiler"]),

    # ── Unit 5: Transport & Actions (positions 16-19, weeks 17-20) ──
    _week(17, "Transport & Actions", "Ulasim ve Hareketler",
          ["car", "bus", "train", "bike", "plane", "boat", "walk", "drive", "ride", "fly"],
          "I go to school by bus. Can you ride a bike?",
          {"listening": "Ulasim araclarini dinler.", "speaking": "Nasil gittigini soyler."},
          ["Ulasim"]),
    _week(18, "Actions & Movement", "Hareketler",
          ["run", "jump", "walk", "sit", "stand", "clap", "swim", "dance", "sing", "climb"],
          "I can run. Can you jump? Let's dance!",
          {"listening": "Hareket fiillerini dinler.", "speaking": "Yapabileceklerini soyler."},
          ["Hareketler"]),
    _week(19, "Numbers 11-20", "Sayilar 11-20",
          ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty"],
          "How old are you? I'm seven.",
          {"listening": "11-20 arasi sayilari dinler.", "speaking": "Yasini soyler."},
          ["Sayilar"]),
    _week(20, "Days of the Week", "Haftanin Gunleri",
          ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "today", "day", "week"],
          "What day is it? It's Monday.",
          {"listening": "Gun isimlerini dinler.", "speaking": "Gunleri siralar ve soyler."},
          ["Zaman"]),

    # ── Unit 6: School & Routines (positions 20-23, weeks 21-24) ──
    _week(21, "School & Routines", "Okul ve Rutinler",
          ["wake up", "get up", "go to school", "have lunch", "do homework", "go to bed", "always", "sometimes", "class", "lesson"],
          "I always wake up at seven. I go to school at eight.",
          {"listening": "Rutin anlatimlarini dinler.", "speaking": "Gunluk rutinini anlatir."},
          ["Okul", "Gunluk Yasam"]),
    _week(22, "Weather", "Hava Durumu",
          ["sunny", "rainy", "cloudy", "windy", "snowy", "hot", "cold", "warm", "weather", "sky"],
          "It's sunny. How's the weather?",
          {"listening": "Hava durumunu dinler.", "speaking": "Havayi anlatir."},
          ["Hava Durumu"]),
    _week(23, "Shapes & Sizes", "Sekiller ve Boyutlar",
          ["circle", "square", "triangle", "star", "heart", "rectangle", "big", "small", "long", "short"],
          "It's a circle. What shape is it? It's big!",
          {"listening": "Sekil isimlerini dinler.", "speaking": "Sekilleri isimlendirir."},
          ["Sekiller"]),
    _week(24, "Birthdays & Parties", "Dogum Gunleri ve Partiler",
          ["birthday", "cake", "candle", "present", "party", "balloon", "happy", "wish", "blow", "celebrate"],
          "Happy birthday! How old are you?",
          {"listening": "Dogum gunu diyaloglarini dinler.", "speaking": "Dogum gununu anlatir."},
          ["Kutlamalar"]),

    # ── Unit 7: Sports & Hobbies (positions 24-26, weeks 25-27) ──
    _week(25, "Sports & Hobbies", "Sporlar ve Hobiler",
          ["football", "basketball", "tennis", "swimming", "running", "cycling", "volleyball", "play", "team", "goal"],
          "I play football. Do you like tennis?",
          {"listening": "Spor isimlerini dinler.", "speaking": "Sevdigi sporlari soyler."},
          ["Spor"]),
    _week(26, "Fun Activities", "Eglenceli Aktiviteler",
          ["draw", "paint", "sing", "dance", "read", "play games", "colour", "build", "collect", "hobby"],
          "My hobby is drawing. I like to sing.",
          {"listening": "Hobi anlatimlarini dinler.", "speaking": "Hobilerini anlatir."},
          ["Hobiler"]),
    _week(27, "The Seasons", "Mevsimler",
          ["spring", "summer", "autumn", "winter", "hot", "cold", "leaves", "snow", "flowers", "sun"],
          "I like summer. It's hot in summer.",
          {"listening": "Mevsim anlatimlarini dinler.", "speaking": "Sevdigi mevsimi soyler."},
          ["Mevsimler"]),

    # ── Unit 8: At the Park & Shop (positions 27-29, weeks 28-30) ──
    _week(28, "At the Park & Shop", "Parkta ve Dukkanda",
          ["tree", "flower", "grass", "bench", "swing", "slide", "bike", "run", "play", "picnic"],
          "I play in the park. I like the swings.",
          {"listening": "Park aktivitelerini dinler.", "speaking": "Parkta yaptiklarini anlatir."},
          ["Dogal Cevre", "Park"]),
    _week(29, "At the Market", "Markette",
          ["buy", "sell", "money", "shop", "basket", "fruit", "vegetable", "fresh", "yummy", "please"],
          "Can I have an apple, please?",
          {"listening": "Market diyaloglarini dinler.", "speaking": "Alisveris yapar."},
          ["Alisveris"]),
    _week(30, "Pets & Nature", "Evcil Hayvanlar ve Doga",
          ["cat", "dog", "hamster", "parrot", "goldfish", "turtle", "puppy", "kitten", "pet", "care"],
          "I have a cat. My pet is small. I take care of it.",
          {"listening": "Evcil hayvan anlatimlarini dinler.", "speaking": "Evcil hayvanini anlatir."},
          ["Hayvanlar", "Doga"]),

    # ── Unit 9: Jobs & Community (positions 30-32, weeks 31-33) ──
    _week(31, "Jobs & Community", "Meslekler ve Toplum",
          ["teacher", "doctor", "police", "firefighter", "farmer", "pilot", "cook", "driver", "dentist", "nurse"],
          "She is a doctor. He is a teacher.",
          {"listening": "Meslek isimlerini dinler.", "speaking": "Meslekleri soyler."},
          ["Meslekler"]),
    _week(32, "Healthy Living", "Saglikli Yasam",
          ["eat", "drink", "sleep", "exercise", "fruit", "vegetable", "water", "healthy", "strong", "clean"],
          "Eat fruit! Drink water! Be healthy!",
          {"listening": "Saglik tavsiyelerini dinler.", "speaking": "Saglikli aliskanliklarini anlatir."},
          ["Saglik"]),
    _week(33, "Helping Others", "Baskalarina Yardim",
          ["help", "share", "kind", "friend", "community", "together", "give", "volunteer", "thank you", "please"],
          "Let's help! Sharing is caring.",
          {"listening": "Yardim diyaloglarini dinler.", "speaking": "Yardim etme orneklerini anlatir."},
          ["Degerler", "Toplum"]),

    # ── Unit 10: Summer & Holidays (positions 33-35, weeks 34-36) ──
    _week(34, "Summer & Holidays", "Yaz ve Tatiller",
          ["summer", "holiday", "beach", "pool", "travel", "visit", "grandparents", "camp", "plan", "excited"],
          "I'm going to the beach. Summer is fun!",
          {"listening": "Tatil planlarini dinler.", "speaking": "Tatil planlarini anlatir."},
          ["Tatil"]),
    _week(35, "Storytelling", "Hikaye Zamani",
          ["story", "once upon a time", "prince", "princess", "dragon", "castle", "magic", "happy", "end", "book"],
          "Once upon a time... The end.",
          {"listening": "Kisa bir hikaye dinler.", "speaking": "Basit hikaye anlatir."},
          ["Hikaye"]),
    _week(36, "Year-End Show", "Yil Sonu Gosterisi",
          ["show", "act", "sing", "dance", "costume", "stage", "audience", "clap", "bow", "well done"],
          "Well done! Let's celebrate!",
          {"listening": "Gosteri talimatlarini dinler.", "speaking": "Sahnede rol alir."},
          ["Kutlamalar"]),
]


# ══════════════════════════════════════════════════════════════════════════════
# GRADE 2 — Pre-A1+ (Starter — Elementary)
# Content bank units:
#   1. My School  2. My Town  3. Food & Meals  4. Wild Animals
#   5. My Body & Health  6. Holidays & Celebrations  7. Transport & Travel
#   8. Nature & Plants  9. Stories & Books  10. Talent Show & Graduation
# ══════════════════════════════════════════════════════════════════════════════

CURRICULUM_GRADE2 = [
    # ── Unit 1: My School (positions 0-3, weeks 1-4) ──
    _week(1, "My School", "Okulum",
          ["classmate", "new", "old", "year", "grade", "ready", "excited", "learn", "study", "together"],
          "Welcome back! This is my school. I'm in Grade 2.",
          {"listening": "Tanitma diyaloglarini dinler.", "speaking": "Okulunu tanitir.", "reading": "Kisa tanitma metni okur.", "writing": "Adini ve sinifini yazar."},
          ["Okul"]),
    _week(2, "My School Bag", "Okul Cantam",
          ["schoolbag", "pencil", "rubber", "ruler", "sharpener", "notebook", "crayon", "scissors", "glue", "marker"],
          "I have a pencil. Have you got a ruler?",
          {"listening": "Okul malzemelerini dinler.", "speaking": "Cantasindakileri soyler.", "reading": "Malzeme listesi okur.", "writing": "Liste yazar."},
          ["Okul"]),
    _week(3, "Colours & Numbers", "Renkler ve Sayilar",
          ["thirty", "forty", "fifty", "light blue", "dark green", "grey", "gold", "silver", "many", "few"],
          "I have thirty red apples. How many blue balls?",
          {"listening": "Sayi ve renk kombinasyonlarini dinler.", "speaking": "Renk ve sayi bildirir.", "reading": "Sayili nesneleri okur.", "writing": "Renk-sayi cumleleri yazar."},
          ["Sayilar", "Renkler"]),
    _week(4, "Our Classroom", "Sinifimiz",
          ["board", "poster", "clock", "bookshelf", "calendar", "map", "chair", "desk", "corner", "tidy"],
          "Our classroom is tidy. There is a clock on the wall.",
          {"listening": "Sinif tariflerini dinler.", "speaking": "Sinifini anlatir.", "reading": "Sinif haritasi okur.", "writing": "Sinif tasviri yazar."},
          ["Okul"]),

    # ── Unit 2: My Town (positions 4-7, weeks 5-8) ──
    _week(5, "My Town", "Benim Kasabam",
          ["school", "hospital", "park", "market", "library", "mosque", "bakery", "pharmacy", "bank", "post office"],
          "The hospital is near the park. I live in a town.",
          {"listening": "Yer tariflerini dinler.", "speaking": "Yerleri anlatir.", "reading": "Harita okur.", "writing": "Mahalle haritasi cizer."},
          ["Sehir"]),
    _week(6, "Directions", "Yonler",
          ["left", "right", "straight", "turn", "stop", "go", "near", "far", "next to", "opposite"],
          "Turn left. Go straight. It's next to the bank.",
          {"listening": "Yon tariflerini dinler.", "speaking": "Yon tarif eder.", "reading": "Yol tarifi okur.", "writing": "Basit yon tarifi yazar."},
          ["Sehir"]),
    _week(7, "My Home", "Evim",
          ["upstairs", "downstairs", "living room", "dining room", "garage", "balcony", "flat", "floor", "furniture", "lamp"],
          "There is a sofa in the living room.",
          {"listening": "Ev tariflerini dinler.", "speaking": "Evini anlatir.", "reading": "Ev tasviri okur.", "writing": "Odasini tasvir eder."},
          ["Ev"]),
    _week(8, "Family Members", "Aile Uyeleri",
          ["uncle", "aunt", "cousin", "parents", "son", "daughter", "grandparents", "twins", "older", "younger"],
          "My uncle is tall. I have two cousins.",
          {"listening": "Aile anlatimlarini dinler.", "speaking": "Genis ailesini anlatir.", "reading": "Aile agaci okur.", "writing": "Aile agaci cizer ve yazar."},
          ["Aile"]),

    # ── Unit 3: Food & Meals (positions 8-11, weeks 9-12) ──
    _week(9, "Food & Meals", "Yiyecek ve Ogunler",
          ["sandwich", "soup", "salad", "pizza", "pasta", "tea", "chocolate", "biscuit", "yoghurt", "rice"],
          "I like pizza. I don't like soup. What do you like?",
          {"listening": "Yemek tercihlerini dinler.", "speaking": "Yemek tercihlerini anlatir.", "reading": "Menu okur.", "writing": "Favori yemegini yazar."},
          ["Yiyecekler"]),
    _week(10, "Healthy Eating", "Saglikli Beslenme",
          ["vegetable", "carrot", "tomato", "cucumber", "onion", "pepper", "potato", "healthy", "strong", "vitamins"],
          "Vegetables are healthy. Eat your carrots!",
          {"listening": "Saglik tavsiyelerini dinler.", "speaking": "Saglikli yemek anlatir.", "reading": "Saglik posteri okur.", "writing": "Saglikli tabak cizer ve yazar."},
          ["Yiyecekler", "Saglik"]),
    _week(11, "At the Restaurant", "Restoranda",
          ["menu", "order", "waiter", "bill", "delicious", "drink", "dessert", "table", "serve", "tip"],
          "I'd like pizza, please. Can I see the menu?",
          {"listening": "Restoran diyaloglarini dinler.", "speaking": "Siparis verir.", "reading": "Menu okur.", "writing": "Menu tasarlar."},
          ["Yiyecekler"]),
    _week(12, "Cooking Fun", "Eglenceli Yemek",
          ["mix", "stir", "bake", "cook", "recipe", "ingredient", "bowl", "spoon", "flour", "sugar"],
          "Mix the flour. Stir the batter. Let's bake a cake!",
          {"listening": "Tarif anlatimini dinler.", "speaking": "Basit tarif anlatir.", "reading": "Tarif okur.", "writing": "Tarif yazar."},
          ["Yiyecekler"]),

    # ── Unit 4: Wild Animals (positions 12-15, weeks 13-16) ──
    _week(13, "Wild Animals", "Vahsi Hayvanlar",
          ["lion", "elephant", "giraffe", "monkey", "snake", "crocodile", "tiger", "bear", "zebra", "penguin"],
          "Lions are big. Penguins can swim.",
          {"listening": "Hayvan ozelliklerini dinler.", "speaking": "Hayvanlari betimler.", "reading": "Hayvan kartlari okur.", "writing": "Hayvan tasviri yazar."},
          ["Hayvanlar"]),
    _week(14, "Animal Habitats", "Hayvan Yasamalanlari",
          ["jungle", "ocean", "desert", "forest", "river", "mountain", "pond", "nest", "habitat", "live"],
          "Fish live in the ocean. Birds live in nests.",
          {"listening": "Habitat anlatimlarini dinler.", "speaking": "Hayvanlarin nerede yasadigini soyler.", "reading": "Habitat kartini okur.", "writing": "Habitat tasviri yazar."},
          ["Hayvanlar", "Doga"]),
    _week(15, "Pets We Love", "Sevdigimiz Evcil Hayvanlar",
          ["cat", "dog", "hamster", "parrot", "goldfish", "turtle", "puppy", "kitten", "feed", "care"],
          "I have a cat. I feed my pet every day.",
          {"listening": "Evcil hayvan anlatimlarini dinler.", "speaking": "Evcil hayvanini anlatir.", "reading": "Hayvan bakimi okur.", "writing": "Evcil hayvanini tasvir eder."},
          ["Hayvanlar"]),
    _week(16, "Animal Sounds & Actions", "Hayvan Sesleri ve Hareketleri",
          ["bark", "meow", "roar", "chirp", "hop", "crawl", "gallop", "fly", "swim", "climb"],
          "Dogs bark. Birds chirp. Frogs hop.",
          {"listening": "Hayvan seslerini dinler.", "speaking": "Hayvan hareketlerini anlatir.", "reading": "Hayvan sarkisi okur.", "writing": "Hayvan hareketlerini yazar."},
          ["Hayvanlar"]),

    # ── Unit 5: My Body & Health (positions 16-19, weeks 17-20) ──
    _week(17, "My Body & Health", "Vucudum ve Sagligim",
          ["shoulder", "knee", "toe", "stomach", "back", "neck", "chin", "elbow", "wrist", "ankle"],
          "My shoulder hurts. Touch your knees.",
          {"listening": "Vucut bolumlerini dinler.", "speaking": "Vucut bolumlerini gosterir.", "reading": "Vucut sarkisi sozlerini okur.", "writing": "Vucut bolumlerini etiketler."},
          ["Vucut"]),
    _week(18, "Staying Healthy", "Saglikli Kalmak",
          ["exercise", "sleep", "wash", "brush", "healthy", "strong", "clean", "rest", "water", "fruit"],
          "Brush your teeth! Wash your hands! Eat healthy food.",
          {"listening": "Saglik tavsiyelerini dinler.", "speaking": "Saglikli aliskanliklarini anlatir.", "reading": "Saglik poster okur.", "writing": "Saglik kurallari yazar."},
          ["Saglik"]),
    _week(19, "Abilities", "Yetenekler",
          ["can", "can't", "swim", "ride a bike", "skip", "climb", "draw", "paint", "read", "write"],
          "I can swim. I can't ride a bike.",
          {"listening": "Yetenek ifadelerini dinler.", "speaking": "Yapabileceklerini anlatir.", "reading": "Yetenek listesi okur.", "writing": "Can/can't cumleleri yazar."},
          ["Yetenekler"]),
    _week(20, "Daily Routines", "Gunluk Rutinler",
          ["wake up", "get up", "have lunch", "do homework", "watch TV", "go to bed", "always", "sometimes", "never", "often"],
          "I always wake up at seven. I sometimes watch TV.",
          {"listening": "Rutin anlatimlarini dinler.", "speaking": "Gunluk rutinini anlatir.", "reading": "Rutin metni okur.", "writing": "Kendi rutinini yazar."},
          ["Gunluk Yasam"]),

    # ── Unit 6: Holidays & Celebrations (positions 20-23, weeks 21-24) ──
    _week(21, "Holidays & Celebrations", "Tatiller ve Kutlamalar",
          ["holiday", "celebration", "festival", "gift", "decorate", "invite", "guest", "special", "traditional", "enjoy"],
          "Happy holiday! We celebrate together.",
          {"listening": "Kutlama diyaloglarini dinler.", "speaking": "Bayram kutlar.", "reading": "Kutlama karti okur.", "writing": "Kutlama karti yazar."},
          ["Kutlamalar"]),
    _week(22, "Birthdays", "Dogum Gunleri",
          ["birthday", "cake", "candle", "present", "party", "balloon", "wish", "blow", "surprise", "celebrate"],
          "Happy birthday! Make a wish and blow the candles!",
          {"listening": "Dogum gunu diyaloglarini dinler.", "speaking": "Dogum gununu anlatir.", "reading": "Davetiye okur.", "writing": "Davetiye yazar."},
          ["Kutlamalar"]),
    _week(23, "Months of the Year", "Yilin Aylari",
          ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
          "My birthday is in May. When is your birthday?",
          {"listening": "Ay isimlerini dinler.", "speaking": "Dogum gununu soyler.", "reading": "Takvim okur.", "writing": "Onemli tarihleri yazar."},
          ["Zaman"]),
    _week(24, "Weather & Seasons", "Hava ve Mevsimler",
          ["spring", "summer", "autumn", "winter", "sunny", "rainy", "snowy", "windy", "cloudy", "foggy"],
          "It's cloudy in autumn. I wear a coat in winter.",
          {"listening": "Hava raporlarini dinler.", "speaking": "Havayi ve mevsimi anlatir.", "reading": "Hava raporu okur.", "writing": "Mevsim paragraf yazar."},
          ["Hava Durumu", "Mevsimler"]),

    # ── Unit 7: Transport & Travel (positions 24-26, weeks 25-27) ──
    _week(25, "Transport & Travel", "Ulasim ve Seyahat",
          ["car", "bus", "train", "plane", "boat", "taxi", "walk", "drive", "ride", "fly"],
          "I go to school by bus. We travel by plane.",
          {"listening": "Ulasim bilgilerini dinler.", "speaking": "Ulasim araclarini kullanir.", "reading": "Bilet okur.", "writing": "Yolculugunu anlatir."},
          ["Ulasim"]),
    _week(26, "Telling Time", "Saati Soyleme",
          ["o'clock", "half past", "morning", "afternoon", "evening", "night", "early", "late", "clock", "watch"],
          "It's seven o'clock. I go to school at half past eight.",
          {"listening": "Saat ifadelerini dinler.", "speaking": "Saati soyler.", "reading": "Program okur.", "writing": "Gunluk programini yazar."},
          ["Zaman"]),
    _week(27, "Clothes & Shopping", "Giysiler ve Alisveris",
          ["jacket", "sweater", "jeans", "trainers", "uniform", "size", "try on", "buy", "price", "cheap"],
          "How much is the jacket? Can I try it on?",
          {"listening": "Alisveris diyaloglarini dinler.", "speaking": "Alisveris yapar.", "reading": "Fiyat etiketi okur.", "writing": "Alisveris listesi yazar."},
          ["Alisveris", "Giysiler"]),

    # ── Unit 8: Nature & Plants (positions 27-29, weeks 28-30) ──
    _week(28, "Nature & Plants", "Doga ve Bitkiler",
          ["tree", "flower", "plant", "leaf", "seed", "root", "garden", "grow", "water", "sunlight"],
          "Plants need water and sunlight. The flower is beautiful.",
          {"listening": "Doga kelimelerini dinler.", "speaking": "Bitkileri anlatir.", "reading": "Bitki posteri okur.", "writing": "Bitki gunlugu yazar."},
          ["Doga", "Bitkiler"]),
    _week(29, "Environment", "Cevre",
          ["recycle", "clean", "dirty", "rubbish", "bin", "save", "protect", "earth", "air", "reduce"],
          "Recycle paper! Save water! Keep the park clean!",
          {"listening": "Cevre mesajlarini dinler.", "speaking": "Cevre tavsiyesi verir.", "reading": "Cevre posteri okur.", "writing": "Cevre slogani yazar."},
          ["Cevre"]),
    _week(30, "Outdoor Activities", "Dis Mekan Aktiviteleri",
          ["camping", "fishing", "hiking", "cycling", "picnic", "barbecue", "tent", "backpack", "compass", "adventure"],
          "Let's go camping! I like hiking.",
          {"listening": "Aktivite planlarini dinler.", "speaking": "Aktivite onerisi yapar.", "reading": "Kamp rehberi okur.", "writing": "Hafta sonu plani yazar."},
          ["Aktiviteler"]),

    # ── Unit 9: Stories & Books (positions 30-32, weeks 31-33) ──
    _week(31, "Stories & Books", "Hikayeler ve Kitaplar",
          ["story", "character", "beginning", "end", "author", "title", "library", "bookmark", "page", "read"],
          "The story begins... I love reading books.",
          {"listening": "Hikaye dinler.", "speaking": "Hikaye anlatir.", "reading": "Kisa hikaye okur.", "writing": "Hikaye sonu yazar."},
          ["Hikaye"]),
    _week(32, "Fairy Tales", "Peri Masallari",
          ["princess", "prince", "king", "queen", "castle", "dragon", "forest", "magic", "brave", "kind"],
          "The princess is kind. The dragon is big.",
          {"listening": "Masal dinler.", "speaking": "Masal anlatir.", "reading": "Kisa masal okur.", "writing": "Masal karakteri cizer ve yazar."},
          ["Hikaye"]),
    _week(33, "Musical Instruments", "Muzik Aletleri",
          ["guitar", "piano", "drum", "flute", "violin", "trumpet", "tambourine", "play", "music", "band"],
          "I can play the guitar. She plays the piano.",
          {"listening": "Muzik aletlerini dinler.", "speaking": "Caldigi aleti soyler.", "reading": "Muzik kulubunu okur.", "writing": "Muzik tercihini yazar."},
          ["Muzik"]),

    # ── Unit 10: Talent Show & Graduation (positions 33-35, weeks 34-36) ──
    _week(34, "Talent Show & Graduation", "Yetenek Gosterisi ve Mezuniyet",
          ["talent", "perform", "stage", "audience", "sing", "dance", "act", "clap", "confident", "proud"],
          "Welcome to our talent show! I can sing and dance.",
          {"listening": "Gosteri diyaloglarini dinler.", "speaking": "Yeteneklerini sunar.", "reading": "Gosteri programi okur.", "writing": "Gosteri hakkinda yazar."},
          ["Gosteri"]),
    _week(35, "Show & Tell", "Goster ve Anlat",
          ["show", "tell", "project", "poster", "present", "favourite", "special", "collection", "proud", "share"],
          "This is my project. Let me show you.",
          {"listening": "Sunumlari dinler.", "speaking": "Sunum yapar.", "reading": "Proje notlarini okur.", "writing": "Sunum notu yazar."},
          ["Sunum"]),
    _week(36, "End-of-Year Party", "Yil Sonu Partisi",
          ["party", "friend", "memory", "thank you", "goodbye", "see you", "next year", "happy", "celebrate", "together"],
          "Thank you, teacher! See you next year!",
          {"listening": "Veda mesajlarini dinler.", "speaking": "Veda eder.", "reading": "Tesekkur karti okur.", "writing": "Tesekkur karti yazar."},
          ["Kutlamalar"]),
]


# ══════════════════════════════════════════════════════════════════════════════
# GRADE 3 — A1 (Elementary)
# Content bank units:
#   1. Friends & Feelings  2. Our City  3. Food Around the World
#   4. Earth & Nature  5. Inventions & Technology  6. Arts & Music
#   7. Space  8. Health & Hygiene  9. Legends & Folk Tales
#   10. End of Year Show
# ══════════════════════════════════════════════════════════════════════════════

CURRICULUM_GRADE3 = [
    # ── Unit 1: Friends & Feelings (positions 0-3, weeks 1-4) ──
    _week(1, "Friends & Feelings", "Arkadaslar ve Duygular",
          ["friend", "best friend", "classmate", "kind", "funny", "clever", "friendly", "share", "together", "feel"],
          "My best friend is Elif. She is kind and funny.",
          {"listening": "Arkadas anlatimlarini dinler.", "speaking": "Arkadasini tanitir.", "reading": "Arkadas mektubunu okur.", "writing": "Arkadasini anlatir."},
          ["Iliskiler", "Duygular"]),
    _week(2, "Describing People", "Kisileri Tanimlama",
          ["hair", "eyes", "glasses", "beard", "slim", "tall", "short", "dark", "fair", "curly"],
          "He has dark hair and brown eyes. She wears glasses.",
          {"listening": "Fiziksel betimlemeleri dinler.", "speaking": "Birini betimler.", "reading": "Kisi tasviri okur.", "writing": "Aile uyesini betimler."},
          ["Kisisel"]),
    _week(3, "Emotions & Empathy", "Duygular ve Empati",
          ["happy", "sad", "angry", "excited", "worried", "scared", "surprised", "proud", "calm", "shy"],
          "How do you feel? I feel excited. Are you okay?",
          {"listening": "Duygu diyaloglarini dinler.", "speaking": "Duygularini ifade eder.", "reading": "Duygu hikayesi okur.", "writing": "Duygularini yazar."},
          ["Duygular"]),
    _week(4, "Likes & Dislikes", "Sevmek ve Sevmemek",
          ["love", "like", "enjoy", "hate", "dislike", "prefer", "favourite", "best", "worst", "opinion"],
          "I love chocolate but I don't like onions.",
          {"listening": "Tercih diyaloglarini dinler.", "speaking": "Tercihlerini belirtir.", "reading": "Anket sonuclarini okur.", "writing": "Tercih paragraf yazar."},
          ["Kisisel"]),

    # ── Unit 2: Our City (positions 4-7, weeks 5-8) ──
    _week(5, "Our City", "Bizim Sehrimiz",
          ["town", "city", "village", "street", "avenue", "building", "bridge", "statue", "square", "centre"],
          "I live in a city. There is a park in the centre.",
          {"listening": "Sehir tariflerini dinler.", "speaking": "Sehrini anlatir.", "reading": "Sehir rehberi okur.", "writing": "Sehrini anlatir."},
          ["Sehir"]),
    _week(6, "Giving Directions", "Yon Tarifi",
          ["turn left", "turn right", "go straight", "cross", "corner", "traffic lights", "roundabout", "map", "lost", "excuse me"],
          "Excuse me, where is the hospital? Turn right at the traffic lights.",
          {"listening": "Yon tariflerini dinler.", "speaking": "Yon tarif eder.", "reading": "Harita okur.", "writing": "Yon tarifi yazar."},
          ["Sehir"]),
    _week(7, "Shopping in the City", "Sehirde Alisveris",
          ["shop", "supermarket", "price", "cheap", "expensive", "buy", "sell", "receipt", "change", "basket"],
          "How much is this? It's ten lira.",
          {"listening": "Alisveris diyaloglarini dinler.", "speaking": "Alisveris yapar.", "reading": "Fiyat listesi okur.", "writing": "Alisveris listesi yazar."},
          ["Alisveris"]),
    _week(8, "Places & Services", "Yerler ve Hizmetler",
          ["library", "hospital", "fire station", "police station", "museum", "cinema", "stadium", "restaurant", "bank", "pharmacy"],
          "The library is next to the park. I go to the cinema on Saturdays.",
          {"listening": "Yer tariflerini dinler.", "speaking": "Yerleri anlatir.", "reading": "Sehir haritasi okur.", "writing": "Mahallesi hakkinda yazar."},
          ["Sehir"]),

    # ── Unit 3: Food Around the World (positions 8-11, weeks 9-12) ──
    _week(9, "Food Around the World", "Dunyanin Yemekleri",
          ["sushi", "pasta", "curry", "taco", "kebab", "croissant", "noodles", "national", "cuisine", "taste"],
          "Sushi is from Japan. Kebab is Turkish. I want to try tacos!",
          {"listening": "Farkli mutfaklari dinler.", "speaking": "Ulkelerin yemeklerini anlatir.", "reading": "Dunya mutfagi metnini okur.", "writing": "Favori mutfagini yazar."},
          ["Yiyecekler", "Dunya"]),
    _week(10, "Meals & Menus", "Ogunler ve Menuler",
          ["breakfast", "lunch", "dinner", "snack", "delicious", "healthy", "menu", "order", "waiter", "restaurant"],
          "What would you like? I'd like pizza, please.",
          {"listening": "Restoran diyaloglarini dinler.", "speaking": "Siparis verir.", "reading": "Menu okur.", "writing": "Favori yemek tarifini yazar."},
          ["Yiyecekler"]),
    _week(11, "Telling Time", "Saat Soyleme",
          ["quarter past", "quarter to", "half past", "o'clock", "a.m.", "p.m.", "midnight", "noon", "schedule", "alarm"],
          "It's quarter past nine. School starts at half past eight.",
          {"listening": "Saat ifadelerini dinler.", "speaking": "Saati dogruca soyler.", "reading": "Program okur.", "writing": "Gunluk programini yazar."},
          ["Zaman"]),
    _week(12, "Daily Life", "Gunluk Hayat",
          ["routine", "wake up", "have breakfast", "go to school", "come home", "do homework", "play", "have dinner", "go to bed", "every day"],
          "I wake up at seven every day. I always do my homework.",
          {"listening": "Rutin anlatimlarini dinler.", "speaking": "Gunluk rutinini anlatir.", "reading": "Bir cocugun gununu okur.", "writing": "Kendi gununu yazar."},
          ["Gunluk Yasam"]),

    # ── Unit 4: Earth & Nature (positions 12-15, weeks 13-16) ──
    _week(13, "Earth & Nature", "Dunya ve Doga",
          ["earth", "ocean", "continent", "mountain", "river", "forest", "desert", "island", "valley", "lake"],
          "The Earth has seven continents. The Amazon is a big forest.",
          {"listening": "Doga bilgilerini dinler.", "speaking": "Dogayi anlatir.", "reading": "Doga kartlarini okur.", "writing": "Doga tasviri yazar."},
          ["Doga", "Dunya"]),
    _week(14, "Seasons & Weather", "Mevsimler ve Hava",
          ["temperature", "degrees", "forecast", "umbrella", "sunglasses", "raincoat", "boots", "warm", "cool", "season"],
          "It's twenty degrees. Take your umbrella.",
          {"listening": "Hava tahminlerini dinler.", "speaking": "Havayi anlatir.", "reading": "Hava raporu okur.", "writing": "Mevsim paragraf yazar."},
          ["Hava Durumu"]),
    _week(15, "Animals Around the World", "Dunyadaki Hayvanlar",
          ["habitat", "endangered", "protect", "wild", "domestic", "ocean", "desert", "jungle", "Arctic", "species"],
          "Polar bears live in the Arctic. We must protect endangered animals.",
          {"listening": "Hayvan belgeselini dinler.", "speaking": "Hayvan anlatir.", "reading": "Hayvan ansiklopedisini okur.", "writing": "Hayvan profili yazar."},
          ["Hayvanlar"]),
    _week(16, "Environment", "Cevre",
          ["pollution", "recycle", "reduce", "reuse", "energy", "solar", "waste", "nature", "forest", "global warming"],
          "We should recycle. Don't waste water!",
          {"listening": "Cevre mesajlarini dinler.", "speaking": "Cevre oneri verir.", "reading": "Cevre makalesini okur.", "writing": "Cevre posteri yazar."},
          ["Cevre"]),

    # ── Unit 5: Inventions & Technology (positions 16-19, weeks 17-20) ──
    _week(17, "Inventions & Technology", "Icatlar ve Teknoloji",
          ["invent", "inventor", "discovery", "science", "technology", "electricity", "telephone", "computer", "important", "change"],
          "Thomas Edison invented the light bulb. Technology changes our lives.",
          {"listening": "Icat hikayelerini dinler.", "speaking": "Onemli icatlari anlatir.", "reading": "Icat hakkinda okur.", "writing": "Icat hakkinda yazar."},
          ["Bilim", "Teknoloji"]),
    _week(18, "Computers & Internet", "Bilgisayar ve Internet",
          ["computer", "tablet", "phone", "internet", "game", "video", "photo", "email", "message", "search"],
          "I use a tablet for homework. Be safe online!",
          {"listening": "Teknoloji kullanimini dinler.", "speaking": "Teknoloji kullanimini anlatir.", "reading": "Internet guvenligini okur.", "writing": "Teknoloji kullanimini yazar."},
          ["Teknoloji"]),
    _week(19, "Numbers & Counting", "Sayilar ve Sayma",
          ["hundred", "thousand", "count", "add", "minus", "total", "first", "second", "third", "last"],
          "There are three hundred students. She is the first.",
          {"listening": "Buyuk sayilari dinler.", "speaking": "Sirali sayilari kullanir.", "reading": "Istatistik okur.", "writing": "Sayisal bilgi yazar."},
          ["Sayilar"]),
    _week(20, "Transport", "Ulasim",
          ["bus", "train", "plane", "ship", "ferry", "taxi", "tram", "metro", "ticket", "station"],
          "I go to school by bus. Let's take the metro.",
          {"listening": "Ulasim bilgilerini dinler.", "speaking": "Ulasim araclarini kullanir.", "reading": "Bilet okur.", "writing": "Yolculugunu anlatir."},
          ["Ulasim"]),

    # ── Unit 6: Arts & Music (positions 20-23, weeks 21-24) ──
    _week(21, "Arts & Music", "Sanat ve Muzik",
          ["paint", "draw", "sculpt", "craft", "pottery", "origami", "canvas", "gallery", "masterpiece", "artist"],
          "I painted a landscape. She made an origami crane. Let's visit the gallery.",
          {"listening": "Sanat etkinlik anlatimlarini dinler.", "speaking": "Sanat eserini anlatir.", "reading": "Sanat sergi rehberini okur.", "writing": "Sanat eserini tasvir eder."},
          ["Sanat"]),
    _week(22, "Musical World", "Muzik Dunyasi",
          ["guitar", "piano", "drum", "flute", "violin", "concert", "melody", "rhythm", "song", "band"],
          "I can play the guitar. Let's go to the concert!",
          {"listening": "Muzik aletlerini dinler.", "speaking": "Muzik zevkini anlatir.", "reading": "Muzik dergisi okur.", "writing": "Muzik tercihini yazar."},
          ["Muzik"]),
    _week(23, "Hobbies & Free Time", "Hobiler ve Bos Zaman",
          ["hobby", "collect", "stamp", "coin", "model", "chess", "skateboard", "photography", "free time", "weekend"],
          "My hobby is collecting stamps. What do you do at weekends?",
          {"listening": "Hobi anlatimlarini dinler.", "speaking": "Hobilerini anlatir.", "reading": "Hobi dergisi okur.", "writing": "Hobisini anlatir."},
          ["Hobiler"]),
    _week(24, "Sports & Games", "Sporlar ve Oyunlar",
          ["match", "score", "team", "player", "coach", "practice", "win", "lose", "champion", "medal"],
          "Our team won the match! The score is 3-1.",
          {"listening": "Spor haberlerini dinler.", "speaking": "Mac anlatir.", "reading": "Spor haberini okur.", "writing": "Favori sporunu anlatir."},
          ["Spor"]),

    # ── Unit 7: Space (positions 24-26, weeks 25-27) ──
    _week(25, "Space", "Uzay",
          ["space", "planet", "star", "moon", "sun", "rocket", "astronaut", "orbit", "galaxy", "telescope"],
          "The sun is a star. There are eight planets in our solar system.",
          {"listening": "Uzay bilgilerini dinler.", "speaking": "Gezegenleri anlatir.", "reading": "Uzay ansiklopedisi okur.", "writing": "Gezegen profili yazar."},
          ["Bilim", "Uzay"]),
    _week(26, "The World", "Dunya",
          ["country", "continent", "ocean", "language", "population", "culture", "national", "international", "global", "diverse"],
          "There are seven continents. People speak many languages.",
          {"listening": "Dunya bilgilerini dinler.", "speaking": "Ulkeleri anlatir.", "reading": "Ulke kartlarini okur.", "writing": "Ulke profili yazar."},
          ["Dunya"]),
    _week(27, "Travel & Exploration", "Seyahat ve Kesif",
          ["travel", "trip", "journey", "suitcase", "passport", "airport", "hotel", "tourist", "visit", "explore"],
          "We are going to Antalya. I packed my suitcase.",
          {"listening": "Seyahat planlarini dinler.", "speaking": "Seyahat planini anlatir.", "reading": "Seyahat blogunu okur.", "writing": "Seyahat plani yazar."},
          ["Seyahat"]),

    # ── Unit 8: Health & Hygiene (positions 27-29, weeks 28-30) ──
    _week(28, "Health & Hygiene", "Saglik ve Hijyen",
          ["headache", "stomachache", "fever", "cold", "cough", "medicine", "rest", "hospital", "sick", "well"],
          "I have a headache. You should rest. Wash your hands often.",
          {"listening": "Saglik diyaloglarini dinler.", "speaking": "Hastaligini anlatir.", "reading": "Saglik onerisi okur.", "writing": "Doktora mektup yazar."},
          ["Saglik"]),
    _week(29, "Healthy Habits", "Saglikli Aliskanliklar",
          ["exercise", "vitamin", "protein", "balanced diet", "junk food", "fitness", "hygiene", "brush teeth", "clean hands", "sleep"],
          "Exercise every day! Eat a balanced diet. Keep your hands clean.",
          {"listening": "Saglik tavsiyelerini dinler.", "speaking": "Saglik tavsiyeleri verir.", "reading": "Saglik rehberini okur.", "writing": "Saglikli yasam plani yazar."},
          ["Saglik"]),
    _week(30, "Festivals & Traditions", "Festival ve Gelenekler",
          ["festival", "tradition", "celebrate", "custom", "costume", "parade", "fireworks", "feast", "ceremony", "heritage"],
          "We celebrate Republic Day on October 29th.",
          {"listening": "Festival anlatimlarini dinler.", "speaking": "Bayram geleneklerini anlatir.", "reading": "Festival bilgisi okur.", "writing": "Bayram anisini yazar."},
          ["Kultur"]),

    # ── Unit 9: Legends & Folk Tales (positions 30-32, weeks 31-33) ──
    _week(31, "Legends & Folk Tales", "Efsaneler ve Halk Hikayeleri",
          ["legend", "folk tale", "hero", "villain", "brave", "wise", "moral", "ancient", "storyteller", "tradition"],
          "Long ago, there was a brave hero. The moral of the story is...",
          {"listening": "Efsane dinler.", "speaking": "Halk hikayesi anlatir.", "reading": "Efsane metnini okur.", "writing": "Kendi efsanesini yazar."},
          ["Hikaye", "Kultur"]),
    _week(32, "Stories & Books", "Hikayeler ve Kitaplar",
          ["story", "character", "beginning", "middle", "end", "author", "title", "chapter", "library", "bookmark"],
          "The story begins... The character is brave.",
          {"listening": "Hikaye dinler.", "speaking": "Hikaye anlatir.", "reading": "Kisa hikaye okur.", "writing": "Hikaye sonu yazar."},
          ["Hikaye"]),
    _week(33, "Famous People", "Unlu Kisiler",
          ["famous", "scientist", "artist", "athlete", "musician", "writer", "leader", "achievement", "inspire", "biography"],
          "Ataturk was a great leader. She is a famous scientist.",
          {"listening": "Biyografi dinler.", "speaking": "Unlu birini anlatir.", "reading": "Biyografi okur.", "writing": "Mini biyografi yazar."},
          ["Biyografi"]),

    # ── Unit 10: End of Year Show (positions 33-35, weeks 34-36) ──
    _week(34, "End of Year Show", "Yil Sonu Gosterisi",
          ["show", "performance", "stage", "act", "sing", "dance", "costume", "rehearsal", "audience", "applause"],
          "Welcome to our show! Let's perform together!",
          {"listening": "Gosteri talimatlarini dinler.", "speaking": "Sahnede rol alir.", "reading": "Gosteri programi okur.", "writing": "Gosteri hakkinda yazar."},
          ["Gosteri"]),
    _week(35, "Project Showcase", "Proje Sergisi",
          ["showcase", "exhibition", "display", "explain", "audience", "feedback", "improve", "creative", "original", "teamwork"],
          "Welcome to our project showcase!",
          {"listening": "Sunumlari dinler.", "speaking": "Projelerini sunar.", "reading": "Proje ozetini okur.", "writing": "Proje ozeti yazar."},
          ["Projeler"]),
    _week(36, "Year-End Celebration", "Yil Sonu Kutlamasi",
          ["celebration", "award", "certificate", "memory", "gratitude", "farewell", "summer", "holiday", "happy", "proud"],
          "Congratulations! Have a wonderful summer!",
          {"listening": "Toren konusmasini dinler.", "speaking": "Tesekkur eder.", "reading": "Sertifika okur.", "writing": "Tesekkur mektubu yazar."},
          ["Kutlamalar"]),
]


# ══════════════════════════════════════════════════════════════════════════════
# GRADE 4 — A1+ (Elementary Plus)
# Content bank units:
#   1. New Beginnings  2. Comparisons & Descriptions  3. Time & Memory
#   4. Global Perspectives  5. Communication Challenges
#   6. Classroom Community  7. Planning & Organizing
#   8. Nature Exploration  9. Astronomy  10. Celebrations & Endings
# ══════════════════════════════════════════════════════════════════════════════

CURRICULUM_GRADE4 = [
    # ── Unit 1: New Beginnings (positions 0-3, weeks 1-4) ──
    _week(1, "New Beginnings", "Yeni Baslangilar",
          ["beginning", "goal", "resolution", "improve", "challenge", "confident", "motivation", "progress", "practice", "skill"],
          "This year I will improve my English. My goal is to read more books.",
          {"listening": "Hedef belirleme diyaloglarini dinler.", "speaking": "Yillik hedeflerini anlatir.", "reading": "Motivasyon metnini okur.", "writing": "Yeni yil kararlari yazar."},
          ["Kisisel"]),
    _week(2, "Back to School", "Okula Donus",
          ["classmate", "subject", "timetable", "break time", "canteen", "library", "homework", "study", "learn", "favourite"],
          "What's your favourite subject? My favourite subject is English.",
          {"listening": "Okul diyaloglarini dinler.", "speaking": "Okul hayatini anlatir.", "reading": "Okul tanitimini okur.", "writing": "Ders programini yazar."},
          ["Okul"]),
    _week(3, "Rules & Obligations", "Kurallar ve Zorunluluklar",
          ["must", "mustn't", "have to", "should", "shouldn't", "rule", "obey", "follow", "allowed", "forbidden"],
          "You must wear a uniform. You shouldn't run in the corridor.",
          {"listening": "Kural aciklamalarini dinler.", "speaking": "Kurallari soyler.", "reading": "Okul kurallarini okur.", "writing": "Sinif kurallari poster yazar."},
          ["Kurallar"]),
    _week(4, "Countries & Nationalities", "Ulkeler ve Milletler",
          ["Turkish", "English", "American", "German", "French", "Japanese", "Italian", "Spanish", "nationality", "language"],
          "I'm Turkish. She's from Japan. He speaks French.",
          {"listening": "Milliyet diyaloglarini dinler.", "speaking": "Kokenini soyler.", "reading": "Ulke profili okur.", "writing": "Ulke profili yazar."},
          ["Dunya"]),

    # ── Unit 2: Comparisons & Descriptions (positions 4-7, weeks 5-8) ──
    _week(5, "Comparisons & Descriptions", "Karsilastirmalar ve Tanimlamalar",
          ["bigger", "smaller", "taller", "shorter", "faster", "slower", "better", "worse", "more", "less"],
          "Elephants are bigger than cats. Cheetahs are the fastest animals.",
          {"listening": "Karsilastirma cumlelerini dinler.", "speaking": "Nesneleri karsilastirir.", "reading": "Karsilastirma metni okur.", "writing": "Iki seyi karsilastirir."},
          ["Gramer"]),
    _week(6, "Describing People", "Kisileri Tanimlama",
          ["appearance", "personality", "kind", "generous", "clever", "shy", "brave", "honest", "curly", "straight"],
          "She is kind and clever. He has curly hair and brown eyes.",
          {"listening": "Kisi betimlemelerini dinler.", "speaking": "Birini betimler.", "reading": "Kisi tasviri okur.", "writing": "Arkadasini tasvir eder."},
          ["Kisisel"]),
    _week(7, "Outdoor Adventures", "Dogada Macera",
          ["camp", "hike", "explore", "discover", "trail", "lake", "cave", "waterfall", "scenery", "wildlife"],
          "We went hiking in the forest. The scenery was beautiful.",
          {"listening": "Macera hikayelerini dinler.", "speaking": "Doga deneyimini anlatir.", "reading": "Macera gunlugu okur.", "writing": "Macera gunlugu yazar."},
          ["Doga"]),
    _week(8, "Describing Places", "Yerleri Tanimlama",
          ["beautiful", "crowded", "quiet", "modern", "ancient", "famous", "huge", "tiny", "peaceful", "noisy"],
          "Istanbul is a huge city. The village is quiet and peaceful.",
          {"listening": "Yer betimlemelerini dinler.", "speaking": "Yerleri betimler.", "reading": "Sehir tasviri okur.", "writing": "Bir yeri tasvir eder."},
          ["Sehir"]),

    # ── Unit 3: Time & Memory (positions 8-11, weeks 9-12) ──
    _week(9, "Time & Memory", "Zaman ve Ani",
          ["yesterday", "last week", "ago", "went", "saw", "ate", "played", "visited", "bought", "had"],
          "I went to the park yesterday. We visited our grandparents last week.",
          {"listening": "Gecmis anlatimlarini dinler.", "speaking": "Dun ne yaptigini anlatir.", "reading": "Gunluk okur.", "writing": "Dunku gunu anlatir."},
          ["Gramer"]),
    _week(10, "History & Heritage", "Tarih ve Miras",
          ["ancient", "modern", "century", "empire", "battle", "discovery", "civilization", "monument", "museum", "historical"],
          "The Ottoman Empire was very large. Let's visit the museum.",
          {"listening": "Tarih hikayelerini dinler.", "speaking": "Tarihi olayi anlatir.", "reading": "Tarih metni okur.", "writing": "Tarih odevini yazar."},
          ["Tarih"]),
    _week(11, "Special Memories", "Ozel Anilar",
          ["remember", "memory", "childhood", "experience", "unforgettable", "exciting", "photo album", "diary", "holiday", "adventure"],
          "I remember my first day at school. It was an unforgettable experience.",
          {"listening": "Ani anlatimlarini dinler.", "speaking": "Ozel anisini paylasir.", "reading": "Ani defteri okur.", "writing": "Bir anisini yazar."},
          ["Kisisel"]),
    _week(12, "Natural Disasters", "Dogal Afetler",
          ["earthquake", "flood", "storm", "tornado", "volcano", "tsunami", "emergency", "safety", "prepare", "rescue"],
          "Turkey has earthquakes. We must be prepared.",
          {"listening": "Afet bilgilerini dinler.", "speaking": "Guvenlik kurallarini anlatir.", "reading": "Afet rehberini okur.", "writing": "Guvenlik plani yazar."},
          ["Guvenlik"]),

    # ── Unit 4: Global Perspectives (positions 12-15, weeks 13-16) ──
    _week(13, "Global Perspectives", "Kuresel Bakis Acilari",
          ["global", "culture", "diversity", "tradition", "custom", "respect", "tolerance", "international", "world", "citizen"],
          "Every culture is special. We should respect diversity.",
          {"listening": "Kuresel konulari dinler.", "speaking": "Farkli kulturleri tartisir.", "reading": "Kultur metni okur.", "writing": "Kultur tanitmasi yazar."},
          ["Dunya", "Kultur"]),
    _week(14, "Turkish Culture", "Turk Kulturu",
          ["tradition", "custom", "ceremony", "hospitality", "cuisine", "handicraft", "folklore", "heritage", "museum", "ancestor"],
          "Turkish hospitality is famous. Our handicrafts are beautiful.",
          {"listening": "Kultur anlatimlarini dinler.", "speaking": "Kultur ozelliklerini anlatir.", "reading": "Kultur metnini okur.", "writing": "Kultur tanitmasi yazar."},
          ["Kultur"]),
    _week(15, "Jobs & Careers", "Meslekler ve Kariyerler",
          ["engineer", "architect", "lawyer", "programmer", "journalist", "designer", "scientist", "manager", "career", "profession"],
          "I want to be an engineer. She works as a designer.",
          {"listening": "Meslek anlatimlarini dinler.", "speaking": "Gelecek meslegini anlatir.", "reading": "Meslek profilini okur.", "writing": "Meslek arastirmasi yazar."},
          ["Meslekler"]),
    _week(16, "Social Responsibility", "Toplumsal Sorumluluk",
          ["volunteer", "donate", "community", "charity", "support", "campaign", "awareness", "action", "citizen", "contribute"],
          "We volunteered at the animal shelter. Help your community!",
          {"listening": "Gonullu calisma hikayelerini dinler.", "speaking": "Toplumsal projelerini anlatir.", "reading": "Kampanya bildirisi okur.", "writing": "Kampanya posteri yazar."},
          ["Degerler"]),

    # ── Unit 5: Communication Challenges (positions 16-19, weeks 17-20) ──
    _week(17, "Communication Challenges", "Iletisim Zorluklari",
          ["phone", "call", "message", "email", "letter", "postcard", "invitation", "respond", "contact", "communicate"],
          "Can I speak to Ali, please? I'll send you a message.",
          {"listening": "Telefon diyaloglarini dinler.", "speaking": "Telefonda konusur.", "reading": "Mesaj ve email okur.", "writing": "Email yazar."},
          ["Iletisim"]),
    _week(18, "Digital Citizenship", "Dijital Vatandaslik",
          ["cyberbullying", "privacy", "password", "safe", "responsible", "digital", "footprint", "share", "respect", "report"],
          "Keep your password safe. Don't share personal information.",
          {"listening": "Dijital guvenlik tavsiyelerini dinler.", "speaking": "Internet kurallari tartisir.", "reading": "Guvenlik rehberini okur.", "writing": "Dijital guvenlik poster yazar."},
          ["Teknoloji"]),
    _week(19, "Media & News", "Medya ve Haberler",
          ["news", "newspaper", "magazine", "reporter", "interview", "headline", "article", "broadcast", "channel", "press"],
          "I read the news every day. The reporter interviewed the mayor.",
          {"listening": "Haber dinler.", "speaking": "Haber anlatir.", "reading": "Gazete makalesi okur.", "writing": "Kisa haber yazar."},
          ["Medya"]),
    _week(20, "Debate & Opinions", "Tartisma ve Gorusler",
          ["debate", "argument", "opinion", "agree", "disagree", "point", "evidence", "persuade", "topic", "conclusion"],
          "I agree with you. In my opinion...",
          {"listening": "Tartisma dinler.", "speaking": "Fikrini savunur.", "reading": "Tartisma metni okur.", "writing": "Fikir paragraf yazar."},
          ["Iletisim"]),

    # ── Unit 6: Classroom Community (positions 20-23, weeks 21-24) ──
    _week(21, "Classroom Community", "Sinif Toplulugu",
          ["team", "cooperate", "role", "leader", "participate", "contribute", "goal", "plan", "delegate", "celebrate"],
          "Let's work together! Everyone has a role in our class.",
          {"listening": "Takim calismasi talimatlarini dinler.", "speaking": "Takimda gorevini anlatir.", "reading": "Takim projesi okur.", "writing": "Takim plani yazar."},
          ["Sosyal"]),
    _week(22, "Emotions & Empathy", "Duygular ve Empati",
          ["empathy", "understand", "support", "comfort", "worry", "relieved", "grateful", "disappointed", "confident", "sensitive"],
          "I understand how you feel. Don't worry, I'm here for you.",
          {"listening": "Duygu diyaloglarini dinler.", "speaking": "Destek ifadeleri kullanir.", "reading": "Duygu hikayesi okur.", "writing": "Empati mektubu yazar."},
          ["SEL"]),
    _week(23, "Our Values", "Degerlerimiz",
          ["respect", "honesty", "kindness", "responsibility", "courage", "peace", "equality", "justice", "empathy", "cooperation"],
          "Be kind to everyone. Respect each other.",
          {"listening": "Deger hikayelerini dinler.", "speaking": "Degerleri tartisir.", "reading": "Deger hikayesi okur.", "writing": "Deger posteri yazar."},
          ["Degerler"]),
    _week(24, "Arts & Crafts", "Sanat ve El Isi",
          ["paint", "draw", "sculpt", "craft", "pottery", "origami", "collage", "canvas", "gallery", "masterpiece"],
          "I painted a landscape. She made an origami crane.",
          {"listening": "Sanat etkinlik anlatimlarini dinler.", "speaking": "Sanat eserini anlatir.", "reading": "Sanat sergi rehberini okur.", "writing": "Sanat eserini tasvir eder."},
          ["Sanat"]),

    # ── Unit 7: Planning & Organizing (positions 24-26, weeks 25-27) ──
    _week(25, "Planning & Organizing", "Planlama ve Organizasyon",
          ["going to", "plan", "intend", "will", "tomorrow", "next week", "future", "arrangement", "appointment", "schedule"],
          "I'm going to visit the museum tomorrow. We will have a picnic.",
          {"listening": "Plan diyaloglarini dinler.", "speaking": "Planlarini anlatir.", "reading": "Etkinlik programi okur.", "writing": "Hafta sonu planini yazar."},
          ["Gelecek"]),
    _week(26, "Cooking & Recipes", "Yemek ve Tarifler",
          ["recipe", "ingredient", "mix", "stir", "bake", "boil", "fry", "chop", "serve", "delicious"],
          "First, mix the flour and eggs. Then, bake for 30 minutes.",
          {"listening": "Tarif anlatimlarini dinler.", "speaking": "Yemek tarifi anlatir.", "reading": "Tarif okur.", "writing": "Favori tarifini yazar."},
          ["Yiyecekler"]),
    _week(27, "Problem Solving", "Problem Cozme",
          ["problem", "solution", "think", "analyse", "strategy", "option", "decide", "evaluate", "logic", "creative"],
          "What's the problem? Let's find a solution.",
          {"listening": "Problem senaryolarini dinler.", "speaking": "Cozum onerir.", "reading": "Problem hikayesi okur.", "writing": "Cozum mektubu yazar."},
          ["Dusunme"]),

    # ── Unit 8: Nature Exploration (positions 27-29, weeks 28-30) ──
    _week(28, "Nature Exploration", "Doga Kesfetme",
          ["explore", "discover", "habitat", "ecosystem", "wildlife", "species", "observe", "binoculars", "trail", "nature walk"],
          "Let's explore nature! I discovered a new species of butterfly.",
          {"listening": "Doga gezisi anlatimlarini dinler.", "speaking": "Doga gozlemlerini anlatir.", "reading": "Doga rehberini okur.", "writing": "Doga gunlugu yazar."},
          ["Doga"]),
    _week(29, "Green Planet", "Yesil Gezegen",
          ["renewable", "solar", "wind", "energy", "carbon", "footprint", "climate", "organic", "biodiversity", "sustainable"],
          "Solar energy is renewable. We should reduce our carbon footprint.",
          {"listening": "Cevre belgesi dinler.", "speaking": "Cevre cozumleri tartisir.", "reading": "Cevre makalesini okur.", "writing": "Cevre mektubu yazar."},
          ["Cevre"]),
    _week(30, "Science & Experiments", "Bilim ve Deneyler",
          ["experiment", "hypothesis", "observe", "measure", "result", "conclusion", "laboratory", "microscope", "chemical", "reaction"],
          "We did an experiment. First, we observed the reaction.",
          {"listening": "Deney talimatlarini dinler.", "speaking": "Deney anlatir.", "reading": "Deney raporu okur.", "writing": "Deney raporu yazar."},
          ["Bilim"]),

    # ── Unit 9: Astronomy (positions 30-32, weeks 31-33) ──
    _week(31, "Astronomy", "Astronomi",
          ["space", "planet", "star", "moon", "sun", "rocket", "astronaut", "orbit", "galaxy", "telescope"],
          "The sun is a star. There are eight planets in our solar system.",
          {"listening": "Uzay bilgilerini dinler.", "speaking": "Gezegenleri anlatir.", "reading": "Uzay ansiklopedisi okur.", "writing": "Gezegen profili yazar."},
          ["Bilim", "Uzay"]),
    _week(32, "Future Plans", "Gelecek Planlari",
          ["will", "going to", "someday", "dream", "achieve", "career", "university", "travel", "discover", "build"],
          "I will study hard. I'm going to be a scientist someday.",
          {"listening": "Gelecek plani diyaloglarini dinler.", "speaking": "Gelecek hayallerini anlatir.", "reading": "Basari hikayesi okur.", "writing": "Gelecek mektubu yazar."},
          ["Gelecek"]),
    _week(33, "Inventions of Turkey", "Turkiye'nin Icatlari",
          ["Turkish", "invention", "contribution", "science", "medicine", "architecture", "engineering", "innovation", "genius", "pioneer"],
          "Turkish scientists have made important contributions.",
          {"listening": "Turk bilim insanlarini dinler.", "speaking": "Turk icatlari anlatir.", "reading": "Bilim insani biyografisi okur.", "writing": "Icat profili yazar."},
          ["Bilim", "Kultur"]),

    # ── Unit 10: Celebrations & Endings (positions 33-35, weeks 34-36) ──
    _week(34, "Celebrations & Endings", "Kutlamalar ve Bitisler",
          ["celebrate", "award", "certificate", "achievement", "proud", "grateful", "ceremony", "speech", "memory", "milestone"],
          "We celebrate our achievements. I'm proud of our class!",
          {"listening": "Kutlama konusmalarini dinler.", "speaking": "Basarilarini paylasir.", "reading": "Toren programi okur.", "writing": "Tesekkur konusmasi yazar."},
          ["Kutlamalar"]),
    _week(35, "Portfolio Day", "Portfolyo Gunu",
          ["portfolio", "collection", "work", "progress", "reflect", "improve", "best work", "growth", "evidence", "proud"],
          "Look at my portfolio! I have improved a lot.",
          {"listening": "Portfolyo sunumlarini dinler.", "speaking": "Portfolyosunu sunar.", "reading": "Degerlendirme formunu okur.", "writing": "Oz degerlendirme yazar."},
          ["Degerlendirme"]),
    _week(36, "Farewell & New Adventures", "Veda ve Yeni Maceralar",
          ["farewell", "goodbye", "thank", "remember", "cherish", "adventure", "next", "middle school", "ready", "excited"],
          "Thank you for everything! I'm ready for middle school!",
          {"listening": "Veda konusmalarini dinler.", "speaking": "Tesekkur ve veda eder.", "reading": "Veda mektubunu okur.", "writing": "Veda mektubu yazar."},
          ["Kutlamalar"]),
]
