"""
Middle School (5-8) Interactive English Games
=============================================
CEFR A2.1-A2.4 level games for ortaokul.
"""


# ── GAME 1: Error Correction ──
def _build_ms_error_correction_html():
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Error Correction</title><style>"
        "*{margin:0;padding:0;box-sizing:border-box}"
        "body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#1a0533,#0d0221);color:#e9d5ff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center}"
        ".gbox{background:rgba(168,85,247,.13);border:2px solid rgba(168,85,247,.4);border-radius:20px;padding:30px;max-width:560px;width:90%;text-align:center}"
        "h1{font-size:1.5em;margin-bottom:8px;color:#c084fc}"
        ".info{font-size:.95em;margin-bottom:12px;color:#d8b4fe}"
        ".diff{display:inline-block;padding:3px 10px;border-radius:12px;font-size:.8em;margin-bottom:10px}"
        ".diff-easy{background:rgba(34,197,94,.25);color:#86efac}"
        ".diff-med{background:rgba(234,179,8,.25);color:#fde68a}"
        ".diff-hard{background:rgba(239,68,68,.25);color:#fca5a5}"
        ".sentence{font-size:1.2em;margin:16px 0;padding:16px;background:rgba(239,68,68,.12);border:2px solid rgba(239,68,68,.3);border-radius:14px;color:#fca5a5;line-height:1.6}"
        ".prompt{font-size:.95em;margin:8px 0;color:#fbbf24}"
        ".opts{display:flex;flex-direction:column;gap:10px;margin:14px 0}"
        ".opt{padding:13px 18px;font-size:1.05em;border-radius:12px;border:2px solid rgba(168,85,247,.4);background:rgba(168,85,247,.1);color:#e9d5ff;cursor:pointer;transition:.2s;text-align:left}"
        ".opt:hover{background:rgba(168,85,247,.25)}"
        ".opt.ok{background:rgba(34,197,94,.35);border-color:#22c55e}"
        ".opt.no{background:rgba(239,68,68,.3);border-color:#ef4444}"
        "#endScr{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(13,2,33,.93);z-index:99;flex-direction:column;align-items:center;justify-content:center}"
        "#endScr.show{display:flex}"
        ".ebtn{margin-top:18px;padding:12px 36px;font-size:1.1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        "</style></head><body><div class='gbox'>"
        "<h1>Error Correction</h1>"
        "<div class='info'>Round <span id='rn'>1</span>/10 &nbsp;|&nbsp; Score: <span id='sc'>0</span></div>"
        "<div id='diffBadge'></div>"
        "<div class='prompt'>Find the correct version of this sentence:</div>"
        "<div class='sentence' id='sent'></div>"
        "<div class='opts' id='opts'></div></div>"
        "<div id='endScr'><h1 id='et'></h1><p id='es' style='font-size:1.2em;margin-top:10px;color:#d8b4fe'></p>"
        "<button class='ebtn' onclick='init()'>Play Again</button></div>"
        "<script>"
        "var AC=new(window.AudioContext||window.webkitAudioContext)();"
        "function snd(f,d){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.value=.15;o.start();g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.stop(AC.currentTime+d)}"
        "function spk(t){try{var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}"
        "var DATA=["
        "{diff:'easy',wrong:'She go to school every day.',opts:['She goes to school every day.','She going to school every day.','She gone to school every day.'],ans:0},"
        "{diff:'easy',wrong:'I has two brothers.',opts:['I having two brothers.','I have two brothers.','I am has two brothers.'],ans:1},"
        "{diff:'easy',wrong:'He don\\'t like milk.',opts:['He doesn\\'t like milk.','He not like milk.','He don\\'t likes milk.'],ans:0},"
        "{diff:'med',wrong:'They was playing in park yesterday.',opts:['They were playing in park yesterday.','They was playing in the park yesterday.','They were playing in the park yesterday.'],ans:2},"
        "{diff:'med',wrong:'She is more taller than me.',opts:['She is more tall than me.','She is taller than me.','She is tallest than me.'],ans:1},"
        "{diff:'med',wrong:'I have been to London on 2019.',opts:['I have been to London at 2019.','I have been to London in 2019.','I have been to London for 2019.'],ans:1},"
        "{diff:'med',wrong:'He gave the book to I.',opts:['He gave the book to mine.','He gave the book to my.','He gave the book to me.'],ans:2},"
        "{diff:'hard',wrong:'If I will study hard, I will pass the exam.',opts:['If I study hard, I will pass the exam.','If I studied hard, I will pass the exam.','If I would study hard, I will pass the exam.'],ans:0},"
        "{diff:'hard',wrong:'The informations are useful for the project.',opts:['The information are useful for the project.','The information is useful for the project.','The informations is useful for the project.'],ans:1},"
        "{diff:'hard',wrong:'She asked me where do I live.',opts:['She asked me where I live.','She asked me where did I live.','She asked me where I do live.'],ans:0}];"
        "var rnd=0,score=0,canClick=true;"
        "function init(){rnd=0;score=0;document.getElementById('endScr').classList.remove('show');next()}"
        "function next(){if(rnd>=10){endGame();return}canClick=true;var d=DATA[rnd];"
        "document.getElementById('rn').textContent=rnd+1;document.getElementById('sc').textContent=score;"
        "var dc={easy:'diff-easy',med:'diff-med',hard:'diff-hard'};"
        "document.getElementById('diffBadge').innerHTML='<span class=\"diff '+dc[d.diff]+'\">'+{easy:'Easy',med:'Medium',hard:'Hard'}[d.diff]+'</span>';"
        "document.getElementById('sent').textContent=d.wrong;spk(d.wrong);"
        "var ops=document.getElementById('opts');ops.innerHTML='';"
        "d.opts.forEach(function(o,i){var b=document.createElement('div');b.className='opt';b.textContent=o;"
        "b.onclick=function(){pick(b,i===d.ans,o)};ops.appendChild(b)})}"
        "function pick(el,ok,txt){if(!canClick)return;canClick=false;"
        "if(ok){el.classList.add('ok');score++;snd(523,.2);document.getElementById('sc').textContent=score;spk(txt)}"
        "else{el.classList.add('no');snd(180,.3);var all=document.querySelectorAll('.opt');all.forEach(function(a,i){if(i===DATA[rnd].ans)a.classList.add('ok')})}"
        "rnd++;setTimeout(next,1200)}"
        "function endGame(){var t=score>=8?'Grammar Genius!':score>=5?'Good Job!':'Keep Practising!';"
        "document.getElementById('et').textContent=t;document.getElementById('es').textContent='Score: '+score+' / 10';"
        "document.getElementById('endScr').classList.add('show');spk(t+' You scored '+score+' out of 10')}"
        "init();</script></body></html>"
    )


# ── GAME 2: Cloze Master ──
def _build_ms_cloze_test_html():
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Cloze Master</title><style>"
        "*{margin:0;padding:0;box-sizing:border-box}"
        "body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#1a0533,#0d0221);color:#e9d5ff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center}"
        ".gbox{background:rgba(168,85,247,.13);border:2px solid rgba(168,85,247,.4);border-radius:20px;padding:30px;max-width:600px;width:92%;text-align:center}"
        "h1{font-size:1.5em;margin-bottom:8px;color:#c084fc}"
        ".info{font-size:.95em;margin-bottom:12px;color:#d8b4fe}"
        ".passage{font-size:1.08em;line-height:2;margin:14px 0;padding:18px;background:rgba(168,85,247,.08);border:1px solid rgba(168,85,247,.25);border-radius:14px;text-align:left;color:#e9d5ff}"
        ".passage select{background:rgba(168,85,247,.3);color:#fbbf24;border:2px solid rgba(168,85,247,.5);border-radius:8px;padding:4px 8px;font-size:.95em;cursor:pointer;margin:0 2px}"
        ".passage select option{background:#1a0533;color:#e9d5ff}"
        ".passage select.ok{border-color:#22c55e;background:rgba(34,197,94,.25);color:#86efac}"
        ".passage select.no{border-color:#ef4444;background:rgba(239,68,68,.2);color:#fca5a5}"
        ".abtn{margin:8px;padding:12px 28px;font-size:1.05em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        ".abtn:hover{background:linear-gradient(135deg,#c084fc,#a855f7)}"
        ".msg{font-size:1em;min-height:22px;color:#fbbf24;margin:8px 0}"
        "#endScr{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(13,2,33,.93);z-index:99;flex-direction:column;align-items:center;justify-content:center}"
        "#endScr.show{display:flex}"
        ".ebtn{margin-top:18px;padding:12px 36px;font-size:1.1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        "</style></head><body><div class='gbox'>"
        "<h1>Cloze Master</h1>"
        "<div class='info'>Passage <span id='pn'>1</span>/8 &nbsp;|&nbsp; Score: <span id='sc'>0</span></div>"
        "<div class='passage' id='passage'></div>"
        "<div class='msg' id='msg'></div>"
        "<button class='abtn' onclick='checkPassage()'>Check Answers</button></div>"
        "<div id='endScr'><h1 id='et'></h1><p id='es' style='font-size:1.2em;margin-top:10px;color:#d8b4fe'></p>"
        "<button class='ebtn' onclick='init()'>Play Again</button></div>"
        "<script>"
        "var AC=new(window.AudioContext||window.webkitAudioContext)();"
        "function snd(f,d){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.value=.15;o.start();g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.stop(AC.currentTime+d)}"
        "function spk(t){try{var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}"
        "var PASSAGES=["
        "{text:'My name is Emma. I {0} in a small town near London. Every morning, I {1} up at seven o\\'clock. I {2} breakfast with my family before I go to school.',blanks:["
        "{opts:['live','lives','living','lived'],ans:0},"
        "{opts:['wake','wakes','waking','waked'],ans:0},"
        "{opts:['has','have','having','had'],ans:1}]},"
        "{text:'Last summer, we {0} to the beach. The weather {1} really hot. We {2} in the sea all day and {3} ice cream in the evening.',blanks:["
        "{opts:['go','went','gone','going'],ans:1},"
        "{opts:['is','were','was','are'],ans:2},"
        "{opts:['swam','swim','swimming','swims'],ans:0},"
        "{opts:['eat','eating','eats','ate'],ans:3}]},"
        "{text:'Tom is {0} than his brother. He is the {1} boy in his class. He plays basketball {2} well because he is very {3}.',blanks:["
        "{opts:['tall','taller','tallest','more tall'],ans:1},"
        "{opts:['tall','taller','tallest','most tall'],ans:2},"
        "{opts:['much','very','too','enough'],ans:1},"
        "{opts:['athletic','athletics','athletically','athlete'],ans:0}]},"
        "{text:'I am going to {0} my grandmother next weekend. She lives {1} a village. I will {2} the bus because it is too far to walk.',blanks:["
        "{opts:['visit','visiting','visited','visits'],ans:0},"
        "{opts:['at','on','in','to'],ans:2},"
        "{opts:['take','taking','took','takes'],ans:0}]},"
        "{text:'Sarah {0} English for three years. She {1} speak it quite well now. She wants to {2} a teacher {3} the future.',blanks:["
        "{opts:['studies','has studied','is studying','study'],ans:1},"
        "{opts:['can','must','should','would'],ans:0},"
        "{opts:['become','becomes','becoming','became'],ans:0},"
        "{opts:['at','on','in','for'],ans:2}]},"
        "{text:'If it {0} tomorrow, we will stay at home. We {1} watch a film and eat popcorn. It will be {2} fun than going outside in the rain.',blanks:["
        "{opts:['rain','rains','rained','raining'],ans:1},"
        "{opts:['can','will','would','must'],ans:1},"
        "{opts:['most','much','more','many'],ans:2}]},"
        "{text:'There {0} a lot of people at the concert last night. The music was {1} loud. Everyone {2} dancing and singing together.',blanks:["
        "{opts:['are','was','were','is'],ans:2},"
        "{opts:['real','really','very much','too much'],ans:1},"
        "{opts:['is','was','were','are'],ans:1}]},"
        "{text:'You {0} brush your teeth twice a day. It is important {1} healthy habits. If you don\\'t take {2} of your teeth, you might get a toothache.',blanks:["
        "{opts:['can','should','would','might'],ans:1},"
        "{opts:['have','having','to have','has'],ans:2},"
        "{opts:['caring','cared','care','cares'],ans:2}]}];"
        "var pi=0,score=0,total=0;"
        "function init(){pi=0;score=0;total=0;document.getElementById('endScr').classList.remove('show');showPassage()}"
        "function showPassage(){if(pi>=8){endGame();return}"
        "document.getElementById('pn').textContent=pi+1;document.getElementById('sc').textContent=score;document.getElementById('msg').textContent='';"
        "var p=PASSAGES[pi],html=p.text;"
        "p.blanks.forEach(function(b,i){var sel='<select id=\"bl'+i+'\">';"
        "sel+='<option value=\"-1\">---</option>';"
        "b.opts.forEach(function(o,j){sel+='<option value=\"'+j+'\">'+o+'</option>'});"
        "sel+='</select>';html=html.replace('{'+i+'}',sel)});"
        "document.getElementById('passage').innerHTML=html}"
        "function checkPassage(){var p=PASSAGES[pi],correct=0,all=p.blanks.length;"
        "p.blanks.forEach(function(b,i){var sel=document.getElementById('bl'+i);var v=parseInt(sel.value);"
        "if(v===b.ans){sel.classList.add('ok');sel.classList.remove('no');correct++}"
        "else{sel.classList.add('no');sel.classList.remove('ok')}});"
        "total+=all;score+=correct;"
        "if(correct===all){snd(523,.2);document.getElementById('msg').textContent='Perfect! All correct!';document.getElementById('sc').textContent=score;"
        "pi++;setTimeout(showPassage,1400)}"
        "else{snd(180,.3);document.getElementById('msg').textContent=correct+'/'+all+' correct. Try again!';document.getElementById('sc').textContent=score}}"
        "function endGame(){var pct=Math.round(score/total*100);"
        "var t=pct>=80?'Cloze Master!':pct>=50?'Good Effort!':'Keep Reading!';"
        "document.getElementById('et').textContent=t;"
        "document.getElementById('es').textContent='Score: '+score+'/'+total+' ('+pct+'%)';"
        "document.getElementById('endScr').classList.add('show');spk(t+' You scored '+pct+' percent')}"
        "init();</script></body></html>"
    )


# ── GAME 3: Paragraph Puzzle ──
def _build_ms_paragraph_order_html():
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Paragraph Puzzle</title><style>"
        "*{margin:0;padding:0;box-sizing:border-box}"
        "body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#1a0533,#0d0221);color:#e9d5ff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center}"
        ".gbox{background:rgba(168,85,247,.13);border:2px solid rgba(168,85,247,.4);border-radius:20px;padding:30px;max-width:600px;width:92%;text-align:center}"
        "h1{font-size:1.5em;margin-bottom:8px;color:#c084fc}"
        ".info{font-size:.95em;margin-bottom:12px;color:#d8b4fe}"
        ".topic{font-size:.9em;color:#fbbf24;margin-bottom:10px}"
        ".slist{display:flex;flex-direction:column;gap:8px;margin:14px 0}"
        ".sitem{padding:12px 16px;font-size:1em;border-radius:12px;border:2px solid rgba(168,85,247,.35);background:rgba(168,85,247,.1);color:#e9d5ff;cursor:pointer;transition:.2s;text-align:left;user-select:none}"
        ".sitem:hover{background:rgba(168,85,247,.22)}"
        ".sitem.sel{border-color:#fbbf24;background:rgba(251,191,36,.15);color:#fbbf24}"
        ".sitem.placed{border-color:#22c55e;background:rgba(34,197,94,.15);color:#86efac}"
        ".ordered{display:flex;flex-direction:column;gap:6px;margin:10px 0;min-height:40px}"
        ".oitem{padding:10px 14px;font-size:.95em;border-radius:10px;background:rgba(34,197,94,.12);border:1px solid rgba(34,197,94,.3);color:#86efac;text-align:left;cursor:pointer}"
        ".oitem:hover{background:rgba(239,68,68,.15);border-color:#ef4444}"
        ".abtn{margin:6px;padding:10px 24px;font-size:1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        ".abtn:hover{background:linear-gradient(135deg,#c084fc,#a855f7)}"
        ".msg{font-size:1em;min-height:22px;color:#fbbf24;margin:6px 0}"
        "#endScr{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(13,2,33,.93);z-index:99;flex-direction:column;align-items:center;justify-content:center}"
        "#endScr.show{display:flex}"
        ".ebtn{margin-top:18px;padding:12px 36px;font-size:1.1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        "</style></head><body><div class='gbox'>"
        "<h1>Paragraph Puzzle</h1>"
        "<div class='info'>Round <span id='rn'>1</span>/8 &nbsp;|&nbsp; Score: <span id='sc'>0</span></div>"
        "<div class='topic' id='topic'></div>"
        "<p style='font-size:.85em;color:#d8b4fe;margin-bottom:6px'>Click sentences in the correct order. Click a placed sentence to remove it.</p>"
        "<div class='ordered' id='ordered'></div>"
        "<hr style='border-color:rgba(168,85,247,.2);margin:8px 0'>"
        "<div class='slist' id='slist'></div>"
        "<div class='msg' id='msg'></div>"
        "<button class='abtn' onclick='checkOrder()'>Check Order</button>"
        "<button class='abtn' onclick='resetRound()'>Reset</button></div>"
        "<div id='endScr'><h1 id='et'></h1><p id='es' style='font-size:1.2em;margin-top:10px;color:#d8b4fe'></p>"
        "<button class='ebtn' onclick='init()'>Play Again</button></div>"
        "<script>"
        "var AC=new(window.AudioContext||window.webkitAudioContext)();"
        "function snd(f,d){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.value=.15;o.start();g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.stop(AC.currentTime+d)}"
        "function spk(t){try{var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}"
        "var ROUNDS=["
        "{topic:'An Email to a Friend',sents:['Dear Tom,','How are you? I hope you are doing well.','I am writing to invite you to my birthday party.','It is on Saturday at 3 pm at my house.','Please let me know if you can come.','Best wishes, Emma']},"
        "{topic:'A Morning Routine',sents:['I wake up at seven o\\'clock every morning.','First, I brush my teeth and wash my face.','Then, I get dressed and go downstairs.','I have breakfast with my family.','After that, I take the bus to school.']},"
        "{topic:'At the Restaurant',sents:['We arrived at the restaurant at seven.','The waiter showed us to our table.','We looked at the menu and chose our food.','The food was delicious and we enjoyed it.','Finally, we paid the bill and went home.']},"
        "{topic:'My Best Friend',sents:['My best friend is called Ali.','We have been friends since primary school.','He is tall, funny, and very kind.','We like playing football together after school.','I am very lucky to have a friend like him.']},"
        "{topic:'A Holiday Story',sents:['Last July, my family went to Antalya.','We stayed at a hotel near the beach.','Every day we swam in the sea and built sandcastles.','In the evening, we ate at different restaurants.','It was the best holiday I have ever had.']},"
        "{topic:'How to Make a Sandwich',sents:['First, take two slices of bread.','Next, spread butter on each slice.','Then, put cheese and tomatoes on one slice.','After that, put the other slice on top.','Finally, cut the sandwich in half and enjoy!']},"
        "{topic:'The School Trip',sents:['Our class went on a trip to the museum last week.','We took the school bus early in the morning.','The guide showed us many interesting things.','We had lunch in the museum garden.','Everyone agreed it was a wonderful day.']},"
        "{topic:'A Letter of Complaint',sents:['Dear Sir or Madam,','I am writing to complain about a product I bought.','The headphones stopped working after two days.','I would like a refund or a replacement.','I look forward to hearing from you soon.']}];"
        "var ri=0,score=0,order=[],placed=[];"
        "function init(){ri=0;score=0;order=[];placed=[];document.getElementById('endScr').classList.remove('show');showRound()}"
        "function shuffle(a){var b=a.slice();for(var i=b.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=b[i];b[i]=b[j];b[j]=t}return b}"
        "function showRound(){if(ri>=8){endGame();return}"
        "document.getElementById('rn').textContent=ri+1;document.getElementById('sc').textContent=score;document.getElementById('msg').textContent='';"
        "var r=ROUNDS[ri];document.getElementById('topic').textContent='Topic: '+r.topic;"
        "placed=[];order=shuffle(r.sents.map(function(s,i){return{text:s,idx:i}}));"
        "renderLists()}"
        "function renderLists(){var sl=document.getElementById('slist');sl.innerHTML='';"
        "order.forEach(function(item,i){if(placed.indexOf(item)===-1){var d=document.createElement('div');d.className='sitem';d.textContent=item.text;"
        "d.onclick=function(){placed.push(item);renderLists()};sl.appendChild(d)}});"
        "var ol=document.getElementById('ordered');ol.innerHTML='';"
        "placed.forEach(function(item,i){var d=document.createElement('div');d.className='oitem';d.textContent=(i+1)+'. '+item.text;"
        "d.onclick=function(){placed.splice(placed.indexOf(item),1);renderLists()};ol.appendChild(d)})}"
        "function resetRound(){placed=[];renderLists();document.getElementById('msg').textContent=''}"
        "function checkOrder(){var r=ROUNDS[ri];"
        "if(placed.length!==r.sents.length){document.getElementById('msg').textContent='Place all sentences first!';return}"
        "var correct=true;placed.forEach(function(item,i){if(item.idx!==i)correct=false});"
        "if(correct){snd(523,.2);score++;document.getElementById('sc').textContent=score;"
        "document.getElementById('msg').textContent='Correct order!';spk('Well done!');"
        "ri++;setTimeout(showRound,1300)}"
        "else{snd(180,.3);document.getElementById('msg').textContent='Not quite right. Try again!'}}"
        "function endGame(){var t=score>=6?'Paragraph Pro!':score>=4?'Good Work!':'Keep Trying!';"
        "document.getElementById('et').textContent=t;"
        "document.getElementById('es').textContent='Score: '+score+' / 8';"
        "document.getElementById('endScr').classList.add('show');spk(t+' Score '+score+' out of 8')}"
        "init();</script></body></html>"
    )


# ── GAME 4: Debate Builder ──
def _build_ms_debate_builder_html():
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Debate Builder</title><style>"
        "*{margin:0;padding:0;box-sizing:border-box}"
        "body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#1a0533,#0d0221);color:#e9d5ff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center}"
        ".gbox{background:rgba(168,85,247,.13);border:2px solid rgba(168,85,247,.4);border-radius:20px;padding:30px;max-width:580px;width:92%;text-align:center}"
        "h1{font-size:1.5em;margin-bottom:8px;color:#c084fc}"
        ".info{font-size:.95em;margin-bottom:12px;color:#d8b4fe}"
        ".topicbox{font-size:1.15em;margin:12px 0;padding:14px;background:rgba(168,85,247,.15);border:2px solid rgba(168,85,247,.4);border-radius:14px;color:#f0abfc;line-height:1.5}"
        ".side{display:inline-block;padding:5px 14px;border-radius:14px;font-size:.9em;margin:8px 0;font-weight:bold}"
        ".side-for{background:rgba(34,197,94,.2);color:#86efac;border:1px solid rgba(34,197,94,.4)}"
        ".side-against{background:rgba(239,68,68,.2);color:#fca5a5;border:1px solid rgba(239,68,68,.4)}"
        ".prompt{font-size:.95em;color:#fbbf24;margin:6px 0}"
        ".opts{display:flex;flex-direction:column;gap:10px;margin:12px 0}"
        ".opt{padding:13px 16px;font-size:1em;border-radius:12px;border:2px solid rgba(168,85,247,.4);background:rgba(168,85,247,.1);color:#e9d5ff;cursor:pointer;transition:.2s;text-align:left}"
        ".opt:hover{background:rgba(168,85,247,.25)}"
        ".opt.ok{background:rgba(34,197,94,.35);border-color:#22c55e}"
        ".opt.no{background:rgba(239,68,68,.3);border-color:#ef4444}"
        "#endScr{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(13,2,33,.93);z-index:99;flex-direction:column;align-items:center;justify-content:center}"
        "#endScr.show{display:flex}"
        ".ebtn{margin-top:18px;padding:12px 36px;font-size:1.1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        "</style></head><body><div class='gbox'>"
        "<h1>Debate Builder</h1>"
        "<div class='info'>Topic <span id='tn'>1</span>/8 &nbsp;|&nbsp; Round <span id='rndType'>FOR</span> &nbsp;|&nbsp; Score: <span id='sc'>0</span></div>"
        "<div class='topicbox' id='topicbox'></div>"
        "<div id='sideBadge'></div>"
        "<div class='prompt' id='prompt'></div>"
        "<div class='opts' id='opts'></div></div>"
        "<div id='endScr'><h1 id='et'></h1><p id='es' style='font-size:1.2em;margin-top:10px;color:#d8b4fe'></p>"
        "<button class='ebtn' onclick='init()'>Play Again</button></div>"
        "<script>"
        "var AC=new(window.AudioContext||window.webkitAudioContext)();"
        "function snd(f,d){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.value=.15;o.start();g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.stop(AC.currentTime+d)}"
        "function spk(t){try{var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}"
        "var TOPICS=["
        "{topic:'Should students use mobile phones at school?',"
        "forQ:{prompt:'Pick the best argument FOR allowing phones:',opts:['Students can use phones as learning tools and dictionaries.','Phones are expensive and might get stolen.','Teachers don\\'t know how to use phones.'],ans:0},"
        "againstQ:{prompt:'Pick the best argument AGAINST allowing phones:',opts:['Phones are made of glass and metal.','Phones distract students and reduce concentration in class.','Some students have newer phones than others.'],ans:1}},"
        "{topic:'Should school uniforms be mandatory?',"
        "forQ:{prompt:'Pick the best argument FOR school uniforms:',opts:['Uniforms are usually blue or grey.','Uniforms reduce bullying based on clothing and create equality.','Uniforms are sold in shops.'],ans:1},"
        "againstQ:{prompt:'Pick the best argument AGAINST school uniforms:',opts:['Uniforms take away students\\' ability to express themselves.','Uniforms are made from fabric.','Some schools don\\'t have uniforms.'],ans:0}},"
        "{topic:'Should homework be banned?',"
        "forQ:{prompt:'Pick the best argument FOR banning homework:',opts:['Students already spend many hours at school and need free time.','Homework is done on paper.','Some students finish homework quickly.'],ans:0},"
        "againstQ:{prompt:'Pick the best argument AGAINST banning homework:',opts:['Homework was invented a long time ago.','Teachers like giving homework.','Homework helps students practise and remember what they learned.'],ans:2}},"
        "{topic:'Is social media good for teenagers?',"
        "forQ:{prompt:'Pick the best argument FOR social media:',opts:['Social media uses the internet.','Social media helps teenagers stay connected with friends and learn new things.','Many adults also use social media.'],ans:1},"
        "againstQ:{prompt:'Pick the best argument AGAINST social media:',opts:['Social media can cause anxiety, cyberbullying, and addiction.','Social media has many users worldwide.','Social media was created in the 2000s.'],ans:0}},"
        "{topic:'Should junk food be banned in school canteens?',"
        "forQ:{prompt:'Pick the best argument FOR banning junk food:',opts:['Junk food is cheaper than healthy food.','Banning junk food helps students develop healthy eating habits.','Junk food comes in colourful packages.'],ans:1},"
        "againstQ:{prompt:'Pick the best argument AGAINST banning junk food:',opts:['Some junk foods taste better than others.','Students should have the freedom to choose what they eat.','Canteens are usually inside the school building.'],ans:1}},"
        "{topic:'Should the school day start later?',"
        "forQ:{prompt:'Pick the best argument FOR starting later:',opts:['Teenagers need more sleep and perform better when rested.','Some teachers prefer mornings.','School buildings are quieter in the morning.'],ans:0},"
        "againstQ:{prompt:'Pick the best argument AGAINST starting later:',opts:['A later start means school finishes later, leaving less time for activities.','Clocks show different times in different countries.','Some students walk to school.'],ans:0}},"
        "{topic:'Should students learn a musical instrument at school?',"
        "forQ:{prompt:'Pick the best argument FOR learning music:',opts:['Musical instruments can be expensive.','Playing music improves brain development and reduces stress.','Music lessons happen in a classroom.'],ans:1},"
        "againstQ:{prompt:'Pick the best argument AGAINST mandatory music:',opts:['Not all students are interested in music and time could be spent on other subjects.','Music has different genres.','Some instruments are louder than others.'],ans:0}},"
        "{topic:'Should exams be replaced by projects?',"
        "forQ:{prompt:'Pick the best argument FOR replacing exams with projects:',opts:['Projects allow students to show creativity and deeper understanding.','Projects can be done at home.','Some projects use coloured paper.'],ans:0},"
        "againstQ:{prompt:'Pick the best argument AGAINST replacing exams:',opts:['Exams have existed for hundreds of years.','Exams are written on paper.','Exams test knowledge fairly and quickly under equal conditions.'],ans:2}}];"
        "var ti=0,phase=0,score=0,canClick=true;"
        "function init(){ti=0;phase=0;score=0;canClick=true;document.getElementById('endScr').classList.remove('show');showQuestion()}"
        "function showQuestion(){if(ti>=8){endGame();return}canClick=true;var t=TOPICS[ti];"
        "document.getElementById('tn').textContent=ti+1;"
        "var isFor=phase===0;"
        "document.getElementById('rndType').textContent=isFor?'FOR':'AGAINST';"
        "document.getElementById('topicbox').textContent=t.topic;"
        "document.getElementById('sideBadge').innerHTML='<span class=\"side '+(isFor?'side-for':'side-against')+'\">'+(isFor?'FOR':'AGAINST')+'</span>';"
        "var q=isFor?t.forQ:t.againstQ;"
        "document.getElementById('prompt').textContent=q.prompt;"
        "var ops=document.getElementById('opts');ops.innerHTML='';"
        "q.opts.forEach(function(o,i){var b=document.createElement('div');b.className='opt';b.textContent=o;"
        "b.onclick=function(){pick(b,i===q.ans,o)};ops.appendChild(b)})}"
        "function pick(el,ok,txt){if(!canClick)return;canClick=false;"
        "if(ok){el.classList.add('ok');score++;snd(523,.2);document.getElementById('sc').textContent=score}"
        "else{el.classList.add('no');snd(180,.3);"
        "var q=phase===0?TOPICS[ti].forQ:TOPICS[ti].againstQ;"
        "var all=document.querySelectorAll('.opt');all.forEach(function(a,i){if(i===q.ans)a.classList.add('ok')})}"
        "if(phase===0){phase=1}else{phase=0;ti++}"
        "setTimeout(showQuestion,1200)}"
        "function endGame(){var max=16,pct=Math.round(score/max*100);"
        "var t=pct>=80?'Master Debater!':pct>=50?'Good Arguments!':'Think Deeper!';"
        "document.getElementById('et').textContent=t;"
        "document.getElementById('es').textContent='Score: '+score+' / '+max+' ('+pct+'%)';"
        "document.getElementById('endScr').classList.add('show');spk(t+' You scored '+score+' out of '+max)}"
        "init();</script></body></html>"
    )


# ── GAME 5: Idiom Detective ──
def _build_ms_idiom_match_html():
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>Idiom Detective</title><style>"
        "*{margin:0;padding:0;box-sizing:border-box}"
        "body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#1a0533,#0d0221);color:#e9d5ff;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center}"
        ".gbox{background:rgba(168,85,247,.13);border:2px solid rgba(168,85,247,.4);border-radius:20px;padding:30px;max-width:560px;width:92%;text-align:center}"
        "h1{font-size:1.5em;margin-bottom:8px;color:#c084fc}"
        ".info{font-size:.95em;margin-bottom:12px;color:#d8b4fe}"
        ".idiom{font-size:1.4em;margin:16px 0;color:#f0abfc;font-style:italic}"
        ".listen-btn{padding:8px 18px;font-size:.9em;border-radius:10px;border:1px solid rgba(168,85,247,.4);background:rgba(168,85,247,.15);color:#d8b4fe;cursor:pointer;margin-bottom:10px}"
        ".listen-btn:hover{background:rgba(168,85,247,.3)}"
        ".prompt{font-size:.95em;margin:6px 0;color:#fbbf24}"
        ".example{font-size:.9em;margin:4px 0 12px;color:#a78bfa;font-style:italic}"
        ".opts{display:flex;flex-direction:column;gap:10px;margin:12px 0}"
        ".opt{padding:13px 16px;font-size:1em;border-radius:12px;border:2px solid rgba(168,85,247,.4);background:rgba(168,85,247,.1);color:#e9d5ff;cursor:pointer;transition:.2s;text-align:left}"
        ".opt:hover{background:rgba(168,85,247,.25)}"
        ".opt.ok{background:rgba(34,197,94,.35);border-color:#22c55e}"
        ".opt.no{background:rgba(239,68,68,.3);border-color:#ef4444}"
        "#endScr{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(13,2,33,.93);z-index:99;flex-direction:column;align-items:center;justify-content:center}"
        "#endScr.show{display:flex}"
        ".ebtn{margin-top:18px;padding:12px 36px;font-size:1.1em;border-radius:12px;border:none;background:linear-gradient(135deg,#a855f7,#7c3aed);color:#fff;cursor:pointer}"
        "</style></head><body><div class='gbox'>"
        "<h1>Idiom Detective</h1>"
        "<div class='info'>Idiom <span id='rn'>1</span>/12 &nbsp;|&nbsp; Score: <span id='sc'>0</span></div>"
        "<div class='idiom' id='idiom'></div>"
        "<button class='listen-btn' onclick='sayIdiom()'>Listen</button>"
        "<div class='example' id='example'></div>"
        "<div class='prompt'>What does this idiom mean?</div>"
        "<div class='opts' id='opts'></div></div>"
        "<div id='endScr'><h1 id='et'></h1><p id='es' style='font-size:1.2em;margin-top:10px;color:#d8b4fe'></p>"
        "<button class='ebtn' onclick='init()'>Play Again</button></div>"
        "<script>"
        "var AC=new(window.AudioContext||window.webkitAudioContext)();"
        "function snd(f,d){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.value=.15;o.start();g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.stop(AC.currentTime+d)}"
        "function spk(t){try{var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.8;speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}}"
        "var DATA=["
        "{idiom:'Break the ice',example:'\"She told a joke to break the ice at the party.\"',ans:'To start a conversation in a social situation',opts:['To start a conversation in a social situation','To break something made of ice','To feel very cold','To stop talking to someone']},"
        "{idiom:'Piece of cake',example:'\"The test was a piece of cake!\"',ans:'Something very easy to do',opts:['A type of dessert','Something very easy to do','A small part of a cake','Something you eat during a test']},"
        "{idiom:'Hit the books',example:'\"I need to hit the books tonight.\"',ans:'To study hard',opts:['To punch a book','To go to the library','To study hard','To buy new books']},"
        "{idiom:'Under the weather',example:'\"I\\'m feeling a bit under the weather today.\"',ans:'To feel sick or ill',opts:['To stand in the rain','To feel sick or ill','To check the weather forecast','To be very cold outside']},"
        "{idiom:'Cost an arm and a leg',example:'\"That new phone costs an arm and a leg.\"',ans:'To be very expensive',opts:['To lose your arms and legs','To be very expensive','To need a doctor','To be on sale']},"
        "{idiom:'Let the cat out of the bag',example:'\"She let the cat out of the bag about the surprise party.\"',ans:'To reveal a secret accidentally',opts:['To free a cat from a bag','To reveal a secret accidentally','To go shopping for pets','To make a big mistake']},"
        "{idiom:'Once in a blue moon',example:'\"We eat out once in a blue moon.\"',ans:'Very rarely, almost never',opts:['Every full moon','When the moon is blue','Very rarely, almost never','Once a month']},"
        "{idiom:'Bite off more than you can chew',example:'\"He bit off more than he could chew with five projects.\"',ans:'To take on too much responsibility',opts:['To eat too much food','To take on too much responsibility','To have a toothache','To talk too much']},"
        "{idiom:'The ball is in your court',example:'\"I\\'ve done my part. The ball is in your court now.\"',ans:'It is your turn to take action',opts:['To play a ball game','It is your turn to take action','To go to a tennis court','To throw a ball to someone']},"
        "{idiom:'Speak of the devil',example:'\"Speak of the devil! We were just talking about you.\"',ans:'Said when the person you were talking about appears',opts:['To talk about scary things','To speak very loudly','Said when the person you were talking about appears','To say something mean']},"
        "{idiom:'Kill two birds with one stone',example:'\"I\\'ll kill two birds with one stone by shopping on my way home.\"',ans:'To accomplish two things with one action',opts:['To hurt birds with stones','To do something impossible','To accomplish two things with one action','To make a choice between two things']},"
        "{idiom:'A blessing in disguise',example:'\"Losing that job was a blessing in disguise.\"',ans:'Something that seems bad but turns out to be good',opts:['A hidden gift','Something that seems bad but turns out to be good','A person wearing a costume','A lucky charm']}];"
        "var rnd=0,score=0,canClick=true;"
        "function init(){rnd=0;score=0;document.getElementById('endScr').classList.remove('show');next()}"
        "function sayIdiom(){spk(DATA[rnd].idiom)}"
        "function next(){if(rnd>=12){endGame();return}canClick=true;var d=DATA[rnd];"
        "document.getElementById('rn').textContent=rnd+1;document.getElementById('sc').textContent=score;"
        "document.getElementById('idiom').textContent='\"'+d.idiom+'\"';"
        "document.getElementById('example').textContent=d.example;spk(d.idiom);"
        "var ops=document.getElementById('opts');ops.innerHTML='';"
        "var sh=d.opts.slice().sort(function(){return Math.random()-.5});"
        "sh.forEach(function(o){var b=document.createElement('div');b.className='opt';b.textContent=o;"
        "b.onclick=function(){pick(b,o===d.ans)};ops.appendChild(b)})}"
        "function pick(el,ok){if(!canClick)return;canClick=false;"
        "if(ok){el.classList.add('ok');score++;snd(523,.2);document.getElementById('sc').textContent=score;"
        "spk('Correct! '+DATA[rnd].ans)}"
        "else{el.classList.add('no');snd(180,.3);"
        "var all=document.querySelectorAll('.opt');all.forEach(function(a){if(a.textContent===DATA[rnd].ans)a.classList.add('ok')})}"
        "rnd++;setTimeout(next,1500)}"
        "function endGame(){var t=score>=10?'Idiom Expert!':score>=7?'Great Detective!':score>=4?'Good Start!':'Keep Learning!';"
        "document.getElementById('et').textContent=t;"
        "document.getElementById('es').textContent='Score: '+score+' / 12';"
        "document.getElementById('endScr').classList.add('show');spk(t+' You scored '+score+' out of 12')}"
        "init();</script></body></html>"
    )
